trufflesuite/truffle

README.md

The example for adding babel in the README.md was incorrect. When buildning this outputed `[object Object]` in the beginning of the app.js. Babel.transform outputs an object where the key `code` has the code we want.

The babel example is now correct.

---

lib/build.es6

Based on our chat on Gitter, I changed the build process to make Truffle clean the inside of the build folder, not replace it. Worked for me.
From what @tcoulter shared, I realized having a `--keep` flag to toggle this behavior may be unnecessary if there's not an actual case where the folder itself needs to be actually recreated.

Clean folder on build, don't recreate it

---

lib/test.es6
package.json
truffle.es6

* added watch:tests task - uses gaze to re-rerun tests automatically. this helps reduce the startup lag between test runs for more immediate feedback
* allow redeploying contracts from within tests
* use evm snapshot/revert before/after tests instead of redeploying
* display Event logs on test failures
* refactor test code
* readme updates
* ~~only use snapshot/revert if the server supports it (can test for it before suite)~~ (implemented)
Logs look something like this:
```
1) should be able to transfer records
Events emitted during test:
---------------------------
[DEBUG] Initializing account
[DEBUG] Adding value to account
{ event: 'Deposit',
data: 
{ _from: '0x82a978b3f5962a5b0957d9ee9eef472ee55b42f1',
_id: '0x666f6f6261720000000000000000000000000000000000000000000000000000',
_value: …
```

Testing improvments

---

example/contracts/ConvertLib.sol
example/contracts/MetaCoin.sol
example/test/metacoin.js
example/truffle.js
lib/contracts.es6
package.json
truffle.es6

Added the ability to link solidity libraries to the contract deploy process. The process follows the following flow:
1. Builds a dependency graph for libraries of all the contracts in the deploy list. This also handles libraries that are dependent on other libraries. We do this by inspecting the compiled binaries for the `__[LibName]_____________________________` marker as documented in the solidity compiler docs.
https://solidity.readthedocs.org/en/latest/contracts.html?highlight=library 
2. Deploys the contracts and libraries based on the dependency graph such that contracts and libraries that have dependencies wait until their dependencies have been deployed and a deploy address has been captured.
3. Inject the deploy address of dependencies into the bytecode using the above marker …

Implementation of solidity library linking

---

lib/test.es6

If present in truffle.json, the contents of the 'mocha' key will be
used as the arguments passed to `new Mocha()`. This is 
useful for e.g. using a different test reporter in CI.

Take mocha config from truffle.json

---

package.json

I don't know for sure if you're abiding by semver with ether-pudding, but I've not been caught out yet, hence I think the caret is a good addition to prevent PRs like this being needed later.
If you disagree, I'll hardcode v2.0.8 and rebase.
NB I've not taken the liberty of bumping the truffle version, though I could do that too and rebase if desired - I know you're spinning a lot of plates!

Bump ether-pudding version

---

docs/advanced/commands.md
docs/advanced/environments.md
docs/getting_started/contracts.md

Updated documentation to match Truffle v.1.0.1
-fixed spelling and formatting
-fixed description of environment configuration settings to use config.js rather than config.json
-removed description of `truffle resolve` cli command

Update documentation. Fix spelling and formatting.

---

cli.js
package.json

I want to use async/await again

add babel-polyfill

---

templates/example.js

Fixes #276 
Retrieving the deployed contract this way does not result in an error.

Fix #276 : Use Example.deployed() to retrieve deployed contract in tests

---

package.json

This is primarily to go above 0.4.5 which caused incorrect inline assembly warnings to be thrown upon compilation, which required a custom Truffle to ignore.
This fixes it.
Fixes #308

Upgrade to solc 0.4.6.

---

README.md

It appears that the **Read the Docs** documentation is deprecated in favour of those found on truffleframework.com, so this just updates the URL in the README

Update link to current documentation

---

lib/commands/build.js
lib/commands/compile.js
lib/commands/console.js
lib/commands/create.js
lib/commands/digest.js
lib/commands/exec.js
lib/commands/init.js
lib/commands/install.js
lib/commands/migrate.js
lib/commands/networks.js
lib/commands/publish.js
lib/commands/serve.js
lib/commands/test.js
lib/commands/version.js
lib/commands/watch.js

This solves first part of #343.
I described an issue in detail there.

Add lazy-require for command dependencies

---

lib/package.js
package.json

This upgrades the version of EthPM Truffle uses. We now use a different host during installation that downloads files from a separate API, which is much faster. This is a stop gap until we/Infura can figure out why IPFS requests are so slow over the normal IPFS api.

Upgrade ethpm

---

.meta

To move logic from truffle-core to separated packages.

Add truffle-debug-utils and truffle-workflow-compile to .meta

---

ISSUE_TEMPLATE.md

Partially addresses Issue #780.  I considered adding a line for the Solidity version since that's also output in `truffle version` but thought it might've been excluded intentionally.  I also swapped two lines' order to keep those with tips together for better visual harmony.

Make it easier to get env info when filing issues

---

README.md

Update the Readme since `testrpc` has been renamed to `ganache-cli`.

Rename testrpc to ganache-cli

---

.travis.yml
package.json
scripts/geth-accounts.js
scripts/test.sh
test/scenarios/happy_path/happypath.js
test/scenarios/migrations/parameters.js
test/scenarios/server.js

Adds `geth:latest` to the list of clients we scenario test against. It's set up as an 'allowed failure' because . . . that's our current position? As such this test is more a notice of breaking changes upstream rather than a verification that we haven't broken anything.  
Another (possibly more rational) approach might be to test against `geth:stable` and require that we pass. We should discuss this. 
Also: have looted @cpurta's excellent [geth-dev-net](https://github.com/cpurta/geth-devnet) for logic and technique, especially for generating geth accounts on launch. Reaching out to him on gitter to ask if this is ok and make sure we are crediting him appropriately in the file.

Add geth client in CI

---

.travis.yml
package.json
scripts/test.sh
test/scenarios/server.js

Fix for #856. There are four execution contexts for truffle's main repo scenario tests:
+ locally against ganache
+ locally against geth
+ in CI at `truffle` main repo (geth is installed). 
+ in CI at any other module (geth is *not* installed).
`CI` is a Travis global so we're not adequately disambiguating case 3 and 4 above.

Fix CI env variable that breaks downstream CI

---

README.md

Removing back to back references to documentation

---

test/scenarios/compile/compile.js
test/scenarios/ethpm/ethpm.js
test/sources/inheritance/contracts/Branch.sol
test/sources/inheritance/contracts/LeafA.sol
test/sources/inheritance/contracts/LeafB.sol
test/sources/inheritance/contracts/LeafC.sol
test/sources/inheritance/contracts/LibraryA.sol
test/sources/inheritance/contracts/Migrations.sol
test/sources/inheritance/contracts/Root.sol
test/sources/inheritance/contracts/SameFile.sol
test/sources/inheritance/migrations/1_initial_migrations.js
test/sources/inheritance/test/inheritance.js
test/sources/inheritance/truffle.js

+ Adds a set of integration tests for [truffle-compile 53](https://github.com/trufflesuite/truffle-compile/pull/53).
+ Adds a small suite of contracts we can use to test inheritance cases.

Add integration tests for minimized compilation

---

cli.webpack.config.js

This might be OSX specific because Travis is running clean, but have been getting an annoying build error because of an electron related  conditional require that webpack can't deal with. Also reported as an issue a couple months ago at webpack [here](https://github.com/webpack/webpack/issues/6504).
```shell
WARNING in ./~/promisify-node/index.js
157:14-27 Critical dependency: the request of a dependency is an expression
ERROR in ./~/adm-zip/util/fileSystem.js
Module not found: Error: Can't resolve 'original-fs' in '/Users/cgewecke/code/consensys/byoc-opti/truffle/node_modules/adm-zip/util'
@ ./~/adm-zip/util/fileSystem.js 2:9-69
@ ./~/adm-zip/util/index.js
@ ./~/adm-zip/adm-zip.js
@ ./~/github-download/lib/zip.js
@ ./~/github-download/lib/github-download.js
@ …
```

Add original-fs to list of nils

---

test/scenarios/commands/ethpm.js

Fixes an ill-conceived test for `truffle publish` that tries to validate an error message which changed in the last week. 
This test is a little weak anyway - it doesn't expect to publish anything - just verify that all the pre-publication steps execute correctly.

Stop testing error message in EthPM test

---

package.json

This should address the security vulnerability reported in #941 (for Truffle).
+ [Issue at mocha](https://github.com/mochajs/mocha/issues/2791) and [confirmed fix](https://github.com/mochajs/mocha/blob/master/CHANGELOG.md#401--2017-10-05).
+ List of [breaking changes](https://github.com/mochajs/mocha/blob/master/CHANGELOG.md#400--2017-10-02) at mocha for v4 - seems ok. . . . .
Incidentally, this issue was found using a new command that comes with NPM 6
```shell
npm audit
```

Upgrade mocha to 4.1.0

---

README.md

The markdown is not correct.  Clicking the badge leads to a 404.
fix #1009

Fix truffle npm badge links

---

packages/truffle-compile/compilerSupplier.js
packages/truffle-compile/index.js
packages/truffle-compile/profiler.js
packages/truffle-compile/test/test_parser.js
packages/truffle-compile/test/test_supplier.js
packages/truffle-core/lib/commands/compile.js

In order to prevent the `provider` name collision.

Rename CompilerProvider to CompilerSupplier

---

packages/truffle-core/package.json
yarn.lock

Addresses #985. More detail at [ethpm 9](https://github.com/trufflesuite/ethpm-js/pull/9), where `node-promisify` was removed. 
This issue affects people running Node 10 - tested this fix locally on `10.4.0`.

Upgrade ethpm to 0.0.16

---

packages/truffle-artifactor/package.json
packages/truffle-box/package.json
packages/truffle-code-utils/package.json
packages/truffle-compile/package.json
packages/truffle-config/package.json
packages/truffle-contract-sources/package.json
packages/truffle-contract/package.json
packages/truffle-core/package.json
packages/truffle-debug-utils/package.json
packages/truffle-debugger/package.json
packages/truffle-deployer/package.json
packages/truffle-expect/package.json
packages/truffle-migrate/package.json
packages/truffle-provider/package.json
packages/truffle-provisioner/package.json
packages/truffle-require/package.json
packages/truffle-resolver/package.json
packages/truffle-solidity-utils/package.json
packages/truffle-workflow-compile/package.json
packages/truffle/package.json

Adds to all package.jsons within `packages`
```javascript
"publishConfig": {
"access": "public"
}
```
This  is what lerna uses to identify publication candidates. More in their docs [here](https://github.com/lerna/lerna#publish).
Do we want to publish all of this?

Add lerna publishConfigs

---

packages/truffle-core/test/npm.js

Another Node 10 crash - something is different about `fs` and it's not happy with the old callbacks. Example error:
```shell
1) NPM integration
"before all" hook: Create a sandbox:
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
at maybeCallback (fs.js:159:9)
at Object.fs.writeFile (fs.js:1278:14)
at test/npm.js:31:10
at /Users/cgewecke/code/consensys/truffle/packages/truffle-box/box.js:47:11
```

Fix npm test for Node 10

---

packages/truffle-compile/test/ComplexOrdered.sol
packages/truffle-compile/test/InheritB.sol
packages/truffle-contract/test/Example.sol
packages/truffle-core/lib/templates/Example.sol
packages/truffle-core/lib/testing/SafeSend.sol

`SafeSend` found by @bit-shift.

Update Solidity sources to the latest constructor syntax (requires Solidity 0.4.22)

---

packages/truffle-core/lib/console.js

Allow the use of the `await` keyword in the console. This is only available if the user's node version supports it.
Big thanks to https://github.com/nfcampos/await-outside for the reference implementation.

Allow `await` keyword in console

---

packages/truffle-contract/lib/contract.js
packages/truffle-contract/test/methods.js

Addresses #1030.  `instance.send` should accept tx params so you can set the `from`, etc. 
Also added a conditional to skip definition of this method if user has already defined it in their contract. Believe this was problematic for [ERC-721](https://github.com/ethereum/eips/issues/721) although now I can't find any reference to a `send` method in the interface.

Make send accept txParams and prefer user-defined send

---

packages/truffle-artifactor/package.json
packages/truffle-box/package.json
packages/truffle-core/package.json
packages/truffle-debugger/package.json
packages/truffle/package.json
yarn.lock

Fixes #1044 
* truffle: ^4.0.0 →  6.0.1
* truffle-artifactor: ^1.0.0 →  6.0.1
* truffle-box: ^3.0.1 →  6.0.1
* truffle-core: ^2.0.0 →  6.0.1
* truffle-debugger: ^4.0.2 →  6.0.1

Upgrade dependency: fs-extra@6.0.1

---

packages/truffle/package.json
packages/truffle/scripts/prereleaseVersion.js

We'd like to publish experimental builds - e.g. webpacks of `packages/truffle` checked out to a branch. Lerna doesn't let you publish a single scoped package. 
This adds a script to `packages/truffle` which checks out a branch and runs `npm version <version-tag>` where <version-tag> is a tagged prerelease increment of the current version. e.g
```shell
4.1.13-next.0
```
Command is:
```shell
node ./scripts/prereleaseVersion.js <branch> <tag>
```
Needs `npm publish` and `git push` added to the end of it. Those are left out so it can be evaluated without causing damage.

Add pre-release script

---

packages/truffle/package.json
packages/truffle/scripts/prereleaseVersion.js

+ Adds a prompt
+ Adds warnings, info and a 'usage' when there are missing `argv`s.
**Output**
(Tested this on a mock repo [here](https://github.com/cgewecke/npm-beta-test)).
```shell
npm-beta-test cgewecke$ npm run prerelease byoc-safe byoc
> npm-beta-test@2.0.0-byoc.2 prerelease /Users/cgewecke/code/consensys/npm-beta-test
> node ./publish.js "byoc-safe" "byoc"
Already on 'byoc-safe'
Your branch is up to date with 'origin/byoc-safe'.
You are about to:
+ increment the package version to 2.0.0-byoc.3
+ publish the package on npm at tag: 'byoc'
+ commit and push this change to branch: 'byoc-safe'
------------------------------------------
Version                | Tag
------------------------------------------
truffle@2.0.0-byoc.3   | truffle@byoc
Are you sure you want to publish: (y/n) >> …
```

Make prerelease publishing script wizard-ish.

---

lerna.json
packages/truffle-debugger/package.json
packages/truffle-debugger/webpack/webpack.config-common.js
packages/truffle-debugger/webpack/webpack.config-test.js

Via babel preset-env's `targets` directive.

Ensure truffle-debugger targets Node 6

---

packages/truffle-artifactor/package.json
packages/truffle-core/package.json
packages/truffle-debugger/package.json
packages/truffle-deployer/package.json
packages/truffle-provider/package.json
packages/truffle/package.json
yarn.lock

This PR unfixes the `ganache-cli` version of all the repositories included in truffle-core and updates it to the latest released version. 
Honestly, I couldn't understand how you guys are dealing with this main repo regarding sub-repositories' dependencies. Please let me know if I'm doing right.

Update ganache-cli to 6.1.4 accepting minor and patch updates

---

packages/truffle-debugger/lib/evm/sagas/index.js

This is for issue #1051 
Simple check that ensures binary is not equal to "0x0" before searching for it and adding the instance to an address.

Ensure not-null binary before adding instance

---

packages/truffle/scripts/prereleaseVersion.js

Fixes a weird issue where `npm version` does not consistently commit the version upgrade. I can't isolate why this happens but it might be `nvm`, might be `yarn`. . . This fix just makes double-sure it happens. Running `git commit` in a repo with no changes is a no-op.

Ensure commit in prerelease publish script

---

packages/truffle-compile/compilerSupplier.js
packages/truffle-compile/index.js
packages/truffle-compile/profiler.js
packages/truffle-compile/test/test_ordering.js
packages/truffle-compile/test/test_supplier.js
packages/truffle-config/index.js

+ modifies config key to support multiple compilers
+ moves existing solc defaults there
+ grandfathers in the old solc key at `truffle-compile`
**Example** (updated)
```javascript
compilers: {
solc: {
version: "0.4.24",
docker: true,
settings: {
optimizer: {
enabled: true,
runs: 1000
}
}
},
vyper: {
version: "0.1.0-beta.1",
snap: true
}
}
```

Add compilers key to config

---

packages/truffle-core/cli.js

+ Underlying issue described at web3 is [here](https://github.com/ethereum/web3.js/issues/1648). 
+ Rejected [PR](https://github.com/ethereum/web3.js/pull/1494) at web3 to end-run warning.
Suggests this isn't obviously the result of negligence cleaning up emitters here. Also not proof of a lack of negligence, although have tried hard not to neglect this.
Also looks like it's not possible to manually set these limits on the PromiEvent since that part of the EventEmitter interface [isn't exposed](https://github.com/ethereum/web3.js/blob/1.0/packages/web3-core-promievent/src/index.js#L52-L60).
Warning looks like this:
```shell
(node:60858) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 data listeners added. Use emitter.setMaxListeners() to increase limit
``` …

Suppress web3 MaxListenersExceededWarning

---

packages/truffle-contract-schema/spec/abi.spec.json
packages/truffle-contract-schema/test/MetaCoin.json
packages/truffle-contract-schema/test/abi-schema.js
packages/truffle-contract-schema/test/solc.js
packages/truffle-contract/README.md
packages/truffle-contract/lib/contract.js

Ref: #1093 
Solidity is moving away from usage of `constant` and `payable` properties in the ABI. This PR removes those fields as being any kind of required, and instead now relies on the `stateMutability` property.
- Update schema accordingly
- Change tests to reflect new requirements
- Also (for good measure) put `pragma experimental "v0.5.0"` in the schema `solc` tests
- Fix a readme

Stop expecting `constant` and `payable` in ABIs

---

packages/truffle-core/cli.js

What *is* [this comment](https://github.com/trufflesuite/truffle/blob/develop/packages/truffle-core/cli.js#L40-L41) about?
> // Don't exit if no error; if something is keeping the process open,
// like `truffle console`, then let it.
Commands launched in`truffle console` do not appear to exit through this callback. It's only run when a terminal launched command exits - e.g. it will only run when you type `.exit` into the repl. 
There's some back and forth in the blame here a year ago and it's not clear what the underlying issue was. 
We need this to `process.exit` now because websockets and eth-block-tracker are a tangle of open interval handlers and unclosed sockets within their own codebases. We're either getting hanging or crashing and strategies for managing one vs. the other are not …

Process exit(0) at cli.js

---

packages/truffle-contract/lib/execute.js
packages/truffle-contract/lib/handlers.js
packages/truffle-contract/lib/override.js
packages/truffle-contract/lib/reason.js

#1102 
+ Makes reason string fetching an error triggered post-fetch rather than a tx triggered pre-fetch 
+ Restores logic that only run gas estimation if no other values have been specified (e.g in the tx params or network config)
+ Moves reason string logic to its own file.
We discussed running these calls using the `defaultBlock` param - haven't added that here - in many cases it would require that we make another call to get the blockNumber. Even that value might not be correct post-call if ganache is auto-mining or something, and we don't want to do it pre-call because it obviates the performance gains we need here. 
Also just think its not worth it to manage this given the rarity of the edge cases that would suffer from a post-tx call and how temporary this logic is anyway - as soon …

Extract reasons on error only

---

packages/truffle-debugger/lib/data/decode/index.js
packages/truffle-debugger/lib/data/sagas/index.js

So that intermediary variables can be used, e.g. when grabbing a struct variable from a mapping.
For instance:
```solidity
Record storage record = someMapping[i];
```
Previously, the debugger couldn't decode `record` because the storage location was kept on the stack. This PR adds support for this.

Dereference stack/memory pointers to storage vars

---

packages/truffle-migrate/index.js
packages/truffle/test/scenarios/migrations/init.js
packages/truffle/test/sources/migrations/init/contracts/Migrations.sol
packages/truffle/test/sources/migrations/init/migrations/1_initial_migration.js
packages/truffle/test/sources/migrations/init/truffle.js

#1111 and #777 
+ Lets this edge case execute as expected - e.g as long as there is a migration file and there are no previous migrations, we should migrate.
+ Adds a test which also verifies Migrations.sol doesn't unnecessarily re-migrate.

Allow Migrations.sol to migrate alone

---

packages/truffle-contract/lib/execute.js
packages/truffle-contract/test/events.js

#1105 
+ Adds logic to enable listening to an event via callback
+ Adds a test for same
I pulled this logic out of the original web3 1.0 draft  assuming that it's a new day and the sun's rays are websocket-enabled. 
This is true for `ganache` but geth is having some teething problems with it.  There are many reports over at web3 that the geth websocket channel is prone to random disconnection which web3 cannot recover from. Additionally large data sends cause the geth client to disconnect - it might not be possible for everyone to use the new feature.

Restore option to listen for event with callback

---

packages/truffle-compile/index.js
packages/truffle-config/index.js
packages/truffle/test/sources/inheritance/truffle.js

The compilers key change in #1083 broke that feature because `truffle-config` does not merge the defaults (which are a multi-level object) with the user defined config (which may not include all the necessary settings). We were missing a test for this in the scenarios. 
+ Makes it possible merge complex config objects into complex defaults if their top level keys are declared in a `deepCopy` array in `truffle-config`
+ Deep merges the `compilers` key (when declared as an object) into the config defaults
+ Uses a solcjs compiler for the compiler scenario tests. The happy path tests use the default so we have both of these cases covered from the `truffle.js` side now.
+ Adds options sanity checks to the `compile` function, making sure we have at least `compilers.solc.settings`

Fix broken compilers config options

---

packages/truffle-debugger/lib/evm/selectors/index.js
packages/truffle-debugger/package.json
yarn.lock

Since context binary searching has been a problem, this sidesteps the problem a bit by finding the closest matching binary string.
Instead of attempting to remove link-references and whatnot, just use the levenshtein distance to determine the number of inserts/deletes/character changes required to change sought binary to possible found binary. Return the closest match as the result.
Filter the results so that a result is only returned in the case where the distance is <=25% the length of the sought binary.
Wikipedia: [Levenshtein Distance](https://en.wikipedia.org/wiki/Levenshtein_distance)

Use levenshtein distance for context binary search

---

packages/truffle-compile/index.js

#1137 
Fixes old `solc` settings not getting assigned to the new compilers key.

Fix grandfathering of `solc` key

---

packages/truffle-artifactor/package.json
packages/truffle-core/package.json
packages/truffle-debugger/package.json
packages/truffle-deployer/package.json
packages/truffle-provider/package.json
packages/truffle/package.json
yarn.lock

#1122 
This should resolve an issue in the dry-run migrations where the account balance is reported incorrectly because of a number conversion bug in `6.1.4`

Upgrade ganache cli to 6.1.6

---

packages/truffle-deployer/index.js
packages/truffle-deployer/src/deployment.js
packages/truffle-reporters/reporters/migrations-V5/messages.js
packages/truffle/test/scenarios/migrations/errors.js
packages/truffle/test/sources/migrations/error/migrations/7_batch_deployments.js

#1136 
This error was in the wrong place / not throwing. 
+ moves array syntax check into the pre-flight validation at `executeDeployment`
+ puts the messaging in the reporter, 
+ adds a test.

Throw batch deprecation error correctly

---

packages/truffle-contract/lib/contract.js
packages/truffle-contract/lib/execute.js
packages/truffle-contract/lib/reformat.js
packages/truffle-contract/package.json
packages/truffle-contract/test/deploy.js
packages/truffle-contract/test/methods.js
packages/truffle-contract/test/sources/Example.sol
yarn.lock

#1126, [relevant suggestion](https://github.com/trufflesuite/truffle/pull/1129#issuecomment-406517580) 
+ Adds logic to transform Web3 1.0's string number outputs to BigNumber|BN|string before returning value from a `.call`. Defaults to BigNumber  for backwards compatibility with Web3 0.x
+ Adds a `numberFormat` setting to the contract abstraction that allows you to configure this at the costructor level
+ Adds tests for these return cases:
+ primitive
+ number array
+ tuple (named and unnamed elements)
+ tuple with a number array as an element
I will add event return value reformatting in a second PR, after this one is reviewed.

Add string number reformatting for .call return values

---

packages/truffle-contract/lib/contract.js
packages/truffle-contract/lib/reformat.js
packages/truffle-contract/test/methods.js

Also capitalizes the allowed values: `["BN", "BigNumber","String"]`

Use BN as default number format

---

packages/truffle-contract/test/methods.js
packages/truffle-contract/test/sources/Example.sol

Makes the overloaded function tests at `truffle-contract` use bytes32 as well as uint to make sure this kind of signature works.

Make overloaded function tests multivariable

---

.gitattributes

A minor update to add syntax highlighting to *.sol files when viewed on GitHub

Adds .gitattributes to recognize *.sol files in GitHub

---

packages/truffle-config/index.js
packages/truffle-core/lib/commands/migrate.js
packages/truffle/test/scenarios/migrations/production.js
packages/truffle/test/sources/migrations/production/truffle.js

Adds option that lets you bypass the auto dry-run on networks we've flagged as auto dry-run. Also overrides the `production` flag (which auto dry-runs). 
The colony migrations targeting a parity client fail on dry-run, reason unknown. This definitely needs to be something people can turn off.

Add `skipDryRun` option

---

packages/truffle-migrate/migration.js
packages/truffle-reporters/reporters/migrations-V5/messages.js
packages/truffle-reporters/reporters/migrations-V5/reporter.js
packages/truffle/test/scenarios/migrations/migrate.js

Targets #1123
These have a really simple implementation at the moment - they just start/stop a spinner with a message. They should be expanded to aggregate gas data.
+ Integrated them into the "Saving Migrations" step so that doesn't seem like it's hanging
+ Also: stopped printing `Saving artifacts` when script doesn't actually deploy any contracts. It's not uncommon for people to use a migration file to run setup and initialization logic separately from the actual deployments.

Add startTransaction / endTransaction reporter hooks

---

packages/truffle-core/lib/commands/develop.js
packages/truffle-core/lib/commands/test.js

#1159
This will produce a nicer error message that contains the tx hash. People will be able to modify their tests to run a single test or contract suite using the `.only` prefix, grab the hash out of the error and pull up the debugger. 
It's possible we should add that flow as some kind of pro-tip thing in the error itself. Currently looks something like this:
```
Error: Transaction: 0x794b7eced61292f319cc8bbe9f293ea5777ef7adfb8e27ad24971e38ebebfc90 exited with an error (status 0). 
Please check that the transaction:
- satisfies all conditions set by Solidity `require` statements.
- does not trigger a Solidity `revert` statement.
at StatusError.ExtendableError (node_modules/truffle/build/webpack:/packages/truffle-error/index.js:10:1)
at new StatusError …
```

Use `noVMErrorsOnRPCResponse` for built in ganache

---

packages/truffle-core/lib/commands/init.js

Updated the bare-box branch, removing `external` from the compilers as suggested, although I think it would be nice to add that back in at some point FWIW.

Make init use new config

---

packages/truffle-artifactor/test/Example.sol
packages/truffle-artifactor/test/ExampleLibrary.sol
packages/truffle-artifactor/test/ExampleLibraryConsumer.sol
packages/truffle-artifactor/test/contracts.js
packages/truffle-contract/test/cloning.js
packages/truffle-contract/test/sources/Example.sol
packages/truffle-contract/test/sources/ExampleLibrary.sol
packages/truffle-contract/test/sources/ExampleLibraryConsumer.sol
packages/truffle-debugger/test/ast.js
packages/truffle-debugger/test/context.js
packages/truffle-debugger/test/evm.js
packages/truffle-debugger/test/solidity.js
packages/truffle/test/sources/ethpm/contracts/Local.sol
packages/truffle/test/sources/ethpm/contracts/PLCRVoting.sol
packages/truffle/test/sources/ethpm/installed_contracts/tokens/contracts/Migrations.sol
packages/truffle/test/sources/ethpm/installed_contracts/tokens/contracts/eip20/EIP20.sol
packages/truffle/test/sources/ethpm/installed_contracts/tokens/contracts/eip20/EIP20Factory.sol
packages/truffle/test/sources/ethpm/installed_contracts/tokens/contracts/eip20/EIP20Interface.sol
packages/truffle/test/sources/inheritance/contracts/Migrations.sol

This PR *almost* makes it possible to replace ``soljson.js`` with the current nightly build (that is to become solidity 0.5.0) while still having the truffle test suite pass.
What still needs to be adjusted is ``packages/truffle-compile/test/test_supplier.js``, resp. ``packages/truffle-compile/test/sources/NewPragma.sol``, but this is tested against different versions of solidity, so some more involved logic is needed here.
Apart from that ``packages/truffle/test/scenarios/contract_names/test_imports.js``, ``packages/truffle/test/scenarios/happy_path/happypath.js`` and ``packages/truffle/test/scenarios/solidity_testing/with_balances.js`` pull some solidity files (presumably from a truffle box) that still use outdated syntax, but I don't really know where those files are coming from …

Update contracts for compatibility with solidity 0.5.0

---

packages/truffle-config/index.js
packages/truffle-reporters/reporters/migrations-V5/reporter.js

Couple tiny fixes for the migrations:
+ Re-orders the insufficient balance message in the reporter because it fulfills two conditions in the error management switch, but we really want the first one.
+ Sets the default gasPrice to 20 gwei. This is still pretty high. Too high?
Note: we aren't really gas estimating when we run commands even though all the logic works on this side. Tried to remove the default config setting in this PR but ganache estimates are not reliable enough for our own unit tests. There are failed transactions when value is sent during the solidity tests for example. 
There's WIP for estimation at ganache right now. Even when it's fixed it will likely be a breaking change for us to remove the defaults if people are using an older ganache version.

Re-order migrations error / use 20gwei default

---

packages/truffle-contract-schema/index.js
packages/truffle-contract-schema/test/schema.js

Currently, truffle-contract-schema's `validate()` function throws a list of objects representing validation errors.
This PR:
- Converts that exception to a real `Error` object, with lightly formatted message text.
- Appends the original `errors` list as a property on the Error object
- Removes the `useDefaults` option from the validation, since it mutates the input object. This was causing problems with the polymorphic ABI item schema.
- Use `verbose` when validating, to ensure that the errors contain the original data value.

Throw real Error instead of list for schema errors

---

packages/truffle-deployer/src/deployment.js

This fixes the blank error message axic found while testing the external compiler. The reporter (which generates the message) isn't launched during the test migrations because we want silence. 
With this change, when running `truffle test`  with an underfunded migration we get:
```
Error: while migrating ConvertLib: Returned error: base fee exceeds gas limit
```
When running `truffle migrate` we get:
```
"ConvertLib" ran out of gas (using a value you set in your network config or deployment parameters.)
* Block limit:  6721975
* Gas sent:     10
```

Throw message even when migrations reporter not enabled

---

packages/truffle-debugger/lib/controller/sagas/index.js
packages/truffle-debugger/lib/evm/selectors/index.js
packages/truffle-debugger/lib/solidity/sagas/index.js
packages/truffle-debugger/lib/solidity/selectors/index.js

Might fix some problems in trufflesuite/truffle-debugger#75
- Continue stepping through Solidity code if `controller.current.location` causes an error
- Use more defaults to prevent unhandled "cannot read whatever of undefined" exceptions

Make debugger fail less hard

---

.travis.yml
packages/truffle-contract-sources/index.js
packages/truffle-contract-sources/package.json
packages/truffle-core/lib/commands/compile.js
packages/truffle-core/lib/test.js
packages/truffle-core/test/compile.js
packages/truffle-core/test/ethpm.js
packages/truffle-core/test/migrate.js
packages/truffle-core/test/npm.js
packages/truffle-debugger/test/helpers.js
packages/truffle-external-compile/README.md
packages/truffle-external-compile/index.js
packages/truffle-external-compile/package.json
packages/truffle-external-compile/test/test_targets.js
packages/truffle-workflow-compile/index.js
packages/truffle-workflow-compile/package.json
packages/truffle/package.json
packages/truffle/scripts/test.sh
packages/truffle/test/scenarios/external_compilers/truffle-compile.js
packages/truffle/test/sources/external_compile/compile-external
packages/truffle/test/sources/external_compile/contracts/.placeholder
packages/truffle/test/sources/external_compile/contracts/ConvertLib.sol
packages/truffle/test/sources/external_compile/contracts/MetaCoin.sol
packages/truffle/test/sources/external_compile/contracts/Migrations.sol
packages/truffle/test/sources/external_compile/migrations/1_initial_migration.js
packages/truffle/test/sources/external_compile/migrations/2_deploy_contracts.js
packages/truffle/test/sources/external_compile/test/.placeholder
packages/truffle/test/sources/external_compile/test/metacoin.js
packages/truffle/test/sources/external_compile/truffle.js

Ref: #1134 
It'd be nice to use Truffle for workflows that don't operate nicely in the context of the current `truffle compile` solc pipeline. This compilation step can be greatly generalized by way of offering configuration for two components:
- Allow specifying arbitrary command to run, for compilation
- Allow specifying targets, with optional arbitrary command to process those targets into Truffle artifacts.
This PR makes changes to `truffle-workflow-compile` to support multiple compilers (at all), and defines a new package `truffle-external-compile`, which implements the above.
In `truffle-workflow-compile`:
- Define `SUPPORTED_COMPILERS`, mapping name to node module
- Detect keys included in `config.compilers` (NOTE: solc is defaulted!)
- Run all compile modules for detected …

Support external compilers

---

packages/truffle-deployer/test/errors.js
packages/truffle-reporters/reporters/migrations-V5/reporter.js

+ Removes a bad conditional check in the reporter dispatcher.
+ Adds a regression test for library link errors that were being swallowed.

Throw link errors

---

packages/truffle/test/scenarios/external_compilers/truffle-compile.js

These fail locally if you don't have the `jq` installed. We have the same problem with the solc native compiler tests and run those conditionally in CI as well. 
PR  skips out of the scenario test unless `process.env.CI`

Skip external compile tests locally

---

packages/truffle-artifactor/package.json
packages/truffle-contract/lib/execute.js
packages/truffle-contract/lib/handlers.js
packages/truffle-contract/lib/override.js
packages/truffle-contract/package.json
packages/truffle-contract/test/deploy.js
packages/truffle-contract/test/methods.js
packages/truffle-core/package.json
packages/truffle-debugger/package.json
packages/truffle-deployer/package.json
packages/truffle-external-compile/package.json
packages/truffle-migrate/package.json
packages/truffle-provider/package.json
packages/truffle-reporters/package.json
packages/truffle-require/package.json
packages/truffle/package.json
yarn.lock

+ Upgrades web3 to beta.35
+ Adds code to extract receipt from new error thrown by web3 and route it to truffle-contract's receipt handler where it get's rejected per the previous pattern. 
+ Check status values as booleans.
+ Updates tests.

Upgrade to web3 beta.35

---

packages/truffle-artifactor/package.json
packages/truffle-core/package.json
packages/truffle-deployer/package.json
packages/truffle-resolver/package.json
packages/truffle/package.json
yarn.lock

Changing the package version at `truffle-contract` [broke](https://travis-ci.org/trufflesuite/truffle/builds/416480241) the lerna installation.
Ran lernaupdate for TC as a dep. Then I floated the changes on a caret - I think this correct based on this description of [lerna link](https://github.com/lerna/lerna/tree/master/commands/link#readme) which suggests that linking checks the version range of the packages. Not 100% sure about this needless to say.
Also checked the release build and it's fine - it has the most recent changes in it. Tests that failed on Travis were passing locally for me when I did the release - I guess everything was linked correctly from before the change.

Fix build for truffle-contract package version change

---

packages/truffle-solidity-loader/.gitignore
packages/truffle-solidity-loader/ISSUE_TEMPLATE.md
packages/truffle-solidity-loader/README.md
packages/truffle-solidity-loader/index.js
packages/truffle-solidity-loader/lib/build_option_normalizer.js
packages/truffle-solidity-loader/lib/logger_decorator.js
packages/truffle-solidity-loader/lib/query_string_parser.js
packages/truffle-solidity-loader/lib/scratch_dir.js
packages/truffle-solidity-loader/lib/truffle_config_locator.js
packages/truffle-solidity-loader/package.json

This pull request will add the original `truffle-solidity-loader` to the truffle mono repo. No code changes were added, only a direct `lerna import ./dir/truffle-solidity-loader --flatten` was used.
The reason this is being added is because this has a direct dependency to `truffle-core` to run.

Adding truffle solidity loader to truffle

---

packages/truffle-workflow-compile/package.json

Hi, 
`truffle-workflow-compile` depends on `truffle-external-compile` since commit https://github.com/trufflesuite/truffle/commit/66ae42c291d8f52f67ef362cd6680f4e18a9ac88. This PR add the missing dependency to the package.json.
Noted while running `npm install truffle-workflow-compile@beta`.
Cheers,
Fabian

add dependency to truffle-external-compile package

---

packages/truffle-contract/package.json

Hi.
I stumbled upon another missing dependency. This time in `truffle-contract`. It needs `bignumber.js` since af7d5ae3366aae10cdd96bc8e29686738fd8545e
Cheers,
Fabian

add missing bignumber.js dependency

---

packages/truffle-migrate/migration.js
packages/truffle-reporters/reporters/migrations-V5/messages.js
packages/truffle/test/scenarios/migrations/errors.js
packages/truffle/test/sources/migrations/error/migrations/8_js_error_sync.js
packages/truffle/test/sources/migrations/error/migrations/9_js_error_async.js

#1208, #1207.
+ Stop swallowing runtime js errors (like ReferenceError) in sync migrations script.
+ (Sneaking this in) Improve migration error output when for case when contract has no bytecode.

Throw js errors from sync migrations correctly

---

packages/truffle-blockchain-utils/index.js
packages/truffle-core/lib/package.js
packages/truffle-core/package.json
yarn.lock

#1209 
This goes with some changes in the EthPM registry package updating it to web3 1.0 as well. We don't really have any working tests for `truffle publish` at the moment unfortunately. The installation tests broke when the manifest work was done. And the publish test has always been weird, trying to claw through as much of the logic as possible before it errors out without publishing....
I *think* this is a fix though.

Update publish for web3 1.0

---

packages/truffle-core/lib/templates/Example.sol

To suppress the following warning:
```
C:\Users\username\projectname\contracts\MyContract.sol:5:3: Warning: No visibility specified.
Defaulting to "public".
constructor() {
^ (Relevant source part starts here and spans across multiple lines).
```

Add "public" to Example.sol constructor

---

packages/truffle-core/lib/test.js

Hi.
The `config.from` property is readonly since some time. 
The from address will either be set through the network configuration or 
will be loaded by Environment.detect.
I think we can remove this statement here.
Cheers, 
Fabian

don't try to set the from address

---

packages/truffle-core/lib/testing/testrunner.js

Issue https://github.com/trufflesuite/truffle/issues/186
Referenced PR on archived repo https://github.com/trufflesuite/truffle-core/pull/6
`truffle test --show-events`

Add --show-events flag to test command

---

packages/truffle-core/lib/commands/test.js

PR https://github.com/trufflesuite/truffle/pull/1232 adds `--show-events` flag, correspondingly this PR is to add this flag to command options.
Original Issue https://github.com/trufflesuite/truffle/issues/186

Add show-events option to test command

---

packages/truffle-contract/lib/execute.js
packages/truffle-contract/lib/handlers.js

Resolves #1241 
There's a small issue with Truffle's handling of transaction receipts which prevents deployment to some Geth clients.
According to the JSON RPC spec for `eth_getTransactionReceipt`:
>[the receipt] also returns either :
> 
>     root : DATA 32 bytes of post-transaction stateroot (pre Byzantium)
>     status: QUANTITY either 1 (success) or 0 (failure)
Truffle assumes that a status is always returned. When the Geth receipt instead has a root specified, Truffle thinks it has failed. This PR resolves that bug by first checking whether a status field exists before throwing an error.

Fix error when migrating to mining Geth client

---

packages/truffle-contract/lib/contract.js

#1172 
Catches the abstract contract error at truffle-contract correctly and tries to explain.

Catch no bytecode condition correctly at truffle-contract

---

packages/truffle-artifactor/package.json
packages/truffle-core/package.json
packages/truffle-debugger/package.json
packages/truffle-deployer/package.json
packages/truffle-provider/package.json
packages/truffle/package.json
yarn.lock

* truffle: 6.1.0-beta.4 →  6.1.8
* truffle-artifactor: 6.1.0-beta.4 →  6.1.8
* truffle-core: 6.1.0-beta.4 →  6.1.8
* truffle-debugger: 6.1.0-beta.4 →  6.1.8
* truffle-deployer: 6.1.0-beta.4 →  6.1.8
* truffle-provider: 6.1.0-beta.4 →  6.1.8
Passes Node 6.

Upgrade dependency: ganache-cli@6.1.8

---

.gitignore
packages/truffle-solidity-loader/README.md
packages/truffle-solidity-loader/index.js

addressed issue where truffle solidity loader would run multiple times if there were multiple imports

Truffle-Solidity-Loadder - Fixed importing multiple Solidity files

---

packages/truffle-compile/compilerSupplier.js

#1259 
+ Fixes misnamed url variables in error handlers for ComplierSupplier calls that fail.
+ Adds missing handling for relative paths in CompilerSupplier version path option.

Correct url variables in request error handler

---

packages/truffle-code-utils/index.js

This PR replaces all `new Buffer` with `Buffer.from`. We should not use Buffer constructor which is deprecated and unsafe.
The behavior of new Buffer() is different depending on the type of the first argument, security and reliability issues can be inadvertently introduced into applications when argument validation or Buffer initialization is not performed.
To make the creation of Buffer instances more reliable and less error-prone, the various forms of the new Buffer() constructor have been deprecated and replaced by separate Buffer.from(), Buffer.alloc(), and Buffer.allocUnsafe() methods.
Check this out: 
* https://nodejs.org/api/buffer.html#buffer_buffer_from_buffer_alloc_and_buffer_allocunsafe
* https://github.com/nodejs/Release#end-of-life-releases

new Buffer is deprecated and unsafe

---

packages/truffle-debugger/lib/data/actions/index.js
packages/truffle-debugger/lib/data/decode/index.js
packages/truffle-debugger/lib/data/decode/utils.js
packages/truffle-debugger/lib/data/reducers.js
packages/truffle-debugger/lib/data/sagas/index.js
packages/truffle-debugger/lib/data/selectors/index.js

Augments variable id's with a stack depth so that if a function appears more than once in the call stack you will see the variables for the appropriate stack frame (more specifically, `data.current.identifiers.refs` will point to the appropriate copy of the variable).  (This augmenting is only done in certain contexts -- specifically, contexts that feed into `data.current.identifiers.refs`, so be aware that there are both augmented and non-augmented IDs still used.)  Variables that are not local to a function get depth 0; depths are started counting from 1 (since that is what the existing code already does).  There is a slight potential bug in that, if `f` (at depth `d`) calls `f` (at depth `d+1`) and then later calls `f` (at depth `d+1`) again, the last of these may see the values from …

Stackframes

---

packages/truffle/scripts/test.sh
packages/truffle/test/scenarios/commands/exec.js

Routes execution through the repo instead of the bundle when running the scenario tests for coverage.

Get coverage reading for scenario tests

---

packages/truffle-compile/compilerSupplier.js
packages/truffle-compile/package.json
packages/truffle-reporters/package.json

This adds ora to the truffle-compile package.  It provides the user with a status update while downloading the solc version list and whenever it needs to download a compiler from solc-bin.
Inspired by issue #1274

Download spinner

---

packages/truffle-core/lib/commands/debug.js
packages/truffle-debug-utils/index.js
packages/truffle-debugger/lib/controller/actions/index.js
packages/truffle-debugger/lib/controller/reducers.js
packages/truffle-debugger/lib/controller/sagas/index.js
packages/truffle-debugger/lib/controller/selectors/index.js
packages/truffle-debugger/lib/debugger.js
packages/truffle-debugger/lib/session/index.js
packages/truffle-debugger/lib/session/reducers.js
packages/truffle-debugger/test/data/decode/helpers.js
packages/truffle-debugger/test/solidity.js

This branch expands the functionality of breakpoints as requested in #1276.  Breakpoints can now be set on a line of the user's choice in a source file of their choice; they can also be set at the current location as before.  Breakpoints are no longer toggled with `b` but rather set with `b` and cleared with `B`.  A breakpoint set with `b` with no arguments is set at the current location; this is the current location *within* the line, like the old breakpoints.  Breakpoints may also be set at a given line (including in another source file), which may also be specified relative to the current line; these breakpoints will stop execution at the *first* encountered location within that line.  Breakpoints in another source file need only have enough of the filename specified to unambiguously …

Improved breakpoint functionality

---

packages/truffle-core/lib/commands/debug.js

As noted in #1302, calling `truffle debug` by itself (without a transaction hash) would return:
```
ReferenceError: callback is not defined
at /[my project folder]/node_modules/truffle-core/lib/commands/debug.js:49:9
at web3.eth.getAccounts.then.accounts (/[my project folder]/node_modules/truffle-core/lib/environment.js:72:9)
at process._tickCallback (internal/process/next_tick.js:68:7)
```
Now it should return a more helpful error 😎 
`truffle debug`
```
Error: Please specify a transaction hash as the first parameter in order to debug that transaction. i.e., truffle debug 0x1234...
at /[my project folder]/node_modules/truffle-core/lib/commands/debug.js:49:21
at web3.eth.getAccounts.then.accounts (/[my project folder]/node_modules/truffle-core/lib/environment.js:72:9)
at …
```

Update truffle debug error handling

---

packages/truffle-compile/parser.js

As noted in #1271, trying to compile a contract with named imports (`import "./item.sol" as Item;`) would return:
`TypeError: Error parsing /Projects/vpod/artemis/contracts/item.sol: Cannot read property '2' of null`
Now the truffle-compile's `parser.js` file should parse and compile the contract successfully.
Call `truffle compile` on a truffle project with a .sol smart contract inheriting another .sol smart contract as a named import.
```
truffle compile
Compiling ./contracts/Example.sol...
Writing artifacts to ./build/contracts
```

Fix Import Regex For Named Imports

---

packages/truffle-config/index.js

#862 (among others)
This PR expands the capability for truffle-config's property descriptions, to enable preprocessing config values. In addition to the normal Node `get` and `set`:
- Define `default` option for specifying default value
- Define `transform` option for preprocessing set values
`default` is necessary because existing directory properties are getting their default values via a function literal.

Support configuring relative paths in `_directory` properties

---

README.md
packages/truffle-core/lib/build.js

Change the way truffle checks for a lack of build configuration.  The config now returns a `null` value instead of `undefined` when it is not set in the config.
Also update the travis build badge to indicate the build status of `next` and not `develop`.

Edit test for null build config

---

packages/truffle-core/lib/commands/develop.js

Truffle develop broke on next because of a failed conditional check.
Calling `truffle develop` would return something like:
```
TypeError: Cannot read property 'accounts' of undefined
at Object.run (/truffle-projects/truffle/packages/truffle-core/lib/commands/develop.js:60:18)
at Command.run (/truffle-projects/truffle/packages/truffle-core/lib/command.js:103:20)
at Object.<anonymous> (/truffle-projects/truffle/packages/truffle-core/cli.js:40:9)
...
```
New expected Behavior:
```
truffle develop
Truffle Develop started at http://127.0.0.1:9545/
Accounts:
(0) 0xb21c7f82d974f7fb83651b7b3a3e6631c0c4028b
(1) 0xb10152e844cf7e5d3983b91cb6c347761fe506f1
(2) 0x38a7dea9500c193478f72a8fa66ec10f2304c689
(3) 0xbf65982f7c3949833c6ca7560eb3cbc4533b22a2
(4) 0x54ec0c29a5f2a251a28b4ed4361f50d6c2ba9e25
(5) …
```

Fix Truffle Develop Undefined Bug

---

packages/truffle-core/lib/commands/console.js
packages/truffle-core/lib/environment.js

Default `truffle console` & `truffle migrate` to use GanacheUI network settings when no network configuration is defined. The network will be defined as `ganache`.
To override the default settings, `truffle migrate --network ganache` or `truffle console --network ganache` will need to be specified with modified `networks.ganache` network settings defined in `truffle-config.js`.
Example of overriding `networks.ganache` to use ganache-cli instead of GanacheUI:
```
networks: {
ganache: {
host: "127.0.0.1",
port: 8545,
network_id: "*"
}
}
};
```
Steps to Test:
Run `truffle migrate` or `truffle console` in a truffle project directory with GanacheUI running in the background.

Default Console & Migration network settings to GanacheUI

---

packages/truffle-core/lib/command.js

`truffle help` was outputting `undefined`

Fix version info in help system

---

packages/truffle-core/lib/mnemonics/mnemonic.js
packages/truffle-core/test/mnemonic.js

Previous tests for the mnemonics user config code were actually hitting the user config directly, which is not ideal. This fix stubs that bit of code so that the user config is left out of it while testing. 
When running npm test in truffle-core, tests should pass, and the mnemonic used is just a default, "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat", rather than the actual mnemonic in the user config. Also, if a mnemonic is not set in the user config, one will not be set by the test (this was not likely to happen anyway, just being extra cautious).

fix mnemonic tests to not actually hit the user config

---

packages/truffle-artifactor/test/contracts.js
packages/truffle-deployer/test/await.js
packages/truffle/test/scenarios/commands/build.js

The Travis Coverage build was failing due to timeouts. In the process of fixing the build, it was discovered that a CompilerSupplier method was missing a conditional check.
New expected Behavior:
Coverage build should pass on the current `next` branch and users should be able to successfully specify a cached version of solc to compile with.

Fix coverage & CompilerSupplier Method

---

.github/stale.yml

Created a yml file to enable configuration for github bot to close stale issues.

add yml file to configure github stale bot

---

packages/truffle-config/index.js
packages/truffle-migrate/index.js

- I added a separate config function to truffle-config, same naming and signature scheme as the test regexp
- I added the new config regexp as second choice to truffle-migrate. While there are no usages of the option version, I did not wan to inadvertently break any code depending on this option.
- separate commits because my editor wanted to reformat every line of code, yay prettier :)

Allow configuration of allowed_extensions for the migrations (fixes #1361)

---

packages/truffle-config/index.js
packages/truffle/test/scenarios/typescript_testing/typescriptTests.js

Allows native .ts support for truffle tests.
Currently, users have to add a workaround to their config file in order to support .ts test files.
For example:
```
test_file_extension_regexp: /.*\.ts$/,
....
};
```
Steps to Test:
https://github.com/ethereum-ts/truffle-typechain-example#setup (minus the config workaround)

Native .ts support for truffle tests

---

packages/truffle-box/box.js
packages/truffle-debugger/test/helpers.js

This PR changes the `sandbox` interface to accept an argument `options` instead of `name` to allow some extra options such as `unsafeCleanup` and `setGracefulCleanup` that interface with the `tmp` module. There is back compatibility where if `options` is a `string`, then it will use it as the `name` directly
You can find an example of using these changes, as well as the motivation for these changes in `packages/truffle-debugger/test/helpers.js` to cleanup the sandboxes when mocha finishes the tests for the debugger.
Here are some comments on the the options:
```
// options.unsafeCleanup
//   Recursively removes the created temporary directory, even when it's not empty. default is false
// options.setGracefulCleanup
//   Cleanup temporary files even when an uncaught exception occurs
```

Add better cleanup for truffle-box sandbox()

---

packages/truffle-debugger/lib/evm/selectors/index.js
packages/truffle-debugger/lib/helpers/index.js
packages/truffle-debugger/lib/trace/sagas/index.js

This pull requests adds support for `STATICCALL`; both places in the code that check whether an opcode is a `CALL` or `DELEGATECALL` now also check for `STATICCALL`.  Note that rather than just updating both of these separately, I factored out the check into a new function in `helpers` so we can just update that if further calling opcodes are added in later versions of Ethereum.
I also added `CALLCODE` as well as `STATICCALL`; `CALLCODE` is of course disallowed in Solidity 0.5.0, and obviously it's deprecated even in older versions, but, hey, maybe you encounter it debugging some historical contract, I don't know.  I figured may as well be prepared for the past as well as the future, so I put it in.
There are of course also some minor unrelated changes to satisfy `eslint`.

Add support for STATICCALL

---

packages/truffle-config/package.json
yarn.lock

This dependency (https://github.com/trufflesuite/truffle/blob/next/packages/truffle-config/index.js#L8) was not in the `package.json`. This PR adds it.

Add configstore dependency to package.json

---

packages/truffle-debugger/test/data/ids.js
packages/truffle-debugger/test/reset.js

The variable ID tests set breakpoints with fixed source IDs instead of just calling the appropriate selector to get the current source ID.  Since in fact source IDs are not assigned deterministically, this resulted in intermittent failures (I'm pretty sure this is the cause).  This pull request fixes that.  It does not address the intermittent failure of the end state variables test.

Fix intermittent failures of variable ID tests by removing fixed source IDs

---

packages/truffle-debugger/lib/evm/sagas/index.js
packages/truffle-debugger/lib/evm/selectors/index.js
packages/truffle-debugger/lib/solidity/sagas/index.js
packages/truffle-debugger/lib/solidity/selectors/index.js
packages/truffle-debugger/test/solidity.js

This pull request makes it so that calls to precompiles once again no longer affect the function depth (as they didn't back when *no* external calls did so!).  Since we're now checking for precompiles in two places -- both the `callstackSaga` and the `functionDepthSaga` -- I factored out the logic for such and put it in a new selector.  This means that the optimization of only getting `instances` and `contexts` once in `callstackSaga` is gone, but I figure that's OK because selectors are memoized anyway.
This pull request also adds a test to verify that precompiles don't affect the function depth.

Keep precompiles from affecting function depth

---

packages/truffle-core/lib/commands/watch.js
packages/truffle-core/package.json

Use a different option to attempt to cope with watching big codebases.
See the different modes in the docs.  
https://www.npmjs.com/package/sane

Tweak options for sane library

---

packages/truffle-debugger/lib/data/selectors/index.js

This pull request prevents anonymous output parameters from displaying (with the empty string for a name) when the user hits `v`, by excluding them for `data.current.identifiers`.  The empty string for a name is confusing, and it doesn't really make sense to display such parameters in the first place as they'll basically only ever contain nonsense except at the very end of their lifetime.  (I didn't bother adding any tests in this PR.)

Suppress anonymous output parameters from data.current.identifiers.

---

packages/truffle-debugger/test/ast.js
packages/truffle-debugger/test/context.js
packages/truffle-debugger/test/data/decode/decoding.js
packages/truffle-debugger/test/data/decode/helpers.js
packages/truffle-debugger/test/data/ids.js
packages/truffle-debugger/test/endstate.js
packages/truffle-debugger/test/evm.js
packages/truffle-debugger/test/helpers.js
packages/truffle-debugger/test/precompiles.js
packages/truffle-debugger/test/reset.js
packages/truffle-debugger/test/solidity.js

[Note: This branch is kind of a mess; it might not end up getting merged in as such.]
This branch upgrades all the test contracts to 0.5.0, and attempts to fix all the resulting problems.  I've already fixed one such problem, namely the lack of support for `STATICCALL`, in PR #1446.  But there's more.
One issue that's come up is that a number of my tests are quite shaky.  This isn't an 0.5.0 problem, but I in my investigations I think I've figured out what's causing it anyway -- namely, I was relying on `sourceId` to be consistent between runs, when it's not.  That's an easy fix.
But the real problems are the 0.5.0-specific problems, which are very consistent.  The failing tests (now that I've fixed the storage decoding tests, where the problem was `STATICCALL`) are:
1. The memory …

Upgrade test contracts to 0.5.0 and fix all resulting problems

---

packages/truffle-config/index.js

To (hopefully) address #1461, but at the very least this should improve performance.
Memoization works via:
- Memo is stored upon `config.provider`'s get
- Memo is reset upon `config.network`'s set
Risks/downsides:
- It might be dangerous to use a memoization mechanism that spans three different parts of the code (i.e., initialization, provider get, network set)
- It's dangerous if the `config.provider` memo is theoretically invalidated but never reset. It might not be sufficient to reset the memo when `config.network = ...` happens.
For instance, `config.network["..."].port = "..."` would result in an invalid memoized `config.provider`.
This may not matter.
- We might want to make a `config.networks["..."].memoize` option, to allow this to be turned off.
For now though... see what Travis …

Memoize config.provider

---

packages/truffle-deployer/src/linker.js

The truffle docs (https://truffleframework.com/docs/truffle/getting-started/running-migrations#deployer-link-library-destinations-) state that:
> If any contract within the destination doesn't rely on the library being linked, the contract will be ignored.
However, if a destination doesn't rely on the library being link, the `link` function returns early, failing to link the other destinations.
This bug seems to have been introduced in https://github.com/trufflesuite/truffle/pull/1028 when a `forEach` was changed to a loop without changing a `return` statement into a `continue`. cc @cgewecke

skip already linked contracts instead of all contracts

---

packages/truffle-core/lib/commands/debug.js

Where `...` is the name of some selector.
For instance, this allows doing something like:
```
debug(...)> :!<data.current.state.memory>.slice(320, 320+32)
```

Add !<...> syntax to debugger watch expressions

---

packages/truffle-core/lib/commands/debug.js

This one-line PR adds the reset command to the list of commands that can't be repeated by pressing enter.  Repeating a reset doesn't make sense and isn't the behavior I expect (I expect it to continue doing next or step or whatever).  So, I just added it to the list of excluded commands.

Prevent the reset command from being repeated with enter

---

packages/truffle-debugger/lib/data/selectors/index.js
packages/truffle-decode-utils/package.json
packages/truffle-decode-utils/src/conversion.ts

- Recursively search through all decoder output and detect decoder's encoding for mappings.
- Strip out the wrapper info and convert the mapping to a JS `Map` object
- Use BN as `Map` key type when Solidity's mapping key type is some kind of `uint` or `int`
Previously:
Now:

Strip mapping metadata from decoder output in debugger

---

packages/truffle-hdwallet-provider/src/index.js

Apparently `this.mnemonic` is doing nothing but serving as an easy way for external code to read terrible secrets

Stop saving this.mnemonic in truffle-hdwallet-provider

---

package.json
packages/truffle/package.json

`truffle run` was missing an `app-module-path` dependency!
Should stabilize `truffle run` for release 🤞

Add missing app-module-path dep

---

packages/truffle-core/lib/environment.js

#1316 
Compare string version of network id and edit Error instantiation in order to allow a string or number representation of the network_id.

Edit network id check

---

packages/truffle-core/lib/commands/version.js
packages/truffle-core/lib/version.js

Handle the case where the user runs truffle version outside of a Truffle project
Fixes issue #1535

Truffle version bug fix

---

packages/truffle-compile/index.js

As a grandfathered config option, `options.solc` should be stabilized and kept as it was (w/o the ability to set config options as `options.solc.settings`). If we want to allow the latter, more work would need to be done in `truffle-config` to enable it.
Thanks to @cds-amal for catching this one before release!

Stabilize options.solc

---

packages/truffle-core/test/compile.js
packages/truffle-core/test/config.js
packages/truffle-core/test/migrate.js
packages/truffle-core/test/npm.js
packages/truffle-core/test/unbox.js
packages/truffle-debugger/test/helpers.js
packages/truffle-decoder/test/truffle-config.js
packages/truffle/test/scenarios/commands/unbox.js
packages/truffle/test/scenarios/cyclic_dependencies/compiles.js
packages/truffle/test/scenarios/happy_path/happypath.js

In preparation for deleting the `web3-one` branch in the truffle-init-default and bare-box repositories, remove references to them in a handful of tests. Replace that branch with a branch that was created name `truffle-test-branch`.

Remove references to web3-one branch in tests

---

README.md

Site links weren't working for me initially. I kept getting 5xx errors. Now they seem to be redirecting properly though, but might as well fix these links anyway.

docs: update site url references to https

---

packages/truffle-core/lib/testing/testresolver.js

Fix for trufflesuite.com#271 & #700.
Windows users (non-WSL) should be able to run `truffle test` successfully on any of our boxes.
Would be nice to have a Windows user manually test w/ this branch (cc @balexander4 ).

allow test import paths to be OS-independent

---

packages/truffle-provider/error.js
packages/truffle-reporters/reporters/migrations-V5/messages.js

The default filename for the truffle config is `truffle-config.js`, this changes the name in the hints and errors to reflect that and reduce confusion.

Refer to the default config file name in error messages and hints

---

packages/truffle-contract/README.md
packages/truffle-contract/package.json

Should clean up the lack of clarity identified by #1619.
Update truffle-contract's bundling so that it includes `web3` and `ethers` in the bundle and excludes `xmlhttprequest`.
Tested this locally with pet-shop and there are no console errors in the browser or in tests.

Fix truffle-contract's browser dependencies

---

packages/truffle-contract/lib/reformat.js

For the bundled version of Truffle (cli.bundled.js), when a contract instance was created from an abstraction that had the `numberFormat` "BigNumber" set, it would throw an error. --> https://github.com/trufflesuite/truffle/issues/1593
On doing some research, it seems others were experiencing the same issue when bundling with webpack https://github.com/MikeMcl/bignumber.js/issues/166. It seems many were experiencing success with requiring the library differently and `truffle-contract` was no different.

Edit the way bignumber.js is required

---

packages/truffle-contract/lib/contract/properties.js
packages/truffle-contract/lib/utils.js
packages/truffle-contract/package.json

- Add missed `ethers` and `truffle-compile` dependencies
- Remove unused `ethereumjs-util`, `ethjs-abi`, `lodash ` and `require-nocache` dependencies
- Move `uglify-es` to `devDependencies`
- Replace `web3.utils` with `web3-utils`
- Replace `ethers.utils.bigNumberify` with `require('ethers/utils/bignumber').bigNumberify`
Production bundle size has been reduced by more than **264 KB (≈12%)**.

Fix truffle-contacts dependencies

---

packages/truffle-config/README.md
packages/truffle-config/package.json
packages/truffle-external-compile/README.md
packages/truffle-hdwallet-provider/README.md
packages/truffle-solidity-loader/README.md
packages/truffle/test/scenarios/resolver/resolver.js

In the interest of moving towards primarily using 'truffle-config.js' instead of 'truffle.js' for the Truffle config file, update some references to it in messages in the codebase.

Update a bunch of messages in the codebase

---

packages/truffle-debugger/lib/evm/selectors/index.js
packages/truffle-debugger/lib/helpers/index.js

This PR adds support for the `CREATE2` opcode.  Due to the dummy address system, no special support different from that for `CREATE` is necessary; I just had to add it to the list of possible creation opcodes.
For technical reasons related to `redux-saga` versions, this branch branches off of the `united-allocator` branch, but it is unrelated to allocation.

Add support for the CREATE2 opcode

---

packages/truffle-compile/index.js
packages/truffle-core/lib/testing/soliditytest.js

- deploy and link test deps at same time, separately from other dependencies
- revert to code in commit 6617b6386414bd812c3dddcdfcf3ab00472f4cef to keep originalMappings for windows file paths
- combine assert and deployedaddresses loading
This is my first time PRing to this project, let me know if everything looks alright. There is a chance I'm not safely handling the linking of the testLibs (assert et. al) but this fix does the job for now.

Fix missing artifacts for Windows in v5.x

---

packages/truffle-debugger/lib/evm/reducers.js

A one-character error caused the reset button to not correctly reset the EVM state and thus not work properly from inside an EVM call.  This is now fixed.

Fix reset button's interaction with EVM calls

---

.github/stale.yml

Increases daysUntilStale to 120 and daysUntilClose to 14. Will not mark issues with an assignee as stale.

Update stale bot

---

packages/truffle-hdwallet-provider/src/index.js

I was having problems using HDWalletProvider when I execute `web3.eth.personal.sign('text', '0x0...')` because seems that the provider needs to implement the method `signPersonalMessage`. Both need the same parameters and both use the same signature algorithm.

Sign personal messages trough signPersonalMessage

---

packages/truffle-debugger/lib/data/actions/index.js
packages/truffle-debugger/lib/data/sagas/index.js
packages/truffle-debugger/lib/data/selectors/index.js
packages/truffle-decode-utils/src/definition.ts
packages/truffle-decoder/lib/decode/index.ts
packages/truffle-decoder/lib/interface/index.ts
packages/truffle-decoder/lib/read/index.ts
packages/truffle-decoder/lib/read/stack.ts
packages/truffle-decoder/lib/types/pointer.ts

The primary purpose of this PR is to fix stack allocation for input parameters to functions.  The existing allocation algorithm assumed all stack variables take up a single word; however, some -- specifically, external functions and some calldata pointers -- take up two.  Since we process input parameters from right to left, this could cause decoding errors for any input parameter which had a two-word input parameter somewhere to the right of it, as its stack allocation would be incorrect.
To accomplish this, the `StackPointer` type has been redefined; instead of containing just a single number, it now contains `from` and `to` numbers.  A new file, `read/stack.ts`, with a function `readStack`, has been added to the decoder, and the `read` function now calls this instead of reading from …

Fix stack allocation

---

packages/truffle-box/package.json

It takes about 3 seconds (default timeout is 2 seconds) on my network to fetch the default package from GitHub. I have a 100mbit line but the peering between GitHub and my ISP just sucks. I suppose there must be others with not so great internet connections that will benefit from the increased timeout.

Increased unbox test timeout

---

packages/truffle-compile/compilerSupplier/loadingStrategies/LoadingStrategy.js
packages/truffle-compile/test/compilerSupplier/loadingStrategies/LoadingStrategy.js

solc-bin.ethereum.org has been causing problems.
We have configured solc.trufflesuite.com to serve 302 redirects to the underlying ethereum.github.io/solc-bin resource, to make it easier to handle service availability in the future, without requiring subsequent upgrades of Truffle.

Use solc.trufflesuite.com URL for solc-bin fetching

---

.eslintrc.json
packages/truffle-compile-vyper/index.js
packages/truffle-compile/index.js
packages/truffle-compile/profiler.js
packages/truffle-core/test/compile.js
packages/truffle-workflow-compile/index.js
yarn.lock

Include solc version in the output during compilation and update some syntax.
Additionally, this restructures the compilation code so that when errors occur they are not swallowed.

Compiler version output

---

packages/truffle-debugger/test/data/ids.js
packages/truffle-debugger/test/data/more-decoding.js
packages/truffle-debugger/test/helpers.js
packages/truffle-debugger/test/reset.js
packages/truffle-debugger/test/solidity.js

This PR is just some internal improvements to the debugger tests.  Specifically, a number of the existing debugger tests involved hardcoded breakpoints, which was hard to read and easy to accidentally get wrong by 1.  This PR adds a `lineOf` function in `test/helpers.js`, which will search for the first line on which a given string occurs.  Now you can set breakpoints with `lineOf`, perhaps searching for a "break here" comment that you have placed.  Moreover, all existing tests that used hardcoded breakpoints have been converted to use this instead.

Avoid raw line numbers in debugger tests with lineOf function

---

packages/truffle-core/lib/commands/debug.js
packages/truffle-debug-utils/index.js

This pull request was inspired by the earlier PR #1346 which seems to have been left to languish.  As was pointed out there, there already is a step counter display, which is visible when using the `p` or `;` commands, so we don't need to add one, really, but I thought I'd make it a bit more obvious that that's what it was by including along with it a display of the total step count.  I also changed the step counter display to be 1-indexed rather than 0-indexed, because it looks pretty odd when it finally stops at `(236/237)`.
In addition, I added a gas remaining display to the `p` and `;` commands as well, because I expect someone will want it; and what with the removal of `msg.gas` in Solidity 0.5.0, this won't be part of the globally-available variables effort that's coming later, so I …

Add total steps and gas displays to 'p' and ';' commands

---

packages/truffle/test/scenarios/migrations/errors.js

Looks like latest geth client throws the following when truffle attempts to migrate w/o enough gas:
```
Error:  *** Deployment Failed ***
"SampleContract" -- The contract code couldn't be stored, please check your gas limit..
```
Updated `migration/errors.js` scenario test to handle this case.

Fix CI Geth Build

---

.travis.yml

CI node 6 build no longer needed since we currently maintain & support v5 & up moving forward.
🍬

Remove v4 CI node 6 build

---

packages/truffle-debugger/package.json
yarn.lock

This PR updates the version of `reselect-tree` used in the debugger (the one change in `reselect-tree` being updating what version of `reselect` is used).

Update reselect-tree version

---

packages/truffle-migrate/resolverintercept.js

Ref: #1738 
Strip off all leading path information, so that, e.g., `"./Migrations.sol"` resolves to the `"Migrations"`.
This relies on the existing limitation that contracts may not share the same name. See #1087 for related issue about this limitation.

Use only contract name for resolver intercept cache

---

packages/truffle-debugger/test/data/more-decoding.js

Some of the tests in `more-decoding.js` were quite slow so I stripped them down a bit so they'd be faster.

Strip down some decoding tests to run faster

---

packages/truffle-core/lib/testing/testrunner.js

Concerning https://github.com/trufflesuite/truffle/issues/1733
I included the values and types (they were unused so far and eslint complained) of all event variables
into the transcript of fired events that get printed when tests fail.

add values and types to events transcript

---

packages/truffle-core/lib/commands/debug.js
packages/truffle-debug-utils/index.js
packages/truffle-debugger/lib/controller/actions/index.js
packages/truffle-debugger/lib/controller/reducers.js
packages/truffle-debugger/lib/controller/sagas/index.js
packages/truffle-debugger/lib/session/index.js

This PR allows one to advance the state a specified number of steps by specifying the number after the `;` command.  I've also updated the help text to mention this.  This PR was inspired by the discussion in PR #1346, and I'm hoping it successfully addresses the problems raised there.
Note that this is our first (intentional) example of a command with an argument being repeatable.  The way I set it up is so that if you repeat it, the argument is lost on repeats; so that `; 3`, followed by a repeat, yields 4 steps, not 6.  Not sure if this is the best way, just what I figured made sense.

Add multiple-advance command

---

package.json
packages/truffle-core/lib/commands/obtain.js
packages/truffle-core/test/lib/commands/obtain.js

Update `truffle obtain` to use '--compiler=version' syntax. Also update the postinstall script to use this syntax to be more clear to the user when installing Truffle.

Update `truffle obtain`

---

packages/truffle-core/lib/commands/develop.js

This PR aims to fix the broken `truffle develop` MetaMask compatibility for the latest ver of MetaMask (6.1.0).
Issue has been raised here by @jgege (#1761) as well as here [MetaMask/metamask-extension#6211](https://github.com/MetaMask/metamask-extension/issues/6211).

Fix truffle develop MetaMask compatibility

---

packages/truffle-artifactor/package.json
packages/truffle-contract/package.json
packages/truffle-core/package.json
packages/truffle-debugger/package.json
packages/truffle-deployer/package.json
packages/truffle-hdwallet-provider/package.json
packages/truffle-provider/package.json
packages/truffle/package.json
yarn.lock

* truffle: 2.3.3 →  2.5.1
* truffle-artifactor: 2.3.3→  2.5.1
* truffle-contract: 2.3.3→  2.5.1
* truffle-core: 2.3.3 →  2.5.1
* truffle-debugger: 2.3.3 →  2.5.1
* truffle-deployer: 2.3.3→  2.5.1
* truffle-hdwallet-provider: 2.3.3→  2.5.1
* truffle-provider: 2.3.3→  2.5.1

Upgrade dependency: ganache-core@2.5.1

---

packages/truffle-debugger/lib/data/selectors/index.js

This PR address issue #1752, where, if a contract `Base` has a subclass `Derived`, and `Derived` has state variables but `Base` does not, the debugger would crash on startup.  (It also fixes a bug where, if `Base` has state variables but `Derived` does not, the state variables in `Base` would not be recorded as inherited by `Derived`.)
The problem is that, under the `SCOPE`/`DECLARE` system, `variables` state for a contract isn't created unless that contract has at least one state variable.  Unfortunately, this is hard to change; so `data.info.scopes.raw` (and its inlined counterpart) will continue to have `variables` undefined for such contracts.  However, I added something to account for this possibility in `data.info.scopes`, so this will no longer cause a crash, and in …

Fix crash resulting from contracts without state variables

---

packages/truffle-core/lib/commands/develop.js
packages/truffle-debugger/test/data/ids.js

This PR modernizes, streamlines, & enhances the configurability of `truffle develop`.
It enables the following `ganache-core` options to be pre-configured:
- `host`
- `port`
- `network_id`
- `gasLimit` (gas)
- `gasPrice`
- `hardfork`
Example `truffle-config.js`:
```
networks: {
develop: {
host: "127.0.0.1",
port: 7545,
network_id: 666,
gas: 1000,
gasPrice: 1,
hardfork: "constantinople"
}
}
};
```

Enhance truffle develop configurability

---

packages/truffle/cli.webpack.config.js

I saw a lots of duplicated bn.js codes in bundled file really big,  and that annoy me to hack the big number issue.

to avoid duplicated bn.js in bundled files.

---

packages/truffle-debugger/lib/data/sagas/index.js

This PR adds partial support for modifier parameters, which previously would not appear in `data.proc.assignments`.  Unfortunately many modifiers skip right over the modifier definition node while debugging, so many modifiers will still not have their parameters appear in `data.proc.assignments` and still will not be able to have their parameters decoded.  Still, for what it's worth, this catches some of them.

Add partial support for modifier parameters

---

packages/truffle-core/lib/commands/develop.js

Fix problem where the console was not being started as part of the callback from environment detection. This resulted in `from` not being available as a default for contract transactions inside `truffle develop`.

Fix missing callback linkage

---

packages/truffle-decoder/lib/decode/storage.ts

This PR fixes a bug raised in issue #1787.  The code for decoding a storage local variable mistakenly does not pass along necessary information to the `storageSize` function.  (Maybe it was a mistake leaving those arguments optional!)  Now it does.

Fix bug with storage locals

---

packages/truffle-migrate/resolverintercept.js

Ref: #1791 
Replace basename stripping with more flexible stripping of leading `./` and trailing `.sol`

Remove resolver intercept cache basename logic

---

packages/truffle-core/lib/version.js

Add web3 version to the list of things that get logged when using 'truffle version'

Add web3 version logging output

---

packages/truffle-compile/profiler.js
packages/truffle-contract-sources/index.js

This PR allows users to run `truffle test` in a truffle vyper project w/o needing to first run `truffle compile`.
This is accomplished by:
- adding the `.vy` file pattern to `truffle-contract-sources/index.js`
- skipping attempts to parse `.vy` files for imports (imports unsupported in vyper)
- skipping attempts to add `.vy` files to solc dependency compilation attempts

Enable out-of-box `truffle test` support for vyper projects

---

packages/truffle-compile/compilerSupplier/loadingStrategies/LoadingStrategy.js
packages/truffle-compile/compilerSupplier/loadingStrategies/VersionRange.js
packages/truffle-compile/package.json
packages/truffle-compile/test/test_supplier.js
packages/truffle-config/index.js
yarn.lock

This PR attempts in part to resolve a permissions issue that plagues many Truffle users. Some poor, unsuspecting folks have installed Truffle or npm using sudo and have been, as a result, experiencing issues with writing to the cache directory. This changes the cache directory to be something much less likely to experience permissions issues.
The new directory to be used is the same that the user-level config for mnemonics etc. uses, namely `~/.config/truffle/` in which a `compilers` directory will be located for cacheing compilers.

Change cache path

---

packages/truffle-decoder/lib/interface/contract-decoder.ts
packages/truffle-decoder/lib/interface/index.ts
packages/truffle-decoder/lib/types/evm.ts

This PR addresses issue #1597, allowing an address to be provided manually (as a string) in the contract decoder.  (The particular format of the address is, anything that's good enough for Web3; we don't process this address at all.)  Note that we do not create a whole `networks` member of the contract object, we just manually set the address -- that should be good enough for our purposes.
In addition, while doing this I took a moment to eliminate the now-unused `variables` field from the `EvmInfo` type.  This should not be a functional change.

Add address parameter to contract decoder

---

packages/truffle-decoder/lib/decode/calldata.ts

This PR factors out calldata struct decoding into its own function to reduce the amount of copypaste.  It contains no functional changes (or at least, it shouldn't).
Notes:
1. I didn't factor out array decoding; I didn't think that really needed it.
2. I didn't include memory struct decoding, even though that also works essentially the same now, because, well, that wouldn't have been so convenient.  In any case I think the copypaste, while not gone, is now down to levels I'd consider acceptable.

Factor out calldata struct decoding

---

packages/truffle-debugger/test/data/calldata.js
packages/truffle-debugger/test/data/ids.js
packages/truffle-debugger/test/data/more-decoding.js
packages/truffle-debugger/test/data/utils.js
packages/truffle-debugger/test/endstate.js

Earlier, out of laziness, I wrote a number of tests that just used deep equality to compare structures filled with BNs.  In fact it's probably faster to clean those BNs to numbers before comparison.  So in this PR I do that.  (I also delete that dummy address test, although of course this change is also made in my PR that removes the dummy address system.)

Clean BNs before comparison to speed up Travis

---

packages/truffle-debugger/lib/session/sagas/index.js
packages/truffle-debugger/lib/trace/sagas/index.js
packages/truffle-debugger/lib/web3/actions/index.js
packages/truffle-debugger/lib/web3/sagas/index.js
packages/truffle-decode-utils/src/constants.ts
packages/truffle-decode-utils/src/evm.ts

This PR adds addresses created during a transaction to the internal list of addresses (which is used for both fetching instances and for displaying addresses affected).  It also fixes a bug in #1814 where if the initial call of the transation was a creation, its storage address would not be obtained properly due to a misnamed variable.
Aside from the bug fix, the effects of this PR are mostly internal -- it does mean that creation calls now show up in "addresses affected", which is nice but minor.  The main point is really setting things up for later when I implement internal function decoding.  I'm not entirely certain whether it's needed for that, but, whatever, we can always take it out later if it's a problem.
Note that because this address list is used for fetching binaries, *failed* …

Include creation calls in the list of addresses

---

packages/truffle-core/lib/version.js

Access the web3 version information through the version property on the Web3 object rather than the package.json information.

Edit method for version info

---

packages/truffle-debugger/lib/data/selectors/index.js
packages/truffle-debugger/lib/evm/actions/index.js
packages/truffle-debugger/lib/evm/reducers.js
packages/truffle-debugger/lib/evm/sagas/index.js
packages/truffle-debugger/lib/evm/selectors/index.js
packages/truffle-debugger/test/data/codex.js
packages/truffle-debugger/test/reset.js

This PR gives the debugger the ability to track storage across call boundaries.  The debugger still can't track storage across transaction boundaries; storage that hasn't been touched (i.e., read from or written to) within the current transaction will still show up as 0.  However, now, if one call within the transaction touches a storage slot, all calls within that transaction sharing that storage address will be able to see it.
This PR is the start of what I'm calling the "codex" -- an effort to have the debugger keep track of the state itself, instead of being totally helpless when the trace won't tell us things directly.  (Arguably, keeping track of calldata was also part of this.)  However, right now we only really need to do this for storage, so, I'm not introducing anything else …

Track storage across intra-transaction call boundaries

---

packages/truffle-core/lib/testing/deployed.js
packages/truffle-core/lib/testing/testsource.js

Truffle v5's release & default support for solidity 0.5.0 introduced a number of breaking changes & necessary quick-response stop gap measures.
This PR addresses one of those stop gaps (#1817), allowing backwards-compatible solidity unit testing for users still developing with `0.4.xx`.
🍻

Enable backwards-compatible 0.4.xx solc unit testing

---

packages/truffle-contract/lib/execute.js
packages/truffle-contract/lib/statuserror.js
packages/truffle-contract/lib/utils.js
packages/truffle-contract/package.json
packages/truffle-interface-adapter/lib/ethereum-overloads.js
packages/truffle-interface-adapter/lib/quorum-overloads.js
packages/truffle-interface-adapter/lib/web3-shim.js
packages/truffle-reporters/reporters/migrations-V5/reporter.js

This extends on #1806 by adding support for Quorum's ability to have 54+ bit block gas limits.
This is blocked by merging #1806 just because it's based off those commits, so the changes here are going to look like more than they actually are. **You can look at the compare here in the meantime**: https://github.com/trufflesuite/truffle/compare/adapter/init-and-quorum...adapter/large-gas

Support Hexstrings and BNs for Gas to Support Quorum's Potential Large Block Gas Limits

---

packages/truffle-core/lib/commands/develop.js

This PR is a fix for #1824 .
Since `truffle develop` is now configurable, we need to sanitize & handle invalid `network_id` values.
☕️

Handle non-integer `truffle develop` network_id values

---

packages/truffle-core/lib/commands/debug.js

Right now, if you have multiple watch expressions, the order of printing is jumbled so that watch expressions don't necessary appear with their corresponding values.  This is because the printing is done with the parallel `Promise.all`.  This PR replaces this with a simple `for` loop so that things print out in order and you can tell which values go with which watch expressions.

Print watch expressions with their values rather than jumbled

---

packages/truffle-core/lib/commands/debug.js
packages/truffle-debug-utils/index.js

Watch expressions have something of a problem with complex objects, as used for representing, say, structs.  If you use a colon expression with such a thing (whether you're making it into a watch expression or not), an unexpected `constructor: undefined` will appear among its properties.  Worse, after doing so, you'll see the same thing even when you just type `v`, which normally does not have this problem!
As best I can tell, this is a problem with `safeEval`, as used by the CLI -- somehow it is altering objects to include this.  That's my inference, anyway.  I don't know how to prevent this, so this PR instead just adds a function to the CLI to strip such things out.  It's pretty hacky, but it seems to work.  Note that the call is made inside `formatValue` in order to prevent the …

Prevent {constructor: undefined} problem with watch expressions

---

packages/truffle-decoder/lib/decode/storage.ts

The decoding logic for `string` and `bytes` in storage includes a special case for when the length is 0, returning the empty string.  However for `bytes` we don't want the empty string, we want `"0x"`.  There's really no need for a special case here, so I just deleted it and now it works fine.

Fix decoding of empty bytes type in storage

---

packages/truffle-debugger/lib/data/sagas/index.js
packages/truffle-debugger/lib/data/selectors/index.js
packages/truffle-debugger/lib/solidity/selectors/index.js

This PR is a companion to #1839.  It should get us back to where we were before Solidity 0.5.6 came out; namely, it should once again be the case that all mapping keys work except for some constant state variables.  (Well, and `msg.data` -- a case that was in fact already a problem before 0.5.6, but which I failed to notice -- but that's what #1839 is for.)
You see, calldata mapping keys work fine when they're a top-level variable.  And unsurprisingly they work fine when they're value types.  But, if they're of type `bytes` or `string`, and are not top-level but rather are an element of a calldata array or struct, they don't work.  Now, before Solidity 0.5.6, this wasn't a problem, because before Solidity 0.5.6, it wasn't legal to put a `string` or `bytes` inside a calldata array or …

Fix calldata mapping keys for Solidity 0.5.6

---

packages/truffle-core/lib/commands/migrate.js

Documents the `--to` flag for running migration files up to a specific number.
📝

Document `truffle migrate` --to flag

---

packages/truffle-core/lib/commands/migrate.js

Adds & documents a `--from` flag for running migration files from a specific number.
🎏

Add & document --from flag to `truffle migrate`

---

packages/truffle-hdwallet-provider/README.md

It was not clear in the documentation that HDWalletProvider is compatible with Web3. Added code snippet for using HDWalletProvider with new and existing Web3 instance.

Update readme: how to use truffle-hdwallet-provider with Web3

---

packages/truffle-compile/compilerSupplier/loadingStrategies/LoadingStrategy.js
packages/truffle-compile/test/test_supplier.js

Change the `compilerCachePath` to cache compilers in a `node_modules` directory (`~/.config/truffle/compilers/node_modules/`).
This helps truffle users avoid the issue outlined in #1813.
Also indirectly related to #1835 .

Fix compiler cache path

---

packages/truffle-debugger/test/data/calldata.js

This test was timing out too often, so I stripped it down a bit.  It used to test decoding for a `string`, a `bytes`, a statically-sized array, a dynamically-sized array, and a struct.  I removed the `bytes` (basically redundant with string) and the statically-sized array.

Strip down calldata test to reduce timeouts

---

packages/truffle-debugger/lib/controller/actions/index.js
packages/truffle-debugger/lib/controller/sagas/index.js
packages/truffle-debugger/lib/session/index.js
packages/truffle-debugger/test/solidity.js

Background: Originally breakpoints were stored in the CLI, not the debugger state; the debugger exposed a function to stop at a specified breakpoint, but you had to supply the list of breakpoints yourself.  Later I moved them into the debugger state, exposing functions to add and remove breakpoints instead of having the list of breakpoints be an input to the `continueUntilBreakpoint` function.
However, I recently realized that if you're using the debugger as a library, this isn't necessarily a convenient interface.  So, I decided to add the old way back in as another way of doing things.  The `continueUntilBreakpoint` function now takes as an optional argument a list of breakpoints.  If supplied, it will continue to one of these breakpoints, rather than using the list stored in the state. …

Restore ability to use external list of breakpoints

---

packages/truffle-debugger/lib/evm/actions/index.js
packages/truffle-debugger/lib/evm/reducers.js
packages/truffle-debugger/lib/evm/sagas/index.js
packages/truffle-debugger/lib/evm/selectors/index.js
packages/truffle-debugger/lib/solidity/actions/index.js
packages/truffle-debugger/lib/solidity/reducers.js
packages/truffle-debugger/lib/solidity/sagas/index.js
packages/truffle-debugger/lib/solidity/selectors/index.js
packages/truffle-debugger/lib/trace/selectors/index.js
packages/truffle-debugger/test/data/codex.js
packages/truffle-debugger/test/solidity.js
packages/truffle-decode-utils/src/definition.ts

Previously, the Truffle Debugger did nothing to handle exceptional halting.  Now, in Solidity, this usually isn't much of a problem, because if one call in the transaction reverts, the entire transaction reverts in short order.  However, this isn't necessarily the case; by using `<address>.call()` (and related functions), one may catch an exceptional halt and resume execution.  As such, we need to be able to handle this case.  This requires additional state to be tracked in both the `evm` and `solidity` submodules.
Before we get to this additional state, though, let's discuss how we detect exceptional halting in the first place.  We can't just look for the `REVERT` or `INVALID` opcodes, as there's any number of ways an exceptional halt might occur.  Thus, we detect an exceptional halt as …

Properly handle failed calls

---

packages/truffle-compile/index.js
packages/truffle-contract-schema/index.js
packages/truffle-contract-schema/spec/contract-object.spec.json
packages/truffle-contract-schema/test/solc.js
packages/truffle-contract/lib/contract/properties.js

This PR stores solc's metadata output in the artifact json on successful compilation.

Add solc metadata output

---

packages/truffle-debugger/lib/solidity/selectors/index.js

This PR changes the default sourcemap used when we can't locate a sourcemap.  The existing fallback mapped the source as progressing character-by-character through source file number 1 (whichever one that is), and always jumping outward.  The effect of this was that when no sourcemap was found, `stepNext` would progress instruction by instruction.  The other effect of this, however, is that it would screw up your Solidity stackframe so you wouldn't see the right variables.
The new fallback instead maps the source as being Solidity-internal and not containing any jumps inward or outward.  Note that this *is* a change in behavior; `stepNext` will now skip over such code instead of going through it one instruction at a time.  If you want to go through it one instruction at a time, though, …

Alter no-source-map fallback to treat as unmapped

---

packages/truffle-compile/compileerror.js
packages/truffle-compile/index.js
packages/truffle-compile/profiler.js

This PR attempts to provide more helpful output when attempting to compile a truffle project using pragma solidity statements incompatible with the currently loaded solc compiler.
<details><summary>Example using truffle out-of-the-box on a solc 0.4.25 file:
</summary>
```
$ truffle compile
Compiling your contracts...
===========================
> Compiling ./contracts/ConvertLib.sol
/Users/cruzmolina/Code/truffle-projects/metacoin/contracts/ConvertLib.sol:2:1: SyntaxError: Source file requires different compiler version (current compiler is 0.5.0+commit.1d4f565a.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.4.25;
^---------------------^
Error: Truffle is currently using solc 0.5.0, but one or more of your …
```

Improve mismatched solc version & pragma statement erroring

---

packages/truffle-debugger/lib/evm/reducers.js
packages/truffle-debugger/test/context.js
packages/truffle-debugger/test/data/codex.js
packages/truffle-debugger/test/data/ids.js

This PR is just a slight update to #1855.  I decided that the `LOAD` case of the `codex` reducer wasn't commented enough so I added some comments.  (Specifically, I was worried that some future person looking at it would think it looks wrong and attempt to "fix" it, so I added some comments explaining why it works the way it does.)  Also, I added a bit more to the tests I added in that PR, so that now some of the `LOAD` case is tested as well, not just the `STORE` case.  Finally, while doing this I noticed that an old test was still lowercasing addresses before comparison, which should no longer be necessary, so I removed the conversion to lowercase.  That's all, just minor internal stuff.

Add some comments and tweak some tests

---

packages/truffle-core/lib/commands/debug.js
packages/truffle-debug-utils/index.js

(Edit: The original verison of this PR had some mistakes, I've edited the text below to match the current version.)
This PR makes it so that watch expressions are treated differently based on whether or not they consist of just a single variable.  Now, when a watch expression does not just consist of a single variable, the `variables` object is first run through an additional `nativize` step before the watch expression is evaluated.  This step converts `Map`s to plain old objects and `BN`s to numbers (although this may cause an error).  The point of this is to allow arithmetic operations and indexing to work normally, just as it would in Solidity, without the user having to use `BN` operations or `get()`.
This does mean that the same object can print out differently depending on whether …

Split off watch variables from watch expressions and make the latter work better

---

packages/truffle-debugger/lib/evm/selectors/index.js
packages/truffle-debugger/lib/helpers/index.js

The debugger had checked for normal halting by checking for `STOP` or `RETURN`.  However, `SELFDESTRUCT` is also a normal halting instruction.  Since a contract that `SELFDESTRUCT`s is not actually deleted until the transaction is finished, this could potentially be relevant.  In any case, this PR fixes that.

Add SELFDESTRUCT as normal halting

---

packages/truffle-decoder/lib/interface/contract-decoder.ts

This PR fixes [this issue](https://github.com/trufflesuite/ganache/issues/1117) that was reported over on the Ganache repo.  The problem appears to be that Ganache passes all contracts in to the contract decoder as relevant contracts, even ones that aren't Solidity.  These don't have an AST, and, as such, cause an error when we try to find their contract node.  So, I've changed the code for getting the contract nodes so it will skip any lacking an AST (or that have an AST but can't find the contract node for whatever reason).

Skip getting contract node if there's no AST

---

packages/truffle-core/lib/commands/debug.js
packages/truffle-debug-utils/index.js

The lack of a PC display in the CLI had been bugging me, so this PR adds one.  Of course, it is only shown when pressing `p` or `;`.  I also got rid of a redundant use of an `evm` selector when we already had that same information available from the `trace` selector we were already using.

 Add PC display to debugger CLI

---

packages/truffle-core/lib/test.js

Currently `truffle test` turns `import_paths` of solidity unit tests into relative file basename paths.
Instead, it should use the full `test_file_path` like the rest of truffle to accurately resolve `import_paths` and return contract artifacts.
Potentially resolves #700, #450, & #1795.

Fix solidity unit test import_paths

---

package.json

This postinstall script is unnecessary and can be removed. It was originally mistakenly intended to be a post-install hook for users installing Truffle from npm. However, this is actually a post-install hook for users cloning Truffle and installing the dependencies through npm.

Remove postinstall script to install solc

---

packages/truffle-core/lib/commands/debug.js
packages/truffle-debug-utils/index.js
packages/truffle-debugger/lib/ast/map.js
packages/truffle-debugger/lib/controller/sagas/index.js
packages/truffle-debugger/lib/controller/selectors/index.js
packages/truffle-debugger/lib/helpers/index.js
packages/truffle-debugger/lib/session/index.js
packages/truffle-debugger/test/solidity.js

This PR addresses issue #1317, at least partially.  It introduces a selector, `controller.breakpoints.resolver`, that, given a breakpoint, returns where it should be moved down to.  The CLI now runs all breakpoints through `controller.breakpoints.resolver` before adding them (and reports back to the user where the breakpoint was *actually* added).  Note that the resolver may return `null` if there is nowhere suitable below to place a breakpoint; in this case the CLI will not add a breakpoint.
Note that the resolver does not work perfectly -- it's something of a hack -- but it should be good enough for common cases; see below for more explanation.  Also note that attempts to *remove* breakpoints are not run through the resolver.  But that's OK, because (in addition to the messages above), …

Move down breakpoints when placed on empty/skipped lines

---

packages/truffle-box/lib/utils/index.js

When the `setUpBox` method failed, it would previously catch the error. This caused this step to fail and ultimately swallow the error, continue unboxing, and report a successful unbox. The error is now thrown and will cause the failure to be reported to the user.

Throw error instead of catching and hiding it

---

packages/truffle-core/lib/commands/migrate.js

This PR adds a tiny fix to make sure we `parseInt` `config.network_id` before checking if the given network is in the `networkWhitelist`.
Based on the truffle config provided in #1322 (https://github.com/DataBrokerDAO/dtx-crowdsale-contracts/blob/master/truffle.js), it looks like this fix resolves that issue.

Parse string numbers from config.network_id during dry-run check

---

packages/truffle-reporters/reporters/migrations-V5/reporter.js

As discussed elsewhere (paritytech/parity-ethereum#8788, paritytech/parity-ethereum#6334, INFURA/infura/issues/43) & raised in #1895, sometimes nodes will return `null` during `getBlock` calls (usually when calling recent/latest blocks). Currently, when this happens it completely ruins the deployment experience. This PR catches falsy values & recursively calls `postDeploy` again.

Handle `null` getBlock returns during live/testnet migrations

---

packages/truffle-core/lib/commands/migrate.js

Edit the help for the migrate command. Document the `--dry-run` and `--skip-dry-run` flags.
In addition, rename a few variables to make the code a bit clearer and update some syntax.

Dry run edit

---

packages/truffle-compile/profiler.js

Handles scenarios where solc doesn't output the pragma statement for source files requiring a different solc compiler version. (Known bug for 0.5.2 thru 0.5.6, but fixed in 0.5.7 [ethereum/solidity#6331]).
Resolves #1896 .

Handle unmatched solc parsing error output 

---

packages/truffle-artifactor/README.md
packages/truffle-artifactor/index.js
packages/truffle-artifactor/test/contracts.js
packages/truffle-artifactor/test/customoptions.js
packages/truffle-artifactor/test/networksave.js
packages/truffle-core/lib/testing/soliditytest.js
packages/truffle-workflow-compile/index.js

This PR updates the documentation to `truffle-artifactor`'s current behavior & API. Also burns some code bringing the package up to ES6, converts the API into async methods, & intends to make the code easier to reason while debugging.
Resolves #1096.

Update truffle-artifactor (docs & codebase)

---

packages/truffle-core/lib/commands/migrate.js
packages/truffle-solidity-loader/README.md
packages/truffle-solidity-loader/index.js
packages/truffle-solidity-loader/lib/genBuildOptions.js
packages/truffle-solidity-loader/lib/getTruffleConfig.js
packages/truffle-solidity-loader/lib/logDecorator.js

This PR primarily reverts #1841 which introduced a bug by aliasing the `--from` flag to `--f`. Doing so, blocked the ability to use `truffle-core` as a standalone pkg which can be passed an address in the form of `config.from` or `options.from`. While in the weeds, I went ahead and updated the documentation & some of the codebase.
Resolves #1870.

Fix truffle-solidity-loader bug & update pkg (docs & codebase)

---

packages/truffle-db/package.json
packages/truffle-db/src/workspace/test/index.ts
yarn.lock

This PR introduces a `WorkspaceClient` helper class for the workspace tests, to make it easier to issue more than one request to graphql in a single test. I added this since I discovered the problem with the tests on the target branch (#1916): compilation wasn't getting added before contract, so the lookup was failing.
This also includes the addition of the `graphql-tag` package, to enable `gql` template strings, e.g.:
```javascript
const GetContractNames = gql`query GetContractNames { contractNames }`
```
Refactoring changes:
- Re-order tests so they're organized by resource type.
- Define WorkspaceClient class to abstract the graphql inner workings
- Start using gql` ... ` tag for test queries
- Switch from using `graphql()` to using graphql's `execute()` function,
since the former only …

Refactor workspace tests and get them passing

---

packages/truffle-hdwallet-provider/README.md
packages/truffle-hdwallet-provider/package.json
packages/truffle-hdwallet-provider/src/index.js
yarn.lock

This PR updates `truffle-hdwallet-provider`'s documentation (clarifies current web3.js compatibility version requirement & updates truffle project example to match infura's updated API), upgrades `web3-engine-provider` dep to latest, & adds a shim to support `sendAsync` methods. Also adds `web3@1.0.0-beta.37` as a dependency to temporarily relieve friction between users & current web3 compatibility issues.
Potentially resolves #1746, #1643, #852, & #1874.

Update truffle-hdwallet-provider (docs & codebase)

---

packages/truffle-decoder/lib/interface/contract-decoder.ts

This PR fixes how the network ID is obtained in the contract decoder.  Rather than reading the first network ID from the artifact, instead it uses a `web3` call.  Note this is now done in `init` (which, recall, is now `async`) rather than in the constructor.  This also means that, if an address was not passed in manually, the address will not be obtained until `init` is run.

Fix getting network in contract decoder

---

packages/truffle-debugger/lib/data/sagas/index.js
packages/truffle-debugger/lib/data/selectors/index.js
packages/truffle-debugger/lib/solidity/selectors/index.js
packages/truffle-debugger/test/data/function-decoding.js
packages/truffle-decode-utils/src/constants.ts
packages/truffle-decode-utils/src/contexts.ts
packages/truffle-decode-utils/src/evm.ts
packages/truffle-decoder/lib/allocate/storage.ts
packages/truffle-decoder/lib/decode/value.ts
packages/truffle-decoder/lib/interface/contract-decoder.ts
packages/truffle-decoder/lib/types/evm.ts

This PR adds support for decoding internal function pointers.  Note that this is supported only in the debugger, not in the contract decoder; attempting to decode an internal function pointer from the contract decoder will simply result in the string `"<decoding not supported>"`.
This PR also fixes a bug in my previous PR for decoding external functions.  In that PR, contexts in the decoder were indexed by contract ID rather than by hash.  However, this causes a problem in that not every context has a contract ID.  This PR changes it so that contexts in the decoder are indexed by... whatever.  (When used from the debugger, it's back to hashes.  When used from the contract decoder, I've left it as contract IDs.)
So, why is decoding for internal functions only supported from the debugger? …

Add decoding for internal functions (debugger only)

---

packages/truffle-debugger/lib/data/selectors/index.js
packages/truffle-debugger/lib/session/index.js

This PR fixes the spoofing of the definition of `this` so that it's based what contract one is in in terms of what node one is on, rather than based on `evm.current.context`.  I originally based it on `evm.current.context` because this meant that we didn't need to be on a node to have a definition.  However, I failed to notice that this does not always yield the correct result, if inheritance or library `internal` functions are involved.
So, I have fixed it to be based on what node one is on.  Note that if one is in unmapped code, there will be no definition, and so `this` will be excluded from the current variables.  That could be considered a regression, I suppose, but I think it's probably OK.  (Remember, until recently attempting to get the variables while in unmapped code simply …

Fix spoofing of "this" definition

---

packages/truffle-hdwallet-provider/package.json
packages/truffle-hdwallet-provider/src/index.js

Updating `truffle-hdwallet-provider`'s `web3-engine-provider` dep in #1897 broke live deployments! It appears the API changed for `web3-engine-provider` and a quick downgrade seems in order.
Resolves #1928.

Revert truffle-hdwallet-provider breaking change dep update

---

packages/truffle-compile-vyper/index.js
packages/truffle-compile-vyper/test/test_compiler.js

Can switching on/off by truffle-config.js for older vyper.
example:
```
vyper: {
source_map: true
}
}
```

Support source map option when compile using vyper.

---

packages/truffle-core/lib/testing/deployed.js
packages/truffle-core/lib/testing/soliditytest.js

This PR enables `native` solc usage during solidity unit testing.
🌴

Enable native solc usage for solidity unit testing

---

packages/truffle-decoder/lib/allocate/general.ts
packages/truffle-decoder/lib/allocate/storage.ts
packages/truffle-decoder/lib/types/errors.ts

This PR is to help address [Ganache issue 1169](https://github.com/trufflesuite/ganache/issues/1169) and related issues.  It is *not* a fix; truly fixing it would require changes to `truffle compile`, so I'll have to talk to @eggplantzzz about that, although it may turn out that a proper fix is not feasible until truffle-db is ready (hopefully not though).
In any case, what this PR *does* do is to throw a specific error type when this error condition occurs -- an `UnknownBaseContractIdError` -- so that Ganache can catch it and respond appropriately (such as by simply not decoding that contract's state) rather than crashing.  So, @davidmurdoch, consider yourself alerted!
Anyway hopefully we'll have a proper fix soon, otherwise for now we can tell people to use the workaround of recompiling …

Throw specific error when can't find base contract during allocation

---

.travis.yml
packages/truffle-contract/scripts/test.sh
scripts/ci.sh
yarn.lock

This PR refactors CI tests to only install external dependencies for relevant jobs. Also ensures only relevant tests for each job are ran (i.e. geth tests in `truffle-contract` now skipped in non-geth jobs).
Specific streamlined dependencies:
`docker pull` for `solc` & `geth`, `apt-get` for `jq` & `snapd`, & `snap install vyper`.
Saves us ~4-5 min for the build.
Resolves #1336.
Also includes updated `yarn.lock` left out from #1930 .

Refactor Travis CI

---

packages/truffle-config/index.js
packages/truffle-core/lib/commands/migrate.js
packages/truffle-core/test/migrate.js
packages/truffle-migrate/index.js

Remove `skipDryRun` from the props in the config so that it can be set on the command line as a flag.

Reformat migrations and implement cleaner dry run behavior

---

packages/truffle-compile-vyper/index.js

For fixed error of `exceeded maxBuffer` when compiled too large Contract that has over 20KB bytecodes.
Maybe this error happens at apply the `sourceMap` option.

change: Change maxBuffer size to 600KB.

---

packages/truffle-contract/lib/utils.js
packages/truffle-contract/test/quorum.js

This PR enables Quorum private transactions by whitelisting the `privateFor` key as a valid transaction parameter.
Works toward resolving #1657.

Enable Quorum Privacy Transactions

---

packages/truffle-contract/test/quorum.js

This is the start of exploration to see how `privateFor` works within Truffle.
My first attempt was to ensure `privateFor` gets passed all the way down, past web3 and through the provider. I added a test to ensure this was the case, and I found that it does, but conditionally. You'll see in the test that without a parameter web3 expects (like `from`) `privateFor` is ignored. 
I don't yet know the problems Quorum users are having. Will add more to this PR as I explore. 
-------------
Issues identified (check-mark means fixed):

Quorum Exploration

---

packages/truffle-decode-utils/src/definition.ts
packages/truffle-decoder/lib/allocate/storage.ts
packages/truffle-decoder/lib/types/errors.ts

A quick addendum to the earlier #1933, this PR adds a similar error when we can't find an enum or struct definition during storage allocation.  Again, this is not a real fix, it's just throwing a specific error so that Ganache can catch it rather than crash.  But, this should provide a band-aid for such situations as [this old Ganache issue](https://github.com/trufflesuite/ganache/issues/1193).  So, @davidmurdoch, once again, consider yourself alerted, you now have a second type of error to catch.  Again, the workaround for now is to recompile (and if necessary redeploy) the project.

Add error for failure to locate struct or enum during storage allocation

---

packages/truffle-contract-schema/index.js

Somewhere (maybe in `truffle-contract`) there's a bug that adds function `signature`s to the ABI during migrations. By adding a check to `transform` and removing any present `signature` key in an `abi` array, this PR ensures that artifacts stay clean and `signature` free!
Potentially resolves #1889 by ensuring `signature`s aren't saved to the artifacts.

Retain clean artifacts by removing function signatures during schema normalization

---

packages/truffle-expect/README.md
packages/truffle-expect/index.js
packages/truffle-expect/package.json
packages/truffle-expect/test/index.js

This PR updates `truffle-expect`'s documentation, reworks a tiny bit of code & adds a bit of code coverage.

Update truffle-expect (mostly docs)

---

packages/truffle-decode-utils/tsconfig.json
packages/truffle-decoder/tsconfig.json
packages/truffle-interface-adapter/tsconfig.json

(internal improvement)
Noticed this when pulling `develop` into `truffle-db` cause `@types/mocha` conflicts with `@types/jest`.
Targeting `develop` to nip this in the bud.

Update tsconfig files to specify explicit @types dependencies

---

packages/truffle-external-compile/index.js

Ref: #1956 
This adds a new `working_directory` option for external compilers, changing the default directory for external commands as well as their outputs.

Add working_directory option for external compiler

---

.travis.yml
README.md
package.json
packages/truffle-contract-schema/package.json
packages/truffle-contract/package.json
packages/truffle-debugger/package.json
packages/truffle-decode-utils/package.json
packages/truffle-decoder/package.json
packages/truffle-resolver/package.json
packages/truffle/package.json
packages/truffle/scripts/prereleaseVersion.js
packages/truffle/scripts/test.sh
scripts/bootstrap.sh
scripts/ci.sh

Firstly, this fixes the circular dependency warnings by making the following packages into peer dependencies:
- truffle-resolver's truffle-contract
- truffle-decoder's truffle
Additionally, this fixes warnings about inconsistent node executables by finding and replacing all instances of package.json files defining scripts in terms of `npm run <script>`. `yarn <script>` is used instead in all cases now.

Fix yarn warnings

---

scripts/ci.sh
scripts/geth.sh

The geth CI job has been broken for a [few weeks](https://travis-ci.org/trufflesuite/truffle/builds/516498633) because geth now [requires](https://ethereum.stackexchange.com/questions/69435/error-account-unlock-with-http-access-is-forbidden-when-unlock-an-account-in-ge) you explicitly allow accounts to be unlocked via web3.  CI creates and funds several accounts using this method in [geth-accounts.js](https://github.com/trufflesuite/truffle/blob/develop/scripts/geth-accounts.js) 
There *is* a test failure in the production migrations tests [here](https://travis-ci.org/trufflesuite/truffle/jobs/526705708#L1418), but it's legit - there's actually a problem there.

Fix Geth in CI

---

.nycrc

Currently the `notes` directory is being included on Coveralls as a source file! (https://coveralls.io/github/trufflesuite/truffle)

Internal improvement: exclude notes from coverage

---

packages/truffle-hdwallet-provider/package.json

The homepage and bugs links in truffle-hdwallet-provider's `package.json` file were pointing to the deprecated repo which was very confusing in npm. They now point to the `truffle-hdwallet-provider` package in the truffle monorepo.

truffle-hdwallet-provider homepage and bugs links updated

---

packages/truffle-artifactor/test/contracts.js
packages/truffle-compile/index.js
packages/truffle-compile/test/test_ordering.js
packages/truffle-compile/test/test_supplier.js
packages/truffle-config/index.js
packages/truffle-contract/test/linking.js
packages/truffle-contract/test/util.js
packages/truffle-debugger/test/helpers.js
packages/truffle-decoder/test/truffle-config.js
packages/truffle-interface-adapter/typings/ganache-core/index.d.ts

Remove default evm version setting for solc in Truffle so that it uses the default unless specified otherwise by the user.

Default evm version

---

packages/truffle/package.json

PR removes `solc` as a separate bundle dep. `solc` is already bundled within `truffle-compile`.

Remove solc-js as an NPM dependency

---

packages/truffle-core/lib/commands/debug.js

This PR removes an error case that is no longer applicable as of the recent changes to `Environment.detect`.  This line wasn't removed from the debugger CLI and that causes it to crash.  This PR removes it.
(Yes, this line is already removed on `notx`, but I don't want to wait for that to be merged in!)

Remove error case that is no longer applicable to prevent debugger crash

---

packages/truffle-decoder/lib/interface/contract-decoder.ts
packages/truffle-decoder/lib/types/errors.ts

This PR causes the contract decoder constructor to throw an exception in case it can't locate the contract node for the contract being decoded, so that this case doesn't crash Ganache.
(Note that if a contract node can't be located *other* than the one for the contract being decoded, it's simply skipped; this is already existing behavior.  But you can't just skip the contract which is supposed to be decoded!)

Throw exception if contract decoder can't locate contract's node

---

packages/truffle-debugger/lib/ast/map.js

This PR fixes a crash that could occur when debugging contracts with inline assembly.  One of the attributes of an `InlineAssembly` node is `externalReferences`, and nested inside `externalReferences` one can find certain objects I'm calling "pseudo-nodes".  They're not actual nodes -- they lack an `id` and a `nodeType`.  But they do have a `src`, which could cause the debugger to land on them.  The lack of `id` would then cause a crash.
This PR fixes the problem by excluding such pseudo-nodes from the set of nodes the debugger can land on, by only putting nodes with actual IDs into the `IntervalTree`.  This means that instead of landing on these pseudo-nodes, the debugger will land on the `InlineAssembly` node they're a part of.
Note that I'm assuming that this is the only way to get …

 Prevent debugger from landing on pseudo-nodes with no id 

---

packages/truffle-core/lib/commands/test.js

Currently users can pass whatever network they like during testing (i.e. `truffle test --network ghostNetwork`). Regardless of whether network configs are present in their truffle config file, truffle will act as if that network actually exists 👻 .
Per #1993 , this behavior can be confusing 😕 so this PR ensures if a network is passed during testing, truffle will proceed to check if the network actually exists.
In general this code should probably be cleaned up and revamped, but for now I think this will suffice.

Fix: Detect test network existence before test run

---

packages/truffle-compile/profiler.js

Some situations (very hard to reproduce) were causing a "stack too deep" error.
I found the cause to be a synchronous loop implemented with `async.whilst` where the callback was being invoked synchronously. I haven't checked for other occurences of this in the codebase.
(I haven't tested this because I don't have the dev environment set up.)

Replace async loop by sync loop

---

packages/truffle-core/lib/testing/testrunner.js

Hi @gnidan 
Testing with Kaleido and some of our private consensus algorithms, we've encountered https://github.com/trufflesuite/truffle/issues/261
I understand the suggestion there was setting `mocha.enableTimeouts` to false would solve it, such as:
https://github.com/kaleido-io/truffle-kaleido-box/blob/773f91bd3a88bc51412f28bc177e4a05a526ef65/truffle-config.js#L19-L21
However, our testing suggest that does not resolve the issue. The timeout still fires after 2mins for the `prepare suite` that contains the hard coded `this.timeout(runner.TEST_TIMEOUT)`.
Whereas the attached change, combined with adding a `before_timeout` option in the mocha section (alongside `enableTimeouts`) increases the timeout.
Do you think you could re-instate the config option, so we can set it in our truffle box? …

Make before_timeout configurable beyond 2min

---

packages/truffle-debugger/lib/web3/sagas/index.js

This PR just uses `join([...tasks])` instead of this manual replication of its functionality.  I'm hoping it might also address #2013, although it's a little unclear what's going on there, so we'll see.

Replace a manual array join with a single call to join

---

packages/truffle-core/lib/commands/migrate.js

In my macbook (node.js 11 ),  I have runing `truffle deploy --network ropsten` : 
```
TypeError: this.determineDryRunSettings is not a function
at Contracts.compile.then (/Users/xingyuwang/.nvm/versions/node/v11.15.0/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/commands/migrate.js:184:10)
```
fix it.

 fix bug for syntax

---

packages/truffle-db/bin/server.js
packages/truffle-db/src/data/schema.ts
packages/truffle-db/src/db.ts
packages/truffle-db/src/helpers/generateId.ts
packages/truffle-db/src/helpers/index.ts
packages/truffle-db/src/loaders/artifacts/index.ts
packages/truffle-db/src/loaders/artifacts/test/index.ts
packages/truffle-db/src/loaders/index.ts
packages/truffle-db/src/loaders/test/index.ts
packages/truffle-db/src/workspace/test/index.ts
packages/truffle-db/test/helpers/generateId.ts
packages/truffle-db/test/helpers/index.ts

This PR seeks to add the ability to trigger the `loader` component of the truffle-db package from Truffle DB's implementation of the GraphQL Playground. 
The following mutation, when run in the Playground on a specific Truffle project: 
```
mutation LoadArtifacts {
loaders {
artifactsLoad {
success
}
}
}
```
will result in the Artifacts for that project as well as the compilations (as determined by manually running `truffle-workflow-compile`) being loaded into the PouchDB in-memory database currently being used by TruffleDB. 
Once this happens, the bytecodes, sources, and compilations related to the project can be queried via Workspace.

Loader playground functionality

---

packages/truffle-core/lib/commands/deploy.js
packages/truffle-core/lib/commands/migrate.js
packages/truffle/test/scenarios/commands/deploy.js
packages/truffle/test/scenarios/commands/migrate.js

This PR adds two very basic tests for `truffle migrate` and `truffle deploy`. These just ensure that both `migrate` and `deploy` run on a fresh `truffle init` without throwing an error.

Internal improvement: Add basic migration tests for migrate and deploy

---

packages/truffle-core/lib/commands/install.js
packages/truffle-core/lib/package.js
packages/truffle/test/scenarios/commands/install.js
packages/truffle/test/scenarios/sandbox.js
packages/truffle/test/sources/install/init/contracts/Migrations.sol
packages/truffle/test/sources/install/init/migrations/1_initial_migration.js
packages/truffle/test/sources/install/init/truffle-config.js

When implementing the Web3Shim (I think), a Web3 require statement was removed in `packages/truffle-core/lib/package.js`. This caused `truffle install` to fail. This PR adds the require statement back in. In addition it provides some pretty output at the end of the job stating that packages were installed.
The output for this command now will look like the following:
It also adds a basic test for `truffle install`, ensuring that `truffle install zeppelin` completes successfully and a basic `truffle init` project has the "installed_contracts" directory that `truffle install xxx` creates.

Fix ethpm bug

---

packages/truffle-core/lib/commands/debug.js
packages/truffle-core/lib/debug.js
packages/truffle-core/lib/debug/compiler.js
packages/truffle-core/lib/debug/index.js
packages/truffle-core/lib/debug/interpreter.js
packages/truffle-core/lib/debug/printer.js
packages/truffle-debug-utils/index.js

That's it. I couldn't take it anymore. #2025 was the last straw.
- Switch to `const`s and `let`s instead of `var`s
- Move a function to debug-utils (`formatValue`)
- Split up lib/commands/debug into:
- a thing that does the compilation (DebugCompiler)
- a thing that houses all the copious print methods (DebugPrinter)
- a thing that inelegantly wraps the giant repl interpreter function that does all that printing (DebugInterpreter)
- a CLIDebugger class that does compilation and sets up the interpreter
- Make the code not gosh darn impossible to read.
- Expose how the heck this could actually be organized in the future.

Tear lib/commands/debug into pieces

---

packages/truffle/test/scenarios/commands/deploy.js
packages/truffle/test/scenarios/commands/migrate.js

Looks like `Server.start/stop` currently expects a `done` callback to be passed to it.
This PR fixes two currently uncaught failing `geth` tests (https://travis-ci.org/trufflesuite/truffle/jobs/534960586#L760) & (https://travis-ci.org/trufflesuite/truffle/jobs/534960586#L785).

Internal improvement: Fix `before` on deployment scenario tests

---

packages/truffle/scripts/test.sh

Now that we leverage lerna for bootstrapping, no need to build truffle twice in CI!

Internal improvement: Remove extra build in geth & integration job

---

packages/truffle-contract/lib/reason.js
packages/truffle-contract/test/methods.js

Continuation of #1652 (cherry picked its first commit). That PR is marked Quorum/Enterprise but this problem affects truffle-contract use with geth generally.  
Geth [requires that eth_call use a block param](https://github.com/ethereum/go-ethereum/issues/2472) and its absence means that `truffle-contract` isn't able to correctly replay  failed transactions and get a reason returned as data. 
Believe 'latest' is the right value here - should work with both instamining dev clients and regular networks. Truffle-contract fetches the reason in a call immediately following a failed tx - 'latest' will be typically be the relevant block.
Have added a test in the [ @ geth ] methods suite.
Additional notes:
+  Ganache returns a gas estimate for transactions that fail, geth doesn't. If you're using …

Get revert reason from Geth clients

---

packages/truffle-artifactor/index.js
packages/truffle-artifactor/templates/class.js
packages/truffle-artifactor/utils.js

This PR fixes an oversight implemented in #1894 to simply `_.merge` existing and new compiled artifacts rather than `_.merge` their known networks before `_.assign`ing other properties. Also cleans up the pkg a bit.
Resolves #2048 .

Fix: appropriately assign & merge artifact properties

---

packages/truffle-core/lib/debug/printer.js
packages/truffle-debugger/lib/data/sagas/index.js
packages/truffle-debugger/lib/data/selectors/index.js
packages/truffle-debugger/lib/evm/actions/index.js
packages/truffle-debugger/lib/evm/reducers.js
packages/truffle-debugger/lib/evm/sagas/index.js
packages/truffle-debugger/lib/evm/selectors/index.js
packages/truffle-debugger/lib/session/sagas/index.js
packages/truffle-debugger/lib/session/selectors/index.js
packages/truffle-debugger/lib/trace/sagas/index.js
packages/truffle-decode-utils/src/contexts.ts

The immediate purpose of this PR is to fix issue #2028.  However, if I just wanted to do that, I could've done it an easier way.  The broader purpose is to lay some more foundations for the reconstruct mode that's eventually coming.
So, as I said, the primary visible effect of this PR is to fix issue #2028.  Now, when a creation call successfully returns, we store in the state the code and address that it returned, so that other parts of the debugger will have access to it.  So, if you then enter a message call to a contract you just created, we will be able to sourcemap it and properly debug it, even if the transaction (or some part of it) later reverts, or even if the contract eventually selfdestructs.  (Note that selfdestructs are still a problem if you *didn't* just create the …

Store code returned by creation calls

---

packages/truffle-compile-vyper/index.js

This PR seeks to add the source contents for Vyper contracts to the contracts build file upon the completion of a successful compilation.
In order to await the results of the `readFile()` function, it was necessary to make `compileAll()` async, as well as making the callback from `execVyper()` async. There may be a more elegant way to do this, so please let me know if that's the case. 
Also, I assume that no additional changes to the source_path object are necessary to make this code compatible with Windows systems, but have not tested on one.

Read file source and save to vyper compilation output

---

packages/truffle-core/lib/debug/interpreter.js
packages/truffle-debugger/lib/evm/actions/index.js
packages/truffle-debugger/lib/evm/reducers.js
packages/truffle-debugger/lib/evm/sagas/index.js
packages/truffle-debugger/lib/evm/selectors/index.js
packages/truffle-debugger/lib/web3/sagas/index.js
packages/truffle-debugger/test/endstate.js

This PR accounts for the possibility that a normal halting instruction might, in fact, halt exceptionally.  In addition, it also fixes what I think is likely a bug I introduced in #2052.  (A `RETURN` can fail if there are insufficient stack arguments; a `SELFDESTRUCT` can fail that same way, or by running out of gas, or if it's inside a static call.  `STOP` is, in fact, the only EVM instruction that is guaranteed not to fail.)
So first off, let me mention a quick improvement over #2052 -- in that previous PR, when determining the address created by a returning creation call, I looked at the stack to determine the address.  But this is foolish, because we already have the address on our callstack as `storageAddress`.  So now we use that instead, and I got rid of the selector I added in …

Account for exceptional halts from normal halting instructions

---

.travis.yml
packages/truffle-compile/compilerSupplier/index.js
packages/truffle-compile/compilerSupplier/loadingStrategies/VersionRange.js
packages/truffle-compile/compilerSupplier/loadingStrategies/index.js
packages/truffle-compile/package.json
packages/truffle-compile/test/compilerSupplier/index.js
packages/truffle-contract/package.json
packages/truffle-deployer/test/deployer.js
packages/truffle/cli.webpack.config.js
packages/truffle/package.json
packages/truffle/scripts/postinstall.js
yarn.lock

This PR seeks to resolve #2034 by removing the `solc-js` compiler component completely from the bundle.
This is handled by:
- leveraging `truffle obtain` in a postinstall to download and cache a default soljson when installing truffle via npm.
- Importing only the `solc/wrapper` to parse soljson's.
- Removing the `Bundled` strategy from the CompilerSupplier.
The current implementation of this can be tested at `truffle@unbundled-solc`.

Enhancement: Remove solc-js compiler from the bundle

---

packages/truffle-contract-schema/package.json
packages/truffle-contract-schema/spec/abi.spec.json
packages/truffle-contract-schema/spec/contract-object.spec.json
packages/truffle-contract-schema/spec/network-object.spec.json
yarn.lock

This PR upgrades `ajv` to `v6` which implements `draft07` of the JSON Schema. It also adds support for tuples (which is how `struct` Solidity types are represented) as a parameter type.
You'll see https://github.com/trufflesuite/truffle/pull/2064/files#diff-da060bd5170ce9e90e14ece903806d3eR135 says that the `components` property has an array of `object` types. This is *supposed to be* `"items": { "$ref": "#/definitions/Parameter" }`, but the https://github.com/bcherny/json-schema-to-typescript dependency we use to generate typings fails due to the recursion  (gets a `Maximum call stack size exceeded` error when building), despite the schema supports this recursion.
The dependency has known about this issue for 2 years now (https://github.com/bcherny/json-schema-to-typescript/issues/76 …

Add Support for Tuples (aka Structs) in the ABI Contract Schema

---

packages/truffle/scripts/postinstall.js

This PR attempts to resolve #2069 by outputting `postinstall` errors rather than throwing them.

Fix: Output instead of throw on postinstall errors

---

packages/truffle-debugger/lib/controller/sagas/index.js
packages/truffle-debugger/lib/solidity/sagas/index.js

This PR fixes some issues resulting from using the `c` command when there is unmapped code.  You could get a problem if you used it from within unmapped code, or if you continued to the end when the end is unmapped.  I fixed this by adding a `break` to the loop if you're already finished (so that the rest of the loop, that could cause a problem, never runs) and by adding a `continue` to the loop if you're in unmapped code (for the same reason) and rearranged other checks so that this works.  Pretty straightforward.

Fix interaction of continue command with unmapped code

---

packages/truffle-contract-schema/spec/network-object.spec.json
packages/truffle-contract-schema/test/MetaCoin.json

I was getting the contract verification error:
```
should be object (type):
{ dataPath: '.networks[\'1559252182005\'].links[\'ConvertLib\']',
schemaPath: '#/type',
params: { type: 'object' },
data: '0xA516d46A37780b71e3d5BaB2070f345967f7b8e0',
```
using `truffle-contract-schema@3.0.10` and `truffle@5.0.15`
you can see the networks object shows that the `ConvertLib` property is a `string` and not an `object`:
```json
"networks": {
"1559252182005": {
"events": {},
"links": {
"ConvertLib": "0xA516d46A37780b71e3d5BaB2070f345967f7b8e0"
},
"address": "0x7d2aF93e5758C578a32B2F2977A74599e12c9a95",
"transactionHash": "0xa607a79b6d6d77d826acf1954c15449cb0fd644e83b26fdc530fe472c564f454"
}
}
```
Going down the rabbit hole, this looks like the schema should be updated rather than the code:
- …

Fix link value type in contract network object schema

---

packages/truffle-debugger/test/data/more-decoding.js
packages/truffle-decoder/lib/decode/value.ts

This PR causes the decoder to discard padding before attempting to decode variables of `uint` or `int` type.  Previously the padding was left in on the theory that it wouldn't affect the result.  However, it turns out that when using short integer types (or short bytestring types), Solidity doesn't actually restore correct padding after an operation that overflows; it only restores correct padding when it performs an operation that requires it to.  So, if you have add two `uint8`s of value 255, the result will be stored as, and currently decode to, a 510, rather than 254 like you might expect; however for practical purposes it acts like a 254 in Solidity, and as such it should decode to such (particularly so that it's handled correctly as a mapping key!).
We already discard padding for …

Discard padding when decoding numeric types

---

packages/truffle-debugger/lib/data/selectors/index.js
packages/truffle-decode-utils/src/definition.ts

I recently learned that prior to Solidity 0.5.0, function definitions didn't have the `kind` property.  I've added this shim for this fact and put it in in the one place we were currently reading the `kind` property.  (There are more such places on `type-and-value` and related branches, but here's the `develop` version.)  I didn't add a similar function for `stateMutability` because I can't find anywhere we used that, but I'll add that too in the future if we want to use it.

Add shim for function kind for pre-0.5.0 contracts

---

packages/truffle-decoder/lib/allocate/calldata.ts
packages/truffle-decoder/lib/allocate/storage.ts

This PR adds allocator support for empty structs and static-length arrays of length 0, which were legal prior to 0.5.0.
In storage, such types take up 1 word, not 0 words, as might be expected.  This PR accounts for that.
In calldata, a static-length array of length 0 is considered a static type regardless of the base type (normally `type[n]` is considered a static type iff `type` is); this can affect the length of other structs or arrays that contain them.  This PR accounts for that.
(OK, calldata variables didn't exist prior to 0.5.0, but we'll still want this change later for decoding transactions and events.)
There are no changes to memory.

Account for empty multivalue types (legal in 0.4.x) in allocator

---

.travis.yml

Fixes an issue where `sudo apt-get update` was pulling an outdated link from `ethereum/ethereum`.

Internal improvement: leverage travis apt addons

---

packages/truffle-debugger/lib/data/sagas/index.js

This PR allows mapping keys that begin with a unary `+` to work.  Unary `+` isn't legal anymore, but it was legal prior to 0.4.18.
As you may recall, our system for recording mapping keys doesn't work if the outermost operation in the index expression is (on the bytecode level) a no-op.  Obviously, that includes unary `+`.  I didn't account for this earlier because I didn't realize it was legal in old versions.  Well, it is, so I've accounted for it, in the same way I've accounted for other no-ops.

Add support for unary + in mapping keys (0.4.x. compatibility)

---

packages/truffle-box/README.md
packages/truffle-box/package.json
yarn.lock

This PR updates the `truffle-box` docs (mainly usage examples) & tidies up the `package.json` deps.

Internal improvement: Update `truffle-box` docs & package.json

---

packages/truffle-box/box.js
packages/truffle-box/test/box.js

This PR mainly adds some coverage for `truffle-box/box.js`. Also swaps `fs` for `fs-extra` and modernizes the code a tiny bit.

Internal improvement: Add coverage for box.js

---

packages/truffle-compile/test/test_parser.js

_(Internal improvement)_
Mark a few truffle-compile tests as being `@native` because they use Docker. I've seen this done elsewhere so I assume it's kosher?

Add native tag to parser test needing docker/native

---

packages/truffle-compile-vyper/package.json
packages/truffle-core/package.json
packages/truffle-hdwallet-provider/package.json
packages/truffle/package.json
packages/truffle/test/scenarios/reporter.js
yarn.lock

This started out as just an upgrade to `diff` to fix the [security vulnerability](https://github.com/trufflesuite/truffle/network/alert/packages/truffle-core/package.json/diff/closed), but turns out we don't even need to use `diff` directly anymore.
- Get rid of awkward v4.1.0 (not used by truffle-core, but installed as a dep for bundled Truffle)
- For every package dependent on mocha@^5, use mocha@5.2.0
- Ignore packages that depend on mocha@^6
- Remove truffle-core's `diff` dependency, use exported function from newer mocha instead

De-dupe Truffle's mocha dependencies

---

packages/truffle-compile/index.js

(Internal improvement)
Truffle's compilation process orders output ABI in source-defined order using the AST parse info. This PR switches to using the current `ast` compilation source property instead of the `legacyAST` compilation source property.
+some refactoring

Use current AST format instead of legacy for ordering ABI output

---

packages/truffle-core/lib/commands/test.js
packages/truffle-core/lib/test.js
packages/truffle-core/lib/testing/testsource.js

In the interest of making the code for truffle test more readable and maintainable, this PR was created! It removes the callback being passed to the run method for `packages/truffle-core/lib/test.js` and instead adopts a Promise-based interface. The callback is now being handled in `packages/truffle-core/lib/commands/test.js`. The war on callbacks wages on!

Internal improvement: Update truffle test code

---

packages/truffle-core/package.json
packages/truffle-core/test/ethpm.js
packages/truffle/package.json
yarn.lock

This PR removes `go-ipfs-dep` & `ipfsd-ctl` as `devDependencies` along with an unused failing test import from `ethpm`.

Internal improvement: remove unused devDeps & failing test import

---

packages/truffle-core/lib/commands/test.js

Fix bug occurring when running truffle test with 0 test files. When there are 0 files that `node-dir` reads in a directory, it returns `undefined` instead of an empty array.

Fix bug with truffle test

---

packages/truffle-debugger/lib/data/sagas/index.js
packages/truffle-debugger/test/data/more-decoding.js

So, it looks like when I implemented code to allow constant state variables to work as mapping keys, I must never have actually tested it very much, because due to a typo, they actually didn't work as mapping keys much at all.
Of course, that typo masked an infinite loop!  I forgot to set `indexValue = null` if we failed to decode a constant state variable being used as a mapping key, meaning (had the typo not prevented the case from ever coming up) any constant state variable we couldn't decode would throw the debugger into an infinite loop.
(Why did I forget that?  Because this is the only case with another nested `if` inside it, meaning it's the only case where it's necessary; other cases that fail will just get caught by the `else` at the end, but these ones won't and need their own …

Fix bugs relating to constant mapping keys

---

packages/truffle-decoder/lib/decode/value.ts
packages/truffle-decoder/package.json
yarn.lock

I originally made this change on `type-and-value`, then realized it was worth backporting to `develop`.  (I'm setting myself up for a merge conflict, but...)
This PR fixes an issue in string decoding by using the `utf8` library to convert Solidity's UTF-8 to Javascript's UTF-16.  Note that Solidity does allow *malformed* UTF-8; in this case, we simply return `null`.  (Note that we detect this case by seeing whether `utf8.decode` throws an error; it doesn't seem to have a check function separate from the decode.)
Why `null` rather than `undefined`?  To avoid throwing the debugger into an infinite loop in case a mapping key is a malformed string.  Yes, this is a bit of a hack, but don't worry, it'll be gone in 5.1; on `type-and-value` we return an object representing the particular …

Correctly decode UTF-8

---

packages/truffle-debugger/test/data/calldata.js
packages/truffle-debugger/test/helpers.js
packages/truffle-decoder/lib/decode/calldata.ts

It seems I accidentally broke decoding of dynamic structs in calldata a while back.  Probably when I factored out struct decoding; in combining the static and dynamic cases, I left out the `startPosition` argument in the call to `decodeAbi`, which is fine in the static case but is very wrong in the dynamic case.  Oops.
(In the static case, you're always reading the member directly, not a pointer to it, so you don't need to know what base that pointer should be considered relative to, because it's not a pointer at all.  In the dynamic case, you may be reading a relative pointer, so you need to know what it's relative to.)
As a check against this happening again, I added an additional (very simple) calldata decoding test to catch this.
Note that in order to make this work I ended up …

Fix a regression in decoding of dynamic structs!

---

packages/truffle-compile/profiler.js

I had this truffle error a few days ago :
```
Compiling your contracts...
===========================
SyntaxError: Unexpected end of JSON input
at JSON.parse (<anonymous>)
at async.map (/Users/mathew/.nvm/versions/node/v10.15.3/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/profiler.js:83:1)
at /Users/mathew/.nvm/versions/node/v10.15.3/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/~/async/dist/async.js:1140:1
at /Users/mathew/.nvm/versions/node/v10.15.3/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/~/async/dist/async.js:473:1
at iteratorCallback (/Users/mathew/.nvm/versions/node/v10.15.3/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/~/async/dist/async.js:1064:1)
at …
```

Invalid artifacts error

---

packages/truffle-core/lib/command.js
packages/truffle-core/lib/commands/obtain.js
packages/truffle-core/test/commands.js

I opened a pull request #2116 and Travis CI build failed. I was thinking not having the latest from develop branch and the git force command cause the issue close while using it on my branch so I have to open a new pull request.
After investigation I found out that the newly implementation for unsupported option validation broke the build. The truffle command that trying to obtain the solc has a bit different help documentation due to the nature of the dynamic option.
I can update the truffle obtain command help so the CI build won't break but this is not a good solution because any future command document with a bit different format will potential break the build or prevent user to run the command.
I think the better approach is to warn the user about the potential problem when an …

Warn/error about unsupported flags #468

---

packages/truffle-core/lib/command.js

This PR fixes a regression introduced in #2125, while building on top of the enhancement.
Makes sure commands initiated within the `develop` and `console` context are passed as expected arrays of strings.

Fix: ensure `console` & `develop` are passed commands as an array

---

packages/truffle-compile/package.json
packages/truffle-compile/profiler.js
packages/truffle-compile/profiler/findUpdatedFiles.js
packages/truffle-compile/profiler/getImports.js
packages/truffle-compile/profiler/index.js
packages/truffle-compile/profiler/isExplicitlyRelative.js
packages/truffle-compile/profiler/minimumUpdatedTimePerSource.js
packages/truffle-compile/profiler/readAndParseArtifactFiles.js
packages/truffle-contract-sources/index.js
packages/truffle-core/lib/test.js
packages/truffle-core/test/profiler.js
yarn.lock

This PR reorganizes the `updated` method for the `Profiler` in truffle-compile. All uses of the `async` module are eliminated. Also much of the logic has been extracted into helper files.
Another change (not truffle-compile related) that this makes is that it allows the main method exposed by truffle-contract-sources to have a Promise interface as well as its old callback one.

Internal improvement: Profiler update

---

packages/truffle-hdwallet-provider/README.md

In README, the example code line for using our own hierarchical derivation path, the parameter `sharedNounce` was missing.

Fixed missing parameter 'sharedNonce' in the constructor

---

packages/truffle-decode-utils/src/types/types.ts
packages/truffle-decode-utils/src/types/values.ts
packages/truffle-decoder-core/lib/decode/calldata.ts
packages/truffle-decoder-core/lib/decode/memory.ts
packages/truffle-decoder-core/lib/decode/storage.ts
packages/truffle-decoder-core/lib/types/storage.ts

Two quick but unrelated fixes that should have been in `type-and-value`.
Number one, I made a mistake writing the `equalSlots` function; it compared things via `==` when they might be `BN`s.  So, as a quick fix, I now apply `toString` before comparing.
Secondly, the various pair objects now have named interfaces so that TypeDoc can handle them better.  (They're now `NameTypePair`, `NameValuePair`, and `KeyValuePair`.)

Fix equalSlots function; give names to pair objects

---

packages/truffle-core/lib/commands/develop.js

This PR allows passing a `fork` ganacheOption from `truffle-config.js` to enable `ganache-core`'s forking feature within the `truffle develop` context.
🍴

Enhancement: enable 'fork' as a config option for use within `truffle develop`

---

packages/truffle-core/lib/commands/develop.js

This hardcoded `truffle-core` prevents running `truffle` from my forked version of `truffle-core` package.

Replace truffle-core/mnemonic require with a relative one

---

packages/truffle-artifactor/package.json
packages/truffle-contract/package.json
packages/truffle-core/package.json
packages/truffle-debugger/package.json
packages/truffle-decode-utils/package.json
packages/truffle-decoder/package.json
packages/truffle-deployer/package.json
packages/truffle-environment/package.json
packages/truffle-external-compile/package.json
packages/truffle-hdwallet-provider/README.md
packages/truffle-hdwallet-provider/package.json
packages/truffle-interface-adapter/package.json
packages/truffle-migrate/package.json
packages/truffle-provider/package.json
packages/truffle-reporters/package.json
packages/truffle-require/package.json
packages/truffle/package.json
yarn.lock

Upgrade web3 packages to 1.2.0.
Non-exhaustive (possibly) list of packages effected by web3 upgrade:
* truffle: 1.0.0-beta.37 →  1.2.0
* truffle-artifactor: 1.0.0-beta.37 →  1.2.0
* truffle-contract: 1.0.0-beta.37 →  1.2.0
* truffle-core: 1.0.0-beta.37 →  1.2.0
* truffle-debugger: 1.0.0-beta.37 →  1.2.0
* truffle-decode-utils: 1.0.0-beta.37 →  1.2.0
* truffle-decoder: 1.0.0-beta.37 →  1.2.0
* truffle-deployer: 1.0.0-beta.37 →  1.2.0
* truffle-environment: 1.0.0-beta.37 →  1.2.0
* truffle-hdwallet-provider: 1.0.0-beta.37 →  1.2.0
* truffle-interface-adapter: 1.0.0-beta.37 →  1.2.0
* truffle-migrate: 1.0.0-beta.37 →  1.2.0
* truffle-provider: 1.0.0-beta.37 →  1.2.0
* truffle-require: 1.0.0-beta.37 →  1.2.0

Dependency update: Upgrade web3 packages to 1.2.0

---

scripts/ci.sh

Resolves Travis CI `vyper` compiler memory issues (`Segmentation fault`) when running `truffle-compile-vyper` tests against a `snap/d` installed vyper compiler.

Internal improvement: Fix CI vyper tests

---

packages/truffle-debugger/lib/data/sagas/index.js
yarn.lock

The main data saga is a monster, and the most monstrous part of it is almost certainly the decoding of mapping keys.  This should have been factored out into its own saga long ago.  Actually, I tried a while back, but for some reason it didn't work -- presumably I didn't yet sufficiently understand generators and invoked it wrong as a result.  Anyway, now I factored it out for real.  The main data saga is still a monster, mind you, but at least it's less of one.
As long as I was doing this on a branch off of `develop` rather than `next`, I thought about changing the fact that on `develop` malformed UTF-8 just decodes to `null`, and using replacement characters instead.  However I realized that due to the information loss such decoded strings would actually fail to work as mapping keys, …

Factor out mapping key decoding into its own saga

---

packages/truffle-codec-utils/src/contexts.ts
packages/truffle-decoder/lib/contract.ts
packages/truffle-decoder/lib/index.ts
packages/truffle-decoder/lib/wire.ts

This PR factors out the wire-decoder functions from the contract decoder, in order to reduce the amount of copypasted code.  In the process, I made a few minor improvements/fixes as well.
Rather than having `TruffleContractDecoder` extend `TruffleWireDecoder`, I took @gnidan's advice and had it contain one internally instead.  This way, multiple contract decoders can be made from the same wire decoder, without having to recompute ABI allocations, etc.  Basically this is potentially useful if you want to have contract decoders for multiple contracts in the same project.
The contract decoder now just delegates to the wire decoder for all wire-decoding functions; its only major function still handled internally is decoding contract state.  This also means the wire-decoding functions no …

Factor out wire decoder from contract decoder

---

packages/truffle-contract/lib/execute.js

Part of #2211 
Adds syntax to listen for method names and arguments.
Example syntax:
```javascript
const instance = await MyContract.deployed();
instance.myMethod().on("execute:send:method", ({ fn, abi, args, contract, address }) => {
// access the abi item information, the arguments used, etc.
}
```
Note: this does not appear to directly conflict with #2035, but there may be reconciliation required later, once truffle-contract is instrumented for the event system.

Emit method information for truffle-contract operations

---

packages/truffle-interface-adapter/lib/quorum-overloads.ts
packages/truffle-interface-adapter/package.json

File `quorum-overloads` from `interface-adapter` imported the underscore library, even though it was not declared on the package.json as a dependency. This caused a `require` of the package (or any other package that depended on it) to fail.
Instead of installing underscore, since other truffle packages already use lodash, this commit changes underscore to lodash, and declares it as a dependency on the package.json.

Fix missing underscore dependency

---

packages/truffle-core/index.js
packages/truffle/cli.webpack.config.js
packages/truffle/package.json
packages/truffle/test/scenarios/library/api.js

#2222 
Makes the following possible (in a plugin context, for example). 
```javascript
const truffle = require("truffle");
await truffle.contracts.compile(config);
```
**Implementation Details**
+ In #2222 I proposed using webpack [expose-loader](https://www.npmjs.com/package/expose-loader) for this because I was concerned about the bundle size growing a lot. The unpacked version *is* bigger here (25-30%), but the packed version sent over the wire from npm is still quite small and it doesn't affect installation speeds. I published my own version to test that issue & validate the POC in the code snippet above - everything worked. Also expose-loader is a nightmare.
+ Added `ganache-core` to the `truffle-core` exports  so consumer can spin up an in-process provider.
+ Added top layer API …

Generate truffle library webpack bundle for package main

---

packages/truffle-compile/legacy/shims.js
packages/truffle-compile/test/legacy/shims.js

For case where trying to shim bytecodes that are undefined

Add missing defaults for shimBytecode

---

packages/truffle-contract/lib/contract/constructorMethods.js
packages/truffle-contract/lib/execute.js

Required for #2205 
Continues along same reasoning as #2251 
In addition to the existing `execute:send:method` and `execute:call:method`, this adds a new event `execute:deploy:method`.
The purpose here is to allow #2252 and #2253 to also offer the behavior of debugging contract deployments in tests.
**Note** Future work might involve changing the names of these events, perhaps before they end up getting used externally too much.

Emit deploy method information in truffle-contract lifecycle

---

packages/truffle-core/lib/test.js

Implements #2211 
Builds on #2073 #2258 
- Use `"truffle-workflow-compile/new"` inside lib/test
- ~~Remove extraneous profiler usage (truffle-workflow-compile does this)~~ turns out this isn't so extraneous
- Capture entire compilation result instead of just dependencyPaths

Switch `truffle test` to use new compile interface

---

packages/truffle-contract/lib/execute.js
packages/truffle-contract/test/methods.js

Fixes #1586 by persisting the data parameter if raw data was included. If no raw data is included, `params.data` is undefined anyway.
More info on the issue can be found [here](https://github.com/nsward/truffle-contract-bug-test). Being able to include raw data in a transaction to a truffle-contract instance is useful in a lot of cases, particularly when interacting with proxy contracts.

Fix sendTransaction dropping data param bug

---

packages/truffle-resolver/fs.js
yarn.lock

This PR attempts to resolve #2134 by ensuring `getContractName` filters out non-json files before attempting to parse them.
Also ES6's `truffle-resolver/fs.js` and cleans up some of the code.

Fix: ensure truffle-resolver/fs only parses json artifacts

---

packages/truffle-artifactor/package.json
packages/truffle-contract/package.json
packages/truffle-core/package.json
packages/truffle-debugger/package.json
packages/truffle-decode-utils/package.json
packages/truffle-decoder/package.json
packages/truffle-deployer/package.json
packages/truffle-environment/package.json
packages/truffle-external-compile/package.json
packages/truffle-hdwallet-provider/package.json
packages/truffle-interface-adapter/package.json
packages/truffle-migrate/package.json
packages/truffle-provider/package.json
packages/truffle-reporters/package.json
packages/truffle-require/package.json
packages/truffle/package.json
yarn.lock

Upgrades dependencies:
- web3
- web3-core-promievent
- web3-eth-abi
- web3-utils
Note: I've removed the carets (^) because I think we should keep these pinned at specific versions.
cc @nivida

Dependency update: Upgrade web3 packages to 1.2.1

---

packages/truffle-config/index.js

This PR fixes a bug where `config.with` was returning a non-`TruffleConfig` object (missing `TruffleConfig` key/values).

Fix: ensure config.with returns a Config object

---

packages/truffle-db/src/loaders/artifacts/index.ts
packages/truffle-db/src/schema.graphql
packages/truffle-db/src/workspace/schema.ts

This PR removes the references to network fork, because we will be treating network forks as a separate resource in order to maintain the immutability of resources. A new resource called "parent" will be developed and will allow us to assess the the correct network that each contract instance is on.

Remove network fork references

---

packages/truffle-contract-schema/spec/abi.spec.json

Solidity 0.5.11 is out and it adds to the ABI JSON the possibility for parameters (input or output) to be tagged with an additional `internalType` field.  I've added this to the schema, for both `Parameter` and `EventParameter`.  Note that I've deliberately left it not required.

Update contract schema with internalType for Solidity 0.5.11

---

packages/truffle-core/lib/debug/mocha.js

Builds on #2251 #2073 #2255 #2260 
This defines the class `CLIDebugHook`, intended for use inside Mocha, to provide an interactive CLI debugger via test global interrupt.
- Define CLIDebugHook to wrap CLIDebugger
- Use #2251 work to capture transaction info for send, or to replay calls as tx

Build mocha hook integration for truffle-debugger

---

packages/truffle-core/lib/commands/test.js
packages/truffle-core/lib/debug/interpreter.js
packages/truffle-core/lib/test.js

#2206 #2205 
Builds on #2252 #2254. Replaces #2050.
- Add `truffle test --debug` flag, to enable in-test debugging mode
- Add `debug()` global for use in JS tests, to indicate breakpoint for Solidity debugging

Provide in-test debugging interrupts for Solidity inside JS tests

---

.travis.yml

We don't really need to run two builds for every PR.
This PR should tell Travis to run only the PR build for normal PRs, running the "push build" only on branches that will be the recipient of pull requests / other merges.

Whitelist specific branches for Travis push builds

---

.travis.yml
scripts/ci.sh

Ubuntu Trusty 14.04 is now EOL by Canonical (https://help.ubuntu.com/community/EOL) and Travis has begun defaulting to Xenial (https://docs.travis-ci.com/user/trusty-to-xenial-migration-guide).
This PR bumps the distro and updates a few commands to use `apt` instead of `apt-get`.

Internal improvement: Update from Trusty to Xenial

---

packages/truffle-artifactor/package.json
packages/truffle-contract/package.json
packages/truffle-contract/test/errors.js
packages/truffle-contract/test/methods.js
packages/truffle-core/index.js
packages/truffle-core/package.json
packages/truffle-debugger/package.json
packages/truffle-deployer/package.json
packages/truffle-environment/chain.js
packages/truffle-environment/environment.js
packages/truffle-environment/package.json
packages/truffle-hdwallet-provider/package.json
packages/truffle-interface-adapter/package.json
packages/truffle-provider/package.json
packages/truffle/package.json
yarn.lock

This pull request bumps the `ganache-core` version in the various `package.json` files from `2.5.7` to `^2.6.1`.  (I'm hoping there wasn't some reason it was fixed at a specific version, no caret, before...)
The specific reason I'm doing this is so that later we can finally enable the globally-available variable tests in the debugger, but I figured I'd do it in all the packages because why not.

Bump ganache-core version

---

packages/truffle-contract/lib/utils.js

I'd been getting annoyed with the fact that `sendTransaction` would throw an exception if for some reason something went wrong during event decoding (e.g., if the event contained an external function among its parameters, or if it was ambiguous in a way that web3 couldn't handle).  So, I put a try/catch around it, and had it return `null` on failure.  In context, that means such events will simply be skipped.  Not ideal, but a decent workaround for the time being that's definitely better than throwing an exception.
This PR does not do any of the following:
1. Make an analogous change to the decoding in truffle test.  I've simply never encountered any analogous problem with the decoding there, so I left it alone.  I mean, I'm sure *something* goes wrong in these cases there, but nothing …

Prevent exception from decoding failure in truffle-contract

---

packages/truffle-codec-utils/src/abi.ts
packages/truffle-codec-utils/src/definition.ts
packages/truffle-codec-utils/src/definition2abi.ts

This PR updates `abi.ts` by adding `internalType` to the ABI type; and it updates `definition2abi.ts` to generate this.  To find the `internalType` from the definition, it simply takes the `typeString` and then strips off any location that may be included at the end.
Since we're now making more use of type strings, I updated the hacky case of the `keyDefinition` function in `definition.ts` to spoof the full `typeDescriptions` rather than just the `typeIdentifier`.  (I left the `baseDefinition` function alone, since it's irrelevant here.)  I also made it so that `keyDefinition` will just, well, take the key definition if there is one -- the function was originally written to be used with expressions, rather than with actual variable definitions, which is why that case was missing.

Update ABI utilities to account for internalType

---

.github/workflows/nodejs.yml
.travis.yml
packages/truffle-deployer/test/errors.js
scripts/ci.sh

This PR leverages Github Actions to run CI checks against Node 8.x, 10.x, & 12.x on Ubuntu. Trims Travis' workload and keeps Travis jobs for Fabric EVM & Coveralls tests (for now).
Also adds Slack Notifications for when a workflow fails or when the build workflow job succeeds.

Internal improvement: Implement GHA CI for Node 8.x, 10.x, & 12.x

---

packages/truffle-codec-utils/package.json
packages/truffle-codec/lib/decode/abi.ts
packages/truffle-codec/lib/decode/constant.ts
packages/truffle-codec/lib/decode/event.ts
packages/truffle-codec/lib/decode/index.ts
packages/truffle-codec/lib/decode/memory.ts
packages/truffle-codec/lib/decode/special.ts
packages/truffle-codec/lib/decode/stack.ts
packages/truffle-codec/lib/decode/storage.ts
packages/truffle-codec/lib/decode/value.ts
packages/truffle-codec/lib/interface/decoding.ts
packages/truffle-codec/lib/interface/index.ts
packages/truffle-codec/lib/read/index.ts
packages/truffle-codec/lib/read/storage.ts
packages/truffle-codec/lib/types/request.ts
packages/truffle-codec/package.json
packages/truffle-decoder/lib/contract.ts
packages/truffle-decoder/lib/wire.ts
packages/truffle-decoder/package.json
yarn.lock

This PR updates the TypeScript version to 3.6 and makes use of its new `Generator` types to improve the typing on the decoder.  No longer do the decoder return types contain a bunch of irrelevant junk; now TypeScript can actually distinguish between a `return`ed value and a `yield`ed request.  I've removed the coercions from the places that use these functions' return values since they're no longer necessary.  And, of course, the `GeneratorJunk` type is gone entirely.
While I was at it, I also removed some unnecessary type predicates that I had put in when I didn't know about discriminated unions.  I also removed some lines from `package.json` that shouldn't have been there, which I assume ended up there mistakenly during a merge.
Unfortunately TypeScript had a bunch of trouble handling …

Update TypeScript to 3.6 and make use of Generator types

---

packages/compile-solidity/parser.js

Solc can compile either of the below import lines (notice the lack of white space in the second one):
`import "Example.sol;`
`import"Example.sol;`
But the regex currently fails on the second one. This update allows either to pass.

Allow absence of whitespace in import statement

---

package.json
yarn.lock

Lerna would not prompt properly on `lerna publish` for OTP/2FA password (I require 2FA on publish for my account). https://github.com/lerna/lerna/releases/tag/v3.14.0 added support for this. This PR updates lerna to the latest release

Update lerna to support OTP Fixes

---

packages/reporters/reporters/migrations-V5/messages.js
packages/truffle/test/scenarios/migrations/describe-json.js

(Builds on #2344)
There is a bug with the `migrate --describe-json` flag which throws when migrating a project that hasn't been migrated before. I guess I didn't capture this because I was always using the `--reset` flag that existing addresses, and the test case only tested the `--reset` case.
This PR fixes the bug and adds a test which creates a fresh sandbox to make sure we test both `deploying` and `replacing` cases.

Fix bug with `deploying` cases with describe-json flag on migrate

---

packages/box/tsconfig.json

Edit paths in packages/box/tsconfig.json to point to the root-level node_modules folder instead of the one for packages/box as they are not installed there.
`./packages/box` has the types dependencies listed in the package.json but they end up being installed at the project root level instead of in `packages/box`.

Bug fix: Correct packages/box/tsconfig.json

---

packages/migrate/index.js
packages/migrate/test/index.js

Looks like the provider wrapper doesn't actually do anything!
It [used to](https://github.com/trufflesuite/truffle/blob/28dca63366004258e8abf1329fbbd1be1ca9948f/packages/truffle-migrate/index.js#L206-L233), but now the wrapper is basically a no-op with restrictions.
This should remove the need for #1307 and solve other problems (@CruzMolina said something about the provider-engine fork, but not sure of specifics.)

Stop wrapping the provider for migrations

---

packages/core/lib/commands/init.js
packages/core/lib/commands/unbox.js
packages/truffle/test/scenarios/commands/init.js
packages/truffle/test/scenarios/commands/unbox.js

This incredible PR enables the passing of a path (as a command line argument) to the init command. For example, one could execute `truffle init ./myPath` to initialize a shiny, brand new project in the `myPath` folder!
As a consequence of this cutting-edge feature, the unbox command has also been enhanced! Now you can also pass a path to the command as an argument as follows: `truffle unbox metacoin /Users/Agatha/secretStuff/myMetacoinProject`. The metacoin box will then be unboxed in the `myMetacoinProject` directory.
**NOTE:** Previously you could provide a path at the end of the URL a la `http://something:my/path`. If you provide your own path as an argument, it overrides this suffix path.
**ANOTHER NOTE:** The nightmare of a method that is known as `normalizeInput` in …

Enhancement: Feature truffle init

---

scripts/ci.sh

geth latest isn't playing nice with Truffle (or at least our CI).
One of these recently merged PRs appears to have caused the issue: ethereum/go-ethereum#20075, ethereum/go-ethereum#19953, ethereum/go-ethereum#20054.

Internal improvement: pin geth to latest stable version

---

scripts/prepare-release.sh
scripts/publish-dist-tag.sh
scripts/publish-release.sh

I made some changes/enhancements when I was doing a dist-tag release, and @gnidan [showed interest in a PR](https://trufflesuite.slack.com/archives/CB276HKKJ/p1567815458430200).
This PR does the following:
- Only runs `npm login` if you're not logged in currently (for dist-tag releasing, I could release multiple times a day. this just prevents me from entering all of my info each time)
- The `publish-dist-tag.sh` used to do `git add .`. While `lerna publish` requires you to have no unstaged changes, I don't want this script to bundle temporary changes (i.e. to the scripts themselves) in the commit. Both @gnidan and I [agreed that it makes more sense for the error and for the user to explicitly fix it rather than just commit it](https://trufflesuite.slack.com/archives/CB276HKKJ/p15678155974 …

Release script enhancements

---

.github/workflows/nodejs.yml

Since Github Actions supports any number of custom workflows, it doesn't pass `CI=true` by default (which Travis does).
Makes sure docker/native solc tests (along with any other tests relying on the env) run in Actions CI.

Internal improvement: Set CI env

---

packages/core/lib/commands/config.js
packages/core/lib/services/analytics/google.js
packages/core/test/lib/commands/config.js
packages/core/test/user-config.js
packages/truffle-core/test/lib/commands/config.js

This PR modifies the `truffle config` command behavior to be similar to other config-getting/setting CLIs.
This PR maintains the previous behavior to prevent a breaking change:
- `truffle config` will prompt the user if they'd like to enable/disable analytics
- `truffle config --(en|dis)able-analytics` will enable/disable user-level analytics
The second flags are now deprecated in favor of the new functionality (i.e. `truffle config set analytics <true|false>`). A message to the user has been added to tell them to use the new syntax.
This PR changes the `Help Usage` to be `truffle config <get|set> <key> [<value-for-set>]`. Here is a run down of each of the different commands:
~- `enable` is an alias for `set` with an implied `value-for-set` to be `true`~
~- `disable` is an alias for `set` …

Abstract the config command to read project-level parameters

---

packages/contract/lib/utils.js

This PR fixes #2373.  The problem was that `BN`'s and `BigNumber`'s alike were both being converted to ethers big numbers by means of `toString()`.  However with `BigNumber` you have to use `toFixed()` to prevent the use of scientific notation.  This PR fixes that.
Side note: Given that ethers's big number class is just a wrapper around `BN`, it's disappointing that ethers doesn't provide (AFAICT) any more straightforward way to convert a `BN` to one... (I suppose converting to a hex string rather than a base 10 string might technically save some computation, but that isn't actually worth worrying about...)

Fix BigNumber encoding

---

packages/core/lib/command.js
packages/truffle/test/scenarios/commands/run.js

(Change discussed in #2381)
This is a stop-gap to prevent... 
```
$ truffle run race --km 5
> > Warning: possible unsupported (undocumented in help) command line option: --km
```
(Love the plugin tests)
[EDIT - CI is [failing](https://github.com/trufflesuite/truffle/pull/2402/checks?check_run_id=232125668#step:6:629) on a truffle/compile-solidity test, believe it's unrelated to this PR]

Mute unsupported options warning for plugins

---

packages/codec/lib/interface/contract.ts
packages/codec/lib/utils/wrap.ts
packages/codec/test/contracts/DecodingSample.sol
packages/codec/test/test/decoding-test.js

This PR fixes a bug regarding watching address keys in the contract decoder.  In PR #2379, I got rid of the `compiler = null` hack when converting definitions to types.  However, I forgot about one other place I used this hack, in the `wrapElementaryViaDefinition` function.  This PR gets rid of that and has the actual compiler version passed in.  I also added a test of address keys to the contract decoder test.  (Note: The contract decoder is still very much under-tested, but I'll worry about that some other time.)
Note I'm planning to basically replace these `wrap` functions with better versions in the future.  But that's a ways out still...

Fix bug with watching address keys in decoder

---

packages/codec/lib/allocate/storage.ts
packages/codec/lib/interface/contract.ts
packages/codec/lib/types/allocation.ts
packages/codec/lib/types/interface.ts
packages/codec/lib/utils/conversion.ts
packages/codec/test/contracts/DecodingSample.sol
packages/codec/test/test/decoding-test.js
packages/debugger/lib/data/selectors/index.js

This PR changes the format of the output returned by the contract decoder's `state` function in order to make sure that all state variables are included even when a base contract and derived contract contain state variables of the same name.
Specifically, instead of state variables being indexed by name and containing just a `Result`, they're now in an array, each containing a name, a `Result`, and a `ContractType` object for the contract they were defined in.  This allows different variables with the same name to be distinguished.
This required some extra information being both passed in to and stored in the output of the main storage allocation function so that these defining contracts can be determined later.  Note that it stores the definition, not the type object; the type object is …

Change return type of state() to allow multiple variables with same name

---

packages/codec/lib/allocate/storage.ts
packages/codec/lib/interface/contract.ts
packages/codec/lib/interface/wire.ts
packages/codec/lib/types/errors.ts
packages/codec/lib/types/interface.ts
packages/codec/lib/utils/interface.ts
packages/codec/test/test/decoding-test.js

That's right, @davidmurdoch, @adrianmcli, it's another breaking change to the decoder!  But it's getting bundled with all the others.  Hoping to write up docs for all this soon.
Anyway.  This PR does several things:
1. The `state` function in the decoder no longer includes the variables.  If you want the variables, that's now a separate `variables` function.
2. The decoder should no longer throw exceptions on startup!  I mean, I can't rule it out entirely, but, if it happens, that means I messed up.  It's no longer expected behavior, no longer something you should have to be prepared for.
3. However, the new `variables` function -- as well as the existing `variable`, `watchMappingKey`, and `unwatchMappingKey` function -- now all begin by checking to see whether allocation succeeded, and, …

Rework interface for getting variables in the contract decoder

---

.github/workflows/nodejs.yml

To prevent build failure when the lack of `secrets` causes the action to break

Stop running Slack notifier for forks

---

packages/truffle-db/bin/server.js
packages/truffle-db/src/loaders/artifacts/index.ts
packages/truffle-db/src/loaders/index.ts

This PR adds working directory to the config passed to truffle db and also the loader, to ensure the proper working directory is accessed for all projects.

Add working directory to config object for loader

---

packages/config/index.js
packages/config/test/methods.js

Allow an option `--config` whereby a user can provide a relative or absolute path to a config file of their choice. Truffle will attempt to load the file and use it during the command flow they specified.
This also adds 2 unit tests for `Config.detect`.

Enhancement: Allow --config flag

---

packages/codec/lib/decode/value.ts
packages/codec/lib/encode/abi.ts
packages/codec/lib/encode/key.ts
packages/codec/lib/format/elementary.ts
packages/codec/lib/format/index.ts
packages/codec/lib/index.ts
packages/codec/lib/interface/contract.ts
packages/codec/lib/interface/index.ts
packages/codec/lib/interface/wire.ts
packages/codec/lib/utils/conversion.ts
packages/codec/lib/utils/errors.ts
packages/codec/lib/utils/inspect.ts
packages/codec/lib/utils/wrap.ts
packages/codec/package.json
yarn.lock

This PR just features various quick cleanup to `@truffle/codec`.  Specifically:
1. After talking to @seesemichaelj, the `AsyncEventEmitter` functionality has been removed from the contract decoder and such; nobody's using this and it's basically out of scope for what the decoder's doing.
2. The decoder classes themselves weren't getting exported, which was troublesome for typedoc and probably also for users.  Now they are.
3. The `Elementary` namespace wasn't exported, which is fine for users, but a problem with typedoc.  Now it's exported.
4. In the `BooleanValue` type, `asBool` has been renamed to `asBoolean` (and this has been made consistent everywhere), since Javascript has `boolean`s, not `bool`s.
5. Instead of indiscriminately exporting all types, we now try to stick to just …

Clean up @truffle/codec

---

packages/contract/lib/contract/constructorMethods.js

This PR fixes an incorrect key (`type`) being passed to `Web3Shim` in `@truffle/contract`.
🐞

Fix: incorrect key in `@truffle/contract`

---

packages/hdwallet-provider/package.json
packages/hdwallet-provider/src/index.ts

After an investigation, I noticed that after building `webpack`, I get a broken bundle, the reason for this is the `debug` module, which cannot work with the browser.
Therefore, I decided to remove this module and add support for browsers.
Related with #2374 issue

@truffle/hdwallet-provider: debug removed (browser support added)

---

packages/core/lib/console.js

`truffle develop` and `truffle console` currently die silently if using the `contracts_build_directory` config option with a directory that has a system file, e.g., `.DS_Store`.
Filtering for json files only fixes the issue.

Fix: Filter console reading of contracts_build_directory for json

---

packages/debugger/lib/evm/reducers.js

This PR fixes a debugger crash resulting from a regression in the codex system.  I think what happened is this:
Originally, when I made the codex system, I made it so that, at debugger startup, it created an account for every contract that got called or created.  However, later we made it so that this didn't include creations.  I forget why, but I assume we had a good reason. :P  This then caused a problem when the `updateFrameStorage` function just assumed that the accounts it was updating already existed, and they might not, potentially crashing the debugger.
So, this PR fixes that; now, if `updateFrameStorage` finds that no account exists, it will create one.  Note that it *does* still rely on the assumption that this will only happen with contracts we create rather than contracts we …

Fix debugger crash from regression in codex system

---

packages/debugger/lib/data/reducers.js
packages/debugger/lib/data/selectors/index.js

This PR hides out-of-scope private state variables in the debugger.  So, if you have a base class `Base` with a private state variable `x`, and are currently stepping through a function in a derived class `Derived`, the variable `x` will not appear when you press the `v` command, nor will it be accessible in watch expressions.
~~To accomplish this, I've slightly modified the `DECLARE` system.  Now, each scope maintains both `variables` and `visibles`; when a variable is declared; it's added to `variables`, but only added to `visibiles` if its visibility is not equal to `private` (i.e., is equal to `public` or `internal`).~~
~~Then, when variables from base classes are added in during computation of `data.info.scopes`, only the `visibles` from these base classes are pulled in.  Note that …

Hide private state variables when out of scope

---

packages/contract/lib/utils.js

This PR fixes an issue reported by @area on Gitter; it turns out that my earlier PR #2401 broke encoding of ethers.js `BigNumber`s.
The reason it broke encoding of these is that I didn't realize we supported them!  Honestly I'm not sure the support was even intentional, but it exists and @area was relying on it, so we'd better not break it.  Our code detects whether a given object is a big number of any sort by using `Web3.utils.isBN` and `Web3.utils.isBigNumber`.  The documentation claims that the latter detects the `BigNumber` class from bignumber.js.  In fact, however, it also detects the `BigNumber` class from ethers.js, despite this being a totally different class!
That's pretty crazy, but I think we have to live with it for now -- or at least, we can worry about it later; first …

Unbreak support for ethers.js BigNumber

---

packages/contract/test/errors.js
packages/core/lib/commands/config.js
packages/core/package.json
yarn.lock

Remove truffle-init which seems to be an unused dependency.
I noticed in some of the logging output that some dependencies are still using the old non-org-scoped packages. In the interest of getting rid of these warnings, truffle-init has been removed as it is not used anywhere.

Dependency update: Remove unused dep

---

packages/core/lib/debug/interpreter.js

This quick PR fixes what's printed by the `;` command.  I noticed it wasn't behaving properly when the transaction halted or had already halted; turned out it wasn't checking that condition and was treated identically to the `p` command.  Now it behaves like `n` and the other advancing commands when the trace finishes.

Correct what's printed by the ; command

---

packages/debugger/lib/evm/sagas/index.js
packages/debugger/lib/evm/selectors/index.js
packages/debugger/lib/solidity/sagas/index.js
packages/debugger/lib/solidity/selectors/index.js
packages/debugger/test/solidity.js

The debugger currently has code to account for the possibility that a call instantly returns, with no trace steps generated for the called account.  This situation comes up when calling a precompiled contract or externally-owned account.  However, I recently learned that there's another situation where it comes up: When the call instantly fails due to attempting to transfer more ether than you have, or when it instantly fails due to overflowing the call stack.  These last two possibilities can also come up with contract creations, not just message calls; however, we were only accounting for it in the case of calls.  This PR modifies the relevant code so that it applies to contract creations as well.
I also added a test of this.

Account for instantly-returning creates

---

packages/debug-utils/package.json
yarn.lock

This PR updates the `@trufflesuite/chromafi` version to 2.1.2.  You see, chromafi uses `deepmerge`, but `deepmerge` (or possibly just old versions of it?) has incompatibilities with Webpack; as such it worked fine in the non-bundled version, but caused the debugger to crash when run bundled.  I updated our version of the chromafi package to use `lodash.merge` instead, which fixed the problem.  Of course, this PR doesn't directly contain that work, but it updates the version so that things work here.

Update @trufflesuite/chromafi version to prevent bundled crash

---

packages/box/package.json
packages/code-utils/tsconfig.json
packages/decoder/lib/decode/calldata.ts
packages/decoder/lib/decode/constant.ts
packages/decoder/lib/decode/index.ts
packages/decoder/lib/decode/memory.ts
packages/decoder/lib/decode/special.ts
packages/decoder/lib/decode/stack.ts
packages/decoder/lib/decode/storage.ts
packages/decoder/lib/decode/value.ts
packages/decoder/lib/interface/contract-decoder.ts
packages/decoder/lib/read/index.ts
packages/decoder/lib/read/storage.ts
packages/decoder/package.json
yarn.lock

Currently `yarn.lock` is out of date. If you delete that file and run `yarn bootstrap`, the bootstrap will fail with a bunch of TypeScript errors. So far, the types file for `inquirer` needs to be locked to a specific version and some `rootPaths` adjusted.
There are some things in debugger/decoder land that likely @gnidan or @haltman-at should take a look at and resolve before this work is finished.

Internal improvement: Keep yarn.lock up to date

---

packages/core/lib/commands/test.js

There is a bug in 5.0.40 where when running `truffle test` it won't search recursively in the test folder for test files. This updates the glob pattern search to do this.

Bug fix: Update glob pattern for test file search

---

packages/core/lib/testing/testsource.js

This ignores all non-json files in the build folder when loading artifacts during testing.

Bug fix: Filter out non-json files in build folder

---

packages/compile-solidity/run.js

If no contracts were found in compiled files, do not attempt to process the contract output.
This fixes a bug regarding the case where there is a source that does not have a contract declared in it. In that case, the compiler output will not have a `contracts` property. When it attempts to process the contracts, an error will occur. This PR checks to see if the `contracts` property is undefined and if it is, returns an empty array.
The one slightly "off" thing about this PR is that the output will be something like the following:
You will notice that it says "Compiling ./contracts/Imports.sol" and later on it says "Everything is up to date, there is nothing to compile". That is because it prints the first message before actually compiling. Once it determines there were no contracts …

Bug fix: Do not process contracts when none are found in compiler output

---

packages/contract/lib/utils.js
packages/core/lib/testing/testrunner.js

This PR provides some temporary workarounds for #2449 until the new decoder is ready.
In the test runner, this consists of putting a try/catch around event decoding and just printing a warning if it fails.
In `contract`, this consists of moving the number formatting call into the try/catch I earlier put around event decoding (thanks @eggplantzzz for figuring out this problem).

Workarounds for test event errors

---

packages/codec/lib/format/values.ts
packages/decoder/lib/decoders/contract.ts
packages/decoder/lib/errors.ts
packages/decoder/lib/types.ts
packages/decoder/test/test/decoding-test.js

This PR replaces the `name` field of `ContractState` with a `class` field, and also adds an `address` field.  The `class` field is a `ContractType` and contains the name among other info.  This is a breaking change.  Tests are updated appropriately.
(Also, `prettier` seems to have done some work here... oops? :-/ )
This PR also makes a slight change to handling of user-inputted addresses.  Before they weren't checked; Web3 would check them when used, but we didn't do the check, which is potentially troublesome.  Now they're checked on use (as in, either they should be checksummed, or else they should be all one case to circumvent the checksum), and converted to checksum form if not in that form already.
I also fixed some comments and some error constructors, which you shouldn't really do …

Replace name with class and address

---

packages/codec/lib/ast/utils.ts
packages/decoder/test/contracts/WireTest.sol

This PR *was* going to fix a bug that I thought existed regarding circular types in the allocator.  It turns out that this bug doesn't exist though.  So instead I added a comment explaining why it doesn't exist (so I don't make this mistake again) and a test of its nonexistence (just in case somene accidentally causes it to exist someday).

Add test & comment re: circular types

---

packages/decoder/lib/decoders/contract.ts
packages/decoder/lib/errors.ts

This PR cleans up the contract instance decoder a little by having it throw an exception if someone asks for a variable that doesn't exist, rather than returning `undefined`.

Throw when can't locate variable asked for

---

packages/decoder/README.md
packages/decoder/lib/index.ts
packages/decoder/lib/types.ts
packages/decoder/test/test/decoding-test.js
packages/decoder/test/test/downgrade-test.js
packages/decoder/test/test/wire-test.js

This PR redoes the `@truffle/decoder` constructor functions.  It also adjusts the documentation and tests to match.
Because of all the added documentation, I'm skipping a long writeup of how the new functions work and why they're organized as they are; you can just see the documentation.  (Which, uh, hopefully I haven't messed up.)  Also @gnidan you will be familiar with it from our earlier discussion. :P
This PR does contain one nasty hack (which is why I've tagged you, @CruzMolina :P ); since there don't currently exist proper types for contract constructor or abstraction objects, I've just declared them myself, containing just the parts that we need.  The intent is to get rid of this later once proper types exist.  (...or maybe not, if that leads to circular dependencies; but the …

Redo @truffle/decoder constructor functions

---

packages/codec/README.md
packages/codec/lib/decode/errors.ts
packages/codec/lib/format/elementary.ts
packages/codec/lib/format/errors.ts
packages/codec/lib/format/index.ts
packages/codec/lib/format/types.ts
packages/codec/lib/format/values.ts
packages/codec/lib/index-typedoc.ts
packages/codec/lib/interface/decoders/contract.ts
packages/codec/lib/interface/decoders/wire.ts
packages/codec/lib/interface/errors.ts
packages/codec/lib/interface/index.ts
packages/codec/lib/types/decoding.ts
packages/codec/lib/types/errors.ts
packages/codec/lib/types/interface.ts

This PR adds a bunch of documentation for the new codec, mostly in the form of TypeDoc comments, but also there's a README.  Hooray...
Note that `Format` has been mostly left alone as self-explanatory, with just occasional comments where I thought it necessary.  The rest though has plenty of comments...

Add documentation for new codec

---

packages/codec/lib/format/utils/inspect.ts
packages/decoder/lib/decoders/contract.ts
packages/decoder/lib/decoders/wire.ts

This PR does two things.  First, it replaces `@hidden` and `@private` with `@protected`.  Second, it puts giant warnings on the nativize function to make clear you shouldn't actually use it in real code.
(Partial addressing of #2505 )

Mark things protected, add warning to nativize

---

packages/decoder/lib/decoders/contract.ts
packages/decoder/lib/decoders/wire.ts

As suggested by @gnidan, this PR adds the following (marked as protected) functions to the wire decoder: `decodeLogWithAdditionalOptions`, `decodeLogsWithAdditionalOptions`, `eventsWithAdditionalContexts`.  This lets us remove the various internal-only parameters from the `decodeLog`, `decodeLogs`, and `events` functions (which now just call the functions above).
The contract decoder is unchanged, since it wasn't using these additonal parameters.  The contract instance decoder however is changed to call these internal versions, since it uses these additional parameters.
(Note: This is again tied to issue #2505 )

Avoid directly exposing internal parameters

---

packages/codec/lib/abi/index.ts
packages/codec/lib/allocate/abi.ts
packages/codec/lib/encode/abi.ts
packages/codec/lib/format/utils/index.ts
packages/codec/lib/format/utils/inspect.ts
packages/codec/lib/index.ts

This PR prunes various things from the codec exports (or just the docs).  Specifically:
* `DecoderOptions` is no longer exported
* `abifyResult` and `abifyType` are no longer exported
* `Abi` no longer has an exported `Decode` submodule
* Since there was no way I could find to avoid exporting it, `abiSizeInfo` is now marked `@protected`
* Similarly with `stringToBytes` (this and `padAndPrependLength` also got a category applied to them to avoid causing an empty "other functions" section)
* Since there was no way to avoid exporting it, the `Exception` module in `Format` is now marked `@protected`

Prune various things from exports/docs

---

packages/decoder/lib/decoders.ts

(Related to #2505)
Somehow, when doing #2507, I forgot to include transaction decoding.  Now that change is applied to transaction decoding as well.

Hide additionalContexts parameter on transaction decoding as well

---

packages/decoder/lib/decoders.ts
packages/decoder/lib/index.ts

(Related to #2505)
Because we can't get TypeDoc to display `async` on async functions, this PR manually marks async functions as such with bold warnings in their docstrings.

Manually mark various functions as async in docstring

---

packages/codec/lib/abi/utils.ts
packages/codec/lib/abify.ts
packages/codec/lib/compiler/utils.ts
packages/codec/lib/contexts/utils.ts
packages/codec/lib/core.ts
packages/codec/lib/evm/utils.ts
packages/codec/lib/format/utils/exception.ts
packages/codec/lib/format/utils/inspect.ts
packages/codec/lib/format/utils/maketype.ts

This PR just updates the `debug` namespaces as per @gnidan's codec reorganization.
(`prettier` seems to have done some work as well...)

Update debug namespaces for codec reorg

---

packages/decoder/lib/decoders.ts

This PR fixes an issue I just noticed with `additionalContexts`.  (I'm realizing now that that little feature has never really been tested and uhhhh I should probably find some way of doing that before we realease it...)
Basically, `additionalContexts` didn't actually work because, in the call to `makeContext`, you'd possibly attempt to take the SHA3 hash of `undefined`, which causes an error.  And even if you avoided that, you'd still be taking the hash of the wrong thing.  And while we override the binary later, we weren't overriding the hash as well.  (Not that it should actually cause a serious problem if you hit this case, but...)
This PR fixes that by overriding the binary *before* the call to `makeContext`, so it should work fine and also produce the correct hash.
We should really …

Fix issue with additionalContexts

---

packages/contract/lib/reformat.js
packages/contract/test/methods.js
packages/contract/test/sources/Example.sol

- Using `_convertNumberArray()` recursively to finally `_convertNumber()`
- Also added one test case for both named and unnamed return values
Fixes #1723

Fix nested array conversion

---

packages/codec/lib/index.ts

This PR adds a note to the format documentation about overlarge lengths and pointers, and how these are considered errors even though by our stated criteria they likely shouldn't be.

Add note about overlarge lengths & pointers

---

packages/decoder/test/contracts/DecodingSample.sol
packages/decoder/test/contracts/DowngradeTest.sol
packages/decoder/test/migrations/2_deploy_contracts.js
packages/decoder/test/test/downgrade-test.js

This PR adds a test for the contract instance decoder's "additional contexts" feature.  It adds a state variable, `doYouSeeMe`, of type `function() external`, and initializes it to `this.causeTrouble`.  Then, it attempts to decode this variable but with a mangled artifact that is missing the deployed bytecode.  Because of the additional contexts feature, the decoding succeeds (with full information) regardless.
It also adds a link to `DecoyLibrary` from `DowngradeTest` just to make the test a little harder to pass. :)  (OK, I guess this doesn't *really* make it harder, but like, it notionally could?  IDK.)

Test additional contexts feature in contract instance decoder

---

packages/decoder/lib/decoders.ts
packages/decoder/lib/index.ts
packages/decoder/lib/types.ts
packages/decoder/test/test/downgrade-test.js
packages/decoder/test/test/wire-test.js

This PR simplifies the return types of `decodeTransaction` and `decodeLog` by having them simply return the decoding (or array of decodings) without the additional complication of `DecodedTransaction` or `DecodedLog`.  The `DecodedLog` type is still present so it can be returned by `events`, though.  Also, the `decodeLogs` function has been removed entirely.  Tests have been updated appropriately.
In addition, the `Transaction`, `Log`, and `BlockType` types from Web3 have been replaced by equivalent types we define.  Note that I renamed `BlockType` to `BlockSpecifier` for clarity.
In writing this I noticed that there may be some slight problems in how block specifiers are currently handled.  I'll fix those in a separate PR.  (Or possibly two PRs, since some of this I'd …

Simplify wire decoder return types; internalize Web3 types

---

packages/decoder/lib/decoders.ts
packages/decoder/lib/types.ts

This PR fixes some wonky behavior of `decoder` regarding `BlockType` inputs (or, as I've renamed it, `BlockSpecifier`).  I was originally going to do this on develop but decided it was too much trouble, so, well, it's a PR against `next`.
There are basically two problems here in need of fixing:
1. If a user enters `"pending"` as the block they want, it won't work properly because our caching system relies on blocks having numbers.
2. If a user enters `"genesis"` as either bounding block in a call to `events`, it won't work properly because it turns out that Web3 doesn't allow using `"genesis"` as a bound in `getPastLogs()`.
To solve these problems, all user-entered blocks are now run through a new method I call `regularizeBlock`.  This returns a type I'm calling …

Regularize behavior of block inputs; fix "pending"

---

packages/compile-solidity/compilerSupplier/index.js
packages/contract-schema/package.json

Bump the default Solidity version to 0.5.12 in CompilerSupplier

Dependency update/Internal improvement: Bump default Solidity version to 0.5.12

---

packages/codec/lib/index.ts

This PR adds a readme for `@truffle/codec`, parallelling the one to `@truffle/decoder`.  It doesn't say a lot, for obvious reasons, but I'm hoping it says enough.

Write codec README

---

packages/migrate/index.js
packages/migrate/migration.js

This will allow a migration to be able to interact with any of the Truffle packages using the same configuration that the migration is using to run.  One example use case (mine) is to compile dynamic contracts based on the result of migration (e.g., hard-code an address in a contract as a gas optimization rather than passing it as a constructor).
Along the way I also cleaned up options vs config a little bit, once `config` is resolved it should be used rather than `options` since it may have different property values once full config resolution is complete.

Makes `config` available in the migration context.

---

packages/resolver/package.json

`resolver/index.js` references `@truffle/contract` yet the project doesn't have a dependency on it.  This means if someone tries to use this package standalone, or as a transitive dependency of some other package, they'll get a runtime failure.

Adds dependency that was missing.

---

packages/interface-adapter/lib/interface-adapter.ts
packages/interface-adapter/lib/web3-interface-adapter.ts
packages/workflow-compile/test/index.js

Continuation of #2480 & #2532 that implements Step 2 for `setProvider` as outlined [here](https://gist.github.com/gnidan/a55bbec28800f64d487054be18730691#file-step2-ts).

Internal Improvement: From Web3Shim to InterfaceAdapter – Step Two: setProvider

---

packages/codec/lib/basic/decode/index.ts
packages/codec/lib/contexts/utils.ts
packages/codec/lib/core.ts
packages/codec/lib/format/utils/maketype.ts
packages/decoder/lib/decoders.ts

This PR moves the `contextToType` function from `Contexts` into the `MakeType` module for consistency, and adjusts appropriately everywhere that calls it.

Move contextToType to MakeType

---

packages/core/lib/commands/test.js

Add flag for truffle test to suppress all output save for the output from the test runner itself.
Inspired by https://github.com/trufflesuite/truffle/issues/2457

Enhancement: Add flag `truffle test --runner-output-only`

---

packages/debug-utils/package.json
yarn.lock

This PR bumps the version of highlightjs-solidity used for the syntax highlighting in the debugger, now that 1.0.8 is out.

Bump highlightjs-solidity version

---

packages/codec/lib/abi-data/allocate/types.ts
packages/codec/lib/ast/read/index.ts
packages/codec/lib/basic/decode/index.ts
packages/codec/lib/contexts/utils.ts
packages/codec/lib/core.ts
packages/codec/lib/evm/types.ts
packages/codec/lib/format/errors.ts
packages/codec/lib/format/utils/exception.ts
packages/codec/lib/format/utils/maketype.ts
packages/codec/lib/mapping-key/encode/index.ts
packages/codec/lib/memory/allocate/types.ts
packages/codec/lib/pointer/types.ts
packages/codec/lib/read.ts
packages/codec/lib/storage/allocate/types.ts
packages/codec/lib/topic/encode/index.ts
packages/decoder/lib/decoders.ts

Branch `scatter-the-pages` currently introduces circular dependencies, mostly around trouble mostly of these kinds:
- Ast was previously not a data location and thus was safer for more things to import wholesale. Ast's new Decode module introduces circular dependencies. Consequently, this PR modifies problematic Ast imports to import specific submodules
- `types` modules seem to mostly need rely only on other types modules directly
- Read modules seem to need to import other Read modules directly
- Encode modules seem to need to import other Encode modules directly
- Decode modules seem to be able to import entire other modules wholesale
Not sure if this is worth codifying, or if it is sound inductive reasoning at all.
Ah, also: revert #2554

Remove circular dependencies from Codec

---

packages/codec/README.md
packages/decoder/README.md
packages/decoder/lib/index.ts

This PR adds brief repository readmes for codec and decoder.  They are short as their main function is to link to the API documentation.
I also fixed an unrelated typo.

Add readme files for codec and decoder repos

---

packages/contract/lib/utils.js
packages/contract/test/methods.js

Bug fix: Properly apply gasMultiplier to gasEstimates

---

packages/decoder/lib/decoders.ts
packages/decoder/lib/index.ts
packages/decoder/lib/types.ts
packages/decoder/lib/utils.ts

This PR renames `ContractObject` to `Artifact` on import for clarity.
Also, while I was at it, I fixed the outdated function name `forContractAbstraction` in the decoder docs.

Rename ContractObject to Artifact for clarity

---

packages/codec/docs/README.md
packages/codec/lib/index.ts

This PR (part of #2505 I guess though I didn't bother adding it there) increases the documented minimum version of Solidity required for full mode from 0.4.9 to 0.4.12, just to be a little safer. :)

Increase minimum Solidity version required for full mode

---

packages/codec/docs/typedoc.json
packages/codec/package.json
yarn.lock

This PR sets typedoc to use our custom theme which lives in the `@trufflesuite/typedoc-default-themes` repo.  Most of the work of course was in making that theme, but that's done, and this PR sets us to use it.
A note: When I `yarn add`ed the theme, it ended up in the top-level `node_modules` directory, not `codec`'s one.  So, uh, hopefully that happens consistently?  Because I don't know of any way to make it work regardless of which one it ends up (although it might not be impossible to hack something together, but that would probably be a task for someone else).

Switch typedoc to our custom theme

---

packages/core/package.json

```
npm install @truffle/core
node node_modules/@truffle/core/build/cli.js
```
> Error: Cannot find module '@truffle/environment'

Adds missing dependency.

---

packages/decoder/package.json

This PR removes some unused dependencies from the decoder (or switches them to `devDependencies` if they were used only in testing).
Btw there were some other things in there I didn't recognize at all, but I assume those are being used for some internal stuff somehow or whatever?  IDK.  I guess not in here but rather in `codec/package.json`.  Like what is `source-map-support`, and is it really a runtime dependency rather than a dev dependency?  ...I guess that's really the only case.  Anyway I left that one alone.

Remove unused dependencies from decoder

---

packages/contract/lib/override.js
packages/interface-adapter/lib/ethereum-overloads.ts
packages/interface-adapter/lib/interface-adapter.ts
packages/interface-adapter/lib/interface-adapter/types/index.d.ts
packages/interface-adapter/lib/web3-interface-adapter.ts

Continuation of #2473 that implements Step 2 for `getTransactionReceipt` as outlined [here](https://gist.github.com/gnidan/a55bbec28800f64d487054be18730691#file-step2-ts).

Internal improvement: From Web3Shim to InterfaceAdapter – Step Two: getTransactionReceipt

---

packages/codec/lib/abi-data/encode/index.ts
packages/codec/lib/format/errors.ts
packages/codec/lib/format/types.ts
packages/codec/lib/format/utils/inspect.ts
packages/codec/lib/format/values.ts

This PR adds typeclass `type` to the type system, so that we don't break things by adding it later.  (Hopefully we don't have to add anything else for quite a while!)  It doesn't actually add anything that produces these, but it does add some rudimentary handling for them.
Note: I added `stateVariableTypes` as an optional property of `TypeType` rather than `ContractType` (or rather `ContractTypeNative`).  I only realized now that seems kind of off.  But, I think it's fine -- `TypeType` is really just meant for internal use; so even if this seems a bit wrong, this better matches how I intend the code to actually work.
Also, the type that would be called `TypeError` is instead called `TypeErrorUnion`, because, uh, yeah, that name's already taken. :P
I also changed a bunch of "should"s to …

Add rudimentary code for TypeType, TypeValue, etc

---

packages/decoder/lib/index.ts

Fix capitalization; these *are* API docs; decodeLog no longer returns a DecodedLog

Harry's brief review of decoder docs

---

packages/environment/package.json

Looks like `@truffle/artifactor` got removed by accident and `@truffle/environment` [requires it](https://github.com/trufflesuite/truffle/blob/develop/packages/environment/environment.js#L6).

Fix: Readd @truffle/environment dep

---

packages/contract/index.js
packages/contract/lib/contract/constructorMethods.js
packages/contract/test/cloning.js
packages/contract/test/contract/constructorMethods.js
packages/core/lib/console.js
packages/core/lib/testing/testrunner.js
packages/interface-adapter/lib/interface-adapter.ts
packages/resolver/index.js

Surfaced from [Gitter conversation](https://gitter.im/ConsenSys/truffle?at=5dcb38ba4adf071a841b760d), this PR fixes a recent breakage caused by the introduction of a networkType argument to the root @truffle/contract factory.
Since @truffle/contract is documented to work via a separate "provision" step, this PR removes the recently-added pre-provision network configuration and aligns it with the more mature provider configuration, since they are effectively related.
This consolidates `setNetworkType` / `setProvider` inside @truffle/contract to be simple facades to a new `configureNetwork` method, and implements the newly-required `setNetworkType` method to the InterfaceAdapter (necessary for the parallelism).

Fix accidental breaking change to resolver

---

packages/migrate/index.js
packages/migrate/migration.js

Previously, useful stack traces were not showing when an error in migrations happened. This was due to the fact that when errors were caught in `migrations/index.js`, a new error was created with the caught error rather than throwing the error directly. This messed up the stack trace. This PR causes the code to throw that error directly.

Bug fix: Throw errors properly to preserve stack trace

---

packages/hdwallet-provider/src/index.ts
packages/hdwallet-provider/test/provider.test.ts

Change default numAddresses from 1 to 10:
- Aligns HDWalletProvider behavior with Ganache's default
Change privateKey for loop logic:
- Ensures only the array length of privateKeys passed are
attempted to be unlocked as accounts
Valid mnemonic's will unlock 10 accounts by default. Only the number of private keys passed will be unlocked.

Enhancement: Make HDWalletProvider's default number of accounts unlocked align with ganache

---

packages/migrate/index.js
packages/migrate/package.json

This PR removes the `async` library from `@truffle/migrate`. It, in my opinion, also cleans up the code a bit and makes it easier to read.

Internal improvement: Update migrations

---

packages/contract/lib/contract/constructorMethods.js
packages/interface-adapter/lib/adapter/types.ts
packages/interface-adapter/lib/adapter/web3/index.ts
packages/migrate/index.js

Continuation of #2473 that implements Step 2 for `getCode` as outlined [here](https://gist.github.com/gnidan/a55bbec28800f64d487054be18730691#file-step2-ts).

Internal improvement: From Web3Shim to InterfaceAdapter – Step Two: getCode

---

packages/truffle/cli.webpack.config.js
packages/truffle/package.json
yarn.lock

Only uses `shebang-loader` where needed & removes seemingly unused `imports-loader` rule along w/ the `imports-loader` devDep.

Internal improvement: Optimize webpack rules

---

packages/truffle/cli.webpack.config.js

Converts function in `externals` to a regex. ~Also turns out `mocha` behaves and bundles correctly (🤞) .~

Internal improvement: tidy up externals in webpack config

---

packages/contract/lib/execute.js
packages/interface-adapter/lib/adapter/types.ts
packages/interface-adapter/lib/adapter/web3/index.ts

Continuation of #2473 that implements Step 2 for `estimateGas` as outlined [here](https://gist.github.com/gnidan/a55bbec28800f64d487054be18730691#file-step2-ts).

Internal improvement: From Web3Shim to InterfaceAdapter – Step Two: estimateGas

---

scripts/ci.sh

Updates Golang to 1.12 on the `fabric-evm` job.
Resolves #2636 .

Internal improvement: Fix fabric-evm job

---

packages/contract/package.json
packages/debug-utils/index.js
packages/debug-utils/package.json
packages/debugger/package.json
packages/resolver/package.json

This PR is an initial effort at getting rid of the use of the `async` library.  No, not the `async` keyword, the `async` library.  Yes, it exists.  Yes, we use it.  Yes, that's confusing.
It's an old library for writing callback-style code, which unfortunately we still have a lot of.  I wanted to get rid of it, but quickly found that rewriting a bunch of callback-style code with `async` (the keyword, that is!) and `await` wasn't really an easy thing to do when it wasn't code I knew at all and some of it used callbacks with multiple success parameters.
So, I'm PRing this partial effort.  I uninstalled `async` from several packages that had it listed but weren't actually using it, and removed its use from `debug-utils`.
It can still be found in `compile-vyper` (one use), and in `core` (a …

Internal improvement: Start removing the use of the async library

---

packages/codec/lib/abi-data/allocate/index.ts
packages/codec/lib/abi-data/allocate/types.ts
packages/codec/lib/abi-data/decode/index.ts
packages/codec/lib/abify.ts
packages/codec/lib/ast/utils.ts
packages/codec/lib/core.ts
packages/codec/lib/decode.ts
packages/codec/lib/evm/types.ts
packages/codec/lib/format/errors.ts
packages/codec/lib/index.ts
packages/codec/lib/pointer/types.ts
packages/codec/lib/read.ts
packages/codec/lib/types.ts

This PR implements return data decoding in `codec`.  It does *not* put an interface for it in `decoder`, partly because it's not yet clear how such an interface should work.  It does, however, add a function `decodeRevertMessage` to `codec` that can be used as something of an interface for revert string decoding.
By the way, here have been some changes to the internals of allocation objects to support this new feature; but as the internal structure of allocation objects (rather than their use) have never really been public-facing, I wouldn't really consider this a breaking change.  There's also a new data location, `returndata`, with corresponding pointer type.  Strictly speaking that wasn't necessary, but I figured it was the right way to do this.  (Also, while making changes to pointer …

Implement return data decoding in codec

---

packages/migrate/index.js
packages/migrate/package.json
yarn.lock

Remove the stupid node-dir library in favor of the almighty glob!! With glob, a slightly more sophisticated search/filter for migrations files will occur.
Previously using node-dir this was causing a problem when there was something, such as an empty folder, in the migrations folder. See #2628. #2420 was the same problem.

Bug fix: Allow extra items in migrations folder

---

packages/contract/lib/utils/ens.js
packages/core/lib/assertions.js
packages/core/lib/testing/deployed.js
packages/core/lib/testing/testrunner.js
packages/core/package.json
packages/deployer/ens.js
packages/deployer/package.json
packages/deployer/src/deployment.js
packages/external-compile/index.js

This PR makes all web3 utility functions use `web3-utils` directly rather than `web3`.

Internal improvement: web3-utils as independent pkg

---

packages/contract/lib/override.js
packages/core/lib/testing/testrunner.js
packages/deployer/src/deployment.js
packages/deployer/test/deployer.js
packages/interface-adapter/lib/adapter/types.ts
packages/interface-adapter/lib/adapter/web3/index.ts
packages/provider/index.js

Continuation of #2473 that implements Step 2 for `getBlockNumber` as outlined [here](https://gist.github.com/gnidan/a55bbec28800f64d487054be18730691#file-step2-ts).

Internal improvement: From Web3Shim to InterfaceAdapter – Step Two: getBlockNumber

---

packages/codec/lib/decode.ts
packages/codec/lib/format/utils/circularity.ts
packages/codec/lib/format/utils/index.ts
packages/codec/lib/format/utils/inspect.ts
packages/codec/lib/memory/decode/index.ts
packages/codec/lib/types.ts
packages/debug-utils/index.js
packages/debug-utils/test/index.js
packages/debugger/test/data/more-decoding.js

This PR implements circularity detection in `codec` (with one change to `debug-utils` as well).  Note that this only really affects the debugger, as only memory structures can be circular in Solidity; storage structures may have circular *types* but are not allowed to take on circular *values*, while ABI-encoded structures aren't even allowed to have circular types.
It's worth noting that the decoded version of a circular structure may not be isomorphic to the original.  It will, however, be bisimilar.  I think that's OK.  At the very least, it's the best we can do at the moment; if we wanted isomorphism, we'd have to rework both the decoder itself and the output format.  As it is I think it's fine.  I mean, you don't expect the decoder to detect aliasing in *non*-circular structures, do …

Implement circularity detection in codec & debugger

---

packages/core/lib/commands/test/helpers.js

When running `truffle test` it won't search recursively in the test folder for test files.
It was fixed closing #2461 and introduced again.

fix: update path generation in test directory

---

packages/compile-ligo/test/sources/LigoContract2.mligo
packages/interface-adapter/package.json
yarn.lock

Updates `@taquito/taquito` to 5.2.0-beta.1.
Also updates a cameligo test contract to match new cameligo syntax.

Dependency update: @taquito/taquito

---

packages/compile-ligo/index.js
packages/tezos-contract/lib/execute.js

Enables more complex deployment scripts such as...
```
const Token = artifacts.require("Token");
module.exports = deployer => {
deployer.deploy(Token, {
totalSupply: "100",
accounts: {
'tz1bwsEWCwSEXdRvnJxvegQZKeX5dj6oKEys': {
balance: '100',
allowances: {}
}
}
});
};
```

Output michelson json & leverage during contract originations

---

packages/provider/index.js

It appears the default 5 second timeout is occasionally too short for live tezos networks.
Bumping to 10 seconds has proven thus far to resolve the issue.

Fix: bump network timeout check

---

packages/core/lib/debug/interpreter.js
packages/core/lib/debug/printer.js
packages/debugger/lib/evm/selectors/index.js

This PR addresses issue #2551.  It has the debugger CLI print the revert message (decoded via Truffle Codec) at the end of a failing transaction.
In order to make this work there is also one change to the debugger library itself.  Previously, the `evm.current.step.returnValue` selector would return `null` if the current instruction wasn't a normal halting instruction, including if it were `REVERT`.  Now, it gets the return value on either `RETURN` or `REVERT`, and simply returns `"0x"` otherwise; it no longer ever returns `null`.
Strictly speaking, this does lead to two crazy corner cases:
1. If the transaction ends with a `REVERT`, but the revert *fails* (by running out of gas), we'll display the revert message even though no revert message technically occurred.  This seems fine.
2. ~~If …

Have debugger CLI print revert string on failing halt

---

packages/codec/docs/README.md
packages/codec/lib/abi-data/allocate/index.ts
packages/codec/lib/abi-data/allocate/types.ts
packages/codec/lib/core.ts
packages/codec/lib/types.ts
packages/decoder/lib/decoders.ts
packages/decoder/test/contracts/DowngradeTest.sol
packages/decoder/test/contracts/WireTest.sol
packages/decoder/test/test/downgrade-test.js
packages/decoder/test/test/wire-test.js

This PR takes various steps to improve the handling of inherited and overridden events in `codec`.  In order to do this it expands the format slightly, so we might want to bump the version up to 0.2.0.
So: Log decodings now contain an optional `definedIn` member.  Whereas `class` is the class that emitted the event, `definedIn` is the class that defined it.  It is optional because, in ABI mode, it is not always possible to determine.
So, let me first explain the problem this PR is trying to solve.  OK, so events can be inherited... no big deal, right?  It's not like our existing code failed to handle that.  If a contract inherits events from another, the inherited events will go in its ABI.  So all's well, right?  Sure, we didn't have `definedIn`, but that information is redundant anyway, …

Better handling of inherited and overridden events

---

packages/core/lib/commands/test/index.js

Previously, looks like lib/commands/test was trying to turn off Ganache VM errors (i.e., operate in standard mode)... but it was using the field name `noVMErrorsOnRPCResponse` instead of the correct `vmErrorsOnRPCResponse`.

Correctly disable VM errors for `truffle test`'s ganache-core

---

packages/compile-solidity/package.json
packages/compile-solidity/test/sources/v0.6.x/ComplexOrdered.sol
packages/compile-solidity/test/sources/v0.6.x/InheritB.sol
packages/compile-solidity/test/sources/v0.6.x/Version6Pragma.sol
packages/compile-solidity/test/test_supplier.js
packages/core/lib/templates/Example.sol
packages/core/lib/templates/Test.sol
packages/core/lib/testing/Assert.sol
packages/core/lib/testing/AssertAddress.sol
packages/core/lib/testing/AssertAddressArray.sol
packages/core/lib/testing/AssertAddressPayableArray.sol
packages/core/lib/testing/AssertBalance.sol
packages/core/lib/testing/AssertBool.sol
packages/core/lib/testing/AssertBytes32.sol
packages/core/lib/testing/AssertBytes32Array.sol
packages/core/lib/testing/AssertGeneral.sol
packages/core/lib/testing/AssertInt.sol
packages/core/lib/testing/AssertIntArray.sol
packages/core/lib/testing/AssertString.sol
packages/core/lib/testing/AssertUint.sol
packages/core/lib/testing/AssertUintArray.sol
packages/core/lib/testing/NewSafeSend.sol
packages/core/lib/testing/deployed.js
packages/core/test/lib/create.js
yarn.lock

*does not include solc v0.6.x compatibility in `@truffle/debugger`, `@truffle/codec` & `@truffle/decoder`.

Enhancement: solc v0.6.x compatibility

---

packages/debugger/lib/data/sagas/index.js

The giant switch in the data saga was missing a `break`!  Quick PR to add it in.
Have to wonder whether this might happen to be the cause of #2673.  Doubt it, don't see how it would cause that, but it's not totally implausible?

Add missing break in data saga switch!

---

packages/contract/lib/utils/index.js
packages/core/lib/logging/TruffleLogger.sol

@CruzMolina I've made a couple minor improvements for the logger, but not sure how to publish onto the NPM tag.
This small PR changes:
- The logger event to watch is now `_TruffleLog` instead of `__Log`
- **Rationale:** Better namespacing
- Users who want to log can now call `TruffleLogger.log` instead of `emit TruffleLogger.__Log`
- **Rationale:** Better developer experience, more similar to `console.log`

Direct function call + more sensible naming

---

packages/codec/lib/ast/utils.ts
packages/codec/lib/stack/decode/index.ts
packages/debugger/lib/data/reducers.js

This PR adjusts `codec`'s AST utils to account for the addition of slice types in 0.6.0.  That's really it.
Note I *didn't* bother adding decoding support for array slices, because there's currently no need for this.  I can go back and add this later if we think it's worth it (it wouldn't be hard).
We do need decoding support for string and bytestring slices, but luckily, I added that long ago!  (Because it was necessary to get `msg.data` to work as a mapping key.)

Adjust AST processing to account for slices

---

packages/codec/lib/abi-data/types.ts
packages/codec/lib/abi-data/utils.ts
packages/codec/lib/ast/utils.ts
packages/codec/lib/contexts/types.ts
packages/codec/lib/core.ts
packages/codec/lib/types.ts
packages/decoder/lib/utils.ts

This PR updates the codec & decoder for the addition of receive functions in 0.6.0.  It also adjusts doc comments appropriately.
Now, when doing a `decodeCalldata`, if the decoding is of type `"message"`, the `abi` field will contain the `receive` ABI rather than the `fallback` ABI if applicable (i.e., a `receive` ABI exists and the transaction had no data).  In order to make this work I decided to just store both these ABIs in the context object rather than do the circuitous thing I had before where I would reconstruct them.
Note: This PR really should have tests.  It doesn't though because upgrading the tests to 0.6.0 is something I'm intending to do separately later and not something I want to deal with right now.

Update codec & decoder for 0.6.0 receive functions

---

packages/codec/docs/README.md
packages/codec/lib/ast/import/index.ts
packages/codec/lib/format/types.ts
packages/decoder/lib/decoders.ts

This PR adds (partial) support for Solidity 0.6.0's globally-declared structs and enums.  For the most part this is pretty simple -- some of this support was actually already there.  The import functions needed to be written (simple enough), and `decoder`'s function to locate user defined types needed to check the nodes directly under the root node as well as those inside a contract.  (The debugger's function to locate these didn't need modification, as it already crawls the whole AST.)
So why is the support partial?  Well, a limitation of our artifact-based system is that we can only get sources that contain at least one contract.  So, if you have a file that only declares data types and no contracts, it's going to get missed, and we're not going to find that data type.  I've updated the …

Add (partial) support for globally-declared structs & enums

---

packages/contract/lib/handlers.js
packages/core/lib/logging/Console.sol
packages/core/lib/testing/testsource.js
packages/migrate/migration.js
packages/resolver/fs.js
packages/truffle/cli.webpack.config.js

I hope I didn't miss any re-namings here, but basically this makes it so that usage requires `Truffle.log` rather than `TruffleLogger.log`.

Rename TruffleLogger to Console

---

packages/core/test/lib/commands/test.js

I created new test file `truffle/packages/core/test/lib/commands/test.js `and  added two tests. One is pretty simple. I just create three different files in two subdirectories and check if output from `determineTestFilesToRun` function from `@truffle/core/lib/commands/test/helpers.js `is showing three files more. 
Second test might be an overkill. It allows to create more customized tree structure according to provided object. Counts number of new files and then call `determineTestFilesToRun` function to check if all new test files were included in test set. I may remove it if you think it is too much.

Recursive test. Fix #2644

---

packages/truffle-db/src/artifacts/json/schema.ts

Since TypeScript fails to recognize Object.entries() pair type

Add some minimal typing to fix processSchema()

---

packages/truffle-db/src/artifacts/schema.ts
packages/truffle-db/src/artifacts/test/index.ts
packages/truffle-db/src/loaders/artifacts/index.ts
packages/truffle-db/src/loaders/artifacts/test/index.ts
packages/truffle-db/src/loaders/queries/contracts.ts
packages/truffle-db/src/schema.graphql
packages/truffle-db/src/workspace/pouch.ts
packages/truffle-db/src/workspace/schema.ts

Currently, the Contract object defines a `constructor` that was the same as ContractInstance's `creation.constructor`, which specified linked binary. Since ContractInstances have a network, this linked binary is available in that context (we can determine link values given a network), and so that's fine.
But, in the context of #2720, which tries to add contracts during compilation, when networks are not available, this proves impossible. We can't get link values, so we can't save linked bytecodes. This PR posits that Contract should just have unlinked bytecode fields (`createBytecode` and `callBytecode`) instead of a Constructor data object.
Changes:
- Remove all notion of contracts having a constructor
- Add createBytecode and callBytecode fields to contract (as regular,
unlinked …

Replace Truffle DB's Contract.constructor with bytecode fields

---

packages/events/defaultSubscribers/compile.js

#2722 
Adjust subscriber output to correctly display warning output.
Previously it looks like the raw warning output from the Solidity compiler was getting passed to the subscriber. Currently only the formatted message is and so the handler function was not adjusted to accept this.

Bug fix: Edit compile subscriber output

---

packages/core/lib/testing/testrunner.js

This PR fixes #2710... sort of.  The underlying bug that got exposed remains, of course, but this fixes the immediate cause of the problem and gets things back to how they were before.
So, what went wrong here is that I accidentally broke the test runner's use of snapshots, forcing it to rely on the buggy redeploy-based fallback.  How did I break it?  Well, uh, the test runner's `rpc` method, that performs RPC calls... I left out the `return` statement.  Oops.  With the `return` added in, snapshotting works just fine and the problem goes away.
Once this is released, I'll open an issue for the underlying redeploy bug that got exposed.  I have no idea what to do about that one.

Add missing return statement to fix snapshot bug

---

packages/debugger/lib/data/sagas/index.js
packages/debugger/lib/data/selectors/index.js
packages/debugger/lib/solidity/selectors/index.js
packages/solidity-utils/index.js
packages/solidity-utils/package.json

This PR does a few things.
First of all, it rewrites the `getHumanReadableSourceMap` function in `solidity-utils` to be a bit more readable, while also expanding it to cover the new modifier depth field included in the source maps as of 0.6.0.
Secondly, it updates the `solidity.current.instructions` selector to include this information as well.
Thirdly, it now puts the modifier depth in the variable ID for modifier variables.  I only did this for modifiers proper, not for base constructors.  Note that you *don't* want to do this for variables not from a modifier, as the base function may have *multiple* modifier depths (the parameters will have modifier depth 0 but the other local variables may be higher).
While I was at it, I removed the overcomplicated logic in …

Use modifier depth to solve double-modifier problem

---

packages/codec/package.json
yarn.lock

This PR pins the version of typedoc used to fix a problem in the codec documentation that was introduced due to a change in typedoc.  (I didn't bother testing every typedoc version to see just where it was introduced, but the problem exists in 0.15.5 and does not exist in 0.15.0.)
I also pinned the version of `@gnd/typedoc` for good measure (why are we using both of these, actually?), although obviously that's not actually necessary.

Pin typedoc version

---

packages/truffle-db/bin/server.js
packages/truffle-db/package.json
packages/truffle-db/src/db.ts
packages/truffle-db/src/workspace/index.ts
packages/truffle-db/src/workspace/pouch/index.ts
packages/truffle-db/src/workspace/pouch/sqlite.ts
packages/truffle-db/src/workspace/test/persistence.spec.ts
yarn.lock

Add another backend storage adapter for Truffle DB, to use pouchdb-adapter-node-websql to write to local sqlite3 databases.

Add sqlite adapter for Truffle DB

---

packages/codec/lib/core.ts
packages/debugger/test/data/ids.js
packages/debugger/test/data/more-decoding.js
packages/decoder/test/wire/contracts/MessageTest.sol
packages/decoder/test/wire/contracts/WireTest.sol
packages/decoder/test/wire/migrations/2_deploy_contracts.js
packages/decoder/test/wire/test/receive-test.js
packages/decoder/test/wire/test/wire-test.js

This PR mostly just adds tests for stuff in previous PRs that I added without tests because the tests were still on Solidity 0.5.x.
However, in adding these tests, I found that decoding of non-function-call transactions (ones that would hit the fallback function, e.g.) didn't actually work right, so I also put in a quick fix there.

Add tests of Solidity 0.6.0 debugging/decoding features... and fix a bug

---

packages/artifactor/package.json
packages/contract/package.json
packages/contract/test/deploy.js
packages/contract/test/errors.js
packages/core/package.json
packages/debugger/package.json
packages/deployer/package.json
packages/deployer/test/errors.js
packages/environment/package.json
packages/hdwallet-provider/package.json
packages/interface-adapter/package.json
packages/provider/package.json
packages/truffle/package.json
yarn.lock

* @truffle/artifactor: 2.8.0 →  2.9.1
* @truffle/contract: 2.8.0 →  2.9.1
* @truffle/core: 2.8.0 →  2.9.1
* @truffle/debugger: 2.8.0 →  2.9.1
* @truffle/deployer: 2.8.0 →  2.9.1
* @truffle/environment: 2.8.0 →  2.9.1
* @truffle/hdwallet-provider: 2.8.0 →  2.9.1
* @truffle/interface-adapter: 2.8.0 →  2.9.1
* @truffle/provider: 2.8.0 →  2.9.1
* truffle: 2.8.0 →  2.9.1

Upgrade dependency: ganache-core@2.9.1

---

packages/contract/lib/utils/index.js
packages/core/lib/logging/Console.sol

This adds the ability to prefix your log events with a short string (one that fits within 32 bytes, because technically it is getting parsed as `bytes32`). For example:
```
Console.log("This is myBool", myBool);
Console.log("This is myInt", myInt);
Console.log("This is myUint", myUint);
Console.log("This is myString", myString);
Console.log("This is myBytes32", myBytes32);
Console.log("This is myAddress", myAddress);
```
This will provide the following output:
```
This is myBool true
This is myInt -4321
This is myUint 1234
This is myString myString
This is myBytes32 0x6d79427974657333320000000000000000000000000000000000000000000000
This is myAddress 0x8990214b1304955D07bBEA94D9B0C2728097c3EB
```
Thanks to @nsward for his suggestion here: …

Add named events to logger

---

packages/artifactor/package.json
packages/compile-solidity/compilerSupplier/index.js
packages/contract-schema/package.json
packages/contract/package.json
packages/contract/test/deploy.js
packages/contract/test/errors.js
packages/core/package.json
packages/debugger/package.json
packages/deployer/package.json
packages/deployer/test/errors.js
packages/environment/package.json
packages/hdwallet-provider/package.json
packages/interface-adapter/package.json
packages/provider/package.json
packages/truffle/package.json
packages/truffle/scripts/postinstall.js
scripts/ci.sh
yarn.lock

This PR brings truffle's defaults up to ~latest Ethereum mainnet~ Istanbul (Muir Glaicier is latest).
Truffle will now spin up `ganache-core` using the `istanbul` hardfork by default.
Truffle will also postinstall & invoke `solc@0.5.16` which targets `istanbul` by default.
Also upgrades a `truffle@contract-schema`'s `solc` devDep to 0.5.16.

Dependency Upgrade: ganache-core@2.9.2

---

packages/debugger/test/data/global.js

Now that we're on ganache-core 2.9.1, where the timestamp bug is fixed, we can finally turn on the globally-available variables tests and not have them fail due to timestamp problems!  Hooray!

Internal improvement: Unskip globally-available variables tests

---

packages/truffle-db/src/loaders/artifacts/index.ts
packages/truffle-db/src/loaders/artifacts/test/index.ts
packages/truffle-db/src/loaders/queries/index.ts
packages/truffle-db/src/loaders/queries/nameRecords.ts
packages/truffle-db/src/loaders/queries/projects.ts
packages/truffle-db/src/schema.graphql
packages/truffle-db/src/workspace/definitions.ts
packages/truffle-db/src/workspace/index.ts
packages/truffle-db/src/workspace/pouch/databases.ts
packages/truffle-db/src/workspace/pouch/types.ts
packages/truffle-db/src/workspace/schema.ts
packages/truffle-db/src/workspace/test/projects.graphql.ts
packages/truffle-db/src/workspace/test/projects.spec.ts
packages/truffle-db/types/stub.d.ts

- Expand workspace databases with support for mutable collections
- Define projectNames mutable collection
- Add queries to resolve current name
- Add mutation to assign current names
- Ensure loader assigns names based on previously current names
Thanks to @fainashalts for much of this work :)

Track collection of current names per project in Truffle DB

---

packages/debugger/test/data/global.js

One of the globally-available variables tests I wrote is timing out.  So, I'm upping its timeout somewhat.

Up timeout on globals test in simple creation

---

packages/core/package.json

It looks like when I put the new decoder in `truffle test`, I forgot to ever actually add it as a dependency of `core`, yikes!  This PR does that.

Add missing decoder dependency in core

---

packages/codec/package.json
packages/debugger/package.json
yarn.lock

This PR downgrades semver from v7 to v6, because v7 isn't compatible with webpack (this is a [known issue](https://github.com/npm/node-semver/issues/306), apparently).  This should fix #2732.
(I also upgraded one case of 6.1.1 to 6.3.0, because why not.)

Downgrade semver to v6 to fix #2732

---

packages/contract-schema/package.json

One script definition in the `contract-schema` package was preventing `lerna bootstrap` from completing successfully on Windows.

Make `lerna bootstrap` work on Windows.

---

packages/contract/package.json

One script definition in the `contract` package was preventing `lerna bootstrap` from completing successfully on Windows.

Internal improvement: Make `lerna bootstrap` work on Windows (@truffle/contract)

---

packages/contract-schema/README.md
packages/contract-schema/spec/contract-object.spec.json

Prettifies the schema for readability & documents the `networkType` default: `ethereum`.
Also updates & re-orgs README to match current spec.

Internal improvement: ContractObject Schema 

---

packages/contract/package.json
packages/interface-adapter/package.json
yarn.lock

* @truffle/contract: 5.2.0-beta.1 →  ^6.0.0-beta.0
* @truffle/interface-adapter: 5.2.0-beta.1 →  ^6.0.0-beta.0
Also loosens pin to caret since `@taquito/taquito` is still in active development (bug fixes, features, enhancements, etc).

Dependency Update: @taquito/taquito@^6.0.0-beta.0

---

.travis.yml

Since Truffle defaults to compiling contracts and caching, postinstalling, obtaining `solc` v0.5.16 for users, we should have Travis CI do the same.

Internal improvement: Update travis build to obtain solc 0.5.16

---

packages/core/lib/console.js
packages/core/lib/test.js
packages/migrate/migration.js
packages/require/require.js

- Make users bring their own version of taquito into
truffle contexts (migrations, tests, the repl, etc).
- Remove InterfaceAdapter from migrations context

Internal improvement: Remove taquito (tezos) from global truffle contexts

---

packages/contract-schema/README.md
packages/contract-schema/index.js
packages/contract-schema/spec/contract-object.spec.json

Adds `michelson` to ContractObject schema.
Updates README for Tezos contracts.

Feature: add michelson to ContractObject Schema

---

packages/artifactor/package.json
packages/contract/package.json
packages/core/package.json
packages/debugger/package.json
packages/deployer/package.json
packages/environment/package.json
packages/hdwallet-provider/package.json
packages/interface-adapter/package.json
packages/provider/package.json
packages/truffle/package.json
yarn.lock

* @truffle/artifactor: 2.9.2 →  2.10.1
* @truffle/contract: 2.9.2 →  2.10.1
* @truffle/core: 2.9.2 →  2.10.1
* @truffle/debugger: 2.9.2 →  2.10.1
* @truffle/deployer: 2.9.2 →  2.10.1
* @truffle/environment: 2.9.2 →  2.10.1
* @truffle/hdwallet-provider: 2.9.2 →  2.10.1
* @truffle/interface-adapter: 2.9.2 →  2.10.1
* @truffle/provider: 2.9.2 →  2.10.1
* truffle: 2.9.2 →  2.10.1

Upgrade dependency: ganache-core@2.10.1

---

packages/contract/package.json
packages/deployer/package.json
yarn.lock

This is in response to https://medium.com/the-ethereum-name-service/ens-registry-migration-bug-fix-new-features-64379193a5a
Bump versions of @ensdomains/ens to ^0.4.0, @ensdomains/resolver to ^0.2.0, and ethereum-ens to ^0.8.0

Dependency update: Bump ens-related packages

---

packages/core/lib/test.js

Addresses #2481.
Before: Calling `console.warn()` during Truffle tests would print out the Truffle config and obscure whatever message was meant to be printed.
After: `console.warn()` works as expected.
====
repro steps:
Simple Truffle test that demonstrates the bug and the fix:
```javascript
console.warn('Test console.warn()');
describe('noop', function() { it('noop', () => {}); });
```
Run with e.g. `truffle test test/basic.js`

Fix console.warn in truffle test

---

packages/config/src/configDefaults.ts

Previously `config.logger` was set to a dummy method.
```
logger: { log: () => {} }
```
As this was the case, whenever `config.events.updateSubscriberOptions` was executed, this method would clobber whatever logger was instantiated for the subscribers. I believe the proper behavior here is to set this property to default to `console`.

Bug fix: Use console as default logger

---

packages/artifactor/package.json
packages/contract/package.json
packages/core/package.json
packages/debugger/package.json
packages/deployer/package.json
packages/environment/package.json
packages/hdwallet-provider/package.json
packages/interface-adapter/package.json
packages/provider/package.json
packages/truffle/package.json
yarn.lock

* @truffle/artifactor: 2.10.1 →  2.10.2
* @truffle/contract: 2.10.1 →  2.10.2
* @truffle/core: 2.10.1 →  2.10.2
* @truffle/debugger: 2.10.1 →  2.10.2
* @truffle/deployer: 2.10.1 →  2.10.2
* @truffle/environment: 2.10.1 →  2.10.2
* @truffle/hdwallet-provider: 2.10.1 →  2.10.2
* @truffle/interface-adapter: 2.10.1 →  2.10.2
* @truffle/provider: 2.10.1 →  2.10.2
* truffle: 2.10.1 →  2.10.2

Upgrade dependency: ganache-core@2.10.2

---

packages/core/lib/commands/config.js

I done found a typo in `config.js` :)

Bug fix: Correct typo on config command property

---

packages/core/lib/commands/test/index.js

Ganache neither defines `noVMErrorsOnRPCResponse`, nor can Truffle make use of the intended option `vmErrorsOnRPCResponse: false`, since that behavior would be a breaking change (identified thanks to #2733)

Remove nonexistent setting that wouldn't work

---

packages/core/lib/testing/soliditytest.js
packages/core/lib/testing/testrunner.js

The Solidity assertion libraries have been broken as of Truffle 5.1.5 due to them not being compiled before initializing the decoder during testing. This PR flips the order of two lines of code that causes these libraries to be compiled before decoder initialization.
After fixing this, the test summary displayed a list of events emitted during the tests which included all of the `TestEvent`s (which is the mechanism by which the assertion libraries operate). Since this is not really information relevant to the user (in that the user does not need to know about these `TestEvent`s events being emitted during testing) they are now filtered out to avoid extra noise and confusion. The failures still display in the test summary as shown below.
This is the result of running the test suite from a …

Bug fix: Fix assertion library

---

CONTRIBUTING.md

Fix unable to add the package to @truffle/core in contributing guide
Ref: https://github.com/lerna/lerna/issues/1683

Fix unable to add the package to @truffle/core in contributing guide

---

packages/compile-solidity/compilerSupplier/loadingStrategies/VersionRange.js

Just add gzip and set timeout when downloading solc. It makes sence for low speed network or some network traffic trouble.

Add gzip and timeout support when downloading solc

---

packages/core/lib/networks.js

- Add tezos network chainId mapping object
to pair currently supported network names
to their chainIds
- Change 'networks' from const to let to allow
mutating & networkId -> chainId translation
- Convert for loop to for..of
- Only translate 'networks' object if
network type is 'tezos', the configured network
name is part of the tezos network mapping, and
the network chainId matches the mapping value.
- Filter out chainId as a valid networkName
- Set networkId to be chainId
- Set networkName appropriately
- Add new networkName to networkNames

Add preliminary Tezos support for 'truffle networks' cmd

---

packages/decoder/package.json

The typings were not generated properly for the `@truffle/decoder` package.
According to these Typescript [docs](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html), typings should be generated with a `--declaration` flag which should yield a `*.d.ts` file. The example `package.json` is:
```json
{
"name": "awesome",
"author": "Vandelay Industries",
"version": "1.0.0",
"main": "./lib/main.js",
"types": "./lib/main.d.ts"
}
```
But the current decoder has a `package.json` with the `types` property that just [points](https://github.com/trufflesuite/truffle/blob/develop/packages/decoder/package.json#L6) to its Typescript source (note the `*.ts` extension rather than `*.d.ts`):
```json
{
"name": "@truffle/decoder",
"version": "4.0.9",
"description": "A decoder and …
```

Decoder typings fix

---

packages/contract/lib/handlers.js
packages/contract/lib/override.js
packages/contract/test/deploy.js
packages/contract/test/util.js

- Include default Web3 error message as part of
contract deployment error handling
- Ignore default Web3 error message only when setting
a custom default block timeout greater than Web3's default (50)
- Ensure promievent receipt is fired when override logic
successfully returns a tx receipt
- Add test util method & test case for simulating tx propagation
delays when deploying contracts via live network gateways
(Infura, Cloudflare, etc)
Using the [reproduction steps](https://github.com/trufflesuite/truffle/issues/2257#issuecomment-558919818) outlined in #2257 against this branch locally, it appears I have been able to overcome the gateway tx delays [discussed](https://github.com/trufflesuite/truffle/issues/1575#issuecomment-579560921) in #1575.
This is a short-term solution that neither …

Enhancement: Extend timeout override polling logic

---

packages/debugger/lib/session/reducers.js
packages/debugger/lib/session/selectors/index.js

I noticed that the `projectInfoComputed` state and selector were still hanging around, from when we had the idea of the debugger separately signalling to the CLI when it was done computing the project info.  Now that we're not doing that, this doesn't actually do anything; there's no action hooked up for the reducer to respond to, so the reducer doesn't do anything and the selector is useless.  So, deleting all this code!

Remove unused projectInfoComputed state & selector

---

packages/truffle-config/index.js
yarn.lock

- Swaps out the deprecated and nonfunctional old
Infura API Provider URL for the new v3 functional URL
- Yarn.lock updated

Fix: Update Infura Provider URL

---

.travis.yml
packages/codec/lib/abi-data/allocate/index.ts

My previous PR, #2851, seems to be causing the Colony tests to fail.  The reason for this seems to be some debugging output I left in that foolishly includes some dereferencing (which, obviously, can fail).  So, I'm just deleting that debugging output.

Fix: Remove problematic debugging output

---

packages/codec/lib/abi-data/allocate/index.ts
packages/codec/lib/abi-data/utils.ts

This PR is intended to address #2723.  So, a little explanation here -- on investigation, it turned out that the actual problem was a *Solidity* error; the Solidity compiler was emitting ill-formed ABIs.  We can't really fix that -- and @Amxx will have to get that fixed, for obvious reasons! -- but I can at least add this workaround that should at least get his tests working again.  (And, to be clear, it *does* get the test in the reproduction example working.)
Note this is a real quick workaround that just checks for obvious ways in which an ABI may be ill-formed.  It does not actually do a full well-formedness check.  Because this is mostly a case we shouldn't have to deal with...

Add workaround to avoid allocating obviously ill-formed ABI items

---

packages/codec/lib/abi-data/allocate/index.ts

This PR is a (partial?) fix for the reopened #2723.  Basically, when going through the base contracts of a given contract to find where a given function is defined, I have code that says, give up if you fail to locate one of the base contracts.  However, I didn't have code that said, give up if due to ID collisions the "base contract" you locate is not a contract at all.  This caused an error when attempting to test @Amxx's project.
I'm actually still getting errors when I try to test his project, but they're unrelated errors and it's not clear they're our fault, so I'm putting up this PR as it is to just fix this one issue.
One thing worth noting: In the particular case at hand, the base contract we're trying to look up is actually the contract itself!  Wondering if perhaps I should put …

Bug fix: Fail inheritance search on bad base node type

---

packages/codec/lib/format/utils/inspect.ts

This PR makes it so that `nativize` converts out-of-range booleans to `true` rather than `undefined`.  This is in order to work better in watch expressions, since when used as mapping keys, out-of-range booleans are treated as `true`.

Nativize boolean-out-of-range errors to true (instead of undefined)

---

packages/core/lib/debug/cli.js
packages/debugger/lib/data/selectors/index.js
packages/debugger/lib/solidity/selectors/index.js

This PR does two things:
Firstly: It fixes #2879.  Um, so, I messed up the check of whether the debugger needs to recompile, and as a result instead of recompiling when it needed to, it was crashing.  Oops!  Fixed now.
(Very odd, since I could've sworn I'd seen it recompiling in some cases...?  A little unclear what's going on there, may be worth looking at...)
Secondly: It prevents various other debugger crashes that I accidentlly introduced in 5.1.16 when source code can't be found for the transaction being debugged.

Prevent some debugger crashes

---

packages/debugger/lib/session/index.js

Just another quick debugger crash fix...

Bug fix: Keep debugger from crashing when can't locate contract node

---

packages/codec/lib/compiler/types.ts
packages/codec/lib/compiler/utils.ts
packages/codec/lib/special/decode/index.ts

One more quick PR to fix a debugger problem that can occur if it can't find the source code.  And then this should be it for now.
I made the choice to treat having no compiler like pre-0.5.0 Solidity for the purposes of decoding globally-available variables.  Notionally we could just exclude these entirely, I guess?  But whatever, this was easiest.

Account for possibility of no known compiler in special decoding

---

packages/decoder/package.json

@gnidan pointed out that this dependency was missing; added it.

Add missing compile-solidity dependency to decoder

---

packages/decoder/package.json

The decoder has been using chai in its tests, but this didn't appear in the package.json.  Now I've added it as a devDependency.

Add missing chai dev dependency in decoder

---

packages/core/lib/debug/printer.js
packages/debug-utils/index.js

**Note: breaks debug-utils**
I noticed that the debugger CLI doesn't really handle tabs in source files very well.  (Likely it might've back before colorization, but I never thought to check that interaction until now.)  I fixed it up so it does.  Long story short, I determined the only way to do this really is, when colorizing source files, detab them first.  (But *don't* detab the uncolorized source!)
I also generally improved our existing detabbing so it actually emulates tab stops instead of just replacing them with a fixed number of spaces.
I also set the default tab width to 8, as that's the most common, but of course that's easy enough to change.  Although it should probably be abstracted a little differently?  Ah well.
I guess this is a breaking change to debug-utils, since some …

Fix tab handling in debugger CLI display

---

packages/codec/docs/typedoc.json
packages/codec/lib/core.ts
packages/codec/lib/index.ts
packages/decoder/lib/decoders.ts
packages/decoder/lib/index.ts
packages/decoder/lib/types.ts
packages/decoder/test/current/contracts/DowngradeTest.sol
packages/decoder/test/current/contracts/WireTest.sol
packages/decoder/test/current/test/downgrade-test.js
packages/decoder/test/current/test/wire-test.js

This PR adds an interface for decoding return values in `decoder`, which previously only existed as low-level functionality in `codec`.
Decoding these can be done with either the `ContractDecoder` or the `ContractInstanceDecoder` -- you need to have one of the for the contract that the return value was received from.  As usual, using the `ContractInstanceDecoder` allows for somewhat more robustness.
To use this, you pass the ABI of the function call you're decoding, the raw data you're decoding, and, optionally, the block the call occurred in and its return status.  (The latter two are grouped into an `options` argument.)
You can't use this to decode return values of constructor calls, even though that functionality exists in `codec`.
Note that normally allocation relies on a contract …

Add interface for decoding return values in decoder

---

packages/debugger/lib/store/common.js

So, I finally profiled the debugger, and it turns out a fair amount of time is spent in this Redux logging middleware that we've never really made much use of.  So, deleting it for speed!

Remove logger middleware from debugger

---

packages/debugger/lib/controller/sagas/index.js

It seems that when I added multi-compilation to support to the debugger, the way I integrated it into `stepOver` was wrong -- I treated any change of file as a reason to stop stepping.  Now I've put that check where it belongs, alongside the line check; a change of file is only a reason to stop stepping if you're at, not beyond, the starting depth.

Fix stepOver to work properly with changes of file

---

packages/core/lib/commands/test/index.js
packages/core/lib/test.js

- Add --bail flag to the command object and help object
- Propagate this bail flag into mochaConfig
I'm not sure what the project's test workflow is, so let me know what kind of tests you need with it. Currently just tested it manually in one of my repos.
Fixes #2848

Add --bail option for truffle test (solves #2848)

---

packages/codec/docs/README.md
packages/codec/lib/abi-data/allocate/index.ts

This PR is intended to address #2876.  Allocation was failing at the event allocation grouping step on certain projects.  Now that I've reproduced the problem, I can finally see why this happens: Multiple contracts with the same name.
Basically this problem if you have contracts A, B, and B', where A inherits from B, B and B' have the same name, and B' rather than B is the one that ended up getting the artifact.  In this case, you can end up in the situation where the allocator can find the node for B, but then can't find the corresponding contract info object (since there's no artifact for it).  Thus the error, since I assumed having one necessarily means having the other.
Unfortunately, as the comment said, I don't really see any good way to truly fix this; instead I just bail out of …

Bug fix: Bail out of event allocation grouping if can't find base contract's info

---

packages/codec/lib/format/values.ts
packages/debugger/lib/helpers/index.js
packages/debugger/lib/solidity/selectors/index.js
packages/debugger/package.json
packages/debugger/test/ast.js
packages/decoder/lib/decoders.ts
packages/decoder/lib/index.ts
packages/decoder/package.json
packages/decoder/test/current/contracts/DecodingSample.sol
packages/decoder/test/current/contracts/DowngradeTest.sol
packages/decoder/test/current/test/decoding-test.js
packages/decoder/test/current/test/downgrade-test.js
packages/solidity-utils/index.js
packages/solidity-utils/package.json

This PR adds support for full decoding of internal function pointers to `@truffle/decoder`.
In order to allow this, a lot of code that used to live in the debugger has been moved to the `solidity-utils` package so that the decoder can import it.  Note that the `solidity-utils` package is uncompiled JS, so I had to eliminate two uses of object spreads.  Also, warning, `decoder` uses it as an untyped import!  But it's all localized to one little block where the internal functions table is set up.
(I did not change the fundamental architecture of internal function pointer decoding -- i.e., `codec` still just relies on a table that's passed in to decode these; it doesn't do the work of decoding them itself.)
There was also one really awkward thing wtih `IntervalTree`.  For reasons unknown to …

Enhancement: Allow @truffle/decoder to fully decode internal function pointers

---

packages/codec/lib/ast/import/index.ts
packages/codec/lib/basic/decode/index.ts
packages/codec/lib/contexts/import/index.ts
packages/codec/lib/contexts/types.ts
packages/codec/lib/evm/import/index.ts
packages/codec/lib/evm/index.ts
packages/debugger/lib/data/selectors/index.js
packages/decoder/lib/decoders.ts
packages/decoder/lib/utils.ts

Big oops here: When moving everything over to the new style of type ID, I fixed two of the import functions, but I forgot one: `contextToType`.
This leaves us with a problem: Where should `makeTypeId` live?  It used to live in `ast/import`, because it was needed there but not in `abi-data/import`.  But now it's needed in `context/import` as well.  I opted to put it in `context/import` and have `ast/import` import it.
Except, there's one more place type objects were being made with old-style IDs... in `basic/decode`!  See, `decodeInternalFunction` was constructing some type objects manually.  We don't want that -- all such construction (and especially, any making of type IDs) should occur in an import function.
So, I added `evm/import` and a function for converting internal function table …

Fix type IDs on contract types from contexts & internal fns

---

packages/compile-solidity/run.js

This PR fixes #2902 by passing the `debug` option through to solc.  I didn't add any tests because I don't know this package well enough, sorry!  But I tested it manually and it works.
By the way, I was looking through the solc documentation for compiler options, and I noticed there's two other options we don't currently pass through: `metadata` and `libraries`.  Does anyone know if there's a reason for this?  It would be easy enough to add them in.  (Would allowing the user to set the metadata format cause any problems?  I have to imagine letting them manually specify libraries probably wouldn't, right?)

Whitelist missing solc options

---

packages/core/lib/networks.js

closes #2906
- truffle networks [--clean] used to fail with non-JSON files
in the directory. These non-JSON files are now ignored.

truffle networks only reads JSON files

---

packages/hdwallet-provider/src/index.ts

I was trying to use a websockets url in the hdwalletprovider.
```
networks: {
launchpad: {
provider: () => new HDWalletProvider(bpaasconfig.mnemonic, 'wss://xxx.settlemint.com/xxx/besu/ws'),
gasPrice: '0',
network_id: '*',
websockets: true,
production: false,
gas: "0x1dcd6400"
},
},
```
I figured this was possible reading the code here
https://github.com/trufflesuite/truffle/blob/develop/packages/hdwallet-provider/src/index.ts#L166-L179
Some issues I detected:
- `providerProtocol` is actually `wss:` so the case never triggers
-  `case "wss":` does not have a `break;` so is always overridden
Quick workaround is passing in my own web3 provider, but this code exists so i made it work

[hdwallet-provider] fix detection of websockets urls

---

packages/decoder/lib/index.ts
packages/decoder/package.json

This PR is intended to address #2841.  Turns out just importing `fs-extra` causes serious problems on web.  But also, I don't need it.  So, removing it.  Hopefully that'll fix the problem.  If not, we'll have to try hackier things...

Bug fix: Remove the use of fs-extra from @truffle/decoder

---

packages/compile-solidity/package.json
packages/core/package.json
packages/events/package.json
packages/reporters/package.json
yarn.lock

Fixes #2923.  It also fixes the missing `ora` dependency in `core`.  It also upgrades it to 4.0.3.  It also removes the redundant `glob` devDependency in `core` while I was at it.

Add missing ora dependency

---

packages/decoder/lib/decoders.ts
packages/decoder/lib/errors.ts
packages/decoder/lib/index.ts
packages/decoder/test/current/test/decoding-test.js

This PR adds a `forAddress` method to the wire decoder, which allows one to spawn an instance decoder based *only* on the address.  It also takes an optional block parameter, in case the contract has since self-destructed or something.
I didn't add a corresponding convenience function that doesn't require spawning a wire decoder first, as the interface would be kind of awkward.
In order to do this, the constructor for `ContractDecoder` has been changed; now, instead of an artifact, it takes a `Contract` and a `Compilation` (and also optionally an artifact).  The code for locating these based on the artifact is now located outside the constructor, in the wire decoder's `forArtifact` function, rather than within it.  Meanwhile, `forAddress` uses different logic for locating these.
I also …

Ehancement: Add forAddress method to wire decoder

---

packages/codec/lib/abi-data/allocate/index.ts
packages/codec/lib/abi-data/utils.ts

Prior to Solidity 0.5.6, the Solidity compiler would put a lot of stuff in library ABIs that it doesn't anymore.  Like... functions that took or returned storage pointers!  Those can't actually validly go in the ABI, and yet it would output an ABI entry for them anyway.
While I want to handle the mess that is library functions someday (there are so many problems with these...), that day is not today.  So, for now, I want to explicitly exclude such invalid ABIs.  There was no check for these before, but now I've added one...

Don't attempt to allocate ABI entries with storage pointers

---

packages/debugger/lib/evm/selectors/index.js
packages/debugger/test/data/global.js

This PR is kind of a minor fix for the debugger.  One of the debugger's problems is that on a failed contract creation (excepting the initial call -- if it's the initial call it works fine, at least with Ganache, but this may be client-dependent), the debugger can't determine the address and so can't set global variables appropriately, instead reporting zero for the address.
There's a good reason it can't determine the address; to do so it would need the nonce, and to get the nonce we'd need reconstruct mode (#2894), which isn't likely to happen anytime soon.  But, that only applies to CREATE!  For a CREATE2, there's no reason it can't *manually* determine the address!  So, now it does that, instead of reporting zero.
I also added a test of this.
Also, uh, I kind of crammed a fix for our …

Manually determine addresses of failed CREATE2s (also: a jump fix)

---

packages/codec/lib/format/types.ts
packages/codec/lib/format/utils/inspect.ts
packages/codec/lib/format/values.ts

This PR expands `TypeType` in `codec` so that it covers enums as well as contracts.  An enum type's value is an array of its different options.  It also updates the inspect utilities to inspect/nativize these properly.
This doesn't really have any effect at the moment; it's just some preparation for some future debugger improvements.
Note that merging this would require updating the `cheerios` branch appropriately (PR #2901).

Internal improvement: Expand TypeType to cover enums as well

---

packages/reporters/reporters/migrations-V5/messages.js

closes #2799
- Add `decAndHex(num)` utlity function that displays a number as decimal with hex in parenthesis
- Use this utility in all migration messages that print gas
I wasn't sure what the versioning process is, so I left the versions as is. But since the dependencies are `core` depends on `migrate` depends on `reporters`, both `reporters` and `migrate` need a version bump to be included in core.

Display all migration gas numbers in dec and hex formats

---

packages/decoder/lib/decoders.ts

This PR fixes two crashes in the decoder.
The first is the following: Suppose that state allocation fails for a given contract (which has an AST), and it's the only contract in its compilation.  When we attempt to create a contract decoder for that contract, we get a crash.  Why?  Well, since state allocation didn't succeed for any contracts in that compilation, the container for the compilation doesn't exist, and we get an error when we try to fetch the allocation for the specific contract from it.  Oops!  Now we check if it exists.
The second is that making the internal functions table really needs to be wrapped in a try/catch because there's a number of reasons it could fail!  So now it is.  We just swallow errors here; there's not really any way to recover from them except to just …

Fix two decoder crashes

---

packages/compile-smartpy/index.js
packages/compile-smartpy/package.json
packages/compile-smartpy/test/test_compiler.js

- Instead of allowing SmartPy-Basic to create the build directory,
have truffle/node make it:
- Adds `mkdirp` as `@truffle/compile-smartpy` dependency
- Slightly adjust `@truffle/compile-smartpy` tests

Fix: Workaround Docker SmartPy permissions issue

---

packages/decoder/lib/index.ts
packages/decoder/test/current/test/decoding-test.js

This PR adds the missing `forAddress` convenience function.  It doesn't have a `block` parameter.  I also change the test of `forAddress` to use this.
I didn't go adding `block` parameters to anything else like I was thinking about because the interface would be kind of awkward conceptually and the cases where it would be relevant are rare at best.  If you really want a `block` parameter, well, there's `forAddress`!

Enhancement: Add missing forAddress convenience function to decoder

---

packages/core/lib/commands/migrate.js
packages/interface-adapter/lib/adapter/tezos/index.ts
packages/migrate/index.js
packages/migrate/migration.js
packages/migrate/test/index.js

In `@truffle/core`:
- Add `--force` flag to help menu and as valid option.
`--force` flag completely disables and ignores the on-chain migrations
tracking system
In `@truffle/migrate`:
- Add on-chain tracking support for `tezos`-specific `Migrations` contract logic
- Add checks for `--force` to enable expected behavior
- Add test cases for `--force` usage
In `@truffle/interface-adapter`:
- Replace `getCode` stub for `TezosAdapter` with the appropriate
`@taquito` contract provider method

Enhancement: Enable configurable on-chain migration tracking

---

scripts/ci.sh

- Runs basic integration test against `tezos-smartpy-example` box

Add `tezos-smartpy-example` to `TEZOS` CI job

---

packages/compile-smartpy/index.js
packages/compile-smartpy/package.json
packages/compile-smartpy/test/test_compiler.js

- Instead of allowing SmartPy-Basic to create the build directory,
have truffle/node make it:
- Adds `mkdirp` as `@truffle/compile-smartpy` dependency
- Slightly adjust `@truffle/compile-smartpy` tests

Workaround Docker SmartPy permissions issue

---

packages/codec/lib/abi-data/allocate/index.ts

Default fall-through is a pain.  Here, it screwed up allocation for return values when in ABI mode.  Break statements added.  Fixed now.
Thanks to @adrianmcli for catching this.

Fix default fallthrough in abi output allocation

---

packages/codec/lib/format/utils/inspect.ts

This doesn't actually matter yet, but I just noticed that the `nativize` code for TypeValueEnum is wrong.  It should return an object indexed by the option names, but instead it returns an array.  Oops.  Fixed this.  (You know, for the future when it matters. :P )

Fix nativize of TypeValueEnum

---

packages/debugger/lib/evm/selectors/index.js

The `isCreate2` variable is there so that we don't bother computing the CREATE2 address if we're not actually on a CREATE2, but, oops, in reality I never used it.  Not sure how eslint didn't catch this?

Don't compute CREATE2 address if not on a CREATE2

---

packages/codec/docs/README.md
packages/codec/lib/ast/types.ts
packages/codec/lib/storage/allocate/index.ts
packages/debugger/test/data/immutable.js
packages/debugger/test/helpers.js
packages/decoder/lib/index.ts

My previous PR got wrong just how immutable variables would be indicated in Solidity 0.6.6.  This PR fixes that.  It also adds a test of unused immutables, now that they are detectable.
Also, I added a bit to the codec/decoder docs.  Hopefully it's a good summary.

Fix allocation of immutables for Solidity 0.6.6

---

packages/codec/lib/format/types.ts

The `typeString` function didn't cover type `type`.  Not sure this matters anywhere, but figured I should implement it since I noticed it missing.

Bug fix?: Implement typeString for TypeType

---

packages/codec/lib/ast/import/index.ts

Looks like I accidentally broke detection of which structs & enums are global and which are local!  Doesn't really affect anything at the moment but the type objects were wrong and it bugged me.  Anyway, fixed now.

Fix detection of local-vs-global types

---

packages/core/lib/debug/cli.js
packages/debug-utils/index.js

When I made it so that the debugger doesn't have to recompile every time it starts up, I did this by checking each compilation's `unreliableSourceOrder` flag.  The idea being, if that flag wasn't set, then that compilation was usable by the debugger, and no recompilation was needed.
Unfortunately, that turns out not to be the case -- there can be times when a bad compilation nonetheless still has that flag unset.  This can result in AST ID collisions that crash the debugger.
To fix this, I've added a check for AST ID collisions to the debugger CLI startup.  Note that the debugger library makes no such check; this is purely a CLI feature.  (I didn't want the debugger walking the tree yet *again*... although I suppose I could add such a check to the existing initial walk fo the tree?  Not …

Bug fix: Add AST ID collision check on debugger CLI startup

---

packages/core/lib/commands/create/helpers.js
packages/core/lib/commands/create/index.js
packages/core/lib/commands/create/templates/Example.ligo
packages/core/lib/commands/create/templates/Example.mligo
packages/core/lib/commands/create/templates/Example.py
packages/core/lib/commands/create/templates/Example.religo
packages/core/lib/commands/index.js
packages/core/test/lib/create.js

In `@truffle/core`:
- Re-enable `create` command export
- Cleanup old unused `builder` `truffle create` command object
- Add `SmartContractType` as optional CLI argument to pass in. Update
help usage, options, and descriptions.
- Add contract templates for:
- SmartPy
- PascaLigo
- CameLigo
- ReasonLigo
- Refactor `commands/create/index`:
- Check for `smartContractType` passed
- Throw helpful error if no `artifactType` passed
- Throw helpful error if no `artifactName` passed
- Pass `smartContractType` to `Create` object
- Refactor `commmands/create/helpers`:
- Tweak `templates.contract.filename` to append contract file extension later
- Rework `processFile` (use `fs.readFileSync`, rename some variables)
- Slightly refactor `replaceContents`
- Slightly refactor `toUnderscoreFromCamel`
- …

Feature: Add Quick-start templates for supported Tezos contracts

---

packages/core/lib/commands/create/helpers.js
packages/core/test/lib/create.js

- Rename internally used vars correctly
- Swap out prefix logic to prefix new migration scripts according to
current migration directory state
- Update `truffle create migration` test case for new prefix logic

Fix: Prefix creation of migration template scripts correctly

---

packages/core/lib/package.js

Parentheses around the `instanceof` check improves readability with or without `!` shorthand.
Filter now has O(1) lookups. 
Check file ending for `.json`, this is a much faster operation and could fix some weird bugs.
Curry anonymous functions to improve readability and shift bulk of code one tab block to the left.

Update package.js, readability, performance, bug

---

packages/core/lib/debug/interpreter.js
packages/core/lib/debug/printer.js
packages/debug-utils/index.js
packages/debugger/lib/controller/actions/index.js
packages/debugger/lib/controller/sagas/index.js
packages/debugger/lib/data/actions/index.js
packages/debugger/lib/debugger.js
packages/debugger/lib/evm/actions/index.js
packages/debugger/lib/helpers/index.js
packages/debugger/lib/session/actions/index.js
packages/debugger/lib/session/index.js
packages/debugger/lib/session/reducers.js
packages/debugger/lib/session/sagas/index.js
packages/debugger/lib/solidity/actions/index.js
packages/debugger/lib/solidity/sagas/index.js
packages/debugger/lib/solidity/selectors/index.js
packages/debugger/lib/stacktrace/actions/index.js
packages/debugger/lib/stacktrace/reducers.js
packages/debugger/lib/stacktrace/sagas/index.js
packages/debugger/lib/stacktrace/selectors/index.js
packages/debugger/lib/store/common.js
packages/debugger/lib/trace/actions/index.js
packages/debugger/lib/trace/sagas/index.js
packages/debugger/package.json
packages/debugger/test/stacktrace.js
yarn.lock

This PR adds stacktraces to the debugger!  Also some other things.
Stacktraces are done as part of a new submodule, the `stacktrace` submodule.  Did this really need to be a new submodule?  Maybe not.  But I find it easier to think about this way.  And this way it's clear that the stack tracing functions are kind of specialized and should not be confused for keeping track of stack frames for other purposes.
(Keeping track of stack frames the ordinary way is pretty easy -- the difficult thing about stack tracing is *not* always throwing away returned stack frames!)
Btw: This PR also introduces the "light mode" option to the debugger.  This option turns off the data submodule.  It's intended for when I integrate the debugger's stack tracing with `truffle test`, since we won't need the data …

Add stacktraces to debugger library and print them in CLI

---

packages/core/lib/repl.js

No need to run `noop` functions, we can just make our own filter with a reduce to collect the `.done` methods.

Update repl.js improve readability & performance.

---

packages/core/cli.js

The `inputArgument.length` check should be first to short circuit.  This looks like a bug.
Improve readability with `array.includes`.  Looks like there would be no benefit to amortize the creation of a `new Set(...etc)` since this is only called once per run?

Update cli.js, improve help conditional

---

packages/core/lib/networks.js

Reduce the time complexity.  If we ignore the first loop, the second loop was O(n * m), now the entire operation including the first loop is O(n).

Update networks.js, improve performance

---

packages/decoder/lib/index.ts
packages/decoder/test/current/truffle-config.js

Addresses a problem raised by @adrianmcli: Even just trying to *import* `fs` can go badly in some contexts where the file system isn't available, so I've stuck it in a try/catch.
This requires doing it via `require` rather than `import` (making it an an untyped import, oh well), but, yeah.
I thought about creating an additional error for trying to use it when the import failed, but I don't really think that's necessary.  If you're trying to use `fs` on web... like, you should know that's not going to work.

Bug fix: Put fs import in a try/catch to avoid web problems 

---

packages/debugger/lib/solidity/selectors/index.js
packages/debugger/lib/stacktrace/actions/index.js
packages/debugger/lib/stacktrace/reducers.js
packages/debugger/lib/stacktrace/sagas/index.js
packages/debugger/lib/stacktrace/selectors/index.js
packages/debugger/test/stacktrace.js

This PR does a few things.
First, in `solidity`, it makes it so that the phantom-stackframe-guard system isn't invoked for constructors.  This is because constructors don't have a jump in marking, so it's inappropriate there.
(Ideally there'd be some way to turn it off for fallbacks/receives/getters, but, well, at least it shouldn't cause any harm there; yes, it can cause multiple functions to collapse into the same stackframe, but since they'll be different functions, it won't cause any variables to get mixed together.)
Secondly, in `stackframes`, I've removed the `skippedInReports` system -- no more skipping any stackframes.  Yeah, this will cause some extra stackframes to appear in reports that are basically junk, but, well, I figured I really don't want to skip fallbacks and receives …

Bug fix: Fixes to phantom guard system and stacktraces

---

packages/core/lib/testing/testsource.js

`indexOf` is bad for tests of inclusion.  In this case the set of elements was only length 2 but this is still a O(n) operation.  Let's just make it O(1).

Optimize testsource.js

---

packages/core/lib/debug/printer.js

No need to loop through with `filter` then `reduce`.  Since filter can be implemented with a reduce we can eliminate the need to loop through `expr.split(".")`'s output twice.
`Object.keys(obj)` is actually a `O(n)` operation.  Lets do this once and save the output.
We can also eliminate the need to map (`O(n)`) this before passing the result to Math.max which is a `O(n)` operation as well. If we just perform the operation in one `reduce` statement.
Nothing imperative here, just low hanging fruit.

Reduce unnecessary repetition of loops

---

packages/core/lib/commands/init.js

We can just use `ensureDirSync` since it ensures that the directory exists. If the directory structure does not exist, it is created. Like `mkdir -p`.  Docs - https://github.com/jprichardson/node-fs-extra/blob/master/docs/ensureDir.md

Remove unnecessary IO

---

packages/core/lib/commands/console.js

O(1) lookups with `Set` vs `Array.indexOf`.
Aggregate `consoleCommands` in one `reduce` to eliminate the need to loop with `filter` then `forEach`.

Optimize console.js

---

packages/core/lib/commands/develop.js

We can get O(1) lookups for every command.
Combine loops to aggregate `consoleCommands`.
No need to reassign the accumulator and copy the previous values in.  The accumulator starts as a fresh object so maintaining immutability has no benefit and only hinders performance.  If I'm not mistaken this was O(n!) and now its O(n).

Optimize develop.js, reduce unnecessary looping

---

packages/contract/lib/execute.js

Function calls using @truffle/contract (`.call()`) act as if `web3.eth.defaultBlock == 'latest'`, even when it isn't. 
The workaround is to add a parameter at the end of the parameter list for every `call()` which is `web3.eth.defaultBlock`.
This is not intuitive, not consistent with a prior major version, and the change does not appear easy to find in documentation.  It's also not clear that this is the best choice for behavior.
I think the behaviour is due to the [line](https://github.com/trufflesuite/truffle/blob/8b8b1aef0112c1e690479fba5da9a8d9d87e65db/packages/contract/lib/execute.js#L117): `let defaultBlock = "latest";` 
That was added in [this commit](https://github.com/trufflesuite/truffle/commit/c588b7d9dc849c53e1732c32144aa3b3b5131bee) by @cgewecke back on Jun 10, 2018, but I …

On calls, pull defaultBlock from web3

---

packages/debug-utils/index.js
packages/debugger/lib/ast/sagas/index.js
packages/debugger/lib/session/index.js
packages/solidity-utils/index.js

This PR fixes some problems reported by @xlab in #2977.
The first of these is that having nonconsecutive sources can crash the debugger.  I fixed both the part that xlab pointed out, and another point in the code I found that could have trouble on nonconsecutive sources (hopefully these were indeed the only such spots).
The second of these is a bit more mysterious: If the check that xlab pointed out was fixed, the debugger would hang on startup.  On investigation, I determined that there were two particular ASTs that would never finish walking.  I was unable to determine any reason for this.  However, I replaced the uses of `yield call(walk, ...)` in the AST saga with a simple `yield* walk(...)`, and this somehow caused the problem to go away.   (No, we're not somehow losing parallelism …

Fix some errors reported by xlab

---

packages/decoder/lib/decoders.ts
packages/decoder/lib/index.ts

This PR reverts the try/catch added in #2975 since that turned out not to be the problem.
Also I added some additional specificity to the `variables()` documentation regarding what error it throws.

Internal improvement: Revert try/catch thing that was useless

---

packages/core/lib/build.js
packages/core/package.json
packages/core/test/npm.js
packages/workflow-compile/legacy/index.js
packages/workflow-compile/package.json
yarn.lock

So from the name of this branch you would think that this PR is about bumping the version of `mkdirp`. However I noticed that since we use `fs-extra` this library is completely unnecessary. So this gets rid of `mkdirp` as a dependency and instead implements `fse.ensureDirSync` in its place.

Dependency update: Get rid of mkdirp

---

packages/core/lib/repl.js

No need to run noop functions.  We can also safely eliminate the `async` dependency if we just loop through and await each done function in a try/catch, finally we can `process.exit();`.
Attempt 2..
I also thought about
```javascript
self.contexts.reduce((prev, context) => {
return context.done ? prev.then(() => context.done()) : prev;
}, Promise.resolve()).finally(process.exit());
```
But I think the `for..of` is more readable.

Update repl.js improve readability & performance

---

packages/core/lib/commands/test/index.js
packages/debug-utils/index.js

In the recent PR to put stacktraces in test (#3005), I accidentally got the branches of the ternary mixed up regarding what message to display on a selfdestruct.  This PR fixes that.  Oops!

Bug fix: Fix message displayed in stacktrace on selfdestruct

---

packages/truffle/package.json
packages/truffle/webpack.config.js

Add 'mode' property to webpack config ~edit 'devtool' property for faster builds, and change the build script to not allocate extra memory for building as it is no longer needed with the updated 'devtool' setting~ and turn off minification to speed up the build.

Internal improvement: Speed up webpack build

---

packages/debug-utils/package.json
yarn.lock

I recently updated highlightjs-solidity with more Yul highlighting (now that I've learned that inline assembly is now actually Yul).  This PR updates debug-utils appropriately.

Dependency update: Update highlightjs-solidity (for Yul)

---

packages/hdwallet-provider/src/index.ts
packages/hdwallet-provider/typings/web3-provider-engine/index.d.ts

Fixes https://github.com/trufflesuite/truffle/issues/2655
Previously, the node process would just exit silently. This would happen for example if you used an invalid API key (example below).
```js
const provider = new HDWalletProvider(
'abc',
`https://rinkeby.infura.io/v3/FAKE_API_KEY`
);
console.log('sending...');
provider.sendAsync({ jsonrpc: '2.0', id: 1, method: 'net_version', params: [] }, (err, res) => {
// never called
console.log('response', err, res);
});
```
This commit adds a missing callback to throw an error when the 'web3-provider-engine fails' to start the 'eth-block-tracker'.

Throw an error when web3-provider-engine fails to start

---

packages/core/lib/console.js

The console on startup would look for artifacts that contained `.json` in the file name.  I've changed it to look for ones that end in `.json`.  This avoids it from picking up, say, Vim swapfiles.

Bug fix: Fix file extension check in console startup

---

packages/compile-solidity/profiler/getImports.js
packages/compile-solidity/profiler/index.js
packages/core/lib/testing/testresolver.js
packages/core/lib/testing/testsource.js
packages/core/test/npm.js
packages/resolver/lib/resolver.ts
packages/resolver/lib/source.ts
packages/resolver/lib/sources/ethpm-v1.ts
packages/resolver/lib/sources/fs.ts
packages/resolver/lib/sources/globalnpm.ts
packages/resolver/lib/sources/npm.ts

ℹ️ **This is a breaking change to @truffle/resolver**
Besides the high-level change to promisify `resolver.resolve`, this PR also includes:
- Rename ResolverSource method `resolve_dependency_path` to `resolveDependencyPath`
- Rename `file` property to `filePath` in return value, since that's what it's called elsewhere (and it's more explicit)
- Convert various old-style classes to use `class` syntax

Convert Resolver.resolve to async

---

packages/contract/package.json

As mentioned in #3024, it looks like `@truffle/debug-utils` is missing from `@truffle/contract`'s `package.json`.

Bug fix: Add missing dependency to @truffle/contract

---

packages/debug-utils/package.json
yarn.lock

Updated higlightjs-solidity for Solidity 0.6.7 and its new `type(I).interfaceId`, now bumping the version here. :)

Dependency update: Update syntax highlighting for 0.6.7

---

packages/contract/lib/contract/index.js

My `debugger` hack to make stacktraces work was causing contract instances to have a `debugger: undefined` field.  That's obviously pretty icky.  So, uh, making sure that's only set when `--stacktrace` is on.

Avoid setting debugger: undefined on contract instances

---

packages/core/lib/debug/printer.js

The `?` command was broken if any watch expression were set due to the use of a non-lambda function.  Rather than switch to a lambda expression, I switched the `forEach` to a simple loop.  Now it works!

Bug fix: Fix (?) command in debugger

---

packages/debugger/package.json
yarn.lock

Updating the reselect-tree version in the debugger to avoid problems with web.

Dependency update: Update reselect-tree version

---

packages/artifactor/package.json
packages/blockchain-utils/package.json
packages/box/package.json
packages/code-utils/package.json
packages/codec/package.json
packages/config/package.json
packages/contract/package.json
packages/core/package.json
packages/debugger/package.json
packages/decoder/package.json
packages/environment/package.json
packages/hdwallet-provider/package.json
packages/interface-adapter/package.json
packages/resolver/package.json
yarn.lock

In #2580, @nogo10 complained of a problem with source-map-support but also suggested that upgrading to 0.5.19 should fix it?  Well, I've thrown up a quick PR to do that and hopefully it does.

Dependency update: Update source-map-support version

---

packages/debugger/lib/evm/sagas/index.js
packages/debugger/lib/evm/selectors/index.js
packages/debugger/lib/helpers/index.js
packages/debugger/lib/solidity/sagas/index.js
packages/debugger/lib/solidity/selectors/index.js
packages/debugger/lib/stacktrace/sagas/index.js
packages/debugger/lib/stacktrace/selectors/index.js

This PR accounts for the possibility of normal halting without a normal halting instruction (a `RETURN`, `STOP`, or `SELFDESTRUCT`). Admittedly such a case is vanishingly unlikely to come up in real code (it requires running off the end of the code, something that nothing produced with the Solidity compiler will ever do), but, eh, may as well since it's easy.
You may notice I renamed or got rid of some selectors.  The name `isHalting` had just gotten too misleading and so I renamed it.  Similarly, constantly distinguishing between normal halts and exceptional halts was just like... we don't need that distinction in most places.  Specifically, `solidity` and `stacktrace` don't need it; only `evm` needs it.  So that distinction is gone in most places, and now in `evm` the distinction is …

Bug fix: Combine & improve return/revert detection

---

packages/core/lib/commands/debug.js

Add a `--network` option to debugger CLI.  Fixes #3015.  Turned out to be way easier than I expected.  Like, everything else turned out to be automatic!

Enhancement: Add --network option to debugger

---

packages/core/package.json
yarn.lock

This PR is intended to fix #2999.  The problem is that Mocha 5.2.0, which we were using, has a bug where `after` hooks aren't run like they're supposed to as they should when it bails out due to `--bail`.
We could solve this by upgrading... but that would mean upgrading to 6.x or 7.x, which is potentially a breaking change, and so potentially off-limits until Truffle 6.  So, I've gone with the safer choice of downgrading to 5.1.1, since the bug is specific to 5.2.0.  This does introduce *other* bugs with `--bail`, but I think they're lesser.  So, uh, yeah...

Downgrade Mocha to 5.1.1 to solve --bail problem

---

packages/core/lib/commands/test/index.js
packages/core/lib/test.js

This PR adds a `--compile-all-debug` flag to Truffle Test, which compiles all contracts in debug mode.  The `--stacktrace-extra` flag now just acts as `--stacktrace --compile-all-debug`.
Also, I changed the version detection to be less buggy.  I didn't account for the fact that there's, like, other things users can enter as versions.  So not all of them will work, but at least they won't crash!  I also checked the docker version string if there is one, although due to how docker does its versions this won't always work if you're using a nightly (but those are necessarily kind of unreliable anyways!).
Also, I added aliases `-b` for `--bail` and `-t` for `--stacktrace`.  Thinking maybe we should add more such aliases in general for, like, all our commands, but I'm starting with these.

Enhancement: add --compile-all-debug flag to Truffle Test, also some aliases

---

packages/debugger/lib/debugger.js

Really minor thing, just changed the `selectors` field on `Debugger` back to a getter.  I only changed it away from a getter because I didn't realize you can use getters like that.  Turns out you can!

Internal improvement: Change selectors field on Debugger back to a getter

---

packages/contract/test/deploy.js
packages/contract/test/methods.js
packages/truffle/test/scenarios/migrations/errors.js
packages/truffle/test/scenarios/migrations/quorum.js
scripts/ci.sh

- makes sure relevant account used in quorum test case is unlocked
- sleep a bit longer for `quorum`
- update insufficient funds error assertion for `GETH` job
- update `GETH` deploy test cases for constructor reverts
- skip `GETH` test case temporarily (geth bug)

Internal Improvement: Fix quorum & geth ci jobs

---

packages/core/lib/testing/testrunner.js

I don't know how often this code runs.  Seems unnecessary to
`.join` on line 142 only to split and rejoin again in `indent`.
`indent` now checks for the default case and should behave as before.
If the `split` is not default it will treat unindented as an array.
It will then rejoin with the `split` parameter.

Remove redundant join/split

---

packages/core/lib/commands/create/templates/Example.sol
packages/core/lib/commands/create/templates/Test.sol
packages/core/lib/testing/Assert.sol
packages/core/lib/testing/AssertAddress.sol
packages/core/lib/testing/AssertAddressArray.sol
packages/core/lib/testing/AssertAddressPayableArray.sol
packages/core/lib/testing/AssertBalance.sol
packages/core/lib/testing/AssertBool.sol
packages/core/lib/testing/AssertBytes32Array.sol
packages/core/lib/testing/AssertGeneral.sol
packages/core/lib/testing/AssertInt.sol
packages/core/lib/testing/AssertIntArray.sol
packages/core/lib/testing/AssertString.sol
packages/core/lib/testing/AssertUint.sol
packages/core/lib/testing/AssertUintArray.sol
packages/core/lib/testing/NewSafeSend.sol
packages/core/lib/testing/OldSafeSend.sol
packages/core/lib/testing/deployed.js

Partial fix for #3051.  Adds SPDX license identifiers to all contracts we make available to users.  Left our own internal testing contracts alone.  Note (@cds-amal?) we'll also need to get the ones in `truffle-box`.

Add SPDX license identifiers to (non-test) contracts

---

packages/contract/lib/contract/constructorMethods.js
packages/core/lib/test.js

This PR fixes #3023.  The basic idea is due to @gnidan.  It's quite simple actually.  Basically, it's only on the use of `deployed()` that we care about having the new info, so we modify `deployed()` to reload it.  Of course, we don't want to do this normally.  So, we have `deployed()` check for the presence of a `reloadJson()` method, and call it only if it exists.  Meanwhile, we have `test.js` set up a method `reloadJson()` on each contract, which does exactly that -- it reloads the JSON using the test resolver.  Pretty simple!
Note that `reloadJson`, like `debugger`, really ought to go by means of the provisioner, but I can't figure that out at the moment, so I'm just putting this bug fix up now and we can figure out the proper way to handle this (and the debugger attach) later.
No …

Bug fix: Add mechanism for Truffle Test to reload contracts' JSON on deploy

---

packages/codec/lib/abi-data/allocate/index.ts
packages/core/lib/debug/interpreter.js
packages/core/lib/debug/printer.js
packages/debugger/lib/data/actions/index.js
packages/debugger/lib/data/reducers.js
packages/debugger/lib/data/sagas/index.js
packages/debugger/lib/data/selectors/index.js
packages/debugger/lib/evm/selectors/index.js
packages/debugger/lib/session/index.js
packages/debugger/test/data/returnvalue.js

This PR adds a `returnValue` method to the `Session` class.  Running this method once the transaction is complete will decode the return value (or revert message).  This PR also adds code in the CLI to print the return value; it will print on successful completion.  It will also print if you hit `v` once the transaction is done, alongside the other variables.  Decoding of revert strings is now done this way also -- the CLI no longer invokes `Codec`'s `decodeRevert` to do the decoding itself, but just uses `session.returnValue()`.  If the transaction reverted, hitting `v` once the transaction is complete will now the revert string as well as the variables.
The debugger side of this is pretty straightforward.  We now need to allocate calldata as well, so we do.  We pass some info to the …

Enhancement: Have debugger print return values on successful completion

---

packages/debug-utils/package.json
yarn.lock

I updated highlightjs-solidity to highlight the `min` and `max` in `type(T).min` and `type(T).max`, added in Solidity 0.6.8.  This updates `debug-utils` to now use this version.

Dependency update: Update highlightjs-solidity for type(T).min & type(T).max

---

packages/db/src/loaders/artifacts/test/index.ts
packages/db/src/loaders/artifacts/test/workflowCompileOutputMock/compilationOutput.json

This PR is kind a mishmash of test updates.
Included changes:
- Remove a mock relation to an incorrect compilation
- Increase a timeout
- Fix a sourcePath mismatch
- Run the test DB instance using the memory adapter

Make some improvements to Truffle DB loaders tests

---

packages/contract-schema/typings/index.d.ts

This PR adds a missing exported function (`validate`) to the `contract-schema` typings
I also earmarked some updates to match the variable names in the `index.js` to the `index.d.ts`

Add `validate` function to `contract-schema` exported typings

---

packages/db/src/artifacts/schema.ts
packages/db/src/artifacts/test/index.ts
packages/db/src/loaders/resources/compilations/add.graphql.ts
packages/db/src/loaders/resources/contracts/add.graphql.ts
packages/db/src/loaders/schema/artifactsLoader.ts
packages/db/src/loaders/schema/test/index.ts
packages/db/src/schema.graphql
packages/db/src/workspace/definitions.ts
packages/db/src/workspace/schema.ts
packages/db/src/workspace/test/compilation.graphql.ts
packages/db/src/workspace/test/compilation.spec.ts
packages/db/src/workspace/test/contract.graphql.ts
packages/db/src/workspace/test/contract.spec.ts
packages/db/src/workspace/test/contractInstance.spec.ts
packages/db/types/stub.d.ts

This PR does two things:
- Rename `SourceContract` -> `ProcessedSource`. The former name turns out to be incorrect, since sources can have multiple contracts, so "processed source" more generally represents the idea here. As a consequence of this change, also remove the `name` field from that object, since it becomes meaningless.
- Add a `contracts` field to ProcessedSource for compilations. This allows the retrieval of all related contracts given only a compilation ID.
Note: it'd be ideal if processed sources could also represent other top-levels, like structs and enums, but (a) that's out of scope for an initial implementation, and (b) those aren't even exposed by Solidity (alas)

Permit querying compilations for related contracts in Truffle DB

---

.circleci/config.yml
.travis.yml

[Travis has a job timeout of 50 minutes](https://docs.travis-ci.com/user/customizing-the-build#build-timeouts). Lately the `COLONY` job has been timin' out, likely due to `ganache-cli` being slower post gas estimation refactoring/bug fixes.
[CircleCI supports longer running jobs](https://app.circleci.com/pipelines/github/JoinColony/colonyNetwork/2175/workflows/623c74b6-bfab-4dee-9d33-f08e5a211e68/jobs/11866/parallel-runs/0/steps/0-106), so let's use it for this one instead!

Internal improvement: Swap out TravisCI for CircleCI for Colony job

---

packages/db/src/db.ts
packages/db/src/loaders/commands/compile.ts
packages/db/src/loaders/commands/index.ts
packages/db/src/loaders/resources/bytecodes/index.ts
packages/db/src/loaders/resources/compilations/add.graphql.ts
packages/db/src/loaders/resources/compilations/get.graphql.ts
packages/db/src/loaders/resources/compilations/index.ts
packages/db/src/loaders/resources/contracts/add.graphql.ts
packages/db/src/loaders/resources/contracts/index.ts
packages/db/src/loaders/resources/nameRecords/index.ts
packages/db/src/loaders/resources/projects/index.ts
packages/db/src/loaders/resources/sources/index.ts
packages/db/src/loaders/schema/artifactsLoader.ts
packages/db/src/loaders/schema/test/index.ts
packages/db/src/loaders/types.ts
packages/db/types/stub.d.ts

This PR refactors the artifactsLoader to expose `db.loadCompilations(workflowCompileResult)` as a standalone method. Previously, the artifactsLoader only offered the capability of forcing a recompilation and collecting all information in one fell swoop. Now, the artifactsLoader defers to `db.loadCompilations()`. This method is intended for use inside the rest of Truffle also, so that the artifactsLoader stops being the only way to load data into Truffle DB.
For reviewing this, probably best to step through the individual commits. Notes:
- The first four commits break specific resources out from the artifactsLoader and incorporate them into the new loaders framework
- The last (fifth) commit adds a pre-processing step at the very beginning, to structure the workflow-compile result into a …

Separate compilation record-keeping in Truffle DB loaders

---

packages/core/lib/debug/interpreter.js
packages/core/lib/debug/printer.js
packages/debug-utils/index.js
packages/debugger/lib/data/selectors/index.js
packages/debugger/lib/evm/selectors/index.js
packages/debugger/lib/solidity/selectors/index.js
packages/debugger/lib/trace/selectors/index.js

This PR fixes various errors that would come up if the transaction had no trace steps.  Some of these bugs were actually relevant even when there were trace steps, oops!
It also makes some changes to the CLI: it makes it so that `p` when there are no trace steps prints a message about this rather than nonsense, and it also adds warning messages on startup (or reset or transaction load) if the transaction has no trace steps.

Bug fix: Make debugger robust against lack of trace steps and add warnings

---

packages/provider/index.js
packages/provider/test/create.js

This PR adds an optional `url` field to the truffle config to allow overriding host/port. This allows endpoints that have a path (i.e. https://mainnet.infura.io/v3/<key> and https://sandbox.truffleteams.com/<id>) as well as anything that uses TLS (aka `https` or `wss`)
Ideally, the motivation here is to reduce the number of steps for users to use a Truffle Teams Sandbox

Add optional `url` option to the config to use instead of host/port

---

packages/debugger/lib/data/sagas/index.js
packages/debugger/lib/data/selectors/index.js
packages/debugger/test/data/yul.js

This PR fixes a bug pointed out by @gnidan, where if an assembly variable was declared with `let x:= call(...)` (or any of the other calling/creating opcodes), the debugger would fail to track it properly, instead attempting to allocate it stack slot -1.
The reason for this is that it assumes the variable will be on the top of the stack on the next instruction; but in a case like this, it actually won't be on top of the stack until the function returns.  So, we have to look ahead to when it returns, using the `nextOfSameDepth` mechanism we already have.
Since we now have *three* possible stacks we could be looking at, I decided to reorganize things a little.  Instead of `stack` and `alternateStack`, there's now just one `stack` variable, and I assign it one of three different selectors …

Bug fix: Fix tracking of Yul variables declared to be result of a call

---

packages/solidity-utils/index.js

It's the revenge of the pseudo-nodes!
Recently, for assembly handling, we had to allow the debugger to land on nodes with no ID, which previously was disallowed.  (By "land on" I'm not referring to where `n` stops, but rather to what goes into the interval tree to be counted as a node that the debugger has hit.)  But in doing so I allowed the debugger to land on nodes with no node type, which causes problems.  So, I have now explicitly disallowed that; those no longer go in the interval tree.
(What nodes, or pseudo-nodes, are these?  They're the references in assembly to outside variables, the same ones that caused us trouble initially and caused us to exclude nodes without IDs in the first place.)
Also, while I was at it, I switched our use of `IntervalTree` back to the usual way, rather …

Bug fix: Prevent debugger from landing on nodes with no node type

---

packages/core/lib/test.js

I thought you put a solc version there.  In fact it's a boolean that says whether to use docker.  Removing some code where I attempted to extract the solc version from the `docker` option.

Oops, I misunderstood the `docker` option

---

packages/core/lib/commands/compile.js
packages/core/lib/commands/exec.js

These options were missing from the main usage printouts for their respective commands.

Fix: Add some missing options to usage printout

---

packages/debug-utils/package.json
yarn.lock

It's a highlightjs-solidity update.  Turned off highlighting for some Yul features that are not actually available in Solidity assembly.  Oops.

Dependency update: Turn off some highlighting that shouldn't be there

---

packages/compile-solidity/test/test_JSparser.js

... and reword other test to serve to validate happy-path (instead of assuring quickness)
As an alternative, if we really wanted to tested the speed improvement, we'd have to measure the time of solcjs vs. native or docker parsers.

Remove unreliable test

---

packages/codec/lib/abi-data/decode/index.ts
packages/codec/lib/stack/decode/index.ts
packages/codec/lib/types.ts
packages/debugger/test/data/calldata.js
packages/debugger/test/helpers.js

This PR updates codec to be able to handle array slices.
Now, array slices are not new in 0.6.9, but what is new is having any reason to decode them.  Now that it's possible to stick them in a calldata local, we have to be able to decode them.
In order to handle this, I've added a new `lengthOverride` option to decoding in codec.  Now, when decoding a dynamically-sized calldata type from the stack, the stack decoder will pass this option to the ABI decoder.  If it is passed, the ABI decoder will use this rather than reading the length out of calldata, and also will not increment `startPosition`, since having `lengthOverride` present means that the pointer points to the start of the data excluding the length.
This actually allows us to simplify the stack decoder, since all …

Update codec to handle array slices

---

packages/core/lib/commands/debug.js

We removed it from `truffle help`, but not `truffle help debug`.  Now should be gone entirely.

Internal improvement: Remove "experimental" from debugger help text

---

packages/contract/test/deploy.js
packages/contract/test/methods.js
scripts/ci.sh
scripts/wait-for-quorum-network.js

quorum job stuff
----------------
`quorum-examples` bumped to `quorum` v2.6.0, which bumps `geth` internally, and requires passing the unlock accounts flag on startup for keystore accounts.
As part of this, I decided to remove the lazy `sleep` CI step and use a retry-promise script to poll the network and resolve before moving onto the `quorum` integration test.
geth job stuff
----------------
`geth` changed some more of their error handling, so relevant affected test cases have been updated to appropriately.

Internal Improvement: Fix quorum & geth ci again again again again

---

packages/debugger/lib/evm/sagas/index.js
packages/debugger/lib/evm/selectors/index.js
packages/debugger/lib/web3/sagas/index.js

This PR supersedes #3095; it also is an attempt to address #2066, but a much better one.
This PR has two commits.  The first is taken straight from #3095.  It handles the Besu compatibility problem that Besu reports the stack and memory in a slightly different format than Geth and Ganache do.  This might change in future versions of Besu, since I alerted Pegasys to this discrepancy, but for now it's there and I figured we ought to be prepared to handle it.  It handles the problem by simply converting the trace on intake to Geth/Ganache format, so it will be in the right format the whole way through.
The second deals with how Geth and Besu handle storage.  (Although Geth is changing this to act like Ganache; [this](https://github.com/ethereum/go-ethereum/pull/21204) is their PR for it. …

Bug fix: Fix Geth and Besu compatibility problems in debugger

---

packages/core/lib/commands/debug.js

When I added the `--network` option to `debug`, I didn't realize that I shouldn't add a default network, because we already have a means for autodetecting the default network, and doing this would override it in bad ways.  Well, now that's removed.  Thanks to @kevinbluer for pointing out the issue.

Bug fix: Remove "development" default from debugger --network option

---

packages/debugger/lib/helpers/index.js

This PR fixes a bug where occasionally the debugger would compute the wrong address for a `CREATE2` that failed.
Normally the debugger reads addresses off the stack, but for failed creations, that's impossible.  For failed `CREATE`s we can't do anything about this, but for failed `CREATE2`s we can, and do, compute the address ourself.
However, sporadically, we'd compute the address incorrectly: The high byte would be zeroed out.  Why was this happening?
Well, it's due to us manipulating 32-byte words as hexstrings, largely.  We'd compute the appropriate hash, cut off the first 12 bytes, then checksum what remained to get our address.
Except... what if the string representing the hash was less than 32 bytes long?  Turns out, the debugger's `keccak256` function didn't include any padding. …

Bug fix: Add proper padding to debugger's keccak256 function

---

packages/core/lib/debug/interpreter.js
packages/core/lib/debug/printer.js
packages/debug-utils/index.js
packages/debugger/lib/controller/sagas/index.js

This PR does several things.  First of all, it fixes #3114.  The `stepInto` function now checks for whether the current line has changed, rather than the current location.  Also, I removed some special cases that just don't seem necessary.
Secondly, the debugger CLI didn't treat `i` and `u` as repeatable; I removed that.
Finally, I fixed the help printout, which would always show the last entered command as step next, regardless of what it actually was.

Bug fixes: Fix step into; fix help display; make i & u repeatable

---

packages/hdwallet-provider/package.json
packages/hdwallet-provider/src/index.ts
packages/hdwallet-provider/typings/web3-provider-engine/index.d.ts
packages/hdwallet-provider/typings/web3-provider-engine/subproviders/filters.d.ts
packages/hdwallet-provider/typings/web3-provider-engine/subproviders/hooked-wallet.d.ts
packages/hdwallet-provider/typings/web3-provider-engine/subproviders/nonce-tracker.d.ts
packages/hdwallet-provider/typings/web3-provider-engine/subproviders/provider.d.ts
yarn.lock

In order to make git NOT a dependency of Truffle, Truffle's fork of `MetaMask/web3-provider-engine` was published as `@trufflesuite/web3-provider-engine`. [Here](https://github.com/trufflesuite/provider-engine) is the repo.
This PR switches `@truffle/hdwallet-provider` to use the newly published package.

Dependency update: Switch to using Truffle's published web3-provider-engine

---

packages/source-fetcher/lib/common.ts
packages/source-fetcher/lib/etherscan.ts
packages/source-fetcher/lib/index.ts
packages/source-fetcher/lib/sourcify.ts
packages/source-fetcher/lib/types.ts

This PR expands adds a source-fetcher for Sourcify.
Because Sourcify doesn't have multiple formats to deal with, it's mostly more straightforward to handle.  First, get the metadata.  Then get the sources.  If they're literal sources we can get them straight out of the metadata -- Sourcify doesn't actually support this yet but they're planning it -- otherwise we look them up by path.
I copied the retry logic from the Etherscan fetcher.  I removed the throttling; hopefully that doesn't cause any problems.
However, there are a few additional wrinkles worth noting.
First, for Sourcify, if Sourcify doesn't list a certain contract, there's no special error JSON we'll get back; rather, we'll just get a 404.  So, we now check errors to see whether they're 404 errors.  At the low level, when …

Enhancement: Add a Sourcify source-fetcher

---

packages/migrate/index.js
packages/migrate/migration.js

- try/catch require's of `Migrations.sol` in
`@truffle/migrate` to ignore non-existence of
Migrations artifact

Enhancement: Make Migrations optional

---

packages/compile-solidity/compilerSupplier/index.js
packages/compile-solidity/compilerSupplier/loadingStrategies/Local.js

This PR fixes the Local loading strategy, by wrapping the soljson before returning it.  Now you can indeed just point your solc version to a local soljson and it'll work.
To preserve compatibility with the old broken way (though I have to wonder if anyone was actually using that?), before wrapping, we check if `soljson.compile` exists, and if it does, we assume it's already wrapped, and refrain from wrapping it again.
Also, while I was at it, I converted `load()` to an `async` function instead of manually constructing a Promise, because there's really no reason for it to do that.

Fix Local loading strategy by wrapping soljson

---

packages/debug-utils/index.js
packages/debugger/lib/stacktrace/reducers.js

Free functions are likely coming to Solidity, and jumps on Yul functions are very likely coming to Solidity soon!  Better make sure our stacktracing can handle them!
This PR does two things:
1. It updates `formatStacktrace` in `debug-utils` to account for the possibility of a function with a name but no contract name;
2. It updates the stacktrace reducer to account for the possibility of a Yul function rather than a Solidity function.
And that's it, pretty straightforward!

Update stacktracing for free & Yul functions

---

packages/codec/lib/format/utils/inspect.ts

Problem I encountered while using the debugger: If even one numeric variable is too big to fit in a `number`, printing/watch expressions breaks entirely.  To remedy this, `nativizeVariables()` now catches errors and returns `undefined` for variables that can't be nativized.  Not great, but better than making it so that you can't even do `:9` if there happens to be a variable equal to 10^18.

Bug fix: Have nativizeVariables() return undefined for variables that throw

---

packages/contract-schema/spec/abi.spec.json

To fix problem with ABI input type `tuple[]`
Raised on Spectrum [here](https://spectrum.chat/trufflesuite/truffle-teams/artifacts-upload-is-not-working~e6758041-1135-4857-9429-96c81e8ecfca)

Support arrays of tuples in ABI schema

---

packages/codec/lib/abi-data/allocate/index.ts
packages/codec/lib/abi-data/allocate/types.ts
packages/codec/lib/abify.ts
packages/codec/lib/core.ts
packages/codec/lib/decode.ts
packages/codec/lib/index.ts
packages/codec/lib/storage/allocate/index.ts
packages/codec/lib/types.ts
packages/core/lib/debug/printer.js
packages/debugger/test/data/returnvalue.js
packages/decoder/lib/types.ts

Really, linked libraries ought to be included as well, but, eh.  It's just gonna have to wait.  There's a reason I didn't do that initially (despite linked libraries having certainly existing back then) and continue to hold off on it now.
Anyway.  This enhancement to `@truffle/codec` makes it so that, when you decode the bytecode returned from a constructor call, the decoded output includes the values of all immutable variables, in addition to what was already present.  Note that this information is only present in full mode, and the abify functions now strip it out.
(Well, not *all* immutables -- I left out any ones that are never actually used.  It was just easier this way.  This is a little inconsistent with how allocation of state variables works, since there they're included.)
In …

Enhancement: Include immutables when decoding returned bytecode

---

packages/hdwallet-provider/package.json
yarn.lock

* @truffle/hdwallet-provider: 14.0.6 →  14.0.7
Properly resolves #3130 .

Upgrade dependency: @trufflesuite/web3-provider-engine@14.0.7

---

packages/provider/index.js

- Wraps `getBlockNumber` call within `Provider.testConnection` within a `setInterval`
When coupled with the `web3-provider-engine` [fix](https://github.com/trufflesuite/provider-engine/pull/6), enables smoother CLI production deployments. (Smoke-tested 20 consecutive successful deployments ✅).
Resolves #3133.

Enhancement: Improve network check for congested networks

---

packages/compile-solidity/compilerSupplier/loadingStrategies/Docker.js

From version 12 on, node doesn't set a very high limit for `execSync`'s `maxBuffer` anymore. So we have to define that limit ourselves to avoid running into an ENOBUFS error for large contract suites.
See https://github.com/nodejs/node/pull/23027 and https://github.com/trufflesuite/truffle/commit/180359b3fc386ce112cc77e63628d2558e4abb08
To see that error message in a real-world project see https://app.circleci.com/pipelines/github/JoinColony/colonyNetwork/2377/workflows/eca45a24-a95a-4bad-8370-153e673cbb75/jobs/12639

Set `maxBuffer` to avoid ENOBUFS error message

---

packages/compile-solidity/compilerSupplier/loadingStrategies/Docker.js

Fix: Bump maxBuffer for Docker solc compilations

---

packages/hdwallet-provider/package.json
yarn.lock

* @truffle/hdwallet-provider: 14.0.7 →  15.0.0-0
Resolves https://github.com/trufflesuite/truffle/issues/2852.
Also fixes regression in versioning.

Upgrade dependency: @trufflesuite/web3-provider-engine@15.0.0-0

---

packages/debug-utils/index.js
packages/debugger/lib/solidity/reducers.js
packages/debugger/lib/solidity/sagas/index.js
packages/debugger/test/helpers.js

Just some minor stuff to handle 0.6.11 better, although we handle it pretty well already.  This has basically two parts:
1. When printing a stacktrace, unmapped code is reported as "unknown location" instead of `undefined:1:1`.
2. Two changes to the phantom stackframe guard.  First, when checking whether to clear it, we check if you're jumping into unmapped code, and if so, we leave it alone.  Second, we no longer clear it on jump outs (that never really served any purpose anyway).  The former is so that jumps into unmapped code before the function starts don't screw things up; the latter is so that returning from that unmapped code doesn't screw things up.

Bug fix: More Yul jump handling

---

.github/workflows/nodejs.yml
.travis.yml
packages/artifactor/package.json
packages/blockchain-utils/package.json
packages/box/package.json
packages/code-utils/package.json
packages/compile-solidity/package.json
packages/compile-vyper/package.json
packages/config/package.json
packages/contract-schema/package.json
packages/contract/package.json
packages/core/lib/test.js
packages/core/package.json
packages/debug-utils/package.json
packages/debugger/package.json
packages/deployer/package.json
packages/expect/package.json
packages/external-compile/package.json
packages/hdwallet-provider/package.json
packages/interface-adapter/package.json
packages/migrate/package.json
packages/provider/package.json
packages/require/package.json
packages/resolver/package.json
packages/truffle/package.json
packages/truffle/test/scenarios/reporter.js
packages/workflow-compile/package.json
yarn.lock

This is a PR to update all packages (except the debugger) to version 8.
Some things to note:
- The `useColors` options looks like it was deprecated and therefore removed here (see breaking changes [here](https://github.com/mochajs/mocha/releases/tag/v8.0.0))
- Mocha 8 is compatible with Node >= 10.12.0 and not Node 13
- The debugger package was left at version 5.x.x because it will require a bit more work to deal with deps like `mocha-webpack` (sorry @haltman-at).
This will be a breaking change as this will force `truffle test` to require the Node versions listed above and keep Truffle from supporting Node v8.

Dependency update: Update Mocha to version 8

---

packages/debug-utils/package.json
yarn.lock

Solidity 0.6.11 adds the `gwei` unit.  I updated highlightjs-solidity to include it.  This PR updates our highlightjs-solidity dependency so we can make use of this.

Update highlightjs-solidity to highlight gwei

---

packages/box/package.json
packages/compile-solidity/package.json
packages/config/package.json
packages/contract/package.json
packages/deployer/package.json
packages/migrate/package.json
packages/resolver/package.json
yarn.lock

Currently Truffle is using 5 different versions of Sinon. This PR bumps them all to 9.0.2 as detailed below.
* @truffle/box: ^6.3.4 →  9.0.2
* @truffle/compile-solidity: ^7.2.2 →  9.0.2
* @truffle/config: ^7.5.0 →  9.0.2
* @truffle/contract: ^7.3.2 →  9.0.2
* @truffle/deployer: ^7.3.2 →  9.0.2
* @truffle/migrate: ^7.3.2 →  9.0.2
* @truffle/resolver: ^7.3.1 →  9.0.2

Dependency update: Bump sinon to 9.0.2

---

packages/artifactor/package.json
packages/blockchain-utils/package.json
packages/box/package.json
packages/code-utils/package.json
packages/config/package.json
packages/hdwallet-provider/package.json
packages/interface-adapter/package.json
packages/resolver/package.json
yarn.lock

In the interest of streamlining some dependency versions, various packages have had their ts-node dependency bumped to 8.10.2. Currently there are 4 different versions of this package used.

Dependency update: Bump ts-node to 8.10.2

---

packages/artifactor/package.json
packages/blockchain-utils/package.json
packages/box/package.json
packages/code-utils/package.json
packages/codec/package.json
packages/config/package.json
packages/decoder/package.json
packages/hdwallet-provider/package.json
packages/interface-adapter/package.json
packages/resolver/package.json
packages/source-fetcher/package.json
yarn.lock

* @truffle/artifactor: ^3.6.3 →  3.9.6
* @truffle/blockchain-utils: ^3.6.3 →  3.9.6
* @truffle/box: ^3.6.3 →  3.9.6
* @truffle/code-utils: ^3.6.3 →  3.9.6
* @truffle/codec: ^3.6.2 →  3.9.6
* @truffle/config: ^3.6.3 →  3.9.6
* @truffle/decoder: ^3.6.3 →  3.9.6
* @truffle/hdwallet-provider: ^3.6.3 →  3.9.6
* @truffle/interface-adapter: ^3.6.3 →  3.9.6
* @truffle/resolver: ^3.8.3 →  3.9.6
* @truffle/source-fetcher: ^3.6.3 →  3.9.6

Dependency update: Bump TypeScript to 3.9.6

---

packages/compile-michelson/LICENSE
packages/compile-michelson/README.md
packages/compile-michelson/index.js
packages/compile-michelson/package.json
packages/compile-michelson/scripts/test.sh
packages/compile-michelson/tests/compile-michelson.test.js
packages/compile-michelson/tests/sources/MichelsonContract.tz
packages/compile-michelson/tests/sources/SolidityContract.sol
packages/config/src/configDefaults.ts
packages/contract-sources/index.js
packages/contract/lib/execute.js
packages/workflow-compile/legacy/index.js
packages/workflow-compile/new/index.js
yarn.lock

Add `@truffle/compile-michelson` pkg:
- Add `LICENSE`
- Add initial `README`
- Add initial `package.json`
- Add initial tests:
- Add basic test contract sources
- Test basic "compiler" integration
- Add CI test script
- Add initial `index` module
In `@truffle/workflow-compile`:
- Add `@truffle/compile-michelson` as package dependency
- Add `@truffle/compile-michelson` to `legacy` and `new` workflow-compile
interfaces
In `@truffle/config`:
- Add `michelson` as a supported "compiler" in `configDefaults`
In `@truffle/contract-sources`:
- Add `.tz` to `glob` contract source `DEFAULT_PATTERN`
In `@truffle/contract`:
- Rework contract origination params (`originateParams`) when deploying
Tezos contracts to support stored native Michelson contract data.
Resolves #3170.

Feature: Initial native Michelson contract support

---

packages/migrate/index.js

Fixes https://github.com/trufflesuite/truffle/issues/3167
As I mentioned in https://github.com/trufflesuite/truffle/issues/3167#issuecomment-658450445, it's the use of `vm` that results in the `artifacts` global not being really a global. It's a variable defined in the context in which the migration script runs, and thus is not seen by modules that are `require`d.
I thought about this quite a bit and there is no way of using `vm` to define a real global value (that is inherited by required modules) that doesn't add a ton of complexity, particularly given the design of the `Migration` and `Require` abstractions. I also don't feel comfortable removing the use of `vm` entirely, which would be a significant architectural change, so I went with a mitigation for the issue I reported in …

Store resolver as a global variable during migrations

---

packages/workflow-compile/.gitignore
packages/workflow-compile/bin/_truffle_workflow_compile
packages/workflow-compile/package.json

Since Teams uses a bash interface to run commands in the build/deployment containers, we need a CLI interface to anything we execute with Truffle. To support Teams debugger usage, we'd like to save the compiler output from `@truffle/workflow-compile::compile()`. Rather than managing our own internal script in the Teams codebase, I believe it makes sense for this to live in the Truffle codebase
This PR adds that script as a `bin` in `packages/workflow-compile`

Add `_truffle_workflow_compile` to allow Teams to save compiler output

---

packages/contract-schema/spec/contract-object.spec.json

(Since this value is used for abstract contracts / interfaces.)
Raised in #3180

Allow `0x` as valid bytecode in contract schema

---

packages/contract-schema/spec/contract-object.spec.json

So I joined the JSON Schema Slack workspace and a helpful contributor found this to be missing. <3 thanks @ChALkeR!

Ensure schema lists networks as type: object

---

packages/debug-utils/index.js
packages/debugger/lib/stacktrace/actions/index.js
packages/debugger/lib/stacktrace/reducers.js
packages/debugger/lib/stacktrace/sagas/index.js
packages/debugger/lib/stacktrace/selectors/index.js
packages/debugger/test/stacktrace.js

As requested by @shanecarey17 on Gitter.
Basically this is pretty straightforward -- stacktraces now contain the contract address.  We do this by getting the address whenever we make an external call and putting it in the trace; that's basically it, really.  However, a few subtleties to note:
1. Since it's a stacktrace, I decided it was most appropriate to print the code address, not the storage address, when calling a library.
2. Of course, for contract creations, the eventual storage address is what will be shown (including if it fails and it's not created).
3. However, if there's a failed creation we can't determine the address for, we'll just print that we don't know the address.
Edit: Also I added tests of this to our existing stacktrace test cases, although I didn't add any *new* …

Enhancement: Add contract addresses to stacktraces

---

packages/hdwallet-provider/package.json
packages/hdwallet-provider/src/index.ts

- rm `web3` dependency from `@truffle/hdwallet-provider`
- import & use `RpcProvider` & `WebsocketProvider` from `web3-provider-engine` where appropriate
- Implements bug fix upstream in https://github.com/MetaMask/web3-provider-engine/commit/bd9ff60ecd0a2f2624012e8d680049ccfb6aaed2
Resolves #3182.

Fix: Sanitize payloads for @truffle/hdwallet-provider

---

.prettierrc.json

Against the [recommendation of the prettier people](https://prettier.io/docs/en/option-philosophy.html) we are overriding the option that will add arrow parens when it can as we want to avoid all the extra noise. :)

Internal improvement: Add prettierrc file

---

packages/contract/lib/promievent.js

In reponse to further detail on #3186.  Seems that `rejectHijacker` is failing to resolve `this` properly in certain contexts?  I don't know why, it's always worked fine for me, but this forces it to get it right by explicitly binding it.

Bug fix: Fix undefined this bug in rejectHijacker

---

packages/box/box.ts
packages/box/lib/utils/unbox.ts
packages/box/package.json
packages/box/test/box.js
packages/box/typings/download-git-repo/index.d.ts
packages/box/typings/github-download/index.d.ts
packages/core/lib/commands/unbox.js
packages/core/test/lib/commands/unbox.js
packages/events/defaultSubscribers/unbox.js
packages/truffle/test/scenarios/commands/init.js
packages/truffle/test/scenarios/commands/unbox.js
yarn.lock

Recently there have been a number of errors related to downloading repos from github via the unbox and init command. A very short search suggested the possibility that these errors could be related to configuration of the library used to make http requests. Unfortunately, the `github-download` library is not super configurable and it has not been updated in 4 years. I found a different library that has much more activity (and has been much more recently updated) and so swapping it out seemed like it might be an easy shot at solving this problem. It also might just be good all around in general to update to a more relevant library.
A bunch of the URL validation/sanitization methods needed to be updated as the new library liked URLs of the format `https://github.com:trufflesuite/some-box` …

Internal improvement: Swap out github download library

---

packages/compile-solidity/compilerSupplier/loadingStrategies/VersionRange.js

I found a method in `VersionRange` referenced in https://github.com/trufflesuite/truffle/issues/1131 that seems to be unused. Removing it here.

Internal improvement: Remove unused method getCommitFromVersion

---

packages/provider/index.js

Implements provider check with exponential backoff using a recursive `setTimeout` pattern.
Resolves #3200.

Fix: Ensure provider check duration is shorter than interval frequency

---

packages/compile-solidity/test/sources/v0.7.x/ComplexOrdered.sol
packages/compile-solidity/test/sources/v0.7.x/InheritB.sol
packages/compile-solidity/test/sources/v0.7.x/Version7Pragma.sol
packages/compile-solidity/test/test_supplier.js

This PR updates a few tests to 0.7.x.  This is *not* a comprehensive test update; it's just a minimal update to get the build passing again.  I've only updated what I needed to.  So, it only *partly* addresses #3207.
Note: I didn't delete the 0.6.x sources, even though they're no longer used.  Should I have?
(We have so many tests still on 0.5.x, oh my)

Internal improvement: Update native solc test to 0.7.x (minimally)

---

packages/debug-utils/package.json
yarn.lock

I updated highlightjs-solidity for Solidity 0.7.0; now updating package.json appropriately.

Dependency update: Update syntax highlighting for Solidity 0.7.0

---

packages/codec/lib/contexts/utils.ts
packages/codec/package.json
packages/core/lib/debug/compiler.js
packages/core/lib/debug/external.js
yarn.lock

This PR fixes a problem where a contract downloaded with `source-fetcher` might not be recognized if it in turn creates another contract.
The problem of course is the metadata hashes.  I already made it so that the CBOR structures at the ends of contracts are ignored for external contexts... but what about in the middle? If a contract creates another contract, or makes use of `type(C).runtimeCode` or `type(C).creationCode`, then you'll get metadata hashes somewhere in the *middle*.
I originally had a solution for this based on starting at the end and working backward, but I failed to notice that wouldn't work if our outer contract includes multiple inner contracts.  So here's a simpler, if somewhat hackier, solution.  For every contract marked as coming from an external source, note down …

Bug fix: Detect external contracts that create other contracts

---

packages/core/lib/commands/compile.js
packages/core/lib/commands/migrate.js
packages/workflow-compile/legacy/index.js
packages/workflow-compile/new/index.js

This option was previously excluded from `truffle help compile`, so this PR remedies that and also adds support for the special case `truffle compile --compiler=none`, which skips compilation.
This approach surfaced from issue #2021

Document `truffle compile --compiler` flag and add `none` as an option

---

packages/core/lib/services/analytics/index.js

This PR checks the user config to see if the user even wants to send analytics before creating a child process. The child process will still check the user config for good redundancy, but it seemed redundant to spin up a process specifically for sending analytics when analytics were disabled.
This was primarily driven for development purposes. I run `node --inspect-brk=9229 packages/core/cli.js` to debug truffle internals, and this caused the fork process to also break and wait for debugger input to continue. This caused a process to keep the port 9229 bound indefinitely until killing or running the debugger

Check analytics config before creating new process

---

yarn.lock

- bumps `ethashjs` to remove `ethereumjs-uti` -> `keccakjs` -> `sha3 `-> `node-gyp` dependencies
Simplifies the `node-gyp` dependency tree to:
Resolves partially #3175 .

Dependency Update: Bump ethashjs

---

yarn.lock

- Bumps `ethereumjs-util` to remove `keccakjs` -> `sha3` -> `node-gyp` dependencies
Eliminates the `node-gyp` dependency from `truffle`!
🔥🔥🔥🔥 
Resolves #3175.

Dependency Update: Bump ethereumjs-util

---

packages/core/lib/commands/init/initSource/contracts/Migrations.sol

This PR does four things:
1. It updates the pragma in `Migrations.sol` so as to allow for Solidity 0.7.x
2. It addresses #3223, switching the `restricted` modifier to use `require`, and including a revert message
3. It fixes the lower bound on the pragma from 0.4.21 to 0.4.22.  Version 0.4.22 is both when the `constructor` keyword was introduced (so it should already have been that) and it's also when support for revert messages was introduced.
4. It replaces the explicit constructor with an initializer.  This is for improved compatibility.  Like, this would allow us to drop the low end of the required version below 0.4.22... except we can't actually, because I added a revert message. :P  But more importantly, it's for forward compatibility -- I believe it's planned that 0.8.0 will …

Use require in Migrations and update for 0.7.0 and future

---

packages/debugger/webpack/webpack.config-test.js

This doesn't matter too much but it's been bugging me.  The debugger tests should run in development mode, but since the webpack upgrade no mode has explicitly been set, and it's been defaulting to production (with a warning).  I'm now explicitly setting it to development.

Internal improvement: Set debugger webpack test config to development mode

---

packages/core/lib/build.js
packages/core/lib/commands/build.js
packages/core/lib/commands/watch.js

Preparation for deprecation of `build` and `watch` in version 6 of Truffle.
Also a missing call to `callback` was causing build to hang when there is no build script present. This PR also fixes this.

Add deprecation messages for build and watch command

---

packages/core/lib/console.js

Because of the handling of expressions with "await" in it, a trailing ";" will break it. So we strip it off!
See https://github.com/trufflesuite/truffle/issues/3206

Bug fix: Sanitize input in console to prevent errors.

---

packages/artifactor/package.json
packages/contract/package.json
packages/core/package.json
packages/debugger/package.json
packages/deployer/package.json
packages/environment/package.json
packages/hdwallet-provider/package.json
packages/interface-adapter/package.json
packages/interface-adapter/test/fabric-evm-getId.test.ts
packages/interface-adapter/test/quorum-decodeParameters.test.ts
packages/interface-adapter/test/quorum-getBlock.test.ts
packages/provider/package.json
packages/truffle/package.json
yarn.lock

* @truffle/artifactor: 2.10.2 →  2.11.2
* @truffle/contract: 2.10.2 →  2.11.2
* @truffle/core: 2.10.2 →  2.11.2
* @truffle/debugger: 2.10.2 →  2.11.2
* @truffle/deployer: 2.10.2 →  2.11.2
* @truffle/environment: 2.10.2 →  2.11.2
* @truffle/hdwallet-provider: 2.10.2 →  2.11.2
* @truffle/interface-adapter: 2.10.2 →  2.11.2
* @truffle/provider: 2.10.2 →  2.11.2
* truffle: 2.10.2 →  2.11.2

Upgrade dependency: ganache-core@2.11.2

---

packages/core/lib/commands/debug.js
packages/environment/environment.js

This is in response to https://github.com/trufflesuite/truffle/issues/3205.
UPDATE: Adding a field to the `builder` object for a command provides it a default when no other value is provided. In this case, the default was getting set to `undefined` and then overwriting `options.network` [here](https://github.com/trufflesuite/truffle/blob/develop/packages/core/lib/command.js#L134). Since it doesn't seem that we have much use for this property, this PR removes it for `debug`.
It still might be useful to keep `builder` around as it allows us to set defaults per command. However, we should be cautious about when to use those defaults.

Bug fix: Remove field to prevent clobbering network name in develop

---

packages/core/lib/debug/printer.js
packages/debug-utils/index.js
packages/debugger/lib/evm/actions/index.js
packages/debugger/lib/evm/reducers.js
packages/debugger/lib/evm/sagas/index.js
packages/debugger/lib/evm/selectors/index.js
packages/debugger/lib/session/sagas/index.js
packages/debugger/lib/session/selectors/index.js
packages/debugger/lib/trace/sagas/index.js

Basically, this PR makes `session.info.affectedInstances` include contract creations again, allowing for a better "addresses affected" display and more assurance of `--fetch-external` working properly (because that uses `affectedInstances`!), without messing up the debugger internals.
So, recall the history here.  Originally `affectedInstances` only included calls.  Then I added creations to it as well.  Then I made the codex system, and those didn't play nicely together, so I removed creations (except, oddly, if the transaction itself was a creation transaction, I didn't remove that; this appears to have been an oversight).  But... having creations in `affectedInstances` is nice.  Problem is, like I said, it doesn't play nicely with the codex system.
So, what do we do?  Separate the two. …

Put contract creations back in affectedInstances, without messing up the codex

---

packages/artifactor/tsconfig.json
packages/blockchain-utils/tsconfig.json
packages/box/tsconfig.json
packages/code-utils/tsconfig.json
packages/codec/tsconfig.json
packages/compile-common/tsconfig.json
packages/config/tsconfig.json
packages/decoder/tsconfig.json
packages/hdwallet-provider/tsconfig.json
packages/interface-adapter/tsconfig.json
packages/provisioner/tsconfig.json
packages/resolver/tsconfig.json
packages/source-fetcher/tsconfig.json

As requested by @gnidan, to go along with #3239.
Note I standardized on using `"es2015"` rather than `"es6"` since that's the proper name, but they're the same thing.  Only three packages were actually upgraded: `decoder`, `provisioner`, and `source-fetcher`.  All the others were already on `"es6"` and just had the target name standardized.  (And `codec` already had `"es2015"` so that was left alone.)

Internal improvement: Upgrade all TS packages to ES2016

---

.github/workflows/nodejs.yml

If the Slack notification fails, that shouldn't cause a test failure.  This change to the GHA YAML file should make that the case, if I've understood correctly.

Internal improvement: Allow test suite success on Slack notification failure

---

packages/debugger/lib/evm/sagas/index.js
packages/debugger/lib/web3/adapter.js

Two bug fixes:
1. I accidentally broke `--fetch-external` with PR #3231; we don't have test cases for it unfortunately and I didn't think to test it.  This PR fixes that.
2. It turns out some Ethereum nodes, when you do `debug_traceTransaction`, will give you both an error *and* a result.  Meaning, there is a result, but they're also returning an error for some reason.  So now, to determine whether to throw, we check for the absence of a result, rather than the presence of an error.

Two debugger bug fixes, including unbreaking --fetch-external

---

packages/core/package.json
yarn.lock

Hoping this solves the redirect problem and gets the tests passing.  We'll see though.
(The substance of this is updating `wget-improved` from 1.4.0 to 1.5.0; unclear if that will fix things.)

Update ethpm-js to resolve redirect issue

---

packages/codec/lib/contexts/utils.ts

When determining affected instances
Got this stack trace when debugging another yam contract transaction:
```
truffle debug 0x1d64875b24732bc2e8880cd0870ea8e301ddde683ce81fea418e9ab4feea90bb --fetch-external
Starting Truffle Debugger...
✔ Compiling your contracts...
⠹ Getting and compiling external sources...TypeError: Cannot read property 'cbor' of null
at Object.values.filter.map.filter.cborSegment (/Users/gnidan/src/work/truffle/packages/codec/lib/contexts/utils.ts:182:65)
at Array.filter (<anonymous>)
at Object.normalizeContexts (/Users/gnidan/src/work/truffle/packages/codec/lib/contexts/utils.ts:180:6)
at Function.normalize (/Users/gnidan/src/work/truffle/packages/debugger/lib/session/index.js:248:37)
at /Users/gnidan/src/work/truffle/packages/debugger/lib/session/index.js:445:41
at …
```

Protect against null values for cborSegment

---

packages/error/package.json

#3272 
Seems like @truffle/error wasn't getting of its files published!
This PR should fix that. Tested this using `yarn pack` and seems to work. Assuming this is good to go, will be pushing out an early Monday night release tonight.

Fix @truffle/error package.json

---

packages/core/lib/console-child.js
packages/core/lib/console.js

This PR moves the network value from being a positional argument sent to the child process to being a part of the input string that gets passed. The string is then split up and used as before in the `console-child.js` file. This code is in response to a comment on the original PR, but since it hasn't been decided whether we're doing it this way I wanted to make it a separate PR. Just wanted to save time in case we do go this route, we can just merge this in.

Pass network as a named --network option instead of positionally

---

packages/compile-solidity/package.json
packages/compile-vyper/package.json
packages/contract-sources/package.json
packages/contract-tests/package.json
packages/core/package.json
packages/debug-utils/package.json
packages/deployer/package.json
packages/environment/package.json
packages/events/package.json
packages/expect/package.json
packages/external-compile/package.json
packages/migrate/package.json
packages/provider/package.json
packages/reporters/package.json
packages/require/package.json
packages/solidity-utils/package.json
packages/workflow-compile/package.json

Thanks to @seesemichaelj for verifying that `exit 0` should be fine on Windows :)
See #3306 for something of a write-up on why this is necessary.

Add no-op prepare script to packages missing it

---

packages/decoder/lib/decoders.ts
packages/decoder/test/current/contracts/WireTest.sol
packages/decoder/test/current/test/wire-test.js

(Sorry about all the `prettier` changes; the actual changes here, aside from the changes to the tests, are:
1. The deletion of line 893
2. The change to lines 905-908 (now 903-906)
3. The deletion of line 1661.)
This PR is in response to an issue pointed out by @tcoulter where the decoder could crash when decoding return values in certain situations.  Specifically, if contract `Derived` extends contract `Base`, where `Base` has no bytecode associated with it (say it's abstract or an interface), and you set up a decoder for `Base` but for an instance of `Derived`, then you'd get a crash when attempting to decode return values with it.
The reason is that, since `Base` has no bytecode, when the instance decoder is set up, it looks as the bytecode of the instance to determine a context hash, …

Bug fix: Better locate allocations for decoding function return values

---

packages/core/lib/debug/cli.js
packages/debug-utils/index.js
packages/debug-utils/package.json
packages/debugger/test/helpers.js
yarn.lock

This PR removes the `gatherArtifacts` function from `debug-utils`, together with the `node-dir` dependency.  Instead the `gatherArtifacts` code is recreated separately in both places that use it (`core/lib/debug` and `debugger/test`).  Since we have basically this same code duplicated in so many places already, one more isn't really any harm...
This should address #3293.

Remove node-dir dependency from debug-utils

---

packages/contract/lib/contract/bootstrap.js
packages/contract/lib/execute.js

Addresses #381 (I think?) and #2293.  Partly addresses #2295.
This PR fixes `method.request()` -- sort of.  The functionality is different from what it used to be before Truffle 5.  Discussing it with @gnidan, he agreed this was OK, as breaking changes between Truffle 4 and Truffle 5 are fine, and this feature hasn't actually worked since Truffle 4.
The new functionality is that, instead of returning a raw JSON RPC object to be used in a JSON RPC call, it returns an object that can be passed to `web3.eth.sendTransaction` (or `web3.eth.call`, or `web3.eth.estimateGas`).
In addition, I implemented `Contract.new.request()` as well, which did not previously exist.  Its functionality of course matches the new functionality of `method.request()`.
Apologies for all the changes caused by …

Fix method.request() but with a slightly different functionality

---

packages/debugger/lib/helpers/index.js
packages/debugger/lib/session/sagas/index.js
packages/debugger/lib/trace/sagas/index.js

This PR adds self-destruct recipients to the list of addresses affected.
This is pretty straightforward; however I decided to rewrite the loop in `processTrace` so that it's only running over the trace once instead of multiple times.
I also restored the `isSelfDestructMnemonic` function which I had previously deleted for lack of use.
I didn't bother writing a test for this but I did test it manually.

Enhancement: Add selfdestruct recipients to addresses affected

---

packages/debugger/lib/evm/actions/index.js
packages/debugger/lib/evm/reducers.js
packages/debugger/lib/evm/sagas/index.js
packages/debugger/lib/session/sagas/index.js
packages/debugger/lib/session/selectors/index.js
packages/debugger/lib/trace/sagas/index.js
packages/debugger/test/context.js

As requested by @gnidan.
This PR makes it so that the `affectedInstances` entry for addresses created during the transaction (note: I didn't include just internal creations, but also the transaction itself if it is a creation) now also contains a field, `constructorArgs`, containing the (encoded) constructor arguments.
This PR also fixes a small bug I accidentally introduced with #3323 -- in that PR, I accidentally removed the check to make sure that we only add contract creations to affectedInstances if the address isn't zero.  I've added it back in here.  Also, when writing #3323, I failed to notice that the variable `creationStartIndex` wasn't really named properly anymore; I've renamed it.
Anyway, the way this PR works is as follows.  During `processTrace`, for creations (that don't …

Enhancement: Put (encoded) constructor arguments in affectedInstances

---

packages/compile-solidity/compilerSupplier/index.js
packages/compile-solidity/compilerSupplier/rangeUtils.js
packages/core/lib/test.js
packages/core/lib/testing/Assert.sol
packages/core/lib/testing/AssertAddress.sol
packages/core/lib/testing/AssertAddressArray.sol
packages/core/lib/testing/AssertAddressPayableArray.sol
packages/core/lib/testing/AssertBalance.sol
packages/core/lib/testing/AssertBool.sol
packages/core/lib/testing/AssertBytes32.sol
packages/core/lib/testing/AssertBytes32Array.sol
packages/core/lib/testing/AssertGeneral.sol
packages/core/lib/testing/AssertInt.sol
packages/core/lib/testing/AssertIntArray.sol
packages/core/lib/testing/AssertString.sol
packages/core/lib/testing/AssertUint.sol
packages/core/lib/testing/AssertUintArray.sol
packages/core/lib/testing/Deployed.js
packages/core/lib/testing/NewSafeSend.sol
packages/core/lib/testing/SolidityTest.js
packages/core/lib/testing/Version.js

This PR is in response to #3292.  It attempts to make version-checking in `truffle test` better and more consistent.  Right now, `test.js` and `testing/Deployed.js` both attempt to check what Solidity version is being used, but they do so in different ways, each with different pitfalls.  This PR has them do it the same way, in a way that should be more robust than what either was doing before.
Note that I basically relied on copy-paste here.  However it may be worth factoring this somehow?  I figured I'd PR this initial version and we could perhaps figure that out later.
Bascailly, before, `test.js` wanted to know whether the version was at least 0.6.3, while `testing/Deployed.js` wanted to know whether it was prior to 0.5.0.  The former could handle versions and version ranges, but not …

Bug fix: Improve version checking during testing

---

packages/error/tsconfig.json
packages/provisioner/tsconfig.json

This PR adds empty `typeRoots` arrays to the `tsconfig.json` files of the `@truffle/provisioner` and `@truffle/error` packages. This will help ensure that the typeRoots for these packages do not need to be implicitly determined. Rather, all packages should explicitly define their typeRoots.

Internal Improvement: Add typeroots empty array to error and provisioner tsconfig.json files

---

packages/core/lib/console-child.js
packages/core/lib/console.js

This PR seeks to allow the re-introduction of the child process for commands from #3255, the `spawn-repl` branch, while fixing a  few issues: 
1. A bug where Artifacts were not available within the `truffle develop` and `truffle console` commands. It appears the context containing the contracts' artifacts was not properly being set for the new repl. 
To test that this bug is fixed: 
a) Run `truffle console` or `truffle develop` in an existing project that has already migrated its contracts. 
b) Enter the name of one of its contracts.
Expected: The artifact for that contract is printed in your terminal. 
a) Run `truffle console` or `truffle develop` in an existing project for which a migration has not been run. 
b) Enter the name of a contract in the project.
Expected: Error thrown
c) Run …

Set context vars

---

packages/compile-solidity/parser.js
packages/compile-solidity/test/sources/v0.4.15/MyContract.sol
packages/compile-solidity/test/test_parser.js
packages/truffle/test/scenarios/commands/install.js

Fix for https://github.com/trufflesuite/truffle/issues/3082.
Not very pretty. Both `solcjs` and `solc` only return the first line of the statement in `formattedMessage` so its not possible to grab the import. This detects multiline imports, parses the import name out of `message` and then parses the full path out of the import from `body`.
Single line import handling isn't changed.
Example of a formattedMessage for multiline import using `solcjs`:
```
{ component: 'general',
formattedMessage:
'ParsedContract.sol:3:1: ParserError: Source "@openzeppelin/contracts/utils/ReentrancyGuard.sol" not found: File import callback not supported\nimport { ReentrancyGuard } from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";\n^----------------------------------------------------------------------- …
```

Fix for multiline import parsing

---

packages/codec/lib/basic/decode/index.ts
packages/codec/lib/evm/import/index.ts
packages/codec/lib/format/utils/inspect.ts
packages/codec/lib/format/values.ts
packages/debugger/test/data/function-decoding.js
packages/debugger/test/helpers.js
packages/solidity-utils/index.js

The main point of this PR is to support free functions in the debugger and decoder, but it ended up doing a few other things as well.  One thing this PR does *not* do, by the way, is making sure that the globally-available variable `this` isn't available in free functions... because it turned out our existing code already did that!  Hooray!  So, really, the main thing ended up just being supporting decoding of function pointers to free functions.
So, first off, this meant a change to the decoder output format.  The `definedIn` field on a `FunctionInternalValueInfoKnown` is now allowed to be `null` to indicate a free function.  Also, a new field has been added to this interface: `id`, an internal ID used for internal functions just in case two free functions somehow have the same name. …

Enhancement: Debugger/decoder support for free functions

---

packages/hdwallet-provider/tsconfig.json

For @types/node and @types/web3, since our setup is meant for everything to be listed explicitly in the tsconfig
(This caused trouble for me when I ran `yarn test`, for a reason I didn't look into [it worked before, also for a reason I didn't look into])

Add missing typeRoots

---

packages/hdwallet-provider/src/constructor/Constructor.ts
packages/hdwallet-provider/src/constructor/LegacyConstructor.ts
packages/hdwallet-provider/src/constructor/getOptions.ts
packages/hdwallet-provider/src/constructor/getPrivateKeys.ts
packages/hdwallet-provider/test/provider.test.ts

In response to https://github.com/richardpringle/truffle/pull/4, this PR goes a bit further to refine the in-progress work started by @richardpringle, @eggplantzzz, and myself to support mnemonic passphrases (which has turned into that, plus a constructor interface redesign + legacy support effort).
This PR offers to suggest alternatives for two aspects of the upstream PR:
- Use more type explicitness to distinguish between the currently-supported options for `new HDWallet()`'s first argument (mnemonic phrase, private key, or list of private keys)
- Don't add support for `{ privateKey }` as a way of using the new interface. We don't need it.
I also noticed some missing `typeRoots`, so there's a commit for that. Opening this as draft, at least because the `typeRoots` change should target …

Use more explicit code style for new HDWalletProvider constructor interface

---

packages/codec/lib/memory/allocate/index.ts
packages/codec/lib/memory/decode/index.ts

In Solidity prior to 0.7.0, it was possible to put struct types containing mappings in memory.  In the memory representation, the mapping would simply be skipped over.
However, what I did not account for is that it's possible to do the same thing with arrays of mappings!  And multidimensional arrays of mappings!  This PR fixes this oversight, which caused such structs in memory to decode incorrectly.
Now, when the allocator/decoder check for skipped types, instead of just checking for typeclass `"mapping"`, they use the new `isSkippedInMemoryStructs` function.
This PR doesn't add any tests, as all this stuff is illegal in 0.7.x and that's what the debugger tests are on.  But I tested it manually.

Bug fix: Fix decoding memory structs containing arrays of mappings

---

packages/codec/lib/conversion.ts

This PR changes the Buffer type being passed to BN.js via the `toArrayLike()`method, because somehow this was triggering a deprecation warning from node in the `spawn-repl` branch. A Buffer is technically a Uint8Array, so I think this should be ok, but would love someone with a better understanding of the `codec` code to take a look and make sure this doesn't break anything.

Change Buffer to Uint8Array to avoid deprecation warning

---

packages/core/cli.js
packages/core/lib/console-child.js
packages/truffle/webpack.config.js

Split code shared by `cli.js` and `console-child.js` out into its own bundle

Bundle commands separately

---

packages/core/lib/debug/printer.js
packages/debugger/lib/data/selectors/index.js

@kevinbluer has requested that the debugger give information on which variables are builtins vs contract variables vs local variables for use in the teams debugger.  So, this PR adds a new selector to do this; the selector is `data.current.identifiers.sections`.
This selector returns an object with three fields: `builtin`, `contract`, and `local`, each of which is an array containing all in-scope variable names that go in the given section.  It should be pretty straightforward to use.
I basically did this a quick-and-dirty way by piggybacking off of `data.current.identifiers.refs`, identifying what section a given variable goes in by where it's stored.  So, variables with a location of `"special"` are builtins; a location of "`stack`" means a local; and a location of `"storage"`, …

Enhancement: Group variables by section in debugger

---

packages/db/bin/server.js
packages/db/src/artifacts/json/resolvers.ts
packages/db/src/artifacts/test/index.ts
packages/db/src/loaders/commands/compile.ts
packages/db/src/loaders/schema/artifactsLoader.ts
packages/db/src/loaders/schema/index.ts
packages/db/src/loaders/schema/test/index.ts
packages/db/src/loaders/test/index.ts
packages/db/src/schema.ts
packages/db/src/workspace/test/utils.ts

This PR removes a comment from the `server.js` file and removes unneeded imports. It also replaces `fs` with `fse` everywhere it is used in the Truffle DB project. Making a separate PR just to be sure nothing wonky is going on and nobody has concerns before merging into our longstanding truffle-db branch.

Use fs-extra in Truffle DB

---

packages/debug-utils/index.js
packages/debug-utils/package.json
yarn.lock

I didn't realize that `chromafi` was adding lots of end of padding to the end of each line.  Unfortunately chromafi has no option to turn this off.  So, I updated our fork to add such an option.  Now we pass that option.  I also made it so we pass the `tabsToSpaces: false` option (though it hasn't seemed to affect anything), since we handle the tabs-to-spaces conversion ourselves already.

Bug fix: Remove end-of-line padding in debugger CLI

---

packages/core/lib/debug/cli.js

So that CLIDebugger can expose all the nice things it does without always starting a Node REPL

Expose debugger session from CLIDebugger

---

packages/core/lib/commands/create/templates/Example.sol
packages/core/lib/commands/create/templates/Test.sol
packages/core/lib/commands/create/templates/example.js
packages/core/test/lib/create.js

This PR is to fix an error with scaffolding tests and contracts which we hit during our webinar.
Template updates
* update pragma to match bare-box
* remove done callback
* use arrow function for contract/it callbacks
``` sh
1) Contract: SS
should assert true:
Error: Resolution method is overspecified. Specify a callback *or* return a
at Context.<anonymous> (test/s_s.js:7:5)
at process._tickCallback (internal/process/next_tick.js:68:7)
```
In a new folder
1. truffle init
1. truffle create test SS
1. truffle create contract SS
1. add a migration file
``` solidity
const SS = artifacts.require("SS");
module.exports = function (deployer) {
deployer.deploy(SS);
};
```
1. truffle test and it should not error

Fix templates for truffle create (test | contract)

---

packages/compile-common/package.json
packages/compile-common/src/profiler/getImports.ts
packages/compile-common/src/profiler/requiredSources.ts
packages/compile-common/src/profiler/resolveAllSources.ts

- Remove a bunch of unused imports
- Replace imported `ResolverSource` type with an interface that contains only the relevant part.
- Get rid of the dependency

Remove @truffle/resolver dependency in @truffle/compile-common

---

packages/codec/lib/compilations/types.ts
packages/codec/lib/compilations/utils.ts
packages/codec/package.json
packages/compile-common/src/types.ts
packages/core/lib/debug/cli.js
packages/core/lib/debug/compiler.js
packages/core/lib/debug/external.js

This PR has two purposes.
The first commit redoes `core/lib/debug/compile.js`, and the other files in that directory that invoke it, so that it can actually return multiple compilations.  PR #3332 accounted for the new compile return format by mashing the different compilations together; here instead I've separated them into different compilations.
The second commit attempts to fix the types on `shimArtifacts` from `codec` to account for the fact that `bytecode` and `deployedBytecode` may be either strings or `Bytecode` objects.  To get it to compile I had to alter some of the types in compile-common, note.  This also makes `compile-common` a devDependency of codec (but not a run-time dependency).

Internal improvement: Some adjustments for the new compile format

---

packages/debugger/lib/evm/selectors/index.js
packages/debugger/lib/trace/selectors/index.js

This PR fixes a crash in the debugger that could happen if a `CALL` instruction (or similar) failed due to insufficient gas.  (There are technically other ways it could happen, but this is the most likely.)
Whenever there's a call or creation, the debugger looks ahead to the call's return to determine its return status or address returned.  To do this, it searches for the next step of the same depth.  But, what if there is no such step?  That's what can happen if the `CALL` never actually happens due to there not being enough gas.  Other parts of the debugger weren't prepared to handle this, and it caused a crash.  So, I made the other parts of the debugger that used this robust against the possibility of `undefined` here.
While I was at it, I also changed the logic there so that it will …

Bug fix: Fix debugger crash on calls with insufficient gas

---

packages/debugger/package.json
yarn.lock

Updating the reselect-tree version in debugger now that [this PR](https://github.com/trufflesuite/reselect-tree/pull/8) has been merged and released.  Now in the future when I accidentally mess up a selector, hopefully I'll get some more informative error messages.

Dependency update: Update reselect-tree version for better errors

---

packages/compile-vyper/index.js

Looks like this variable name was wrong

Fix short-circuit check that Vyper's unneeded

---

.eslintrc.json
package.json
yarn.lock

This PR turns on linting for typescript with `eslint`, or rather with `typescript-eslint`, as `eslint` doesn't quite do it itself.
The changes to accomplish this are as follows:
1. Add `@typescript-eslint/eslint-plugin` and `@typescript-eslint/parser` as dev dependencies of Truffle (in the project root), and enable them in `.eslintrc.json`
2. Certain rules in `.eslintrc.json` were on [the list](https://www.npmjs.com/package/@typescript-eslint/eslint-plugin#extension-rules) of rules that now require the `@typescript-eslint/` prefix, so I added that.
3. Finally, of course, I added an `eslint --fix` step for TS files in our pre-commit script.
One thing worth noting here: In testing whether this worked, I tried making sure the `quote-props` rule still worked, only to find that, uh, it already …

Internal improvement: Turn on eslint for typescript

---

package.json
yarn.lock

Updates `eslint`.  I was hoping this would fix the `quote-props` problem.  It didn't.  (I'll file an issue with them.)  PRing this anyway.
Edit: Oops.  There is no `quote-props` problem.  It works fine, silly me.  Anyway, updating all the same.

Dependency update: Update eslint to 7.9.0

---

packages/codec/lib/abi-data/allocate/index.ts
packages/codec/lib/abi-data/allocate/types.ts
packages/codec/lib/abi-data/decode/index.ts
packages/codec/lib/abify.ts
packages/codec/lib/bytes/encode/index.ts
packages/codec/lib/contexts/utils.ts
packages/codec/lib/core.ts
packages/codec/lib/decode.ts
packages/codec/lib/format/utils/inspect.ts
packages/codec/lib/format/values.ts
packages/codec/lib/mapping-key/encode/index.ts
packages/codec/lib/memory/decode/index.ts
packages/codec/lib/stack/decode/index.ts
packages/codec/lib/storage/allocate/index.ts
packages/decoder/lib/decoders.ts
packages/decoder/lib/types.ts
packages/decoder/test/current/test/decoding-test.js
packages/source-fetcher/lib/sourcify.ts

Figured I'd run the linter over my stuff now that we're linting TS.  This is what it turned up.  (Prettier also made a bunch of changes in the process, mostly in `codec/lib/abi-data/decode`...)
Almost all of this is removing unused variables; however, there was one case of a parameter that needed an initial `_`.  Also in one case I decided I didn't want to delete the unused types I was defining so instead I exported them. :)
Interesting case: One decoder test, written in JS, turned up with an unused import of `util`.  Why did this turn up now and not earlier?  Well, someone had stuck an `eslint-disable-line` for the `no-unused-vars` rule on it.  But we're no longer using `no-unused-vars`, but rather `@typescript-eslint/no-unused-vars`!  So this could potentially come up elsewhere.  Anyway …

Internal improvement: Resolve linting problems in various packages

---

packages/codec/lib/compilations/types.ts

The `externalSolidity` flag on codec's `Compilation` type used to be for Solidity only (OK or notionally also Yul), but due to #3212 it should now be safe to use with any language.  I never updated the comment, though, and it's part of our codec documentation so I really should.  So, did that here.
I could have changed the name of the flag, but that seemed more trouble than it was worth, so I left it alone.  Can change that though if people think that should really be done.  Obviously then I'd have to change it where it's used as well.

Internal improvement: Update doc comment about externalSolidity flag

---

packages/compile-solidity/compilerSupplier/loadingStrategies/VersionRange.js

Truffle is currently constructing bad URLs for fetching the Solidity compiler version list. It is adding an extra trailing "/" to the base of the URL. This PR strips off trailing commas from the base part of the URL before adding "/list.json".

Bug fix: Fix URL construction in the CompilerSupplier

---

packages/compile-common/src/shims/NewToLegacy.ts

These were missing from the shim, so these weren't getting saved in the artifacts, so the debugger wasn't getting them when running off of artifacts.  Added now.

Bug fix: Add generatedSources and deployedGeneratedSources to shims

---

packages/core/lib/testing/AssertBytes32.sol

Getting a warning message when using the most recent compiler
"  truffle/AssertBytes32.sol: Warning: SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source codeontaining "SPDX-License-Identifier: <SPDX-License>" to each so. Please see https://spdx.org for more information."

Include SPDX-License on AssertBytes32.sol

---

packages/compile-solidity/compilerSupplier/loadingStrategies/VersionRange.js

There is another instance where the `VersionRange` loading strategy (for `CompilerSupplier`) constructs a URL. This should make this construction more flexible: especially when a user enters their own `compilerRoots`.

Internal improvement: Update URL construction in VersionRange strategy

---

packages/contract-schema/spec/abi.spec.json

#2065 
- Ensure non-tuple parameters do not allow `components` property
- Ensure tuple parameters require `components` property
- Ensure components validate as parameters
- Ensure there is at least one component in each tuple

Validate tuple parameters in ABI schema

---

packages/compile-common/src/types.ts
packages/compile-vyper/index.js
packages/external-compile/index.js

- Add to compile-common types
- Implement as pass-through for compile-vyper and external-compile

Add `sourcesWithDependencies` to compile interface

---

packages/contract-schema/spec/abi.spec.json
packages/db/src/artifacts/json/schema.ts

Older versions of solc didn't emit `stateMutability` in ABI output.
This PR makes either `stateMutability` required **or** `payable` and/or `constant` (depending on the kind of function)

Support pre-stateMutability ABIs in schema

---

packages/codec/lib/compilations/utils.ts
packages/decoder/lib/decoders.ts

In response to #3419.
When adding support for internal sources, I didn't think about how it would affect the parts of `decoder` and `codec` that scan ASTs for types or contracts.  So, I've put some guards around these -- now, instead of just checking that ASTs are present, we check that they have `nodeType` equal to `"SourceUnit"` (not `"YulBlock"`).  With the guards the issue goes away.

Bug fix: Check that asts are Solidity before scanning their nodes

---

packages/codec/lib/compilations/utils.ts
packages/compile-common/src/types.ts
packages/core/lib/debug/cli.js
packages/core/lib/debug/external.js
packages/core/lib/test.js

(Possibly a pre-emptive bug fix although nothing's been reported!)
I noticed that, since the compile changes, `test.js` also does the thing that `debug/compiler.js` had been altered to do -- namely, to squash multiple different compilations together, rather than keeping them separate.  I'd already fixed this in `debug`, but now I wanted to do it in `test` as well.
In order to do this though I started by making a change to `Codec`.  The function `shimArtifacts` always returned a `Compilation[]` rather than a `Compilation`, and so to do what I wanted with it in `debug` was a little awkward.
So, I factored it.  Now `shimArtifacts` is just a wrapper around `shimContracts`, which returns a `Compilation`; and for actual use, I added another wrapper around it, `shimCompilations`, which directly …

Internal improvement: Separate multiple compilations in testing & factor doing so

---

packages/decoder/test/current/contracts/DecodingSample.sol
packages/decoder/test/current/contracts/DowngradeTest.sol
packages/decoder/test/current/contracts/MessageTest.sol
packages/decoder/test/current/contracts/Migrations.sol
packages/decoder/test/current/contracts/SliceTest.sol
packages/decoder/test/current/contracts/WireTest.sol
packages/decoder/test/current/test/wire-test.js
packages/decoder/test/current/truffle-config.js
packages/decoder/test/legacy/contracts/WireTest.sol
packages/decoder/test/legacy/test/wire-test.js
packages/decoder/test/legacy/truffle-config.js

So I recently merged #3420, but I didn't add any tests, and it's been kind of bothering me that there are no tests for that.
So, I added one.  I added a dummy test to the decoder test called `SliceTest`; this contract doesn't actually do anything, it's never used, but it includes code to perform array slicing because that generates internal sources.  The point is just to have something present with internal sources to make sure this doesn't crash the decoder.
Of course, to do this, I had to update the decoder tests to 0.7.x.  This caused a problem that one of the things being tested is no longer legal, so that test got moved to the legacy section.  (*Part* of what it's testing is still legal, but I thought it was more trouble than it's worth to attempt to split the test into still-legal …

Internal improvement: Update decoder tests to 0.7.3 and add a test

---

packages/debugger/lib/data/selectors/index.js

In response to #3440.
The problem is that the CLI debugger's `v` command could cause errors if there were variables with an allocation but no definition, e.g. the `this` builtin if you weren't in a known contract.
This used to not cause problems because the CLI debugger used to print out variables in whatever order it got them from `variables()`, and such variables simply wouldn't appear there.  However, now it uses `data.current.identifiers.sections` to group the variables into sections.  And I didn't think to exclude variables without definitions from the latter.  So sometimes it might get a variable name from that selector, look up that variable in the output of `variables()`, find nothing, and then get stuck when it tries to format `undefined` instead of the variable's decoded value. …

Bug fix: Restrict data.current.identifiers.sections to variables with definitions

---

packages/db/src/db.ts
packages/db/src/loaders/commands/compile.ts
packages/db/src/loaders/commands/index.ts
packages/db/src/loaders/commands/initialize.ts
packages/db/src/loaders/commands/names.ts
packages/db/src/loaders/commands/projects.ts
packages/db/src/loaders/resources/nameRecords/index.ts
packages/db/src/loaders/schema/artifactsLoader.ts
packages/db/src/loaders/types.ts

This PR pulls out adding name records, putting that functionality behind a boolean so that we can ensure that when Truffle DB is integrated with the rest of Truffle that we do not update names when `test` is being run. In the course of this work, I also pulled out the logic for adding projects, so that it is now done before we load compilations and everything else.

Pull name logic and projects loading into separate commands

---

packages/db/src/db.ts
packages/db/src/loaders/commands/names.ts
packages/db/src/loaders/resources/bytecodes/index.ts
packages/db/src/loaders/resources/compilations/index.ts
packages/db/src/loaders/resources/contracts/index.ts
packages/db/src/loaders/resources/nameRecords/index.ts
packages/db/src/loaders/resources/projects/index.ts
packages/db/src/loaders/resources/sources/index.ts
packages/db/src/loaders/types.ts
packages/db/src/meta/index.ts
packages/db/src/workspace/definitions.ts
packages/db/src/workspace/index.ts
packages/db/src/workspace/pouch/databases.ts
packages/db/src/workspace/pouch/fs.ts
packages/db/src/workspace/pouch/memory.ts
packages/db/src/workspace/pouch/sqlite.ts
packages/db/src/workspace/pouch/types.ts
packages/db/types/stub.d.ts

This stuff lived in a pouch-specific module, but it's more widely useful than that, so this PR moves this boilerplate logic into a more cohesive place, along with some additional changes along the way.
In particular:
- Define types for filtering resources based on mutability or namedness (`MutableResource`, etc.)
- Include in this new module the `IdObject` and `NamedResource` types from loaders
- Redefine each resource's input type as the actual resource input, not the input to the mutation.
- Define additional types for mutation input and mutation payload
- Tighten up the base collection type to use less `any`
- Make actual workspace Databases implementation more typesafe

Move core resource type definitions to @truffle/db/meta

---

packages/db/.madgerc
packages/db/bin/build
packages/db/bin/codegen.js
packages/db/configs/base.json
packages/db/package.json
packages/db/src/index.ts
packages/db/tsconfig.base.json
packages/db/tsconfig.codegen.json
packages/db/tsconfig.json
yarn.lock

Currently, @truffle/db is set up to require that users import `@truffle/db` by itself first, which alters Node's runtime dependency resolution to know about `@truffle/db/*` paths.
This is really gross, and we've now been favoring use of `ttypescript`, which allows us to update all generated (`dist/`) `require` statements to use the `paths` specified by the tsconfig. This is how we do things in @truffle/codec already.
In addition, this PR sets up [madge](https://github.com/pahen/madge), because madge is cool. In order to get this to work, I had to move `./configs/base.json` to `tsconfig.base.json`.
<details>
<summary>Preview module dependencies</summary>
</details>
You can now recreate this locally with `yarn madge --image deps.pdf` (and `yarn madge --circular` to verify we haven't …

Replace module-alias with ttypescript in Truffle DB

---

packages/core/lib/testing/TestRunner.js

Recently while updating `TestRunner.js`, a variable error was made. This corrects the mistake which fixes redeploys during testing.
Fixes https://github.com/trufflesuite/truffle/issues/3437

Bug fix: Fix variable error

---

packages/artifactor/package.json
packages/contract-tests/package.json
packages/contract-tests/test/errors.js
packages/contract/package.json
packages/core/package.json
packages/db/package.json
packages/debugger/package.json
packages/decoder/package.json
packages/deployer/package.json
packages/environment/package.json
packages/interface-adapter/lib/adapter/types.ts
packages/interface-adapter/package.json
packages/migrate/package.json
packages/provider/package.json
packages/require/package.json
packages/truffle/package.json
yarn.lock

This work used to be in https://github.com/trufflesuite/truffle/pull/3447 but was moved to this branch due to problems merging/rebasing that couldn't be resolved.
@truffle/artifactor: 1.2.1 → 1.2.9
@truffle/contract: 1.2.1 → 1.2.9
@truffle/contract-tests: 1.2.1 → 1.2.9
@truffle/core: 1.2.1 → 1.2.9
@truffle/db: 1.2.2 → 1.2.9
@truffle/debugger: 1.2.1 → 1.2.9
@truffle/decoder: 1.2.1 → 1.2.9
@truffle/deployer: 1.2.1 → 1.2.9
@truffle/environment: 1.2.1 → 1.2.9
@truffle/interface-adapter: 1.2.1 → 1.2.9
@truffle/migrate: 1.2.1 → 1.2.9
@truffle/provider: 1.2.1 → 1.2.9
@truffle/require: 1.2.1 → 1.2.9
truffle: 1.2.1 → 1.2.9

Dependency update: Bump web3 to 1.2.9
