lib/contracts.es6

I figure if four people who do this full-time barely realized that this might be the case, it will probably help other people.

Helpful error message for failed contract deployment

---

lib/test.js

It looks like this is all that's needed to fix #223.

Have a nonzero exit code on test failures

---

example/app/javascripts/app.js

`balance` is never used in the example `app.js`

Remove unused variable

---

docs/getting_started/contracts.md

Change `truffle deploy` to `truffle migrate`.

Change `truffle deploy` to `truffle migrate` in docs. 

---

example/contracts/ConvertLib.sol
example/contracts/MetaCoin.sol
example/contracts/Migrations.sol
templates/Example.sol

Also update versions to latest `solc`

Add solidity pragma to template contract

---

lib/repl.js

Encountered this error message while running `truffle console` and noticed the typo :)

Fix minor typo

---

lib/testing/testrunner.js

Hey @tcoulter and co!
Here’s a first pass at fixing #365
It looks like this broke when [these lines](https://github.com/ConsenSys/truffle/blob/master/lib/testing/testrunner.js#L47-L70) got commented out. It also looks like we no longer have access to `project_contracts` in that scope :/.
What I did here was read in all the contract files in place. I’m not thrilled about this because we are reading the contract files in again in `testsource.js`.
I see a few options:
1. Move all the file reading stuff into `testrunner.js`and pass the `mapping` object to TestSource’s constructor
2. Move all of the file reading stuff into the constructor of TestSource and add a getter method that returns the contracts that could be called from `testrunner.js`
3. Some combination of the two
4. Something I …

Fix #365: Event logging on test failure

---

README.md

Might save others the 20 minutes I spent trying to figure out why I was getting an error :)

Noob error I ran into

---

.travis.yml
package.json
test/scenarios.js
test/scenarios/commandrunner.js
test/scenarios/contract_names/2_deploy_contract.js.template
test/scenarios/contract_names/3_deploy_relative_import.js.template
test/scenarios/contract_names/4_deploy_floating_import.js.template
test/scenarios/contract_names/contract.sol
test/scenarios/contract_names/floating_import.sol
test/scenarios/contract_names/relative_import.sol
test/scenarios/contract_names/test_imports.js
test/scenarios/cyclic_dependencies/Ping.sol
test/scenarios/cyclic_dependencies/Pong.sol
test/scenarios/cyclic_dependencies/compiles.js
test/scenarios/happy_path/happypath.js
test/scenarios/memorylogger.js
test/scenarios/migrations/2_deploy_contract.js.template
test/scenarios/migrations/parameters.js
test/scenarios/reporter.js
test/scenarios/server.js
test/scenarios/solidity_testing/TestWithBalance.sol
test/scenarios/solidity_testing/with_balances.js

Scenario tests on the bundle.

---

README.md

I found out that the image link is broken

Fix README.md logo link

---

package.json

Upgrade solc to v0.4.13

---

package.json

Upgrade solc to v0.4.17

---

package.json

https://github.com/trufflesuite/truffle/issues/628

Upgrade solc to v0.4.18

---

test/scenarios/cyclic_dependencies/compiles.js
test/scenarios/server.js

trufflesuite/truffle#543
(**Repo tests for branch build** may fail until https://github.com/trufflesuite/truffle-core/pull/64 is merged+released)

Provide increased gas limit setting for scenario tests

---

cli.webpack.config.js
package.json

Add sourcemap pkg and enable in webpack

---

package.json

I think truffle  should use latest solc 0.4.21

Update package.json to use latest solc version 0.4.21

---

test/scenarios/happy_path/happypath.js
test/scenarios/solidity_testing/with_balances.js

Add logging in tests

---

package.json

Upgrade solc to 0.4.22

---

test/scenarios/commandrunner.js
test/scenarios/commands/ethpm.js
test/scenarios/commands/exec.js
test/sources/exec/contracts/Executable.sol
test/sources/exec/script.js
test/sources/exec/truffle.js

+ Adds a little test for  [truffle-core 132](https://github.com/trufflesuite/truffle-core/pull/132)
+ Modifies scenario command runner to accept command flags
+ Moves ethpm tests into a `commands` folder.

Add `truffle exec` test

---

test/scenarios/migrations/parameters.js
test/scenarios/npm_dependencies/2_deploy_contract.js.template
test/scenarios/npm_dependencies/2_deploy_extralib.js.template
test/scenarios/npm_dependencies/2_deploy_extralib2.js.template
test/scenarios/npm_dependencies/3_deploy_extralibx.js.template
test/scenarios/npm_dependencies/3_deploy_extraotherlib2.js.template
test/scenarios/npm_dependencies/contract.sol
test/scenarios/npm_dependencies/dep-package.json
test/scenarios/npm_dependencies/dep2-package.json
test/scenarios/npm_dependencies/extralib.sol
test/scenarios/npm_dependencies/extralib2.sol
test/scenarios/npm_dependencies/extraotherlib2.sol
test/scenarios/npm_dependencies/npmdeps.js
test/scenarios/npm_dependencies/root-package.json
test/scenarios/npm_dependencies/test-contracts.js.template

See https://github.com/trufflesuite/truffle/issues/554 for the overall issue.

Add test scenario for migrating NPM dependencies

---

packages/truffle-core/lib/commands/compile.js

Formatting fix to print recent docker images as list.

Pretty print docker list correctly

---

packages/truffle-blockchain-utils/.gitignore
packages/truffle-blockchain-utils/.travis.yml
packages/truffle-blockchain-utils/README.md
packages/truffle-blockchain-utils/index.js
packages/truffle-blockchain-utils/package.json

Add truffle-blockchain-utils to repo

---

README.md

Self-explanatory. Should we address how someone might make a dependency uniform across the packages? Or ask them to do that?

Instructions for adding dependencies

---

packages/truffle/cli.webpack.config.js

Specify webpack context to suppress absolute paths

---

packages/truffle-config/index.js
packages/truffle-core/lib/commands/debug.js
packages/truffle-core/lib/environment.js
packages/truffle-core/lib/networks.js
packages/truffle-core/lib/test.js
packages/truffle-provider/index.js
packages/truffle-provider/package.json
packages/truffle-provider/test/create.js
packages/truffle/test/scenarios/contract_names/test_imports.js
packages/truffle/test/scenarios/happy_path/happypath.js
packages/truffle/test/scenarios/migrations/parameters.js

Reverts trufflesuite/truffle#1055
(Since #1072 `develop` -> `next` merge is a non-trivial conflict)
cc @cgewecke @benjamincburns

Revert "truffle-provider: allow async provider creation"

---

packages/truffle-artifactor/package.json
packages/truffle-core/package.json
packages/truffle-debugger/package.json
packages/truffle-deployer/package.json
packages/truffle-provider/package.json
packages/truffle/package.json
scripts/ci.sh
yarn.lock

Upgrade ganache-cli to 6.1.4.

---

packages/truffle-debugger/package.json
yarn.lock

Upgrade bignumber.js to ^7.2.1

---

packages/truffle-core/lib/commands/migrate.js
packages/truffle-core/lib/commands/test.js
packages/truffle/test/scenarios/migrations/npm.js

@cgewecke Okay see the commits for the stuff.

Fix migrate deps dry run and tests

---

packages/truffle-core/cli.js
packages/truffle-core/lib/commands/debug.js

New PR from #1106 
This should resolve issue #690 and also issues on old repo:
trufflesuite/truffle-migrate#31
trufflesuite/truffle-migrate#14

Fix hanging on migrate command

---

.gitattributes
packages/truffle-core/lib/testing/Assert.sol

* GitHub isn't able to properly syntax highlight Assert.sol because the indentation isn't correct. I've made that fix in this PR.

Update .gitattributes to show syntax highlighting for Solidity files

---

packages/truffle-contract/lib/execute.js
packages/truffle-contract/lib/reformat.js
packages/truffle-contract/lib/utils.js
packages/truffle-contract/test/events.js
packages/truffle-contract/test/sources/Example.sol
packages/truffle-deployer/test/await.js
packages/truffle-deployer/test/deployer.js

#1165 
Companion to #1145.  
+ Renamed the reformatter method so it's more general.
+ Added test for numerical event outputs

Reformat event numbers as BN

---

packages/truffle-compile/profiler.js

Fix file name in profiler parsing error

---

packages/truffle-core/lib/command.js

This fixes a misnamed variable in the command file in truffle-core.

Bug fix in command file

---

README.md

Fix logo image URL

---

packages/truffle-core/cli.js

Validate that the user is running at least Node 8.
Inspired by issue #1273

Validate node version

---

packages/truffle-box/lib/utils/unbox.js

#1309 
To ensure the truffle-box exists, look for the box configuration specifically instead of the current behavior of looking for truffle.js

Verify truffle-box.json existence when unboxing

---

CONTRIBUTING.md
README.md

Hi there, I created a new command for truffle (I'll probably open a PR for it soon). It was my first time using `lerna` and a few things were not trivial in the process of contributing to the project. So I wrote a quick CONTRIBUTING.md file to help new comers like me. 
This is a first version, hopefully main contributors could document the project.

Create a new CONTRIBUTING.md file to help developpers

---

packages/truffle-hdwallet-provider/.gitignore
packages/truffle-hdwallet-provider/.travis.yml
packages/truffle-hdwallet-provider/LICENSE.md
packages/truffle-hdwallet-provider/README.md
packages/truffle-hdwallet-provider/index.js
packages/truffle-hdwallet-provider/package.json
packages/truffle-hdwallet-provider/test/provider.js

(This is @benjamincburns's work from #1368, just doing this to observe how subtrees work)

Import HDWallet Provider into monorepo

---

packages/truffle-core/lib/build.js
packages/truffle/test/scenarios/commands/build.js

Add check to see if builder is null so as not to execute a method on it and add a test

Quick bug fix in /build

---

packages/truffle-hdwallet-provider/index.js
packages/truffle-hdwallet-provider/package.json

Merged in `web3-one` branch, bumped version due to new feature additions from the small mess of PRs I merged yesterday.

Hdwallet web3 one

---

packages/truffle-debugger/lib/session/sagas/index.js

Fixes: https://github.com/trufflesuite/truffle-debugger/issues/51

Fix undefined sourcePath in debugger

---

packages/truffle-hdwallet-provider/.gitignore
packages/truffle-hdwallet-provider/.npmignore
packages/truffle-hdwallet-provider/package.json
packages/truffle-hdwallet-provider/src/index.js
packages/truffle-hdwallet-provider/test/provider.js
packages/truffle-hdwallet-provider/webpack/webpack.config.js
yarn.lock

No more native deps required.
Should make @davidburela happy :-D

hdwallet provider: Update deps, webpack, fix test

---

README.md
package.json

Upgrade devDependency and readme to specify latest version of lerna.

Upgrade lerna

---

packages/truffle-migrate/index.js

Add missing variable to make error clearer

Fix error message

---

.travis.yml
packages/truffle/test/scenarios/commands/build.js
packages/truffle/test/scenarios/commands/help.js

Added timeouts so geth build completes.

Geth build fix

---

packages/truffle-core/lib/commands/migrate.js
packages/truffle-core/lib/commands/test.js
packages/truffle-migrate/migration.js
packages/truffle-workflow-compile/index.js

Allows plugging in your own custom artifactor package.
Example:
```
artifactor: require("advanced-truffle-artifactor"),
...
};
```

Pluggable Artifactor Packages

---

packages/truffle-contract/lib/contract.js
packages/truffle-contract/lib/execute.js
packages/truffle-contract/lib/handlers.js
packages/truffle-contract/lib/utils.js
packages/truffle-deployer/src/deployment.js
packages/truffle-provider/index.js
packages/truffle-provider/wrapper.js
packages/truffle-reporters/reporters/migrations-V5/reporter.js

Since that is, what it seems, what that function wants
Seems related to https://github.com/ethereum/web3.js/issues/1916
Also: add a proper catch statement so this sort of exception doesn't just get completely ignored.

Pass empty-string instead of 0x to abi.decodeLog

---

packages/truffle/test/scenarios/commands/init.js

Add an integration test for truffle init

---

packages/truffle-core/lib/environment.js

Check to ensure that the network id in the truffle config matches the network id returned by the network before performing migrations for safety

Migration network id check

---

packages/truffle-config/index.js

Revert content that was changed in truffle-config to memoize the provider

Revert provider memoization

---

packages/truffle-compile-vyper/index.js

Vyper compiler output - handle both Windows and linux line endings

---

packages/truffle-artifactor/package.json
packages/truffle-box/package.json
packages/truffle-compile/package.json
packages/truffle-contract-schema/package.json
packages/truffle-contract-sources/package.json
packages/truffle-contract/package.json
packages/truffle-core/package.json
packages/truffle-debug-utils/package.json
packages/truffle-debugger/package.json
packages/truffle-decoder/package.json
packages/truffle-deployer/package.json
packages/truffle-external-compile/package.json
packages/truffle-hdwallet-provider/package.json
packages/truffle-reporters/package.json
packages/truffle-sawtooth-seth-provider/package.json
packages/truffle-workflow-compile/package.json
packages/truffle/package.json
yarn.lock

This PR is output from running [`lernaupdate -d`](https://www.npmjs.com/package/lerna-update-wizard) a bunch.

Homogenize package dependencies

---

packages/truffle-core/lib/commands/run.js
packages/truffle-core/lib/run.js
packages/truffle-core/test/mockPlugins/truffle-cb-stub/index.js
packages/truffle-core/test/mockPlugins/truffle-cb-stub/truffle-plugin.json
packages/truffle-core/test/mockPlugins/truffle-other-stub/index.js
packages/truffle-core/test/mockPlugins/truffle-promise-stub/index.js
packages/truffle-core/test/mockPlugins/truffle-promise-stub/truffle-plugin.json
packages/truffle-core/test/mockPlugins/truffle-stub/index.js
packages/truffle-core/test/run.js
packages/truffle/test/scenarios/commands/run.js

Completes #1512 & resölves #1482.

Handle asynchronous 3rd party plugins (2.0)

---

packages/truffle-core/lib/commands/debug.js

Other breakpoint edits have messages, this should too.  This is really just an oversight in my last PR.

Add message to confirm that all breakpoints have been removed

---

packages/truffle-hdwallet-provider/webpack/webpack.config.js

Fix truffle-hdwallet-provider webpack config

---

packages/truffle-core/cli.js
packages/truffle-core/lib/commands/version.js
packages/truffle-core/lib/version.js
packages/truffle-core/test/lib/version.js

Rearrange version logging methods and print solc version specified in the config if it exists

Update version methods

---

packages/truffle-core/test/unbox.js

Update unbox specs to cleanup after themselves.

Update unbox specs

---

packages/truffle-artifactor/package.json
packages/truffle-compile/package.json
packages/truffle-contract-schema/package.json
packages/truffle-contract/package.json
packages/truffle/package.json

Remove caret from solc in package.json files.

Ship w/ solc 0.5.0

---

packages/truffle-core/lib/commands/test.js

Add the `--show-events` option to the help for the test command.

Update help for test command

---

packages/truffle-hdwallet-provider/package.json
yarn.lock

add devDeps for truffle-hdwallet-provider

---

packages/truffle-reporters/reporters/migrations-V5/messages.js

`npm i truffle-hdwallet-provider` now defaults to a web3 1.0 compatible hdwallet provider.

Update migrations truffle-hdwallet-provider reporter msg

---

packages/truffle-hdwallet-provider/package.json
yarn.lock

Resolves #1538. Tested manually.

Fix truffle-hdwallet-provider deps

---

packages/truffle-core/lib/commands/init.js
packages/truffle-reporters/reporters/migrations-V5/messages.js

Remove some references to the web3-one branch of bare-box and a note concerning the web3-one branch of truffle-hdwallet-provider: also make the linter happy with messages.js

Remove some references to web3-one branches

---

notes/release/v5.0.0/dist/_merged.md
notes/release/v5.0.0/dist/output.md
packages/truffle-artifactor/package.json
packages/truffle-contract/package.json
packages/truffle-core/package.json
packages/truffle-debugger/package.json
packages/truffle-deployer/package.json
packages/truffle-hdwallet-provider/package.json
packages/truffle-provider/package.json
packages/truffle/package.json
yarn.lock

* truffle: ^2.3.1 →  2.3.3
* truffle-artifactor: ^2.3.1 →  2.3.3
* truffle-contract: ^2.3.1 →  2.3.3
* truffle-core: ^2.3.1 →  2.3.3
* truffle-debugger: ^2.3.1 →  2.3.3
* truffle-deployer: ^2.3.1 →  2.3.3
* truffle-hdwallet-provider: ^2.3.1 →  2.3.3
* truffle-provider: ^2.3.1 →  2.3.3

Upgrade dependency: ganache-core@2.3.3

---

packages/truffle-core/lib/templates/Example.sol
packages/truffle-core/test/create.js

#1636 
Update the contract template to the current major version of solidity (^0.5.0).

Finish #1636

---

packages/truffle-compile/compilerSupplier/loadingStrategies/VersionRange.js
packages/truffle-compile/test/compilerSupplier/loadingStrategies/VersionRange.js

Clean up method interface

---

packages/truffle-compile/compilerSupplier/loadingStrategies/Docker.js

Build out Docker strategy to have functionality for downloading docker images that are not found locally

Update Docker strategy

---

packages/truffle-db/src/data/util-helpers.ts
packages/truffle-db/src/data/utils.ts

First attempt at refactoring this utils file. I'm not sure I completely love it, but I think it's a step in the right direction. I ran `yarn test` and all the tests pass, not sure if that's sufficient or not.

Refactor truffle-db utils

---

packages/truffle-provider/error.js
packages/truffle-provider/wrapper.js

Pass the options to ProviderError to provide more information to the user when encountering a connection error

Provide more feedback with connection error

---

.gitignore
packages/truffle/.gitignore

Delete truffle package .gitignore and add it to the one at root level

.gitignore

---

.eslintrc.json
packages/truffle-compile-vyper/index.js
packages/truffle-compile/index.js
packages/truffle-compile/profiler.js
packages/truffle-core/test/compile.js
packages/truffle-workflow-compile/index.js

Reverts trufflesuite/truffle#1714

Revert "Compiler version output"

---

.travis.yml

Since edge seems to be causing a segfault.

Use vyper beta instead of bleeding edge

---

packages/truffle-compile/profiler.js

Make method async to get rid of some indentation and to cause errors that occur in that block of code to not get swallowed up whole.

Fix profiler

---

packages/truffle-migrate/migration.js

Fix empty networks object in Migrations.json artifact

---

packages/truffle-compile-vyper/index.js
packages/truffle-compile/index.js
packages/truffle-reporters/reporters/migrations-V5/messages.js
packages/truffle-workflow-compile/index.js

Change logic slightly so certain text doesn't get printed when nothing was compiled

Reduce output when compilation is up to date already

---

packages/truffle-core/lib/testing/testrunner.js

Drop the first topic entry for the abi.decodeLog since it is an event signature and not an indexed data.
**Reason**
I have noticed that logged events have the indexed data shifted one topic behind.
```
Events emitted during test:
---------------------------
Transfer(_from: <indexed> 0xFC378dAA952ba7f163c4a11628f55a4df523b3EF (address), _to: <indexed> 0x0000000000000000000000000000000000000000 (address), _value: 147000 (uint256))
``` 
Instead of:
```
Events emitted during test:
---------------------------
Transfer(_from: <indexed> 0x0000000000000000000000000000000000000000 (address), _to: <indexed> 0x414eed0De746DA736aea2E700ca48CF6ae8544b3 (address), _value: 147000 (uint256))
```
As you can see the first `_from` value `0xFC378dAA952ba7f163c4a11628f55a4df523b3EF` is esentially the …

Fix non-anonymous events logging in testrunner

---

packages/truffle-db/src/workspace/schema.ts
packages/truffle-db/src/workspace/test/index.ts

Small change to change type of id from String to ID

String to ID

---

packages/truffle-decoder/lib/decode/stack.ts

This PR allows `msg.data` to be used as a mapping key and work properly.
When `msg.data` is used as a mapping key, a calldata pointer representing it *is* put on the stack; it has start 0 and length equal to the length of calldata.  However, presently, for two-word calldata pointers, we throw out the length word, and retrieve the length info from the previous calldata slot instead (for consistency).  Ordinarily this works fine, but for `msg.data`, this has a problem; we'd have to look before the beginning of calldata!
So, to fix this, decoding a calldata pointer from the stack of type `string` or `bytes` will now work by using the length info and then skipping straight to `decodeValue`, rather than throwing it out and proceeding to `decodeCalldata`.
Note that for dynamic-length arrays we …

Allow msg.data to work as mapping key

---

packages/truffle-migrate/index.js

This PR handles the case where a user has already deployed their truffle project to a given chain and decides to deploy to a new chain sharing the same `network_id`.
This is handled by checking if the Migrations code already exists on the chain being deployed to. If it isn't there, migrations proceed as expected.

Check for on-chain Migrations before deploying

---

packages/truffle-core/lib/templates/example.js

#1696 issue brought to attention @gnidan suggested creating a PR.

Add import as noticed in #1696

---

packages/truffle-hdwallet-provider/package.json
yarn.lock

Add @babel/core@^7.0.0-0 peer dependency for truffle-hdwallet-provider

---

packages/truffle-db/package.json
packages/truffle-db/src/artifacts/json/resolvers.ts
packages/truffle-db/src/artifacts/json/schema.ts
packages/truffle-db/src/artifacts/schema.ts
packages/truffle-db/src/artifacts/test/index.ts
packages/truffle-db/src/data/schema.ts
packages/truffle-db/src/data/utils.ts
packages/truffle-db/src/schema.graphql
packages/truffle-db/src/schema.ts
packages/truffle-db/src/workspace/pouch.ts
packages/truffle-db/src/workspace/schema.ts
packages/truffle-db/src/workspace/test/index.ts
packages/truffle-db/test/fixtures/Migrations.json
yarn.lock

This PR updates the truffle-db workspace to match the truffle-db data model. Specifically, contract, compilation, and contractConstructor were changed to represent the new data model correctly.

Update workspace new data model

---

packages/truffle-decoder/lib/interface/contract-decoder.ts

This PR makes two related changes to the contract decoder.  One is performance-related: The contract decoder now caches its storage and code requests to avoid repeating them.  (Although, its request for the contract's own code on startup is no longer used for any sort of caching.)  The other is that now, `state` and `variable` both begin by locking in the block number that will be used for all requests, so that if decoding happens just as a new block is mined, we don't decode an inconsistent state.  (If `state` is called, though, we don't bother refetching the code based on the block number; we assume `state` is being called on a block where the contract exists with its current code.  So the code is still used for caching in that sense.)
To lock in the block number, we check if the passed …

Add cache to contract decoder, and lock in block number at decoding start

---

packages/truffle-contract-schema/README.md
packages/truffle-contract-schema/package.json

Fix truffle-contract-schema readme link

---

package.json
packages/truffle-interface-adapter/.gitignore
packages/truffle-interface-adapter/lib/ethereum-overloads.ts
packages/truffle-interface-adapter/lib/index.ts
packages/truffle-interface-adapter/lib/quorum-overloads.ts
packages/truffle-interface-adapter/lib/web3-shim.ts
packages/truffle-interface-adapter/package.json
packages/truffle-interface-adapter/test/quorum-getBlock.test.ts
packages/truffle-interface-adapter/tsconfig.json
packages/truffle-interface-adapter/typings/ganache-core/index.d.ts
scripts/bootstrap.sh
yarn.lock

Since #1842 is taking longer than expected, I decided to make this PR to do the typescript port without the AxCore stuff for the interface adapter.
Added that `prepare` statement for you @gnidan ;)

Port the interface-adapter to typescript

---

packages/truffle-core/lib/testing/testrunner.js

Use the config mocha timeout if available

---

packages/truffle-workflow-compile/README.md
packages/truffle-workflow-compile/package.json
packages/truffle-workflow-compile/test/index.js
packages/truffle-workflow-compile/test/sources/SimpleStorage.sol

This PR updates `truffle-workflow-compile`'s documentation & adds a bit of code coverage. Also removes unused dependencies.

Update truffle-workflow-compile (mostly docs)

---

packages/truffle-contract/index.js

Add a version property to the truffle contract object.

Add version prop to truffle-contract

---

packages/truffle-compile/profiler.js

I was getting a reference error on this line. I think this is the right fix.

Fix reference error

---

packages/truffle-workflow-compile/README.md
packages/truffle-workflow-compile/package.json
packages/truffle-workflow-compile/test/index.js
yarn.lock

Updates `truffle-workflow-compile` tests to align with the reformat to migrations (#1955).

Internal improvement:  truffle-workflow-compile tests

---

packages/truffle-blockchain-utils/index.js
packages/truffle-blockchain-utils/package.json
packages/truffle-blockchain-utils/test/methods.js

Tiny bit of code coverage, `package.json` update & misc es6 stuff.

Internal improvement: truffle-blockchain-utils

---

packages/truffle/package.json

Reverts trufflesuite/truffle#1915

Revert "Remove solc-js as an NPM dependency"

---

packages/truffle-config/README.md
packages/truffle-config/index.js
packages/truffle-config/package.json
packages/truffle-config/test/methods.js

This PR adds some docs, coverage, & tidies up misc things (es6 code, package.json links, etc).

Internal improvement: truffle config (docs & coverage)

---

CONTRIBUTING.md

Add a note about the main entry point in Truffle to the contributing docs. This is, in my opinion, one of the more important first things to start understanding and learning about the way Truffle operates.

Edit contributing docs

---

packages/truffle-migrate/index.js

Check to see if the migrations folder exists and whether it has files before running migrations. Previously when running migrations without a migrations folder or with an empty migrations folder, it would throw an error. This performs a check beforehand to avoid this.

Bug fix: Edit migrations

---

packages/truffle-contract/index.js
packages/truffle-contract/lib/contract/constructorMethods.js
packages/truffle-contract/lib/utils.js
packages/truffle-contract/package.json
packages/truffle-contract/scripts/test.sh
packages/truffle-contract/test/contract/constructorMethods.js
packages/truffle-contract/test/index.js
packages/truffle-contract/test/networks.js

This PR attempts to make `lib/contract/constructorMethods.js` more maintainable and easier to reason about. During the process, some helper methods were created and added to `utils.js`, the `package.json` was tidied up a bit, and other misc changes were made.

Internal improvement: refactor lib/contract/constructorMethods.js in truffle-contract

---

packages/truffle-debugger/lib/controller/sagas/index.js

This PR fixes #2088. The problem was that not all of the stepping sagas had a check saying they should stop if they reached the end of the trace.  Now they do.

Fix hanging step commands

---

packages/truffle-artifactor/index.js
packages/truffle-artifactor/utils.js

Inspired by Code Climate, this lil PR aims to improve `truffle-artifactor`'s maintainability and reduce tech debt.
https://codeclimate.com/github/trufflesuite/truffle/compare/ccArt

Internal improvement: shorten save function (maintainability) 

---

packages/truffle-core/lib/commands/unbox.js
packages/truffle/test/scenarios/commands/unbox.js

This PR modernizes & removes deprecated code from `lib/commands/unbox.js`, also adds a bit more coverage.

Internal improvement: Tidy up unbox command & add some coverage

---

packages/truffle-box/lib/utils/index.js
packages/truffle-box/lib/utils/unbox.js
packages/truffle-box/package.json
packages/truffle-box/test/utils-index.js
packages/truffle-box/test/utils-unbox.js
yarn.lock

This PR modernizes & updates the `truffle-box/lib/utils` files to minimize callbacks. Adds `request-promise-native` as a dep and streamlines truffle box repo verification. Also adds some code coverage.

Internal improvement: Refactor truffle-box/utils & add some coverage

---

packages/truffle-artifactor/package.json
packages/truffle-contract/package.json
packages/truffle-core/package.json
packages/truffle-debugger/package.json
packages/truffle-deployer/package.json
packages/truffle-environment/package.json
packages/truffle-hdwallet-provider/package.json
packages/truffle-interface-adapter/package.json
packages/truffle-provider/package.json
packages/truffle/package.json
yarn.lock

* truffle: 2.5.5 →  2.5.7
* truffle-artifactor: 2.5.5 →  2.5.7
* truffle-contract: 2.5.5 →  2.5.7
* truffle-core: 2.5.5 →  2.5.7
* truffle-debugger: 2.5.5 →  2.5.7
* truffle-deployer: 2.5.5 →  2.5.7
* truffle-environment: 2.5.5 →  2.5.7
* truffle-hdwallet-provider: 2.5.5 →  2.5.7
* truffle-interface-adapter: 2.5.5 →  2.5.7
* truffle-provider: 2.5.5 →  2.5.7

Upgrade dependency: ganache-core@2.5.7

---

packages/truffle-box/box.js
packages/truffle-box/lib/config.js
packages/truffle-box/test/sandbox.js
packages/truffle-core/test/config.js
packages/truffle-core/test/lib/commands/compile.js
packages/truffle-core/test/lib/create.js
packages/truffle-core/test/migrate.js
packages/truffle-core/test/npm.js
packages/truffle-core/test/profiler.js
packages/truffle-debugger/test/helpers.js
packages/truffle/test/scenarios/cyclic_dependencies/compiles.js
packages/truffle/test/scenarios/happy_path/happypath.js
packages/truffle/test/scenarios/solidity_testing/solidityTests.js
packages/truffle/test/scenarios/typescript_testing/typescriptTests.js

This PR makes the `Box.sandbox` method async and adds some code coverage. Tests using `sandbox()` updated where necessary. Also modernizes `lib/config.js` in `truffle-box`. 
**Breaking change to truffle-box**

Internal improvement: Convert `truffle-box` sandbox() from callback to promise

---

packages/truffle-artifactor/package.json
packages/truffle-config/package.json

Upgrade lodash in two packages to solve security vulnerability

Upgrade lodash dependency

---

packages/truffle-core/lib/console.js

This PR relates to #2157 
Also, thanks to @gnidan for quick comments :)
I set the branch somehow complicated so I just removed the fork and made the new one 👍 so that I can submit two separate PRs.

Add `accounts` global to truffle console

---

packages/truffle-core/lib/testing/deployed.js

Fix for https://github.com/trufflesuite/truffle/issues/2225

Change regex to avoid clashing with hex 0a5b0 etc.

---

packages/truffle-compile/compilerSupplier/loadingStrategies/Docker.js

Add --rm flag to docker run solc commands to be removed on exits

---

packages/truffle-hdwallet-provider/src/index.js
packages/truffle-hdwallet-provider/test/urlValidatation.js

Ensure that HDWalletProvider will throw an error when the url provider is without slash / slashes

---

packages/truffle-contract/lib/utils.js

feat(truffle-contract/utils): define tx_params

---

.travis.yml
packages/truffle/scripts/test.sh
packages/truffle/test/scenarios/genesis_time/genesis_time_invalid.js
packages/truffle/test/scenarios/genesis_time/genesis_time_undefined.js
packages/truffle/test/scenarios/genesis_time/genesis_time_valid.js
packages/truffle/test/scenarios/library/api.js
packages/truffle/test/scenarios/migrations/quorum.js
packages/truffle/test/sources/migrations/quorum/truffle-config.js
scripts/ci.sh

This PR sets up a preliminary CI job to run truffle scenario tests against Quorum.
Also tags a few misc test cases as non-geth CI tests.

Internal improvement: Quorum CI job

---

packages/truffle-core/lib/commands/develop.js

Document the previously hidden `--log` option

Internal improvement: Add --log option to develop command file

---

packages/truffle-contract-schema/index.js
packages/truffle-contract-schema/test/networks.js

https://github.com/trufflesuite/truffle/issues/2224

networks.{id}.events is empty at build file

---

packages/truffle-core/lib/commands/compile.js

Instantiate compilerSupplier in listVersions method and use the promise interface of truffle-workflow-compile

Internal improvement: Make small optimization for truffle compile

---

packages/truffle-artifactor/package.json
packages/truffle-compile/package.json
packages/truffle-config/package.json
packages/truffle-contract-schema/package.json
packages/truffle-contract/package.json
packages/truffle-contract/test/cloning.js
packages/truffle-core/package.json
packages/truffle-workflow-compile/package.json
packages/truffle/package.json
yarn.lock

Co-authored-by: barakman barakman@yahoo.com

Bump solc version to 0.4.26

---

packages/reporters/reporters/migrations-V5/messages.js
packages/reporters/reporters/migrations-V5/reporter.js
packages/truffle-core/lib/commands/migrate.js
packages/truffle-migrate/index.js
packages/truffle-migrate/migration.js
packages/truffle/test/scenarios/migrations/describe-json.js
packages/truffle/test/scenarios/migrations/describe.js

This PR adds a `--describe-json` flag for `truffle migrate` which outputs a standardized format (a JSON object with `status` and `data` fields) for the migration status. This is primarily to make the migration output to be machine-readable/consumable.
Here is an example output for the `metacoin` project:
```
$ truffle-dev migrate --describe-json --reset
Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.
MIGRATION_STATUS:{"status":"preAllMigrations","data":{"dryRun":false,"migrations":[{"file":"/home/mike/work/truffle/metacoin/migrations/1_initial_migration.js","number":1,"isFirst":true,"isLast":false,"dryRun":false,"interactive":false},{"file":"/home/mike/work/truffle/metacoin/migrations/2_deploy_contracts.js","number":2,"isFirs …
```

Add `migrate --describe-json` to output machine-readable migration information

---

README.md

Give people a way to know about our Spectrum community space.

Internal improvement: Add spectrum badge to the readme

---

packages/environment/package.json
packages/interface-adapter/package.json

Add publishConfig prop to...
1. @truffle/environment
2. @truffle/interface-adapter

Internal improvement: Update package.json

---

packages/contract-schema/spec/contract-object.spec.json

Remove allOfs in contract object properties so this schema can work with Truffle DB

Remove unnecessary allOfs in contract object properties

---

packages/box/package.json
yarn.lock

Add missing inquirer package to @truffle/box and update yarn.lock

Dependency update: Add missing inquirer package

---

packages/compile-solidity/test/test_JSparser.js
packages/compile-solidity/test/test_parser.js

As stopgap solution to get build passing

Skip failing tests

---

packages/artifactor/package.json
packages/blockchain-utils/package.json
packages/box/package.json
packages/code-utils/package.json
packages/interface-adapter/package.json
yarn.lock

Updates packages:
- `@truffle/artifactor`
- `@truffle/blockchain-utils`
- `@truffle/box`
- `@truffle/code-utils`
- `@truffle/interface-adapter`
(Leaving the decoder+friends out of it for now because I don't want to make the merge conflicts worse)

Upgrade typescript to ^3.6.3

---

package.json

Adds prettifying of `.ts `files to project git hook.
🕺 
Inspired by @MrRefactoring .

Internal improvement: prettify .ts files

---

packages/hdwallet-provider/package.json
packages/hdwallet-provider/src/index.ts
yarn.lock

Downgrade ethereumjs-tx as the newer version was not working with geth chains (Rinkeby).

Bug fix: Downgrade dependency for Geth compatibility

---

packages/hdwallet-provider/src/index.ts
packages/hdwallet-provider/typings/web3-provider-engine/index.d.ts

Added missed `callback` argument (#2431)

@truffle/hdwallet-provider: send method fixed

---

packages/hdwallet-provider/src/index.ts
yarn.lock

I replaced `apply` with `call`, as this is a more performance solution
You can find confirmations [here](https://jsperf.com/call-apply-segu) or search for: `call vs apply performance`

@truffle/hdwallet-provider: improving performance

---

packages/expect/package.json
packages/hdwallet-provider/package.json
packages/solidity-utils/package.json

Update email addresses in package.jsons

Bug fix?: Update emails

---

packages/codec/lib/compiler/utils.ts
packages/codec/lib/format/values.ts
packages/decoder/lib/decoders/contract.ts
packages/decoder/lib/index.ts

This PR just updates or adds some comments and docstrings.

Update various comments/docs

---

packages/decoder/lib/index.ts

Categorize decoder funcs

---

packages/codec/lib/common/types.ts
packages/codec/lib/core.ts
packages/codec/lib/encode/abi.ts
packages/codec/lib/encode/key.ts
packages/codec/lib/format/elementary.ts
packages/codec/lib/format/errors.ts
packages/codec/lib/format/index.ts
packages/codec/lib/format/types.ts
packages/codec/lib/format/values.ts
packages/codec/lib/types.ts

This PR adds a lot of categories.  It also adds (perfunctory) docstrings to everything that got a category to avoid empty white boxes.
Part of #2505.

Add lots of categories and (perfunctory) docstrings

---

packages/decoder/test/contracts/ShadowTest.sol
packages/decoder/test/migrations/2_deploy_contracts.js
packages/decoder/test/test/shadow-test.js
packages/decoder/test/truffle-config.js

I decided the functionality to fetch variables by name or qualified name could use some testing, so I added some.

Add tests of getting variable by name or qualified name

---

packages/codec/lib/format/utils/inspect.ts

This PR makes a pointless change to the codec docs to test the autodeploy system as requested by @gnidan!
(I didn't have enough time tonight to do the next real thing I had planned, sorry.)

Dummy PR to test codec docs autodeploy

---

packages/core/lib/test.js

Suppress some logging that was accidentally left in for --runner-output-only
Mistake on https://github.com/trufflesuite/truffle/pull/2527

Patch --runner-output-only PR

---

packages/artifactor/package.json
packages/contract/package.json
packages/contract/test/deploy.js
packages/contract/test/errors.js
packages/contract/test/methods.js
packages/core/package.json
packages/debugger/package.json
packages/deployer/package.json
packages/deployer/test/errors.js
packages/environment/package.json
packages/hdwallet-provider/package.json
packages/provider/package.json
packages/truffle/package.json
yarn.lock

* @truffle/artifactor: 2.7.0 →  2.8.0
* @truffle/contract: 2.7.0 →  2.8.0
* @truffle/core: 2.7.0 →  2.8.0
* @truffle/debugger: 2.7.0 →  2.8.0
* @truffle/deployer: 2.7.0 →  2.8.0
* @truffle/environment: 2.7.0 →  2.8.0
* @truffle/hdwallet-provider: ^2.8.0 →  2.8.0
* @truffle/provider: 2.7.0 →  2.8.0
* truffle: 2.7.0 →  2.8.0

Upgrade dependency: ganache-core@2.8.0 

---

packages/interface-adapter/lib/interface-adapter.ts
packages/interface-adapter/lib/web3-interface-adapter.ts
packages/reporters/reporters/migrations-V5/reporter.js

Continuation of #2473 that implements Step 2 for `getBalance` as outlined [here](https://gist.github.com/gnidan/a55bbec28800f64d487054be18730691#file-step2-ts).

Internal improvement: From Web3Shim to InterfaceAdapter – Step Two: getBalance

---

.nycrc

~Let's see what happens...~
Cool, looks like this is ready.

Internal improvement: add @truffle/debugger to code coverage report

---

packages/contract/.gitignore
packages/truffle/.gitignore

Improves local DX.
No longer need to specifically ignore `@truffle/contract`'s `dist` & `truffle`'s  `build` folders.

Internal improvement: improve ag/grep search results

---

packages/core/lib/console.js
packages/core/lib/package.js
packages/core/lib/test.js
packages/environment/environment.js
packages/interface-adapter/lib/adapter/types.ts
packages/interface-adapter/lib/adapter/web3/index.ts
packages/migrate/migration.js

Continuation of #2473 that implements Step 2 for `getAccounts` as outlined [here](https://gist.github.com/gnidan/a55bbec28800f64d487054be18730691#file-step2-ts).

Internal improvement: From Web3Shim to InterfaceAdapter – Step Two: getAccounts

---

packages/core/lib/testing/soliditytest.js

This could still be working when bundled, so maybe it's just an internal improvement.

Internal improvement: ensure proper decoding of solidity unit test event logs

---

packages/resolver/fs.js

Converts `forEach` to `for...of`.
Resolves #2176.

Fix for truffle testing resolver bug

---

packages/core/lib/commands/migrate.js

Enhancement: add goerli network id to the migrations network whitelist

---

.travis.yml
scripts/ci.sh

Internal improvement: Add Colony E2E CI Job

---

README.md
package.json

Internal improvement: use workspace dependency lerna when bootstrapping

---

packages/contract/lib/utils/index.js

Fix: update require path for browser bunding

---

packages/contract-schema/typings/index.d.ts
packages/deployer/package.json
packages/interface-adapter/lib/adapter/types.ts
packages/interface-adapter/lib/index.ts
packages/interface-adapter/test/fabric-evm-getId.test.ts
packages/interface-adapter/test/quorum-getBlock.test.ts
yarn.lock

Also pins `@ensdomains/resolver` to v0.1.9.

Internal improvement: fix import/export typings bug

---

packages/debug-utils/package.json
yarn.lock

Looks like I ended up doing one tiny piece of work over the break. :)

Update hljs-sol to 1.0.10 for Solidity 0.6.0

---

.gitignore

Ignore persisted DB in Truffle DB tests

---

packages/core/lib/commands/test/index.js

Reverts trufflesuite/truffle#2691
#2733

Revert "Correctly disable VM errors for `truffle test`'s ganache-core"

---

scripts/ci.sh

Woops, looks like I left this out of #2731 .

Internal improvement: downgrade vyper for coverage job

---

packages/debugger/test/ast.js
packages/debugger/test/context.js
packages/debugger/test/data/calldata.js
packages/debugger/test/data/codex.js
packages/debugger/test/data/decoding.js
packages/debugger/test/data/function-decoding.js
packages/debugger/test/data/global.js
packages/debugger/test/data/ids.js
packages/debugger/test/data/more-decoding.js
packages/debugger/test/endstate.js
packages/debugger/test/evm.js
packages/debugger/test/helpers.js
packages/debugger/test/load.js
packages/debugger/test/precompiles.js
packages/debugger/test/reset.js
packages/debugger/test/solidity.js

This PR updates the debugger tests to Solidity 0.6.1.

Update debugger tests to Solidity 0.6.1

---

packages/truffle-db/src/helpers/generateId.ts
packages/truffle-db/src/workspace/pouch/databases.ts

(Waiting on #2750) 
This PR also changes the behavior of ID fields to omit nully values

Use generateId helper in workspace

---

packages/truffle-db/src/loaders/artifacts/index.ts
packages/truffle-db/src/loaders/artifacts/test/index.ts
packages/truffle-db/src/loaders/queries/index.ts
packages/truffle-db/src/loaders/queries/nameRecords.ts
packages/truffle-db/src/schema.graphql
packages/truffle-db/src/schema.ts
packages/truffle-db/src/workspace/definitions.ts
packages/truffle-db/src/workspace/index.ts
packages/truffle-db/src/workspace/schema.ts
packages/truffle-db/src/workspace/test/contractInstance.spec.ts
packages/truffle-db/src/workspace/test/nameRecord.graphql.ts
packages/truffle-db/src/workspace/test/nameRecord.spec.ts
packages/truffle-db/src/workspace/test/network.graphql.ts
packages/truffle-db/src/workspace/test/network.spec.ts
packages/truffle-db/types/stub.d.ts

(Waiting on #2751)
(This is @fainashalts's code, pulled from #2715)

Add NameRecord resource to Truffle DB

---

packages/truffle-db/src/schema.graphql
packages/truffle-db/src/workspace/definitions.ts
packages/truffle-db/src/workspace/index.ts
packages/truffle-db/src/workspace/schema.ts
packages/truffle-db/src/workspace/test/projects.graphql.ts
packages/truffle-db/src/workspace/test/projects.spec.ts
packages/truffle-db/types/stub.d.ts

(This was taken from @fainashalts's work in #2715)

Add Project resource to Truffle DB

---

packages/artifactor/package.json
packages/contract/package.json
packages/contract/test/deploy.js
packages/contract/test/errors.js
packages/core/package.json
packages/debugger/package.json
packages/deployer/package.json
packages/deployer/test/errors.js
packages/environment/package.json
packages/hdwallet-provider/package.json
packages/interface-adapter/package.json
packages/provider/package.json
packages/truffle/package.json
yarn.lock

Reverts trufflesuite/truffle#2758.
Sorry @haltman-at !

Revert "Upgrade dependency: ganache-core@2.9.1"

---

packages/compile-ligo/index.js
packages/contract-schema/package.json
packages/contract/package.json

See commits! Path issues! Workarounds! Windows! \o/

[WIP] Tezos development on Windows! 

---

packages/workflow-compile/new/index.js

Ensures `contracts_build_directory` & `compilerInfo` is output on successful compilations.

Fix: Hook up new workflow-compile interface to use @truffle/events

---

packages/compile-ligo/index.js
packages/compile-ligo/test/sources/LigoContract3.religo
packages/compile-ligo/test/test_compiler.js
packages/contract-sources/index.js

- Add .religo as a valid contract file ext
- add test case & dummy ReasonLIGO contract

Feature: Implement support for ReasonLIGO contracts

---

packages/contract/lib/contract/constructorMethods.js

- Replace logic for accessing a contract's storage schema.
- Leverage taquito's michelson encoder.
- Contract storage schema now accessible pre-deployment in
addition to post-deployment.

Enhancement: Enhance storageSchema TruffleContract getter

---

packages/core/lib/testing/soliditytest.js

Yay for Google's Closure Tools!

Fix: Address constant reassignment of solcVersion

---

packages/migrate/index.js
packages/migrate/migration.js

- try/catch require's of Migrations.sol in
@truffle/migrate to ignore non-existence of
Migrations artifact
- adjust misc code accordingly

Make Migrations contract optional

---

packages/compile-ligo/index.js

Two important changes: 
1. Normalize all paths, then construct VM paths from the normalized versions. Also, don't use process.env.PWD, because it's not available in cmd/Powershell. 
1. Use `spawn()` instead of `exec()` to handle escaping arguments. I didn't actually test that this was required, but as you can see in [the docs](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options), `spawn()` takes care of OS-specific escaping. Ain't nobody got time for anything less.

Make it work on Powershell/cmd, and still work in Git Bash.

---

packages/core/lib/commands/init.js

Very straightforward. New box is here! https://github.com/truffle-box/tezos-bare-box

Point to the Tezos bare box on truffle init

---

packages/hdwallet-provider/package.json
yarn.lock

Fix: Add @types/web3 as a devDep of @truffle/hdwallet-provider

---

packages/core/lib/debug/interpreter.js

Oops, sorry, one more.  Forgot to test breakpoints.  Fixed now.

Prevent problems with breakpoints when location unknown

---

packages/contract/package.json
packages/interface-adapter/package.json
yarn.lock

Upgrade taquito dependency:
* @truffle/contract: 6.1.0-beta.0 -->  6.1.1-beta.0
* @truffle/interface-adapter: 6.1.0-beta.0 -->  6.1.1-beta.0
Link to taquito release notes: https://github.com/ecadlabs/taquito/releases/tag/6.1.1-beta.0

Upgrade dependency: @taquito/taquito@6.1.1-beta.0

---

packages/truffle/test/scenarios/migrations/errors.js

Differentiates geth & ganache behavior when transacting with insufficient funds.

Internal improvement: Adjust test case for GETH job

---

scripts/ci.sh

- Runs basic integration test against `tezos-smartpy-example` box

Internal Improvement: Add `tezos-smartpy-example` to `TEZOS` CI job

---

packages/core/lib/commands/unbox.js
scripts/ci.sh

- Also default `truffle unbox` to `tezos-bare-box`

Internal improvement: Add extra script steps for testing tezos-bare-box

---

packages/contract/package.json
packages/interface-adapter/package.json
yarn.lock

* @truffle/contract: 6.1.1-beta.0 →  6.2.0-beta.0
* @truffle/interface-adapter: 6.1.1-beta.0 →  6.2.0-beta.0

Dependency upgrade: @taquito/taquito@6.2.0 beta.0

---

packages/truffle/test/scenarios/commands/deploy.js
scripts/ci.sh

- Remove deprecated `--override.istanbul` flag
- Simplify a scenario test (`fail` is not defined lolz)

Internal improvement: Fix `geth` job

---

scripts/ci.sh

Internal improvement: Fix `quorum` job

---

packages/core/lib/repl.js

Reverts trufflesuite/truffle#2972

Revert "Update repl.js improve readability & performance."

---

scripts/ci.sh
scripts/geth.sh

Internal improvement: Pin geth to stable

---

packages/contract/lib/execute.js

So, turns out I forgot to test one of the most basic cases: An ordinary, successful transaction being sent.
Without the PromiEvent functionality, these never return!  Note this doesn't apply to deployments because `deploy` has extra code to handle the return values, so it's not relevant.  So, I added code here to actually return the receipt.  I had it only run if `promiEvent.debug` is set just in case it would interfere with existing functionality.  (Yeah I don't have a great idea how PromiEvent stuff works...)

Bug fix: Fix test hang when --stacktrace is used

---

packages/debugger/lib/data/sagas/index.js

It seems that when I revised the data saga to account for modifier depth, I accidentally missed a few spots.

Bug fix: Fix mapping key tracking in modifiers

---

packages/workflow-compile/legacy/index.js

Re-throw same error instead of wrapping in new Error

---

packages/blockchain-utils/index.ts
packages/compile-vyper/index.js
packages/compile-vyper/package.json
packages/contract/lib/utils/index.js
packages/contract/test/networks.js
packages/core/lib/networks.js
packages/core/lib/package.js
packages/core/package.json
packages/core/test/npm.js
yarn.lock

🅰️ This will be a breaking change for `@truffle/blockchain-utils`

Internal improvement: Get rid of more async library usage

---

packages/core/lib/testing/testsource.js

Related to the comments in https://github.com/trufflesuite/truffle/pull/2956

Eliminate redundant maps

---

packages/debugger/test/helpers.js

Spotted a duplicated line in the debugger tests.  Removing it.

Internal improvement: Remove duplicated line

---

packages/decoder/package.json

Found this unused devDependency, removed it.

Internal improvement: Remove unused @types/utf8 dependency from decoder

---

packages/truffle/test/scenarios/migrations/quorum.js

At @CruzMolina's suggestion since it's been timing out.

Internal improvement: Up timeout on quorum test

---

packages/preserve-to-filecoin/.gitignore
packages/preserve-to-filecoin/jest.config.js
packages/preserve-to-filecoin/lib/dealstates.ts
packages/preserve-to-filecoin/lib/filecoin.ts
packages/preserve-to-filecoin/lib/index.ts
packages/preserve-to-filecoin/lib/test/filecoin.ts
packages/preserve-to-filecoin/package.json
packages/preserve-to-filecoin/tsconfig.json
packages/preserve-to-ipfs/lib/index.ts
packages/preserve-to-ipfs/lib/ipfs.ts
yarn.lock

Tests require Textile's devenet to run.

Preserve to filecoin

---

packages/compile-vyper/index.js
packages/compile-vyper/test/sources/VyperContract1.vy
packages/compile-vyper/test/sources/VyperContract2.v.py
packages/compile-vyper/test/sources/VyperContract3.vyper.py
packages/compile-vyper/test/test_compiler.js
packages/core/lib/package.js

Reported by goncalo.sa in the consensys-truffle slack channel. Please ping him there to alert him after this fix is released.

Correct missing variable assignment

---

packages/hdwallet-provider/package.json
yarn.lock

* @truffle/hdwallet-provider: 15.0.0-0 →  15.0.0-2
Resolves #2852.

Upgrade dependency: @trufflesuite/web3-provider-engine@15.0.0-2

---

packages/resolver/lib/sources/npm.ts

There is currently an issue where Truffle will not find built artifacts in the node_modules folder during testing. This happens when an artifact is not imported in one of a user's contracts. See [this issue](https://github.com/trufflesuite/truffle/issues/1250). This PR searches the working directory `node_modules` folder when it cannot find a built file in the `build` folder.
closes https://github.com/trufflesuite/truffle/issues/1250

Bug fix: Correctly find built artifacts in node_modules

---

package.json
yarn.lock

Since @eggplantzzz recently updated the Typescript version, I thought I'd update the Prettier version to be compatible with all the latest TypeScript stuff (or however far ahead it's compatible, anyway).

Dependency update: Update Prettier version

---

packages/resolver/lib/sources/fs.ts

Fix incorrect return value on Windows path resolver

---

packages/debug-utils/index.js

This is a redone version of #3159, but outside `debugger` itself (it's in `debug-utils` instead); I wasn't really comfortable with it being in `debugger`.  Otherwise this is the same except for the exact invocation.  Also at @gnidan's suggestion I added more comments about how to use it.  Also, this time I didn't include the test, sorry.
Otherwise it's the same, so I'l copy in the rest of the PR text:
----
As requested by @kevinbluer and @seesemichaelj. I'd do a non-hacky way, but, well, as discussed I am busy and this was fast.
The code here is pretty straightforward, frankly. It does a full step-through, recording all the sources used, then reports them all out at the end. The horrible long-winded name is to remind you that it's a hack and should not be used for anything other than its …

Add redone transaction source function (still hacky)

---

packages/core/lib/test.js
packages/migrate/index.js

Spun out from #3171 and related to #3167.

Ensure `config` is an available global in test and migrate

---

packages/contract/lib/promievent.js

I am very confused how this ever worked.  It never caused a problem when I tested it.  Yet like... no way that should ever have worked, right...?
I think this should do away with #3186, but we'll need to check back and see.

Bug fix: Add missing const statement

---

packages/hdwallet-provider/package.json
yarn.lock

* @truffle/hdwallet-provider: 15.0.0-2 →  15.0.13-0
Step 1 towards resolving #3182.

Upgrade dependency: @trufflesuite/web3-provider-engine@15.0.13-0

---

packages/compile-michelson/.gitignore
packages/compile-michelson/README.md
packages/compile-michelson/package.json
packages/compile-michelson/scripts/test.sh
packages/compile-michelson/src/index.ts
packages/compile-michelson/tests/compile-michelson.test.ts
packages/compile-michelson/tsconfig.json
yarn.lock

Internal Improvement: Port @truffle/compile-michelson to TS

---

packages/codec/lib/abi-data/decode/index.ts

(Apologies for all the `prettier` changes; the actual changes -- ignoring `debug` calls -- is the addition of lines 79-83.)
This PR fixes a decoding error.  When decoding a calldata array `arr` of dynamic length, whose elements are in turn of dynamic length, the "length override" taken from the stack pointer to `arr` was applied not only to `arr`, but also to its elements.  Of course it was, because options are propagated through like that!  One way to handle this would be to deliberately stop the propagation of length overrides depending on circumstances, explictily overriding the override with `undefined`, but I took a different approach.  Instead, length overrides will simply be ignored unless you're directly decoding a pointer from the stack.  So, `arr` will have the length override …

Bug fix: Only apply length overrides when decoding from stack

---

.prettierrc.json

Update prettier to avoid trailing commas

---

packages/artifactor/index.ts
packages/artifactor/package.json
packages/artifactor/test/methods.js

Emit warnings when duplicate contract names are found during compilation

---

.travis.yml

- Bump Travis CI jobs to Node 10.x

Internal Improvement: Bump Travis CI jobs to Node 10.x

---

packages/core/lib/commands/exec.js
packages/require/require.js

Update exec to include the config as a global and slightly rework call to Require.exec.
Closes https://github.com/trufflesuite/truffle/issues/3221

Enhancement: Add config global to `truffle exec`

---

packages/interface-adapter/package.json

Internal Improvement: Fix @truffle/interface-adapter -> @truffle/provider -> @truffle/interface-adapter dependency cycle

---

packages/core/lib/commands/compile.js
packages/core/lib/commands/help.js

So that it doesn't appear in the help output

Mark --save-intermediate as internal

---

packages/hdwallet-provider/package.json
yarn.lock

* @truffle/hdwallet-provider: 15.0.13-0 →  15.0.13-1
Resolves #3110

Upgrade dependency: @trufflesuite/web3-provider-engine@15.0.13-1

---

packages/debugger/lib/data/sagas/index.js

This PR should finally get rid of that previously-irreproducible `ref` error (#2673, currently closed due to lack of repro).
The case where the assignment does not exist is now handled.  It's handled in two ways:
Firstly, we try a fallback method: We ask, could the base be a top-level state variable?  If so, we can look up its allocation to determine the base path.
Secondly, if that also fails, `fetchBasePath` now returns `null`, and the places that call it have been altered to check for this and bail out early if so.
I think all this mess really suggests we should switch to handling mapping keys the other way.  But that can come later...

Bug fix: Account for missing base path ref in data saga

---

packages/provisioner/package.json

A possible fix to #3279, the solution it's based in #3273

Fix @truffle/provisioner package.json

---

packages/db/package.json

Before 0.1.0 accidentally enters the world ;)

Use prerelease versioning for @truffle/db package

---

packages/core/package.json
packages/truffle/package.json

Remove other packages' dependencies on @truffle/db

---

packages/box/box.ts
packages/debugger/package.json
packages/debugger/test/ast.js
packages/debugger/test/context.js
packages/debugger/test/data/calldata.js
packages/debugger/test/data/codex.js
packages/debugger/test/data/decoding.js
packages/debugger/test/data/function-decoding.js
packages/debugger/test/data/global.js
packages/debugger/test/data/ids.js
packages/debugger/test/data/immutable.js
packages/debugger/test/data/more-decoding.js
packages/debugger/test/data/returnvalue.js
packages/debugger/test/data/yul.js
packages/debugger/test/endstate.js
packages/debugger/test/evm.js
packages/debugger/test/helpers.js
packages/debugger/test/load.js
packages/debugger/test/precompiles.js
packages/debugger/test/reset.js
packages/debugger/test/solidity.js
packages/debugger/test/stacktrace.js
packages/truffle/test/scenarios/solidity_testing/solidityTests.js
yarn.lock

As suggested by @gnidan, I've taken the parts of #3331 related to `@truffle/box` and the debugger tests and pulled them out into their own PR.  You can see the description there.

Internal improvement: Fix sandbox resolution, update debugger tests to 0.7.0

---

packages/debugger/lib/data/selectors/index.js

Solidity 0.7.0 removed the global `now` identifier, so this PR removes it from the debugger on 0.7.x.
Also, swapped cases of `{...variables, ...builtins}` to `{...builtins, ...variables}` as I figure it's a little safer.
Didn't add any tests; tested this manually.

Remove now identifier from debugger on Solidity 0.7.x

---

packages/db/src/schema.graphql
packages/db/src/workspace/schema.ts
packages/db/src/workspace/test/source.spec.ts

This pull request contains some small changes to the schema in order to line up better with the data model in the documentation.

Change some schema properties to match data model better

---

packages/truffle/scripts/analyze.sh

Change file name to be the correct file for analyze script.

Update name of webpack,config.js file in analyze script

---

README.md
packages/box/test/sources/mock-local-box/truffle-box.json
packages/compile-solidity/profiler/loadParser.js
packages/compile-solidity/run.js
packages/core/README.md
packages/core/lib/command.js
packages/core/lib/commands/create/templates/Test.sol
packages/core/lib/commands/init/initSource/truffle-config.js
packages/core/lib/package.js
packages/decoder/test/current/truffle-config.js
packages/decoder/test/legacy/truffle-config.js
packages/deployer/README.md
packages/truffle/README.md
packages/truffle/test/sources/install/init/truffle-config.js
packages/truffle/test/sources/migrations/fabric-evm/truffle-config.js
packages/truffle/test/sources/migrations/init/truffle-config.js
packages/truffle/test/sources/migrations/quorum/truffle-config.js
packages/truffle/test/sources/migrations/success/truffle-config.js

Fixes broken links throughout the docs, package JSONs and READMEs.

Replace framework with suite in URLs

---

packages/debugger/lib/data/sagas/index.js

This PR reorganizes the debugger's data saga somewhat to avoid the slew of globalish variables up front and to not make so many selector calls when they aren't needed.  Also, while I was at it, I changed a bunch of `let`s to `consts` and added some comments in some cases where I didn't do that.
See, currently, the data saga starts with a bunch of selector calls and variable declarations.  Not only is this basically making a bunch of globalish variables, but the unnecessary selector calls could potentially slow things down, too.
So, I've taken most of these calls and declarations and moved them to where they're actually used.  I did leave up front a few ones that are common enough that it would be inconvenient to move them below, but most of that clutter is now gone...
Anyway, the result …

Internal improvement: Reorganize data saga to defer selector calls and variable assignments

---

packages/abi-utils/lib/types.ts
packages/codec/lib/ast/utils.ts

- Update codec/ast/utils to define parametersToAbi as generic

Require EventParameters include indexed

---

.github/workflows/nodejs.yml

Internal improvement: Add Node 14.x GHA jobs

---

package-lock.json
package.json

Bump husky to ^4.3.0 and lint-staged to to ^10.4.2

Dependency update: Bump husky and lint-staged

---

packages/db/src/graphql/schema.ts

This PR extends the existing query for all resources of a given type to allow looking up multiple resources at once given a list of IDs.
Query syntax looks something like:
```graphql
query {
contracts(filter: { ids: ["0x..."] }) {
id
}
}
```

Allow querying @truffle/db for resources given a list of IDs

---

packages/db/src/pouch/databases.ts

... in case multiple identical inputs are given to the same add/update

Deduplicate mutated resources in @truffle/db

---

packages/debugger/lib/trace/sagas/index.js

When I added the constructor argument processing on transaction load, I didn't account for the possibility that a given `CREATE` might not have a corresponding return step.  (This can happen if e.g. the `CREATE` instruction itself fails, e.g. due to out-of-gas.)  This would cause a debugger crash.  This fixes that.

Bug fix: Fix debugger crash when a CREATE instruction fails

---

packages/source-fetcher/lib/common.ts
packages/source-fetcher/lib/etherscan.ts
packages/source-fetcher/lib/sourcify.ts

Real minor thing, quick addendum to #3559, I realized this info should probably also go in the error.

Internal improvement: Add fetcher name to InvalidNetworkError

---

packages/contract/lib/handlers.js
packages/provisioner/src/index.ts

related to https://github.com/trufflesuite/truffle/issues/2688

Enhancement: Allow users to disable the confirmation listener that web3 implements

---

packages/artifactor/index.ts
packages/migrate/Migration.js

So that networks and contract instances get saved in DB

Hook up `truffle migrate` to @truffle/db

---

packages/debug-utils/package.json
yarn.lock

Dependency update: Update @trufflesuite/chromafi version to update hljs version

---

packages/debugger/test/helpers.js

Distinct compilations were being combined.  I got rid of this, and also simplified the setup.  Debugger tests will now run directly off of compiler output.

Internal improvement: Avoid combining distinct compilations in debugger tests

---

packages/truffle/package.json

Add license property for Truffle package

---

packages/core/lib/commands/create/helpers.js

Even when you have a license listed in your project configuration it wasn't
being used for new contracts, with this small change the license listed in
config will be used.
How to see it working?
1. `truffle init someproject`
2. `cd someproject`
3. Edit `truffle-config.json` and add a key `license: "GPL"` or whatever
license you want to use.
4. `truffle create contract Contract`
5. `head -n1 contracts/Contract.sol` should show the new license.
In case the license is not present in the `truffle-config.json` file it will
check for it in the `package.json` file. The process to check this is the same
than the previously mentioned but writting the license in `package.json`.

Use license from config/package for new contracts

---

packages/resolver/lib/sources/truffle/Deployed.ts

Replace pragma versions differently depending on whether we have a single version or a range

Bug fix: Fix pragma version replacement for DeployedAddresses

---

packages/contract/README.md

constructor on line 141 was misspelled

Fix spelling error in README.md

---

packages/db/package.json

This hanging process was bothering me

Force-exit @truffle/db's jest when it finishes

---

packages/db/src/meta/pouch/adapters/base.ts

Instead of delegating to `workspace.find()` with no selector, since this existing approach doesn't seem to return complete information for all adapters. (I observed missing data against a running CouchDB)

Use Pouch's `allDocs` method for workspace.all()

---

packages/core/lib/console.js
packages/environment/environment.js

For people using Infura or another node that doesn't have unlocked accounts, the `eth_accounts` RPC method could result in an exception. Since one of the first things that Truffle does is get a list of unlocked accounts, this means that you have to set up HDWalletProvider or such just to do things like debug a transaction.
This PR catches these exceptions to delay the point of failure to situations that actually require being able to sign messages.
Note: this PR doesn't actually address those use cases at all, figuring that the existing opaque error in this situation is just as bad as any future opaque error that happens as a result. Assuming this is a low-impact downside, the **upside of this** is that you can debug mainnet transactions with an archive node without needing to specify a …

Allow `truffle debug` without a mnemonic

---

packages/db/src/resources/networks/index.ts

... as a minor convenience instead of Network.ancestors

Add Network.genesis query to @truffle/db

---

packages/db/src/resources/contracts.ts

- Fix for Contract.compilation, since it's optional
- Fix for Contract.processedSource, since compilation is optional

Fix possible undefined for Contract queries in @truffle/db

---

packages/workflow-compile/index.js

Oops; something musta rebased wrong

Fix another broken db `connect()`

---

scripts/ci.sh
scripts/geth.sh

Do not merge. This is just to see how CI behaves with this version of Geth.

Update version of Geth used

---

packages/artifactor/test/customoptions.js
packages/blockchain-utils/index.ts
packages/compile-vyper/test/test_compiler.js
packages/contract-tests/test/networkObject.js
packages/contract/lib/utils/index.js
packages/core/exec.js
packages/core/test/ethpm.js
packages/resolver/test/globalnpm.ts

#3849 I have renamed at appropiate files to camelCase. If any changes then please let me know.

Renamed snake_case to camelCase at desired files

---

packages/preserve-to-buckets/.gitignore
packages/preserve-to-buckets/README.md
packages/preserve-to-buckets/jest.config.js
packages/preserve-to-buckets/lib/clear.ts
packages/preserve-to-buckets/lib/connect.ts
packages/preserve-to-buckets/lib/index.ts
packages/preserve-to-buckets/lib/ipfs-adapter.ts
packages/preserve-to-buckets/lib/search.ts
packages/preserve-to-buckets/lib/upload.ts
packages/preserve-to-buckets/package.json
packages/preserve-to-buckets/scripts/test.sh
packages/preserve-to-buckets/test/buckets.fixture.ts
packages/preserve-to-buckets/test/buckets.test.ts
packages/preserve-to-buckets/test/utils/fetch.ts
packages/preserve-to-buckets/test/utils/preserve.ts
packages/preserve-to-buckets/truffle-plugin.json
packages/preserve-to-buckets/tsconfig.json
packages/preserve/lib/ConsoleReporter.ts
yarn.lock

- Connect with buckets using auth keys
- Clear existing bucket contents
- Upload files to the bucket
- Add a skipped test with production test
- Improve preserve error logging for thrown non-error objects

Implement @truffle/preserve-to-buckets

---

packages/db/src/project/index.ts

- Extract `populateNetworks` helper method
- Short-circuit when address does not exist

Stop populating network for undeployed artifacts in @truffle/db

---

packages/core/lib/commands/db/commands/query.js
packages/core/lib/commands/db/index.js

Note: this is pretty barebones, e.g. this does not yet support requests with variables (should it?)

Add initial `truffle db query <query>` command

---

README.md

Updating the language here to clarify that all PRs should be against `develop`, not `next`.

Update README to clarify what to PR against

---

packages/artifactor/package.json
packages/codec/package.json
packages/contract-tests/package.json
packages/contract/package.json
packages/core/package.json
packages/db/package.json
packages/debugger/package.json
packages/decoder/package.json
packages/deployer/package.json
packages/environment/package.json
packages/external-compile/package.json
packages/interface-adapter/package.json
packages/migrate/package.json
packages/provider/package.json
packages/reporters/package.json
packages/require/package.json
packages/source-fetcher/package.json
packages/source-map-utils/package.json
packages/truffle/package.json
yarn.lock

Web3 1.3.6 is out, so I updated all our web3 to web3 1.3.6.

Dependency update: Update web3 (and etc) to 1.3.6

---

packages/core/lib/debug/cli.js

Fix truffle debug badCompilations error

---

packages/db/package.json

`tsConfig` has been renamed to `tsconfig`

Fix deprecated ts-jest config

---

packages/events/defaultSubscribers/init.js

This PR adds instruction to help a developer after they created a truffle project with `truffle init` as discussed in #4041

add next steps for init command

---

packages/codec/lib/contexts/utils.ts

Addresses #4093.
This PR makes it so that, if a given contract is lacking compiler information, the decoder/debugger (this is handled purely in codec so it applies to both) will read it out of the bytecode if possible.
Starting in Solidity 0.5.9, the CBOR section of Solidity bytecode includes the version in the `solc` field.  For prerelease versions the version is given as a string; for release versions it's given as a 3-byte bytestring, with the bytes being the major, minor, and patch components of the version.
This PR makes it so that `normalizeContexts` will read this information from the bytecode and put it in the context if the context doesn't have it.  Note that it only affects contexts, not sources.  The `normalizeContexts` function might not seem like the most natural place to put …

Enhancement: Detect solc version from CBOR if absent in artifact

---

packages/compile-solidity/compilerSupplier/loadingStrategies/LoadingStrategy.js
packages/core/lib/command.js
packages/truffle/test/scenarios/migrations/unhandled-rejection.js
packages/truffle/test/sources/migrations/unhandled-rejection/contracts/Migrations.sol
packages/truffle/test/sources/migrations/unhandled-rejection/migrations/1_initial_migration.js
packages/truffle/test/sources/migrations/unhandled-rejection/truffle-config.js

This PR is to progress the conversation as per @gnidan

Also remove `unhandledRejection` to soljson wrapper

---

packages/core/lib/debug/external.js

Addresses #4096.
This PR fixes a problem with #3605.  Versions downloaded from Etherscan or Sourcify will have a fancy version string, but versions for use with Docker require just a simple version string (e.g., just `"0.8.4"`, not `"v0.8.4+commit.c7e474f2"`).  The format required is also different for prerelease versions of solc.
So, this PR fixes this as follows:
1. If you're using Docker and a release version of solc, the version string is now transformed appropriately.
2. If you're using Docker and a prerelease version of solc, we no longer use Docker for compiling the downloaded sources.  This is because performing a similar transformation for prerelease versions of solc turned out not to be possible.  This is for two reasons: (A) the version string we get from Etherscan or Sourcify …

Bug fix: Fix use of Docker with --fetch-external

---

packages/compile-solidity/package.json
yarn.lock

Attempts to address #4134... we'll see where exactly the tests fail.

Dependency update: Update solc/wrapper to 0.6.9

---

packages/core/lib/commands/init/initSource/truffle-config.js
packages/decoder/test/current/truffle-config.js
packages/decoder/test/legacy/truffle-config.js

since including secrets in plain text in files that might be committed to git is not great practice

remove dead infuraKey references

---

packages/core/lib/console.js
packages/truffle/test/scenarios/commands/develop.js
packages/truffle/test/sources/develop/contracts/Migrations.sol
packages/truffle/test/sources/develop/contracts/contract.sol
packages/truffle/test/sources/develop/snippets/helper.js
packages/truffle/test/sources/develop/truffle-config.js

1. Build truffle
1. Setup up test project
```console
reprod hotfix-require # or run in a clean directory
use-truffle-bundle     # use the bundled truffle
truffle init
echo 'module.exports.console = { require: [ {path: "./snippets/index.js"}]};' >> truffle-config.js
mkdir snippets
echo 'module.exports = { testFix: () => console.log("SUCCESS!") }' > ./snippets/index.js
truffle develop
```
1. You should be able to run `testFix()` from the develop console and it should return 'SUCCESS'
<details> <summary>:bug: output</summary>
```console
Scenarios
develop
1) should load snippets
0 passing (3s)
1 failing
1) Scenarios
develop
should load snippets:
Expected "Snippet Loaded" in output:
---truffle develop log---       Truffle Develop started at http://127.0.0.1:9545/
---truffle develop log--- …
```

Use original-require to import user modules

---

packages/artifactor/package.json
packages/codec/package.json
packages/contract-tests/package.json
packages/contract/package.json
packages/core/package.json
packages/db/package.json
packages/debugger/package.json
packages/decoder/package.json
packages/deployer/package.json
packages/environment/package.json
packages/external-compile/package.json
packages/interface-adapter/package.json
packages/provider/package.json
packages/reporters/package.json
packages/source-fetcher/package.json
packages/source-map-utils/package.json
packages/truffle/package.json
yarn.lock

Bump web3 to 1.5.1

---

packages/debug-utils/package.json
yarn.lock

Update for Solidity 0.8.7 highlighting.

Dependency update: Update highlightjs-solidity to 1.2.2

---

packages/hdwallet-provider/package.json
packages/hdwallet-provider/src/index.ts
yarn.lock

This change should be tested with Geth

Upgrade @ethereumjs/common to ^2.4.0 and @ethereumjs/tx to ^3.3.0

---

packages/hdwallet-provider/package.json
packages/hdwallet-provider/src/index.ts
yarn.lock

Reverts trufflesuite/truffle#4263

Revert "Upgrade @ethereumjs/common to ^2.4.0 and @ethereumjs/tx to ^3.3.0"

---

packages/provider/index.js

Just looking for a good first issue to go through the PR process the first time. 
https://github.com/trufflesuite/truffle/issues/3072

Enhancement: Add provider host to network connection error messages.

---

packages/truffle/test/scenarios/migrations/errors.js
packages/truffle/test/sources/migrations/error/migrations/10_migrations_funds_geth.js
packages/truffle/test/sources/migrations/error/migrations/6_migrations_funds.js
scripts/ci.sh
scripts/geth.sh

This updates the version of Geth used by the CI as web3 should be compatible with the stable version now.

Update version of Geth used in CI

---

packages/artifactor/package.json
packages/codec/package.json
packages/contract-tests/package.json
packages/contract/package.json
packages/core/package.json
packages/db/package.json
packages/debugger/package.json
packages/decoder/package.json
packages/deployer/package.json
packages/environment/package.json
packages/external-compile/package.json
packages/interface-adapter/package.json
packages/provider/package.json
packages/reporters/package.json
packages/source-fetcher/package.json
packages/source-map-utils/package.json
packages/truffle/package.json
yarn.lock

Straightforward dependency update.  Sorry for the merge conflicts this will cause. :P
~~Edit: I have no idea why this is failing CI.  We may want to report this to web3.~~

Dependency update: Update web3 to 1.6.0

---

README.md

There was an error made while trying to link to the github page for ganache-ui. This PR fixes the link.

Patch bad link

---

packages/core/lib/services/analytics/google.js

Link to issue: #4379 
I just add logging to setAnalytics function.

Report analytics status after setting them

---

packages/decoder/lib/ProviderAdapter.ts

... to account for a problem with MetaMask's injected provider, which assumes the very old semantics that `provider.send()` returns a synchronous response (not even via a callback!)

Account for the oldest kind of provider by favoring `provider.sendAsync()` over `provider.send()`

---

packages/core/lib/commands/config.js

This PR add command 'truffle config list' mentioned in #4379

Add command `truffle config list`

---

packages/source-map-utils/package.json
yarn.lock

Follow-on to #4504 due to me forgetting something.  Sorry, I took care of this in `debugger`, but I forgot we also had this in `source-map-utils`!  Now this should finally be all.

Dependency update: Update json-pointer to 0.6.1 (again)

---

packages/core/lib/debug/printer.js

Adding comment to specify the debug commands (p) and (;) use the
variable instructionLines.

Adding comment to specify the debug commands use the variable

---

packages/require/package.json

This dependency wasn't listed, thanks to @eggplantzzz for pointing this out!

Internal improvement: Add missing dependency to @truffle/require

---

packages/compile-common/package.json
packages/compile-vyper/package.json
packages/core/package.json
yarn.lock

colors
* @truffle/compile-common: ^1.4.0 → 1.4.0
* @truffle/compile-vyper: ^1.4.0 → 1.4.0
* @truffle/core: ^1.4.0 → 1.4.0

Update dependency: colors@1.4.0

---

packages/debugger/package.json
yarn.lock

Looks like I missed removing this package when doing #4547.  Well, it's unused, so let's finish what I started and remove it from the manifest!  This should also address several of the warnings that people are getting on installation. :)

Internal improvement: Remove unused package from debugger

---

packages/events/defaultSubscribers/migrate/Messages.js
packages/truffle/test/scenarios/migrations/empty.js
packages/truffle/test/sources/migrations/empty/.eslintrc.json
packages/truffle/test/sources/migrations/empty/migrations/1_initial_migration.js
packages/truffle/test/sources/migrations/empty/truffle-config.js

I've also added a regression test so it won't happen again.

Fixing issue #4408 (Empty migration results in total cost being printed as 0 undefined)

---

packages/events/defaultSubscribers/compile.js
packages/events/defaultSubscribers/migrate/Reporter.js
packages/events/defaultSubscribers/migrate/index.js

Addresses #4679 and other undefined in the migration output.

Remove junk from migration output

---

packages/dashboard/package.json

Add description to @truffle/dashboard package.json

---

.eslintrc.json
packages/db/.eslintrc.json

Ran into this with @cds-amal this week while working on unit tests. Husky will bark at you after making changes to existing tests without this change.

Add .eslintrc to truffledb

---

packages/core/cli.js

addresses https://github.com/trufflesuite/truffle/issues/4866

Update Node version check to check for versions < 12

---

packages/debugger/test/sourcemapping.js

I spotted this extra parenthesis and it was annoying me. :P

Internal improvement: Remove extra parenthesis from test description

---

packages/dashboard-message-bus/lib/message/types.ts

dashboard-message-bus:add analytics message type

---

packages/encoder/test/wrap-fc.test.ts

This PR fixes a problem that would occur in the encoder tests where it would occasionally fail due to tiny imprecisions in float-to-decimal conversions.
I don't know of any good way to ensure that the encoder gets these cases exactly right, so instead, I'm allowing a little bit of wiggle room.  Note that we only allow the wiggle room when passing in a `number` or `Number`; for other inputs, which are decimal to begin with, we require exact matching.  But when passing in a binary floating-point input, i.e. `number` or `Number`, I've allowed a tolerance of 10^-24.  That's probably as good as we're going to get, since I don't see a good way right now to make `encoder` handle floating-point inputs better.  Note that because we need to detect `Number`s as well as `number`s, we use lodash's …

Internal improvement: Allow a tiny amount of tolerance on float-to-decimal tests

---

packages/config/src/configDefaults.ts
packages/events/defaultSubscribers/dashboard.js
packages/provider/wrapper.js
packages/truffle/test/scenarios/migrations/migrate.js

Fixes that should've been included in #4875.

Fix dashboard subscriber

---

package.json

Enable prettier for `.jsx` and `.tsx`

---

packages/box/package.json
packages/compile-solidity/package.json
packages/dashboard-message-bus/package.json
packages/dashboard/package.json
packages/source-fetcher/package.json
yarn.lock

* @truffle/box: ^0.21.1 →  0.26.1
* @truffle/compile-solidity: ^0.21.1 →  0.26.1
* @truffle/dashboard: ^0.24.0 →  0.26.1
* @truffle/dashboard-message-bus: ^0.24.0 →  0.26.1
* @truffle/source-fetcher: ^0.21.1 →  0.26.1

Dependency update: bump axios to 0.16.1

---

packages/box/package.json
packages/core/package.json
packages/migrate/package.json
yarn.lock

* @truffle/box: ^7.0.0 →  8.2.2
* @truffle/core: ^7.0.0 →  8.2.2
* @truffle/migrate: ^7.0.0 →  8.2.2

Dependency update: bump inquirer to 8.2.2

---

packages/core/lib/commands/migrate/prepareConfigForRealMigrations.js
yarn.lock

In the [PR to remove the reporters package](https://github.com/trufflesuite/truffle/pull/4436) (I think), there was an error where a function name changed and the location where it is called was not. This PR updates the code to call the correct function.

Bug fix: correct error in function name

---

scripts/geth-accounts.js

Improve code, using a constant, init variable to improve readability and clean code

fix: Improve code and readability

---

packages/events/defaultSubscribers/dashboard.js

events: fix logspam from dashboard transaction spinner

---

CODEOWNERS

See [GitHub docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) for more info.

internal: auto-request reviews from dev team on non-draft PRs

---

packages/codec/lib/compilations/utils.ts

So, it looks like I accidentally broke the debugger's phantom stackframe system.  Again.  But really the problem wasn't with the phantom stackframe system... it was actually a problem with `shimContracts` which I accidentally exposed.
The real problem was that if multiple contracts were declared in the same source, but neither `sources` nor `files` was passed in, they wouldn't all get a primary source ID.  The first one to get processed would, and then the rest wouldn't.  This is because I overloaded the `index` return value from `getIndexToAddAt`.  I had it return a number to indicate "put this source at this index", and `null` to indicate "we already have this source, we don't need to add it".  But, actually, we need that index even if we already have the source, because it's used for …

Bug fix: Ensure all contracts get primary source id attached in shimContracts (fix phantom stackframes, again)

---

packages/debugger/package.json
yarn.lock

Hopefully this addresses #5074 and #5075??

Dependency update: Update reselect-tree to 1.3.7

---

packages/codec/lib/format/utils/inspect.ts

Since I missed this when I did this for the other inspectors

Add nonstandard inspect method to ContractInfoInspector

---

packages/core/lib/commands/init/initSource/truffle-config.js

This PR isn't trying to make it perfect, just a little bit better. :-)

improve default truffle-config.js readability

---

packages/source-fetcher/lib/etherscan.ts

Etherscan added sepolia!  Adding it to source-fetcher.

Enhancement: Add sepolia support to etherscan fetcher

---

packages/source-fetcher/lib/networks.ts
packages/source-fetcher/lib/sourcify.ts

Sourcify added more networks, updating!

Add support for more networks to sourcify source fetcher

---

packages/contract-tests/test/deploy.js
packages/debugger/test/ast.js
packages/debugger/test/context-vyper.js
packages/debugger/test/context.js
packages/debugger/test/data/calldata.js
packages/debugger/test/data/codex.js
packages/debugger/test/data/function-decoding.js
packages/debugger/test/data/global-const.js
packages/debugger/test/data/global.js
packages/debugger/test/data/helpers.js
packages/debugger/test/data/ids.js
packages/debugger/test/data/immutable.js
packages/debugger/test/data/more-decoding.js
packages/debugger/test/data/returnvalue.js
packages/debugger/test/data/yul.js
packages/debugger/test/endstate.js
packages/debugger/test/evm.js
packages/debugger/test/load.js
packages/debugger/test/precompiles.js
packages/debugger/test/reset.js
packages/debugger/test/sourcemapping.js
packages/debugger/test/stacktrace.js
packages/debugger/test/step.js
packages/debugger/test/txlog.js
packages/environment/environment.js

Update Ganache Options to use miner.blockGasLimit 

---

packages/truffle/test/scenarios/commands/compile.js
packages/truffle/test/scenarios/commands/test.js
packages/truffle/test/sources/toyProject/test/simpleTest.js

There is a test called "happy path" that seems out of place. It tests basic commands on a simple project. These seem more appropriately housed in the commands folder in "scenarios".

Internal improvement: Move several tests to a better location

---

packages/contract/lib/utils/index.js

Fix typo in utils/index.js

---

packages/dashboard-message-bus-common/lib/messages.ts
packages/dashboard/package.json
packages/dashboard/src/Dashboard.tsx
packages/dashboard/src/components/common/AnalyticsToggle.tsx
packages/dashboard/src/components/common/Popover.tsx
packages/dashboard/src/components/common/SettingsIcon.tsx
packages/events/defaultSubscribers/dashboard.js
yarn.lock

This PR adds some frontend components for asking users whether they are willing to enable Truffle's analytics. Some screenshots below (please note the language used, happy to reword it!):

Add dialogue to Truffle Dashboard to encourage friendly opt-in for better product plz

---

packages/debugger/package.json
packages/truffle/package.json
yarn.lock

bump webpack to 5.73.0
bump webpack-cli to 4.10.0

Dependency updates: Bump some webpack packages

---

packages/debug-utils/index.js
packages/debugger/lib/controller/selectors/index.js
packages/debugger/lib/data/selectors/index.js
packages/debugger/lib/evm/selectors/index.js
packages/debugger/lib/session/selectors/index.js
packages/debugger/lib/sourcemapping/selectors/index.js
packages/debugger/lib/trace/selectors/index.js

The first commit of this PR adds an explanatory comment that I noticed was missing while going over this code with @cds-amal.  The second updates the style of a bunch of comments for consistency.  Yeah that second one doesn't actually matter at all (or doesn't anymore now that the debugger docs are dead), but it was bugging me, so why not.
...also, `prettier` made some changes again.  Not sure why it keeps going back and forth on this matter, may have to look into that...

Internal improvement: Add a comment and update some others

---

packages/debugger/lib/web3/adapter.js

Just realized I left this comment in, it's wrong.  Removing it!

Internal improvement: Remove incorrect comment

---

.gitignore

Update `.gitignore` to match new contract dist folder

Internal improvement: Ignore browser-dist

---

packages/source-fetcher/lib/networks.ts
packages/source-fetcher/lib/sourcify.ts

Sourcify has added support for Optimistic Goerli, so adding it here!  (Etherscan should also be adding it in the coming weeks, but they haven't yet.)

Enhancement: Add optimistic goerli to sourcify fetcher

---

packages/debugger/lib/web3/sagas/index.js

Since the merge has now happened on Goerli, I figured I'd go ahead and do this!  Note that I'm adding this PR without tests, since Ganache doesn't yet support Paris and the debugger tests rely on Ganache.  But I can go back and modify tests appropriately once Ganache does support Paris!  (Indeed, I'll likely have to...)
Other than the question of what to do about `0x44` in disassembly, which I'm intending to continue to put off for now, the debugger should only need one update for the merge: Determining the value of `block.difficulty`.  See, `block.difficulty` compiles to the opcode `0x44`, which pre-merge returns the difficulty but post-merge will return the mix hash.  As such, I've altered the place where we get the difficulty so that it will use the mix hash if it's nonzero, and the …

Enhancement: Prepare debugger's `block.difficulty` reporting for the merge

---

packages/codec/lib/compilations/types.ts

Fix typo in compilations/types.ts

---

packages/debugger/lib/txlog/selectors/index.js

This PR fixes a bug in the computation of an event's status in the `flattedEvents` selector in txLog.
In order to determine whether a given event was succesfully emitted or whether it was reverted, we need to determine the status of the call it occurred in.  However the txLog doesn't include that information directly because it's implicit in the rest of the txLog.  Except, oops, extracting it is a bit more involved than I realized!
I assumed that return kinds `"return"` and `"selfdestruct"` mean status `true`, while `"revert"` and `"unwind"` meant status `false`.  Except, `unwind` doesn't necessarily mean status `false`, because it could also be triggered by an internal call performing a *successful* EVM return.  Oops!  So actually in the case of an `unwind`, to determine the return …

Fix computation of event status in flattedEvents

---

packages/contract/README.md

Fix typo in contract/README.md

---

packages/preserve/lib/preserve.ts

Fix typo in preserve.ts

---

packages/decoder/test/current/test/compatible-nativize.js

Bump the timeout of a flaky test to longer period.

[internal improvement] decoder: bump timeout

---

package.json
yarn.lock

lerna is now being maintained again, yay! Let's see what happens when I bump this...

bump lerna to ^5.6.1

---

README.md

**Reasoning**
Added comma to make sentence structure flow better. Truffle has 3 distinct value propositions, each requiring their own name space, or separation of concerns.
Removed a comma to make second sentence flow directly into the content. Since we begin with a preposition, and the opening is short, we can go right into what a user gets with Truffle.

added one comma, removed one comma

---

packages/contract-tests/test/methods.js

Fix typo in methods.js

---

packages/truffle/test/scenarios/commandRunner.js

I've used this technique to debug on CI and it's a pain to hack it up every time. This is an effort to save myself some typing, and share the technique. This PR enables setting the `DEBUG` environment when using `commandRunner`. This would be useful to enable and capture truffle `DEBUG` output in CI to examine `commandRunner`'s `stdout` and `stderr`
<details><summary>Expand to see sample output</summary>
```console
truffle:     truffle unbox [ @standalone ]
truffle:       when run without arguments
truffle: 	---truffle commandRunner stdout--- |	CommandRunner
truffle: 	---truffle commandRunner stdout--- |	execString: node /home/runner/work/truffle/truffle/packages/truffle/build/cli.bundled.js unbox --force
truffle: 	---truffle commandRunner stderr--- |	2022-10-28T16:02:50.758Z unbox { …
```

Instrument commandRunner

---

packages/artifactor/package.json
packages/codec/package.json
packages/compile-common/package.json
packages/compile-solidity/package.json
packages/compile-vyper/package.json
packages/contract/package.json
packages/db/package.json
packages/debug-utils/package.json
packages/debugger/package.json
packages/decoder/package.json
packages/deployer/package.json
packages/environment/package.json
packages/migrate/package.json
packages/profiler/package.json
packages/resolver/package.json
packages/source-map-utils/package.json
packages/truffle/package.json

works towards resolving https://github.com/trufflesuite/truffle/issues/5705

get rid of unnecessary gitHead property from package.jsons

---

packages/core/lib/console.js

Fix for weird truffle migrate formatting in truffle develop console

Fix: add workaround for weird migration format

---

packages/resolver/package.json
packages/truffle/package.json
yarn.lock

Bump [`@ganache/console.log` to v0.3.0](https://github.com/trufflesuite/ganache/tree/develop/src/chains/ethereum/console.log#readme). I also pinned the dependency, where it was using `^`, whoops.

Bump and pin @ganache/console.log

---

packages/abi-utils/package.json
packages/artifactor/package.json
packages/codec/package.json
packages/contract-tests/package.json
packages/contract/package.json
packages/core/package.json
packages/db-kit/package.json
packages/db/package.json
packages/debugger/package.json
packages/decoder/package.json
packages/deployer/package.json
packages/encoder/package.json
packages/environment/package.json
packages/events/package.json
packages/external-compile/package.json
packages/fetch-and-compile/package.json
packages/hdwallet-provider/package.json
packages/interface-adapter/package.json
packages/migrate/package.json
packages/provider/package.json
packages/require/package.json
packages/resolver/package.json
packages/source-fetcher/package.json
packages/source-map-utils/package.json
packages/test/package.json
packages/truffle/package.json
yarn.lock

Updates web3 to 1.8.2.  Hopefully this passes CI.

Update web3 to 1.8.2

---

.github/workflows/nodejs.yml

Disable slack actions until communication integration is resolved.

Disable slack actions

---

packages/expect/package.json
yarn.lock

Just updating this out-of-date dev dependency...

Bump tsd dev dependency to ^0.25.0

---

packages/abi-utils/package.json
packages/artifactor/package.json
packages/codec/package.json
packages/contract-tests/package.json
packages/contract/package.json
packages/core/package.json
packages/db-kit/package.json
packages/db/package.json
packages/debugger/package.json
packages/decoder/package.json
packages/deployer/package.json
packages/encoder/package.json
packages/environment/package.json
packages/events/package.json
packages/external-compile/package.json
packages/fetch-and-compile/package.json
packages/hdwallet-provider/package.json
packages/interface-adapter/package.json
packages/migrate/package.json
packages/provider/package.json
packages/require/package.json
packages/resolver/package.json
packages/source-fetcher/package.json
packages/source-map-utils/package.json
packages/test/package.json
packages/truffle/package.json
yarn.lock

Web3 updated, let's use it assuming no problems! :)

Update web3 to 1.10.0

---

packages/resolver/package.json
yarn.lock

PR to unbreak things, hopefully for the last time!

Update abi-to-sol to ^0.7.0

---

packages/fetch-and-compile/package.json

This dev dependency was missing!  Added it.

Add missing sinon dev dependency

---

packages/dashboard-hardhat-plugin/test/hardhat.test.ts

This test keeps timing out, upping it!
I may add more timeout increases to this PR if they come up.

Increase timeout on failing hardhat test

---

packages/dashboard-hardhat-plugin/test/hardhat.test.ts

These have been timing out a lot.  Increasing the timeouts further.
May also increase other timeouts if I see any (these aren't the only ones I've seen recently, just the most frequent).

Further increase timeouts on hardhat related tests

---

packages/core/test/lib/mnemonics/mnemonic.js
packages/debugger/test/data/calldata.js

This test has also been timing out a bit, upping it.  May add more increases to this PR if they seem necessary.
Edit: Also removed some unused imports due to the linter complaining.

Increase timeout on some more tests, remove needless imports

---

packages/dashboard/src/components/MantineGlobal.tsx

Improve dashboard debugger contrast

---

packages/core/cli.js

Didn't remember to get this as part of #6169.

Enforce new minimum node version

---

packages/environment/chain.js
packages/environment/develop.js
packages/environment/package.json
yarn.lock

deps(environment): node-ipc@9.2.1 -> @achrinza->node-ipc@9.2.7

---

packages/dashboard-hardhat-plugin/package.json

This snuck its way in here somehow, removing it.

Remove gitHead field that snuck its way in

---

yarn.lock

Partial dedupe.
Follow-up to:
- #6185

chore: dedupe devDependencies and library packages
