packages/codec/package.json
packages/contract-tests/package.json
packages/contract/package.json
packages/core/package.json
packages/db/package.json
packages/debugger/package.json
packages/deployer/package.json
packages/external-compile/package.json
packages/reporters/package.json
yarn.lock

This work used to be in #3448 but was moved to this branch due to problems merging/rebasing that couldn't be resolved.
Update web3 ancillary packages to 1.2.9

Dependency update: Bump ancillary web3 packages to 1.2.9

---

packages/db/bin/codegen.js
packages/db/src/db.ts
packages/db/src/definitions/types.ts
packages/db/src/loaders/commands/initialize.ts
packages/db/src/loaders/commands/names.ts
packages/db/src/loaders/resources/bytecodes/index.ts
packages/db/src/loaders/resources/compilations/index.ts
packages/db/src/loaders/resources/contracts/index.ts
packages/db/src/loaders/resources/nameRecords/index.ts
packages/db/src/loaders/resources/projects/index.ts
packages/db/src/loaders/resources/sources/index.ts
packages/db/src/loaders/schema/artifactsLoader.ts
packages/db/src/loaders/types.ts
packages/db/types/stub.d.ts

This would result in `interface Resource { id }` as well as `type Resource = Source | ...`, but I figure we don't need those; I'm just ignoring those from the output.

Remove I prefix from autogenerated @truffle/db DataModel types

---

packages/db/package.json
packages/db/src/db.ts

... importing as type only, to keep it as a devDep
Note: this causes a problem with our git hooks, so I had to do `--no-verify`. Looks like this is a problem with us being very behind for our `husky` dependency.

Replace custom config type in @truffle/db with @truffle/config

---

packages/db/src/db.ts
packages/db/src/loaders/commands/compile.ts
packages/db/src/loaders/commands/initialize.ts
packages/db/src/loaders/commands/names.ts
packages/db/src/loaders/resources/bytecodes/index.ts
packages/db/src/loaders/resources/compilations/index.ts
packages/db/src/loaders/resources/contracts/index.ts
packages/db/src/loaders/resources/nameRecords/index.ts
packages/db/src/loaders/resources/projects/index.ts
packages/db/src/loaders/resources/sources/index.ts
packages/db/src/loaders/run.ts
packages/db/src/loaders/types.ts
packages/db/types/stub.d.ts

This PR improves internals for @truffle/db loaders system by collecting existing patterns into first-class citizens. Mostly, this is two-part:
Pretty straightforward - this PR defines a new type `LoaderRunner`, and provides a constructor for obtaining such an value given a Truffle DB instance.
... to serve in place of the existing `Generator</* ... ugly params ... */>`s everywhere.
This type is generic, accepting between 0..2 type parameters as arguments:
```typescript
type Load<T = any, N extends RequestName | string = string>
```
These arguments function as follows:
- `T` represents value ultimately returned by the loader. Think: `const result: T = yield *generateResourceLoad()`
- `N` represents a specific kind of query or mutation defined by the data model. For loaders that only issue …

Unify @truffle/db loaders infrastructure

---

package.json

This new version of Husky warns us that we have `git add` in our Husky steps, which apparently is unnecessary (or at least unnecessary now).  Removing it to get rid of the warning.

Internal improvement: Remove git add from husky steps

---

packages/provider/wrapper.js

On web3 version 1.2.9, a websocket provider returns `false` as a value for `error` as noted in the issue below. On the previous version we used it returned `null`. This causes it to always throw in the post hook [here](https://github.com/trufflesuite/truffle/blob/47686d9dedc3174e3133b89b3da9f4cd1d2eae82/packages/provider/wrapper.js#L73). This allows for `error` to be `false` as well as `null`/`undefined`.
Fixes https://github.com/trufflesuite/truffle/issues/3464

Bug fix: Allow for `false` value in provider callback

---

packages/db/src/definitions/compilations.ts
packages/db/src/definitions/contracts.ts
packages/db/src/test/compilation.graphql.ts
packages/db/src/test/contract.spec.ts

This PR adds a lookup to Compilation to query all known contracts that specify that compilation ID.

Allow querying @truffle/db for compilation contracts

---

packages/resolver/lib/resolver.ts
packages/resolver/lib/sources/abi.ts
packages/resolver/lib/sources/index.ts
packages/resolver/package.json
packages/truffle/test/scenarios/commands/build.js
yarn.lock

Define ABI resolver source that extends from FS resolver source:
- Support only `resolve()` (explicitly exclude `require()`)
- Catch imports that end in `.json` or `.abi.json`
- Defer to `abi-to-sol` to generate Solidity source

Allow importing ABI JSON files in Solidity

---

packages/debug-utils/package.json
yarn.lock

This should prevent `husky` from being installed as a dependency rather than a dev dependency.  Thanks to @interfect for noticing the problem.

Dependency update: Upgrade @trufflesuite/chromafi version to 2.2.1

---

packages/compile-solidity/run.js

A crash of this form was pointed out by @interfect on Gitter.  Dunno why there's no AST, but looking at that can come later, I think; first I figure I'll just prevent the crash.

Bug fix: Check for missing AST in orderABI to prevent crash

---

packages/core/lib/debug/cli.js
packages/core/lib/debug/interpreter.js
packages/debugger/lib/debugger.js
packages/debugger/lib/session/index.js
packages/debugger/lib/session/selectors/index.js

**This PR is a breaking change to `@truffle/debugger`.**
As requested by @seesemichaelj, this PR makes it so that when a debugger method fails to load a transaction, it will throw an error, rather than succeeding and then exposing that error via another mechanism.  (That other mechanism is still there, though, and we still use it in the CLI to avoid having to change too much.)
So, now the debugger's `load()` method will throw an error if it fails to load a transaction, rather than having no effect (other than setting the error), and `Debugger.forTx()` will throw if it fails to load the transaction, rather than returning a debugger with no transaction loaded.

Bug fix: Make forTx and session.load throw on failure (breaking change!)

---

packages/db/src/db.ts
packages/db/src/loaders/resources/bytecodes/index.ts
packages/db/src/loaders/resources/compilations/index.ts
packages/db/src/loaders/resources/contracts/index.ts
packages/db/src/loaders/resources/nameRecords/index.ts
packages/db/src/loaders/resources/projects/index.ts
packages/db/src/loaders/resources/sources/index.ts
packages/db/src/loaders/run.ts
packages/db/src/loaders/types.ts

In addition to existing graphql requests, this PR allows the various loader generator functions to issue requests to either the DB schema or to a web3 provider.

Add support for web3 requests in @truffle/db loaders

---

packages/compile-common/src/shims/LegacyToNew.ts
packages/compile-common/src/shims/NewToLegacy.ts
packages/compile-common/src/types.ts
packages/contract-schema/index.js
packages/contract-schema/spec/contract-object.spec.json
packages/contract-schema/spec/network-object.spec.json
packages/contract/lib/contract/properties.js

Define property `db` on the ContractObject schema and the NetworkObject schema, allowing artifacts to contain relevant information about @truffle/db resources.
For example, artifacts will be expected to contain information something like:
```javascript
{
// ... rest of artifact ...
"db": {
"source": {
"id": "0xb63608deefb65ab93e8beebe5fb0397417c14dc54cb6cee5748e590d16ca5986"
},
"createBytecode": {
"id": "0x5ad957bd618157fd28fac3ffa61dd5275ff6de8494e32323029a31daef7ac56a"
},
"callBytecode": {
"id": "0x5ec2ead4cd51f88805b33da49c5ec4c57388992ae1f6492f8b17c38c5045d3d6"
},
"compilation": {
"id": "0x8534281c01751b9701e53e91fd97733f092ab2a1048f215fb4ced35f67b2644d"
},
"contract": {
"id": "0xa3d6cdfe66ead5c6843c5297248b79ab7090e8230247b2f8a9637ea7fd04b8c6"
}
}
}
```

Add @truffle/db contract correlation to artifacts

---

packages/db/src/definitions/contracts.ts
packages/db/src/index.ts
packages/db/src/pouch/databases.ts
packages/db/src/pouch/index.ts
packages/db/src/pouch/sqlite.ts

This PR is a bit of a grab-bag to catch some things I noticed during a round of acceptance testing:
- Make a few resolvers more robust in the face of null dereference errors
- Make sure the pouch databases properly wait until everything's initialized before allowing use (this fixes some race conditions)
- Pass the entire config object to the @truffle/db server to ensure there won't be any missing fields

Fix some minor errors in @truffle/db implementation

---

packages/core/lib/debug/printer.js
packages/debugger/lib/data/selectors/index.js
packages/debugger/test/data/global-const.js
packages/debugger/test/helpers.js

Solidity 0.7.4 added the ability to declare file-level constants.  This PR adds support for them in the debugger.
There are several parts to this.  Firstly, we need these to show up in `data.current.identifiers.refs`.  They show up fine in `data.current.identifiers` and `data.current.identifiers.definitions` (their scope is the whole `SourceUnit` they're declared in), but they're not in `data.current.identifiers.refs` because they never get processed for assignment by the data sagas.
So, we need them to show up there somehow.  I didn't think there was a great way of handling this via the assignments system (would they be assigned when you entered the relevant source...?) so I did it in what is maybe a hackier way: In `data.current.identifiers.refs`, any variables we can't locate an …

Add debugger support for file-level constants

---

packages/core/lib/debug/interpreter.js
packages/debug-utils/index.js
packages/debugger/lib/controller/actions/index.js
packages/debugger/lib/controller/reducers.js
packages/debugger/lib/controller/sagas/index.js
packages/debugger/lib/controller/selectors/index.js
packages/debugger/lib/session/index.js

This PR adds two new commands to the debugger CLI, `g` and `G`.  (Not sure if these are the best letters to use but I couldn't think of anything better; they can be changed, anyhow.)
The `g` command makes it so that all debugger commands can now step into generated sources, even if not starting from inside one, instead of just `;` and `c`.  The `G` command restores the default behavior, where you can only step into a generated source if you're already inside one or use `;` (or `c` and happen to hit a breakpoint inside one).
In order to implement this, the controller now has an extra bit of state, `stepIntoInternalSources`, and there's a new session method to set this state, `setInternalStepping`.  The `stepNext` method checks this state and, if it's on, it ignores its conditions about not …

Enhancement: Add debugger commands to turn internal sources on/off

---

packages/core/lib/debug/cli.js
packages/core/lib/debug/interpreter.js

This one's pretty simple.  Debugger CLI wouldn't error out if you tried to load an invalid transaction with `--fetch-external`.  Redid the startup so now it does.  Note I got rid of the reliance on the `session.status.isError` selector, although we still use that elsewhere.  Oh well.  Maybe we can redo that more thoroughly later.
Also, unrelated, but while I was at it I added a second commit changing `selectors.session` to just `session` everywhere in `interpreter.js` since that longhand version hasn't been necessary for a while.

Bug fix: Cause debugger CLI to error on invalid tx with --fetch-external

---

packages/db/src/graphql/schema.ts
packages/db/src/pouch/databases.ts

So that queries and mutations that accept a list of inputs thus return a list of outputs that one-to-one correspond to the inputs.
This allows filtering for lists of IDs, some of which may be unknown resources, and it allows mutating multiple resources, some of which may be repeated in the list or cause errors

Ensure isomorphism in @truffle/db input/output

---

packages/hdwallet-provider/README.md
packages/hdwallet-provider/src/constructor/Constructor.ts
packages/hdwallet-provider/src/constructor/types.ts
packages/hdwallet-provider/src/index.ts
packages/hdwallet-provider/test/provider.test.ts

- Implemented additional config option in constructor: `pollingInterval`
- specified in ms
- passed on to `Web3ProviderEngine` which uses the value for polling new blocks
- Added tests for both default and custom values
- Updated relevant section in docs for this
- Give developers a way to reduce "chattiness" over JSON-RPC
- In particular, needed for `rskj`, but would be just as useful for `geth`
- Partially resolves [#3948](https://github.com/trufflesuite/truffle/issues/3498)
- Related [stackoverflow question](https://stackoverflow.com/q/64656558/194982)

feat: configurable polling interval

---

packages/db/.madgerc
packages/db/package.json
packages/db/src/db.ts
packages/db/src/index.ts
packages/db/src/loaders/commands/compile.ts
packages/db/src/loaders/commands/index.ts
packages/db/src/loaders/commands/migrate.ts
packages/db/src/loaders/commands/names.ts
packages/db/src/loaders/index.ts
packages/db/src/loaders/project.ts
packages/db/src/loaders/resources/compilations/find.graphql.ts
packages/db/src/loaders/resources/compilations/get.graphql.ts
packages/db/src/loaders/resources/compilations/index.ts
packages/db/src/loaders/resources/contractInstances/index.ts
packages/db/src/loaders/resources/contracts/find.graphql.ts
packages/db/src/loaders/resources/contracts/get.graphql.ts
packages/db/src/loaders/resources/contracts/index.ts
packages/db/src/loaders/resources/nameRecords/get.graphql.ts
packages/db/src/loaders/resources/nameRecords/index.ts
packages/db/src/loaders/resources/networks/add.graphql.ts
packages/db/src/loaders/resources/networks/get.graphql.ts
packages/db/src/loaders/resources/networks/index.ts
packages/db/src/loaders/run.ts
packages/db/src/loaders/schema/artifactsLoader.ts
packages/db/src/loaders/test/index.ts
packages/db/src/meta/index.ts
packages/db/types/stub.d.ts

To bridge the gap between @truffle/db and Truffle at large.
This adds a top-level `const { Project } = require("@truffle/db")` that exposes methods corresponding to existing Truffle workflows.

Define project-based abstraction for loading Truffle stuff to @truffle/db

---

packages/deployer/src/deployment.js
packages/deployer/test/deployer.js

- Implemented additional config option in `TruffleConfig.networks.${networkName}`: `deploymentPollingInterval`
- specified in ms
- passed on to `deployer`
- Added tests for both default and custom values
- Give developers a way to reduce "chattiness" over JSON-RPC
- In particular, needed for `rskj`, but would be just as useful for `geth`
- Did **not** update relevant section in docs for this
- Neither `packages/config/README.md`, `packages/deployer/README.md`, nor `packages/migrate/README.md` contains network config related instructions.
- Will need to do separate PR to update the relevant docs published at `http://trufflesuite.com/docs/getting_started/migrations`
- Partially resolves [#3948](https://github.com/trufflesuite/truffle/issues/3498)
- Related [PR …

feat: configurable deployment polling interval

---

packages/db/src/graphql/schema.ts

Rather than specifying that it's just a regular property

Properly mark abstract getter as such

---

packages/debugger/lib/data/selectors/index.js

This selector is completely unused and refers to a piece of state that no longer exists; it will only ever return `undefined`.  It's from back when one had to wait for decoding to be ready.  That's no longer the case, and this should have been tossed long ago.

Internal improvement: Remove unused selector

---

packages/core/lib/debug/interpreter.js
packages/core/lib/debug/printer.js
packages/debugger/test/data/global-const.js

Just some simple improvements to the debugger CLI regarding the `g` and `G` commands.  These commands will now print a different message if you try to set the debugger to a state it's already in.  Also, the `?` command will now also print out whether generated sources are on or off.
...also while I was at it I fixed a typo in a test description. :P

Improve CLI printouts regarding generated sources

---

packages/core/lib/commands/create/index.js

At the moment you need to create contracts, migrations and tests one by one,
with this option you will be able to create all at once.
Please, note that I didn't add any test for this. Happy to do it if you think they are needed and you can point me in the right direction.

Allow `truffle create all [name]`

---

packages/debugger/lib/controller/sagas/index.js
packages/debugger/test/data/global-const.js

This PR fixes an issue where breakpoints in user sources could behave in a confusing way when generated sources are present.  It also fixes a second issue where node-based breakpoints could be hit multiple times without leaving the node.
Let's say you place a breakpoint on a line; hit `c` to get to that line; and then hit `c` again.  You would expect that the debugger doesn't stop on that line again until it's left it at least once.  However, if generated sources are present, then the debugger might appear to do just that -- the reason is that it *has* left it, by entering a generated source; but from the user's point of view, this looks wrong.
So, I added an additional check, to both node-based and line-based breakpoints.  If you started in a user source, and generated sources are turned …

Bug fix: Prevent confusing breakpoint behavior with internal sources (and fix node-based breakpoints)

---

packages/debug-utils/package.json
yarn.lock

I updated highlightjs-solidity with the new stuff from Solidity 0.7.5, this PR updates us to the newest version of it.

Dependency update: Update syntax highlighting for 0.7.5

---

.github/workflows/nodejs.yml

OK, I have very little idea if I've done this correctly.  People please look this over.
The idea -- as suggested by @gnidan a bit ago -- is that we should have a GHA job that checks that, if `yarn bootstrap` is run on the branch you're PRing, `yarn.lock` is not modified.  The idea being that if running `yarn bootstrap` modifies `yarn.lock`, you should have done that on your branch and committed the change.
That's what this PR attempts to do.  I have very little idea if I've done this correctly, as mentioned.  Hopefully at least the new job won't fail this very PR? :P  (Edit: It finally didn't! :) )
You can also see that I made the Slack notification depend on this new job in addition to the existing jobs.
Also, while I was at it, I removed the `push` trigger for the `truffle-db` branch, …

Internal improvement: Add GHA check that yarn.lock is not modified on bootstrapping

---

packages/debugger/package.json

This is what I need to do locally to keep things from breaking.  Intended so coverage can work in #3548.

Internal improvement: Add workaround to mocha-webpack problem to debugger test script

---

packages/debug-utils/package.json
yarn.lock

As best I can tell, none of the breaking changes in highlight.js 10.x are at all relevant to us.  Doing a quick test, it seems fine.  Addresses #3551.

Dependency update: Update highlight.js to 10.x

---

packages/contract-tests/test/enums.js
packages/contract-tests/test/sources/Example.sol
packages/contract/lib/contract/bootstrap.js
packages/contract/lib/contract/index.js

This PR (suggested by @gnidan) adds enums to contract objects.  Note that top-level enums are not covered; only enums defined in a contract.
So, let's say you define a contract `C` which defines `enum E { e0, e1, e2 }`.
Then now, the contract object for `C` will have a field `C.E` which is an object `{e0: 0, e1: 1, e2: 2}`.  So, you could write `C.E.e2` for `2`.  This allows one to pass in enums to functions that take them without needing to worry about their numerical value.
Also, all the enums will be under `C.enums`, so you could also do `C.enums.E.e2` for `2`.  (I made it so that `C.E` will only be created if it doesn't overwrite anything, so `C.enums.E` exists as a fallback way to get at `E`.)
Note, I set all this up in `bootstrap.js`.  This is... not really the right for place for …

Enhancement: Add enum objects to contract objects

---

packages/db/bin/codegen.js
packages/db/package.json
packages/db/src/resources/contracts.ts

Use @truffle/abi-utils to normalize the ABI JSON and define corresponding types for querying in @truffle/db

Enable querying @truffle/db ABIs for individual entries

---

packages/codec/lib/core.ts
packages/debugger/lib/controller/sagas/index.js
packages/debugger/lib/data/sagas/index.js
packages/debugger/lib/data/selectors/index.js
packages/debugger/lib/debugger.js
packages/debugger/lib/evm/selectors/index.js
packages/debugger/lib/session/index.js
packages/debugger/lib/session/reducers.js
packages/debugger/lib/session/sagas/index.js
packages/debugger/lib/session/selectors/index.js
packages/debugger/lib/solidity/selectors/index.js
packages/debugger/lib/trace/sagas/index.js
packages/debugger/lib/txlog/actions/index.js
packages/debugger/lib/txlog/reducers.js
packages/debugger/lib/txlog/sagas/index.js
packages/debugger/lib/txlog/selectors/index.js
packages/debugger/test/txlog.js

OK, here's the initial version of the visualizer!  Or rather the new debugger subsystem that generates a JS tree object that will be used as input to some sort of visualizer.  (Note: The form of this object will really need to be documented somewhere.  I suppose this PR writeup will serve as the initial place, but it should really live somewhere else later!)
This initial version contains decoding for function calls, return values, and related information.  It does not include gas information.  It also does not include events or storage writes.  Those will come in future versions of the visualizer.  (Storage writes in particular is going to take a while...)
You can get the transaction tree object by running the debugger to the end (not in light mode!) and viewing the selector …

Enhancement: The visualizer (v1: Function calls and such)

---

packages/core/lib/debug/external.js
packages/source-fetcher/lib/common.ts
packages/source-fetcher/lib/etherscan.ts
packages/source-fetcher/lib/index.ts
packages/source-fetcher/lib/sourcify.ts
packages/source-fetcher/lib/types.ts

**Note: This PR is a breaking change to `@truffle/source-fetcher`**.
I realized that source-fetcher probably ought to throw if you give it an invalid network ID.  So now it does.  The `isNetworkValid` method is gone, because it's now unnecessary.  Note obviously this required appropriate modifications to `external.js`.

Internal improvement: Make source-fetcher throw on invalid network

---

packages/compile-common/src/types.ts
packages/compile-solidity/index.js
packages/compile-solidity/run.js
packages/compile-vyper/index.js
packages/compile-vyper/test/test_compiler.js
packages/external-compile/index.js
packages/workflow-compile/index.js
packages/workflow-compile/test/index.js

This PR adds a `sources` object to the `workflow-compile` result, and makes necessary changes in the `compile-common`, `compile-solidity`, `compile-vyper` and `external-compile` packages.
Of note, the vyper compilation result does not include `ast` or `legacyAST`, and external compilations will return an empty array for sources since the user does their own source management when using an external compiler.

Add sources to compile result

---

packages/debugger/test/ast.js
packages/debugger/test/context.js
packages/debugger/test/data/calldata.js
packages/debugger/test/data/codex.js
packages/debugger/test/data/decoding.js
packages/debugger/test/data/function-decoding.js
packages/debugger/test/data/global-const.js
packages/debugger/test/data/global.js
packages/debugger/test/data/helpers.js
packages/debugger/test/data/ids.js
packages/debugger/test/data/immutable.js
packages/debugger/test/data/more-decoding.js
packages/debugger/test/data/returnvalue.js
packages/debugger/test/data/yul.js
packages/debugger/test/endstate.js
packages/debugger/test/evm.js
packages/debugger/test/helpers.js
packages/debugger/test/load.js
packages/debugger/test/precompiles.js
packages/debugger/test/reset.js
packages/debugger/test/solidity.js
packages/debugger/test/stacktrace.js
packages/debugger/test/txlog.js

The debug module names in the debugger test didn't begin with `debugger`, and it was bugging me, so I changed it.
...also the one in `yul.js` was misnamed.

Internal improvement: Fix debugger test debug module names

---

packages/source-fetcher/lib/etherscan.ts
packages/source-fetcher/lib/types.ts

This PR adds rudimentary support for Vyper contracts on Etherscan to source-fetcher.  Because these have no associated settings, it's pretty straightforward; the source code is just the given source code (no need to process that), and for the compiler version, we just strip off the initial `vyper:`, which I'm taking to be a prefix added by Etherscan, rather than a legitimate part of the version string.

Enhancement: Add rudimentary Etherscan Vyper support to source-fetcher

---

packages/db/src/resources/bytecodes.ts
packages/db/src/resources/compilations.ts
packages/db/src/resources/contractInstances.ts
packages/db/src/resources/contracts.ts
packages/db/src/resources/index.ts
packages/db/src/resources/projectNames.ts
packages/db/src/resources/projects.ts
packages/db/src/resources/sources.ts
packages/db/src/resources/types.ts

The directory moved but these didn't get updated

Fix logger names for @truffle/db resources

---

packages/db/src/pouch/index.ts

Since this will be vastly more performant than `fs`

Change default @truffle/db adapter to `sqlite`

---

packages/truffle/test/scenarios/commands/build.js

Taken from #3461, in hopes of fixing #3523 #3524 and #3525

Lengthen timeout for build scenario test

---

.prettierrc.json

Since people seem to want this, thought I'd turn this on!

Internal improvement: Turn on spaces in object literals in prettier

---

packages/codec/lib/compilations/types.ts
packages/codec/lib/compilations/utils.ts
packages/debug-utils/index.js
packages/decoder/lib/decoders.ts

Now that #3550 is merged, this is possible!  **Edit: This PR is now a breaking change to `@truffle/codec`.**
This PR does two things.  The first is that it makes it so that `shimCompilations` (and the new `shimCompilation`) make use of the `sources` information on a compilation, if it is present.  Note that on `shimContracts`, I've added this as an optional argument on the *end* in order to prevent a breaking change.  If `inputSources` is passed to that, it will use that for the sources information, instead of trying to dig it out of `contracts` and `files`.
The second thing is that in `debug-utils`, it adds one more check for whether the debugger CLI should recompile: If there's a gap between the index of the last user source and the first generated source, that will now trigger a …

Enhancement: Have debugger/decoder make use of sources info in compilations

---

packages/compile-vyper/index.js
packages/compile-vyper/test/test_compiler.js
packages/debugger/lib/session/index.js
packages/decoder/lib/decoders.ts
packages/solidity-utils/index.js

This might be a breaking change to `compile-vyper`?  Or to something? (Edit: We've agreed it's not since it never worked properly in the first place!)
So this has several parts to it:
1. Biggest change -- Vyper source maps will now go under `deployedSourceMap` in the artifact, not `sourceMap`, because they're source maps for the deployed bytecode!  (As best I can tell, Vyper doesn't support source maps for constructors, for whatever reason.)  Note that Vyper source maps are a different format from Solidity's, so I'm unsure this is *really* the right place, but, um, it's an improvement at least I guess...?
2. The decoder now checks that any source maps it's attempting to use are Solidity source maps, not Vyper source maps.
3. The debugger now attempts to convert Vyper source maps to …

Bug fix: Better handling of Vyper source maps (including putting them in the right place in the artifact!)

---

packages/compile-vyper/index.js
packages/compile-vyper/test/test_compiler.js

As requested by @gnidan.  Gets rid of the sourceMap option for compiling Vyper contracts, in favor of just always getting the source map.  Tests have also been adjusted appropriately.

Turn on source maps in Vyper w/o an option

---

packages/workflow-compile/index.js

So that @truffle/db resources are referenced in the resulting `truffle compile` artifacts

Ensure artifacts are saved with db info

---

packages/compile-solidity/run.js

Solidity version 0.7.5 adds the `viaIR` compilation setting, so I've added support for that.
Solidity version 0.7.4 adds `modelCheckerSettings`, so I've added support for that.  Note that I've made this separate from `settings` because that's how Solidity does it, but if we think it should be part of `settings` we could do it that way as well.
Also Solidity version 0.7.3 added the `stopAfter` option, but I decided not to add support for that now because uhhh that seems a bit dicey, we'll have to figure out later what to do about that.
Edit: After trying out `stopAfter` myself, it seems that supporting it would require us to modify `outputSelection`, so yeah, we'll figure that out later, I guess?

Add support for viaIR and modelCheckerSettings

---

packages/codec/lib/compilations/utils.ts
packages/debugger/lib/session/index.js

Fixes a bug I accidentally introduced in #3565: If `inputSources` was passed, the shimmed output sources didn't get IDs.  Now they do, with ID equal to `index.toString()` (which is kind of hacky but what we do elsewhere and works well enough).

Bug fix: Put IDs in shimmed sources when inputSources is passed

---

packages/solidity-utils/index.js

Fixing up a mistake I made in #3571.
See, translating `-1:-1:0` to `-1:-1:-1` doesn't actually work because, uh, then other things after it will also be recorded as being in file `-1`.  Oops.  So, I undid that.  And then I went further and got rid of the pre-existing special cases around -1 there, because why were those even there?
Instead, I made it so that later during processing, having start and length both equal to -1 gets translated to them both being 0 instead, because negative start and length seems potentially problematic.  But again, I didn't do this during the initial processing.  Hm, I guess I could have, but honestly I like this better I think.
Anyway, this should all basically work properly now.
Also while I was it, I took out that unnecessary `numInstructions` estimation in …

Bug fix: Fix handling of -1s in source maps

---

packages/source-fetcher/lib/etherscan.ts
packages/source-fetcher/lib/sourcify.ts
packages/source-fetcher/lib/types.ts
packages/source-fetcher/package.json
yarn.lock

Adds a `specializations` field to the output of source-fetcher.  This contains the libraries information and (when retrieving from Etherscan only) the constructor arguments information.  When retrieving from Sourcify, constructor arguments will not be present.  Also obviously libraries info is omitted for Vyper.
Constructor arguments is given as a hex string, of course, but note that I did *not* put a `"0x"` in front, for consistency with how we do it in the debugger (and also easy concatenation).
Libraries are given in a form understandable to solc.  When dealing with JSON (from Etherscan or Sourcify), well, it's right in the JSON.  When dealing with non-JSON Etherscan, we have to parse the `Library` field.  Fortunately that's just a semicolon-delimited list, with the individual entries …

Add specializations to source-fetcher

---

packages/db/src/project/compile/compilations.ts
packages/db/src/resources/compilations.ts

This removes the non-nullability requirement for source and processed source inputs, as well as fixes the resolvers to handle the case where these are null.
This addresses the situation where @truffle/workflow-compile reports `null` paths for particular source indexes

Allow Compilations to have missing sources in @truffle/db

---

packages/db/src/graphql/schema.ts
packages/db/src/graphql/types.ts
packages/db/src/meta/index.ts
packages/db/src/project/index.ts
packages/db/src/project/names/current.ts
packages/db/src/project/names/nameRecords.ts
packages/db/src/project/names/projectNames.ts
packages/db/src/project/test/artifacts/index.ts
packages/db/src/project/test/assignNames.spec.ts
packages/db/src/project/test/integration.spec.ts
packages/db/src/resources/bytecodes.ts
packages/db/src/resources/compilations.ts
packages/db/src/resources/contractInstances.ts
packages/db/src/resources/contracts.ts
packages/db/src/resources/nameRecords.ts
packages/db/src/resources/networkGenealogies.ts
packages/db/src/resources/networks.ts
packages/db/src/resources/projectNames.ts
packages/db/src/resources/projects.ts
packages/db/src/resources/sources.ts
packages/db/src/resources/types.ts
packages/db/src/test/nameRecord.graphql.ts
packages/db/src/test/nameRecord.spec.ts
packages/db/src/test/projects.graphql.ts
packages/db/src/test/projects.spec.ts

Externally, this does the following:
- Fix name-keeping logic (by correctly returning `previous`, and by handling duplicates in Project abstraction)
- Add NameRecord.history to track previous records. This accepts optional `limit` and `includeSelf` inputs, for convenience.
- Expose `type` field for all resources.
- Remove NameRecord's `name` and `type`; NameRecords need to know resource type, so also define `TypedResourceReferenceInput` for when adding NameRecords.
- Move ProjectName's `name` and `type` fields to ProjectName.key, since `type` will now always return `ProjectName`.
- Expose `id` property on Project abstraction instances.
Internally, this does a few things to support the above:
- Hook up `type` field in `src/graphl/schema` by defining it as a field resolver.
- Remove `id` …

Improve @truffle/db project name-keeping by adding `type` field to all resources

---

packages/source-fetcher/lib/types.ts

Updates the types used in `source-fetcher` to reflect additions to solc settings (specifically, `viaIR`).  Has no functional effect at present, just keeping things up to date.

Internal improvement: Update types used in source-fetcher

---

.github/workflows/nodejs.yml

Two people have asked recently what the yarncheck job does, because, well, the yarncheck job doesn't say anywhere what it does!  This PR adds a message saying `"Please run yarn and commit all changes to yarn.lock"` when it fails so people will be able to see what it is they need to do. :)

Internal improvement: Add failure message to yarncheck job to increase clarity

---

packages/contract-schema/index.js
packages/contract-schema/test/solc.js

So `contract-schema` had a mechanism for copying AST to legacyAST when the latter doesn't exist.  Problem is, the check didn't work -- it would check the `schemaVersion` on the dirty object, despite dirty objects typically not having this set -- and so AST was getting copied over legacyAST even when the latter existed.  I've replaced it with a simpler check: Now, AST is copied to legacyAST precisely when there is no legacyAST; `schemaVersion` is not checked.

Bug fix: Fix overwriting of legacyAST by AST

---

packages/abi-utils/package.json
packages/compile-common/package.json
packages/source-fetcher/lib/types.ts

I noticed that `abi-utils` and `compile-common` both have `contract-schema` listed as a dependency.  However, both of these packages only use *types* from `contract-schema`, so this should be devDependency.  I've reclassified things appropriately.
Also, I updated an out-of-date comment in source-fetcher (as source-fetcher now supports Vyper sources on Etherscan, even though the CLI debugger won't actually make use of these).

Internal improvement: Reclassify some dependencies as devDependencies

---

packages/debugger/package.json

Just some stuff I missed in #3598, `@truffle/debugger` had some unused dependencies listed, namely `@truffle/compile-solidity` and `@truffle/expect`, so those are gone now.

Internal improvement: Clean up debugger dependencies

---

packages/codec/lib/compilations/utils.ts
packages/compile-solidity/run.js
packages/compile-vyper/index.js
packages/compile-vyper/test/test_compiler.js
packages/compile-vyper/vyper-json.js
packages/core/lib/debug/interpreter.js
packages/debug-utils/index.js
packages/debugger/lib/data/selectors/index.js
packages/decoder/lib/decoders.ts

Per earlier discussion, language names will now be capitalized.  Compiler names will not be -- so `"Vyper"` is the language, `"vyper"` is the compiler. :)  Anyway this PR does that.
This PR might be a breaking change to some packages?  Not sure.  I'll call it a **breaking change to debug-utils**, but we can probably get away with not calling it a breaking change to any others...
(Also as long as I was touching the syntax-highlighting code in `debug-utils` I also cleaned it up some, even though that's not the main point of this PR.)

Internal improvement: Capitalize names of languages (Solidity, Yul, Vyper)

---

packages/codec/lib/abi-data/decode/index.ts
packages/codec/lib/ast-constant/decode/index.ts
packages/codec/lib/basic/decode/index.ts
packages/codec/lib/bytes/decode/index.ts
packages/codec/lib/errors.ts
packages/codec/lib/memory/decode/index.ts
packages/codec/lib/stack/decode/index.ts
packages/codec/lib/storage/decode/index.ts

So, I think Codec's error handling was causing some problems.  The decoding functions would just catch errors and *assume* they were expected errors we knew what to do with.  Seems they weren't always.  Now I've added a check for this, and the error will be rethrown if it's not a `DecodingError` (i.e., an expected error that we threw).
Kind of wondering if I should factor this, but not clear where the function would live?  This is probably OK for now.
(In more detail, the problem is that unexpected errors, instead of getting rethrown, were having their `error` field extracted -- which would be `undefined` since it wasn't a `DecodingError` -- and returned inside an error result.  This would then cause problems *later* when other code attempted to *use* that `undefined`, and we would have …

Bug fix: Have codec rethrow unexpected errors in decoding

---

packages/core/lib/debug/external.js

As suggested by @gnidan.  Now, if you have the `docker` turned option in your solc config, it will also be applied to sources compiled with `--fetch-external`.  Pretty simple, really.

Allow using docker with --fetch-external

---

packages/compile-solidity/compilerSupplier/rangeUtils.js
packages/resolver/lib/sources/truffle/Deployed.ts
packages/resolver/test/Deployed.ts

When testing while using "pragma" as the version, Truffle would crash when attempting to create the `DeployedAddresses` library as there was no infrastructure to handle this. This PR updates the `rangeUtils` to return the default solc version in the case where "pragma" is specified.

Bug fix: Better handle deployed addresses library compilation

---

packages/debugger/test/helpers.js
packages/decoder/package.json
packages/decoder/test/current/test/decoding-test.js
packages/decoder/test/current/test/downgrade-test.js
packages/decoder/test/current/test/receive-test.js
packages/decoder/test/current/test/wire-test.js
packages/decoder/test/helpers.js
packages/decoder/test/legacy/test/shadow-test.js
packages/decoder/test/legacy/test/wire-test.js
yarn.lock

Addresses #3310.  This PR gets rid of the use of Truffle Test in the decoder tests, hopefully finally ending the headache they've posed and defusing any potential future problems they might pose with `lerna`.
To do this I reconstituted them along the lines of the debugger tests.  However I didn't want to remove the existing structure, so I kept the existing structure as two truffle projects in place and added `helpers.js`, much like exists in the debugger, to set things up.  However unlike in the debugger, we already have the structure of a Truffle project here, so we don't need to set up a sandbox, but rather just use `Config.detect` and `Environment.detect`.  We do use a temporary directory for the contracts build directory, but that's it.
The tests are a fair bit slower now due to …

Internal improvement: Remove use of Truffle Test in decoder tests

---

packages/db/src/resources/networks.ts
packages/db/src/test/networkGenealogy.graphql.ts
packages/db/src/test/networkGenealogy.spec.ts

- Move list to `networks`, renamed from `network`
- Return only a single `alreadyTried`, rather than a separate `alreadyTried` for each candidate

When searching @truffle/db network relationships, return one CandidateSearchResult instead of list

---

packages/contract-tests/test/linking.js
packages/contract/lib/contract/constructorMethods.js

Currently on a `@truffle/contract` object (the type, i.e. `MetaCoin`) the `link` method only accepts another `@truffle/contract` object as an argument and will incorrectly link if you pass an instance. This PR adds support for passing a `@truffle/contract` instance (not the type, i.e. `await MetaCoin.deployed()`).
It also refactors the method into a big `switch` statement which more clearly conveys what is happening there.
~It is a little bit wonky to test for `contract._json.contractName` but I'm not sure if there is a better way to test that it is an instance. Ideas?~
related to https://github.com/trufflesuite/truffle/issues/3584

Bug fix: Allow contract instances as an argument to the link method

---

packages/contract-tests/test/errors.js
packages/contract-tests/test/lib/utils/ens.js
packages/contract-tests/test/lib/utils/index.js
packages/contract/lib/utils/index.js

Currently the `is_tx_params` method is used to determine whether an argument to a function is the tx params. This function checks the keys of the object provided and returns once it finds that one of them matches the whitelisted fields. This PR adds the `overwrite` key to the whitelist. ~and will also accept an empty object. Accepting an empty object does seem a bit strange to me. It seems like it would make user errors more likely or cause misunderstandings but I suppose it could be better UX. This fix causes `@truffle/contract` to check all of the keys and make sure they match some term from the whitelist.~
related to https://github.com/trufflesuite/truffle/issues/2843

Bug fix: Correct `is_tx_params` method

---

packages/compile-solidity/index.js
packages/compile-vyper/index.js
packages/compile-vyper/package.json
packages/config/src/configDefaults.ts
packages/external-compile/index.js
packages/external-compile/package.json

Sometimes when we compile, we take `Config.defaults()` and merge the given options into it.  Sometimes we don't.  I made it so we always do.  Note I didn't do it in each individual function, I just made sure each path eventually hits it.  I did this for all three compile packages.
Also, in the defaults, I added `settings` under `vyper`, and added a comment explaining where the default solc version is found (since you might expect it to be there, but it's not).  I originally also changed `vyper-json.js` in `compile-vyper` to not do `settings || {}`, since I figured that would be unnecessary now, but uh that didn't end up working, so, uh, I left it alone...?  Not sure if that means I did someting wrong elsewhere...

Consistently use Config.default() when compiling

---

packages/compile-solidity/compilerSupplier/rangeUtils.js

Thanks to @eggplantzzz for noticing the problem here.  We now use `semver.valid()` to guard the use of `semver.gte()`, just as we use `semver.validRange()` to guard the use of `semver.ltr()`.
Also, while I was at it, I tossed in `{ loose: true }` options everywhere just to make things extra-safe. :)

Bug fix: Guard against crashes from bad semver use

---

packages/core/lib/commands/create/templates/Example.sol
packages/core/lib/commands/create/templates/Test.sol
packages/core/lib/commands/init/initSource/contracts/Migrations.sol
packages/core/test/lib/create.js
packages/resolver/lib/sources/truffle/Deployed.ts
packages/resolver/solidity/Assert.sol
packages/resolver/solidity/AssertAddress.sol
packages/resolver/solidity/AssertAddressArray.sol
packages/resolver/solidity/AssertBalance.sol
packages/resolver/solidity/AssertBool.sol
packages/resolver/solidity/AssertBytes32.sol
packages/resolver/solidity/AssertBytes32Array.sol
packages/resolver/solidity/AssertGeneral.sol
packages/resolver/solidity/AssertInt.sol
packages/resolver/solidity/AssertIntArray.sol
packages/resolver/solidity/AssertString.sol
packages/resolver/solidity/AssertUint.sol
packages/resolver/solidity/AssertUintArray.sol
packages/resolver/solidity/NewSafeSend.sol

Updates the Migrations file for 0.8.0.  Because we got rid of the explicit constructor earlier, all we should need to do is bump the pragma here. :)
Note @cds-amal I'm guessing you may want to do the same thing in your Truffle Boxes...

Update Solidity sources (e.g. Truffle Init Migrations file) for 0.8.0

---

packages/db/package.json
packages/db/src/process/index.ts
packages/db/tsconfig.base.json
yarn.lock

- Replace @zerollup/ts-transform-paths with typescript-transform-paths, since the former does not work anymore (for unknown reason)
- Fix an export that seems to go missing from compiler output, possibly due to unsupported syntax with typescript-transform-paths

Upgrade @truffle/db typescript to ^4.1.3

---

packages/compile-solidity/run.js

Solidity 0.7.6 and up use `settings.modelChecker` rather than a separate `modelCheckerSettings`, so I've added support for that.
NB @gnidan and @fainashalts: Despite being moved under `settings` now, the model checker settings still do not go in the metadata.

Add support for settings.modelChecker

---

packages/debug-utils/package.json
yarn.lock

I published a new version of highlightjs-solidity with syntax highlighting updates for Solidity 0.8.0, now this PR has us use it.

Dependency update: Upgrade highlightjs-solidity to 1.0.20 (Update syntax highlighting for 0.8.0)

---

packages/codec/lib/ast/import/index.ts
packages/codec/lib/compiler/types.ts
packages/codec/lib/compiler/utils.ts
packages/codec/lib/special/decode/index.ts
packages/core/lib/commands/develop.js
packages/core/lib/commands/test/index.js
packages/debugger/lib/evm/reducers.js
packages/debugger/lib/web3/adapter.js
packages/debugger/lib/web3/sagas/index.js
packages/debugger/test/data/global.js
packages/debugger/test/helpers.js
packages/decoder/package.json
packages/environment/environment.js
yarn.lock

The main purpose of this PR is to update the debugger's globally-available support for Solidity 0.8.0.  This means two things:
1. In Solidity 0.8.0, `msg.sender` and `tx.origin` are now of type `address`, rather than `address payable`.  That doesn't really matter that much, but we keep track of it, so I updated it.  This purely required changes in `codec`.
2. In Solidity 0.8.0, the `block` special variable has a new property `block.chainid`, which contains the chain ID as a `uint`.  I added support for this.  Note that there is a version check; it won't appear when debugging an earlier version.
Doing this second part required both changes in `codec/lib/special/decode`, but also in the debugger itself, to actually get the chain ID and pass it to `codec`.  Fortunately very little needed to …

Enhancement: Update globally-available variables for 0.8.0; also set _chainId in exposed Ganache instances

---

packages/decoder/test/current/test/decoding-test.js

So, since I switched the decoder tests to `Ganache.provider`, they're slower than they used to be, and this preparation step keeps timing out.  I'm upping the timeout.
Note: I also made this change on #3627, but that isn't merged yet and I assume @gnidan is going to take some time to review that, so I made this separate PR in addition so it can get merged quickly.

Internal improvement: Increase timeout on timing-out decoder tests

---

packages/compile-vyper/index.js
packages/contract-sources/index.js

Addresses #3455.
There were two things going wrong here:
1. To some extent this was actually a generic problem and not specific to Vyper; I turned on `dot: true` in `contract-sources` so it can find hidden files and directories.
2. Unfortunately this didn't fix the problem, because `compile-vyper` was doing a separate minimatch check, so I turned on `dot: true` there as well.
Anyway now hidden sources, and sources in hidden directories, should work!

Bug fix: Allow compile-vyper to compile hidden files/directories

---

packages/compile-vyper/index.js
packages/compile-vyper/package.json
packages/compile-vyper/test/test_compiler.js
packages/compile-vyper/vyper-json.js

Addresses #3629.  (PS we should also close the ancient #2209 once this is released; really that should have been closed with #3583, but I only found that issue later, and also #3583 broke things, so, uh, yeah...)
So, when making all the changes to `compile-vyper` recently in #3583, I also changed it to use the new bytecode output format.  Unfortunately, there's something I did not realize: The new bytecode output format requires that there be no `0x` prefix.  And Vyper always puts on such prefixes -- yes, even in its JSON output format, even though Solidity does *not* do this, and even though Vyper's *documentation* says it doesn't do this either.  Because this change happened so late in the PR and seemed harmless, it didn't get properly tested; and because our `compile-vyper` tests are …

Bug fix: Fix Vyper bytecode prefix

---

packages/core/lib/debug/cli.js
packages/core/lib/debug/external.js

This PR makes it so that if `truffle debug --fetch-external` encounters an error while compiling contracts, it will print a warning rather than erroring out.  Specifically, there's now a try/catch around the compile step, and on an error, `failure` is set to `true` and we retry with the next fetcher.  Also, there's now `failureReason`, so we can distinguish fetch failures from compile failures; it will be `"fetch"` or `"compile"` as appropriate.  The compile failures get added to a new array, and the warnings printout will include them.
Also, I made it so that `failure` is reset to `false` when getting a particular address succeeds because, like, why do we need to warn that there were problems with a certain address if at least one of the fetchers succeeded?  Like, if etherscan had …

Enhancement: Allow fetch-external to proceed with warning if compile fails

---

packages/abi-utils/lib/normalize.ts
packages/abi-utils/lib/types.ts
packages/codec/lib/abi-data/allocate/index.ts
packages/codec/lib/abi-data/allocate/types.ts
packages/codec/lib/abi-data/utils.ts
packages/codec/lib/core.ts
packages/codec/lib/types.ts
packages/core/lib/debug/interpreter.js
packages/core/lib/debug/printer.js
packages/debug-utils/index.js
packages/debug-utils/package.json
packages/debugger/lib/data/selectors/index.js
packages/debugger/lib/stacktrace/selectors/index.js
packages/debugger/test/data/calldata.js
packages/debugger/test/data/returnvalue.js
packages/decoder/lib/decoders.ts
packages/decoder/test/current/test/decoding-test.js
yarn.lock

OK, so, this PR does a few things.  I'll split it into three main groups: Panics; fallback return values; and other stacktrace-related improvements.
Part one: Panics.  This PR adds support for decoding of panics.  This affects Codec, the debugger, `debug-utils`, the debugger CLI, and `abi-utils`.
You may be wondering -- abi-utils?  It affects abi-utils because revert decodings now contain the corresponding ABI.  So, I've added error ABI entries to the types there.  Of course, these don't really exist yet, but acting as if they do seemed the best way to do this decoding in a future-proof manner.  In addition to simply adding the type, I also added support for the type to various ABI-related functions, both here and in Codec.  I did not add arbitraries for this type.
The changes to Codec …

Enhancement: Add support for decoding of panics and fallback return values (and also some other stacktracing improvements)

---

packages/core/lib/debug/cli.js
packages/debug-utils/index.js

I noticed that the debugger was doing a recompile every time I tried to debug Vyper.  Something about Vyper was always triggering the recompile check.  What was it?  That in Vyper ASTs, some nodes do have an `id` field, but it's not the node ID, it's something else, and so these often generate false-positive for collisions.  So, I've restricted the check to Solidity sources.
Note that Vyper ASTs do have node IDs, but they're in the `node_id` field, not the `id` field.  However, checking them for collisions would be pointless, as they're only unique per source, not per compilation.  So, as mentioned, we restrict the check to Solidity.

Bug fix: Prevent unnecessary recompilation when debugging Vyper

---

packages/core/lib/commands/debug.js
packages/core/lib/debug/cli.js
packages/core/lib/debug/compiler.js
packages/core/lib/debug/external.js

As requested by @cds-amal.
This PR adds three new options to the debugger CLI: `--compile-tests`, `--force-recompile`, and `--force-no-recompile`.
The interesting new one is `--compile-tests`.  This causes the debugger CLI to compile your Solidity test contracts so you can debug them.  Hooray!  It also forces a recompilation more generally.
There's also `--force-recompile`.  It's not called `--compile-all` because it doesn't save the results.  Anyway, this forces the debugger to do a recompile on startup, even if its heuristics would say that it doesn't need to.  You know, in case there's a problem they miss.
Finally there's `--force-no-recompile`.  This forces the debugger *not* to recompile, in case the debugger erroneously thinks there's a problem, or you're pretty sure any problems …

Enhancement: Allow debugger to debug Solidity test contracts (also, some other new options)

---

packages/core/lib/commands/debug.js
packages/core/lib/debug/cli.js

Rename some of the options I introduced in #3637 for consistency.  I avoided doing this at first because I thought it would be inconsistent with how `truffle migrate` works, which it would, but it would be totally consistent with how `truffle test` works, so it's fine I figure.  (I guess `truffle test` technically *does* do a save, but it does it to a temporary directory, so that doesn't count!)

Internal improvement: Rename debugger compile options for consistency

---

packages/resolver/solidity/AssertAddressArray.sol
packages/resolver/solidity/AssertBytes32.sol
packages/resolver/solidity/AssertBytes32Array.sol
packages/resolver/solidity/AssertInt.sol
packages/resolver/solidity/AssertIntArray.sol
packages/resolver/solidity/AssertUint.sol
packages/resolver/solidity/AssertUintArray.sol

Since [Solidity 0.8.0](https://blog.soliditylang.org/2020/12/16/solidity-v0.8.0-release-announcement/), the use of `byte` has been disallowed and `bytes1` must be used instead. 
> Type System: Disallow the byte type. It was an alias to bytes1.
This PR removes `byte` to compile `Assert*.sol` with Solidity 0.8.0.

Unalias `byte` to `bytes1`

---

packages/compile-vyper/index.js

Addresses #3647.
This PR makes it so that `compile-vyper` won't attempt to do anything if there are JSON files present in the contracts directory but no actual Vyper files.  I had JSON count as Vyper to support Vyper's native ability to import JSON, but we don't always want that, as there might be JSON present for other reasons and no actual Vyper.  So, I changed the "are there any Vyper files present?" check to restrict to actual Vyper files, not including JSON.

Bug fix: Prevent Vyper compilations when JSON but no Vyper

---

packages/codec/lib/compilations/utils.ts
packages/debugger/lib/session/index.js

This PR fixes two bugs that would prevent using the debugger with Vyper versions prior to 0.1.0-beta.17.
The first bug is that it turns out, in Vyper versions prior to 0.1.0-beta.17, the AST's root node is... not a node.  The AST is just an array of nodes, there's nothing for the root.  This naturally caused problems when we tried to do things with its `src` field to determine a contract's primary source.  So, now, we check if the AST is an array, and if it is, we replace it by `ast[0]`.  What if it's an *empty* array...?  Well, uh, then that attempt fails, but I also generally made things more robust by allowing `shimContracts` to check the source map as well, because why not.
The second bug is that sufficiently old Vyper versions don't have an AST.  Now that should be fine, right?  A …

Bug fix: Fix problems with using debugger with Vyper versions prior to 0.1.0-beta.17

---

packages/resolver/lib/sources/abi.ts

We need to check that `resolver.body` is falsy in the ABI source because what is returned from the FS source is always of the  form `{ body: <value>, filePath: <value> }` and thus `resolver` will always be truthy. It will then proceed to use `undefined` as an argument to the `path` module which would cause it to crash. So to correct this, use `resolver.body` as that will be undefined in the case that nothing is resolved.

Bug fix: Fix check for resolved source

---

packages/resolver/lib/sources/truffle/index.ts

Addresses #3651.
This PR fixes a problem that if you tried to use a `truffle` resolver source, but the contracts build directory was missing, the `resolve` function would crash.  It would call `fs.readdirSync` on the build directory, but if the build directory was absent, this would crash.  So, I added a check to see first if it exists, and if not, it just sets the files found there to `[]`.  This seems to solve the problem.

Bug fix: Prevent crash from missing build directory in Truffle resolver source

---

packages/compile-solidity/compilerSupplier/rangeUtils.js
packages/compile-solidity/test/compilerSupplier/rangeUtils.js

There was an error in the `rangeContainsAtLeast` method and here it is fixed. Some tests have also been added.

Bug fix: Fix RangeUtils method

---

packages/compile-vyper/index.js

Right now I occasionally get errors when compiling Vyper without `--all` because `compile-vyper`'s `necessary()` method calls `sources()` instead of `sourcesWithDependencies()`, so sometimes the compiler it can't locate imported sources.  So, this PR changes that.  I also removed the `compilationTargets` logic because -- now that I understand a bit better how that's supposed to work -- I've realized that's not the appropriate place to handle that.
Note that right now the `sourcesWithDependencies()` method in `compile-vyper` just calls `all()`, because we don't currently have an import parser for Vyper like we do with Solidity.  Obviously that's not great for performance, but it's better than failing to compile at all!
Anyway, now Vyper should always compile at least.  We might want to see …

Bug fix: Have compile-vyper's necessary() call sourcesWithDependencies(), remove compilationTargets logic

---

packages/db/src/resources/projects.ts
packages/db/src/resources/types.ts
packages/db/src/test/projects.graphql.ts
packages/db/src/test/projects.spec.ts

- Add `contracts` field to Project, to query for all current, name-assigned contracts
- Add `networks` field to Project, to query for all current, name-assigned networks
- Factor out a `resolve` function to resolve a given name and/or type for a project; update the existing `network` and `contract` resolvers to use this new function.

Allow querying collections of project names

---

packages/resolver/lib/sources/truffle/Deployed.ts
packages/resolver/solidity/AssertInt.sol
packages/resolver/solidity/AssertIntArray.sol

Solidity 0.8.0 requires additional explicitness in type conversions that wasn't required before.  The ones that are relevant here are the following:
1. You can't directly convert `int256` to `uint8`, because that's changing both size and signedness at once;
2. Address literals are no longer considered payable.
The former caused a problem with `AssertInt` and `AssertIntArray`, since there are points where those do `uint8(n % radix)`, with `n` being an `int256`.  Fortunately in these cases we are guaranteed that `n` is positive, as they all lie within `if (n>0) { ... }` blocks, so I just changed these to `uint8(uint(n % radix))`, which works fine.
The latter caused a problem with creating the `DeployedAddresses` library, since it would attempt to use literal addresses as `address payable`. …

Bug fix: Add newly-required type conversions in Assert libraries for Solidity 0.8.0

---

packages/compile-solidity/index.js
packages/compile-solidity/profiler/shouldIncludePath.js
packages/compile-solidity/test/profiler/shouldIncludePath.js
packages/resolver/lib/sources/abi.ts
packages/truffle/test/scenarios/compile/compile.js
packages/truffle/test/sources/inheritance/contracts/Abi.abi.json
packages/truffle/test/sources/inheritance/contracts/Root.sol

JSON files were not being included in compilation because the `shouldIncludePath` in the profiler was not updated to allow this. With the additions of support for abi JSON files, we now have to allow these sources to be whitelisted here so they can be passed to the Solidity compiler (after resolution and the generation of the relevant Solidity of course).
**Update:** There are a couple of additional changes added to this PR:
- when the abi resolver has a problem resolving a JSON file (likely because it is Vyper-related JSON) it will return a blank Solidity file (with just a license line and pragma expression)
- after `requiredSources` we exit compilation when we only find JSON files to be compiled (in this case no Solidity must import the JSON and thus must not be appropriate for …

Bug fix: Update profiler method to allow json files for compilation

---

packages/core/test/config.js
packages/core/test/lib/create.js
packages/core/test/migrate.js

So, there are these three tests that keep timing out.  I know that @eggplantzzz is working on getting us better CI, but in the meantime, I'm upping the timeouts on two of them.  The third one actually already had a longer timeout set, but, the call to set it did nothing because the test was defined as an arrow function!  For those who don't know, you don't want to write your tests to be arrow functions because then you can't to do things like `this.timeout(10000)` or `this.skip()`.  Anyway so in addition to upping those two timeouts I also made a bunch of tests no longer arrow functions, including the one that was causing the problem.

Internal improvement: Increase some timeouts and fix some tests that were arrow functions

---

packages/db/src/process/run.ts

Since this field is required according to spec (even though Ganache doesn't require it)

Add missing id to @truffle/db jsonrpc requests

---

packages/db/src/pouch/couch.ts
packages/db/src/pouch/index.ts

This PR allows the use of an existing CouchDB service as the persistence layer for @truffle/db.
To use this, update `truffle-config.js` with the URL and auth credentials, e.g.:
```javascript
// ... rest of truffle-config
db: {
enabled: true,
adapter: {
name: "couch",
settings: {
url: "http://localhost:5984",
auth: {
username: "admin",
password: "password"
}
}
}
}
};
```

Add @truffle/db couch adapter

---

packages/core/lib/commands/packages.js

The `packages` command used for the ethpm v3 implementation should not take a callback when integrated with the rest of the 5.2.0 work. This PR updates it to return a `Promise`.

Bug fix: Update packages command to not take a callback

---

packages/resolver/solidity/Console.sol

`Console.sol` currently has no license identifier and causes the compiler to print warnings which is ugly. Get rid of them!

Add license to Console.sol

---

packages/db/src/db.ts

This PR adds request information to `DEBUG=db:db`, to make it easier to debug when something goes wrong.

Add debug logging for failed GraphQL requests

---

packages/db/src/pouch/databases.ts
packages/db/src/project/migrate/networkGenealogies/index.ts
packages/db/src/project/migrate/networkGenealogies/test/index.spec.ts
packages/db/src/resources/networks.ts

Turns out that the `Network.possibleAncestors` and `Network.possibleDescendants` queries start to explode reliably once you add thousands of networks. I found this by slurping mainnet and adding random historic blocks. After awhile (~5000 added blocks or so), WebSQL comes back with "too many parameters", which suggests something is going wrong with how PouchDB+friends end up constructing SQLite queries.
I went down the avenue of implementing an alternative TypeORM adapter, instead of PouchDB entirely, but my naïve approach ran into this same problem, and getting that to work, albeit giving us more control, would be a significant amount of effort, to effectively match much of the functionality of existing adapters.
This PR identifies and proposes a different approach to this problem: hack …

Work around PouchDB / WebSQL query construction problem in @truffle/db

---

packages/core/lib/commands/init/initSource/truffle-config.js

the key `websockets` throws an error and needs to be changed to `websocket` to work. The commented out key should be corrected.

Change "websockets" -> "websocket"

---

.circleci/config.yml

Adds a dummy CircleCI job so that CircleCI doesn't fail out due to no config being found.
We could probably just have a config file with no jobs or workflows in it, but, eh, erring on the safe side I guess.

Internal improvement: Add dummy CircleCI job to prevent failure from no config

---

packages/db/src/resources/networkGenealogies.ts

This PR adds indexes to NetworkGenealogy for `ancestor` and `descendant` (since that's how we look those up)

Add missing indexes to @truffle/db resources

---

packages/core/lib/commands/db/index.js
packages/truffle/package.json
yarn.lock

Couple minor issues:
- Update truffle's dependency version for @truffle/db
- Stop using `yargs.commandDir()`, which doesn't play nice with bundled code. We'll have to add `.comand()`s individually from now on.

Fix @truffle/db for bundled Truffle

---

packages/core/lib/commands/db/commands/serve.js

Since there's no longer any such thing as "just don't call the callback"

Ensure `truffle db serve` does not exit

---

packages/compile-common/package.json

I just noticed that, although `compile-common` depends on `contract-sources` and `expect`, they weren't in its `package.json`.  This PR fixes that.

Add missing dependencies to compile-common

---

packages/db/src/resources/networks.ts

Since this has long been replaced by the network genealogy system

Remove Network.fork field from @truffle/db

---

packages/core/lib/commands/compile.js
packages/core/lib/commands/migrate.js
packages/db/src/project/names/resources.ts
packages/db/src/project/test/assignNames.spec.ts
packages/migrate/Migration.js
packages/workflow-compile/index.js

This PR updates the logic for `truffle compile` and `truffle migrate` to assign contract names. This works by exposing a new `Compile.assignNames` method in workflow-compile and calling that from the places where it's relevant.
Note that doing it this way means that we get name assignments for those commands, but not for `truffle test`.

Hook up @truffle/db name assignments in compile and migrate

---

packages/abi-utils/lib/arbitrary.ts

Since Solidity 0.8.1 is out now, which adds `Panic` to the syntax as something you can catch, I figured I'd add `Panic` to the forbidden words in the ABI arbitraries.  It's probably not actually reserved as such, but I figure it's good to err on the safe side and avoid any potential naming collision with any sort of Solidity-meaningful word.

Add "Panic" to forbidden names in ABI arbitraries

---

packages/resolver/solidity/AssertInt.sol
packages/resolver/solidity/AssertIntArray.sol

Solidity 0.8.1 wasn't supposed to be a breaking release, sure, but, well, there are certain conversions they meant to disallow in 0.8.0 but forgot to, so now they're disallowed in 0.8.1.  So, I've updated our Assert libraries once again to ensure that they still compile with Solidity 0.8.1.

Bug fix: Fix Truffle's Assert libraries for Solidity 0.8.1

---

packages/debug-utils/package.json
yarn.lock

Updated highlightjs-solidity to highlight the word `Panic` now that you can catch those, this is just the PR here to now use this. :)

Dependency update: Update highlightjs-solidity to 1.0.21 (update syntax highlighting for Solidity 0.8.1)

---

packages/compile-common/src/profiler/profiler.ts
packages/compile-common/src/profiler/resolveAllSources.ts
packages/resolver/lib/resolver.ts
packages/resolver/lib/sources/truffle/index.ts
packages/resolver/lib/sources/vyper.ts
packages/truffle/test/scenarios/resolver/resolver.js

Addresses #3668.
This PR does two things:
Firstly, it allows resolution to fail in `resolveAllSources`.  This is so that resolution errors will show up to the user as compile errors rather than often-unhelpful Truffle errors.  To do this, the `resolve()` wrapper in `profiler.ts` is modified to include a try/catch, and a definedness check is added in `resolveAllSources`.  Note that I wanted to make sure unexpected errors get rethrown, but resolver doesn't currently throw structured errors; and, well, I didn't want to bother making it do so, this is just a quick fix, so I just checked the start of the message instead.
Secondly, it allows resolution of empty sources.  Currently we just checked whether `body` is truthy, which would mean that empty sources could not be resolved.  So I changed …

Bug fix: Allow resolution failure in resolveAllSources(); allow resolution of empty sources

---

packages/resolver/lib/resolver.ts
packages/resolver/lib/sources/abi.ts

This PR alters the `ABI` resolver source so that, instead of extending `FS`, it acts as a wrapper over another resolver source.  And if the ABI resolver source is turned on, instead of being added singly right before FS, every resolver source gets an ABI equivalent wrapped around it and added right before it.  So, the effect is that now you can also import JSON files as Solidity from e.g. an NPM module or whatever.
I was originally going to do it where there's *just* the `ABI` resolver sources, and these handle both the ABI and non-ABI cases (like the `Vyper` resolver source), but, uh, I thought that might be a bit confusing, and, well, this was easier.  Um, the `resolveDependencyPath` that I added is still in there from that approach, guess that's not actually needed, oops, just noticed …

Enhancement: Allow importing ABI JSON from non-FS sources

---

packages/compile-vyper/index.js

Addresses #3755.
This PR fixes three bugs in Vyper compilation.  Two of these are specific to non-JSON compilation, and one is specific to Vyper prerelease versions.
1. In non-JSON compilation, the `source_map` format was included even if the version was too low (apparently it's only `vyper-json` that complains about such things); if the version was high enough, it would be included twice!  Now I've removed it from the starting array of formats, so if it doesn't get pushed on, it's not there, and if it does get pushed on, it's the only copy.  (It's this one that caused #3755; including `source_map` twice caused the source map to get read as the empty string, and then `JSON.parse` would fail on that.)
2. Also in non-JSON compilation, later code below didn't account for the possibility that …

Bug fix: Fix several Vyper compilation bugs (specific to non-JSON Vyper and prerelease Vyper)

---

packages/compile-vyper/index.js
packages/compile-vyper/vyper-json.js

This PR makes it so that if `vyper-json` is not installed, we can still compile Vyper using JSON if `vyper` 0.2.5 or later is installed, using `vyper --standard-json`.  This feature, to compile via JSON but with the `vyper` executable instead of a separate `vyper-json` executable, was only added in Vyper 0.2.5, so we can't do it any earlier than that.
Ideally there would be a better way to check for this than checking the version, but I don't see one that wouldn't involve invoking `vyper` a third time, and I want to avoid that.  So, I think this is fine.
So now `checkVyper`, when `json` is set to true, will also return `jsonCommand`, which will either be `"vyper-json"` or `"vyper --standard-json"`.  This will be passed to `compileJson`, which will use the specified command when invoking …

Use `vyper --standard-json` if vyper-json not available

---

packages/truffle/test/scenarios/solidity_testing/ImportEverything.sol
packages/truffle/test/scenarios/solidity_testing/solidityTests.js
scripts/ci.sh

This PR adds a test that our Solidity testing libraries (assertions, deployed addresses, and `SafeSend`) compile with the latest version of Solidity.  Note that (like our other tests that use latest Solidity), this new test uses `version: native`, and I've added an installation of Solidity to the integration tests so that this can work.
**Note that due to the pragma this test will break whenever there's a breaking Solidity release.**  That's a little annoying, I suppose; I could remove the upper bound from the pragma so that doesn't happen.  However, the potential for *non*-pragma breakage is the point of the PR!  This new test ensures that our build breaks whenever a breaking Solidity release breaks our assertion libraries, and forces us to update them when that happens.  (Well, or …

Internal improvement: Add test that assertion libraries compile with latest Solidity

---

packages/artifactor/package.json
packages/codec/package.json
packages/contract-tests/package.json
packages/contract-tests/test/errors.js
packages/contract/package.json
packages/core/package.json
packages/db/package.json
packages/debugger/package.json
packages/decoder/package.json
packages/deployer/package.json
packages/environment/package.json
packages/external-compile/package.json
packages/interface-adapter/package.json
packages/migrate/package.json
packages/provider/package.json
packages/reporters/package.json
packages/require/package.json
packages/source-fetcher/package.json
packages/source-map-utils/package.json
packages/truffle/package.json
yarn.lock

Finally!
Note that this PR updates all web3 packages to 1.3.4, but leaves `@types/web3` in place.  Ideally we eventually tear that out, but I think that can be done later on a package-by-package basis.

Update web3 to 1.3.4

---

packages/artifactor/package.json
packages/codec/package.json
packages/contract-tests/package.json
packages/contract-tests/test/errors.js
packages/contract/package.json
packages/core/package.json
packages/db/package.json
packages/debugger/package.json
packages/decoder/package.json
packages/deployer/package.json
packages/environment/package.json
packages/external-compile/package.json
packages/interface-adapter/package.json
packages/migrate/package.json
packages/provider/package.json
packages/reporters/package.json
packages/require/package.json
packages/source-fetcher/package.json
packages/source-map-utils/package.json
packages/truffle/package.json
yarn.lock

Reverts #3763 due to web3 1.3.4 spewing a bunch of irrelevant warnings all over the console.

Revert web3 version update (from 1.3.4 back down to 1.2.9)

---

packages/db/src/meta/data.ts
packages/db/src/meta/graph/schema.ts
packages/db/src/meta/index.ts
packages/db/src/meta/pouch/adapters/base.ts
packages/db/src/resources/contractInstances.ts
packages/db/src/resources/networks/index.ts
packages/db/src/resources/networks/resolveRelations.ts
packages/db/src/resources/projects/index.ts
packages/db/src/resources/projects/resolveContractInstances.ts
packages/db/src/resources/projects/resolveNameRecords.ts
packages/db/src/resources/projects/test/contractInstances.spec.ts
packages/db/src/resources/types.ts
packages/db/types/stub.d.ts

This PR adds the `Project.contractInstance` and `Project.contractInstances` queries for easy deployed instance lookups.
Since contract instances _themselves_ are not named, these queries filter based on **contract name** and/or **network name**. (`Project.contractInstance` requires both, `Project.contractInstances` allows either/both/neither). These queries use these names to determine a "best fit" match for contract instances.
The process is a bit tricky, and different for contract names vs. for network names.
For filtering by network name:
- The name resolution part is easy: there's no need to look for historical name records for a given network. Assume that the currently assigned network resource for that name represents the actual blockchain we want, and that the contract instances …

Allow querying @truffle/db for a project's contract instances

---

packages/truffle/package.json
packages/truffle/webpack.config.js

As per #3768, to keep the bundle size down.

Internal improvement: Make @truffle/debugger a webpack external for truffle

---

packages/core/cli.js

This might address #3756, I'm not sure.  We'll have to ask them.
This PR fixes a bug where exit status codes weren't being set correctly; this is particularly relevant to Truffle Test, where the exit code should be equal to the number of failed tests.  Truffle Test was returning this number correctly, but `cli.js` was ignoring it and returning zero regardless!  Now this is fixed.

Bug fix: Propagate exit statuses properly

---

packages/abi-utils/package.json
packages/artifactor/package.json
packages/blockchain-utils/package.json
packages/box/package.json
packages/code-utils/package.json
packages/codec/package.json
packages/compile-common/package.json
packages/config/package.json
packages/db/package.json
packages/decoder/package.json
packages/error/package.json
packages/hdwallet-provider/package.json
packages/interface-adapter/package.json
packages/provisioner/package.json
packages/resolver/package.json
packages/source-fetcher/package.json
yarn.lock

Typescript had some security release, so I figured I'd update to their new releases with the fix.  I updated the 3.9.x ones to 3.9.8 and the 4.x ones to 4.1.4.  This also gets us down to just two Typescript versions. :P  (Well, lerna would count it as more, since some of them are pinned and some are not; I didn't bother standardizing that.)  I'm not going to attempt to consolidate them futher, since finding a single Typescript version that works for everything (or updating the stuff that relies on 3.9.x to work with 4) would be a bigger task...

Dependency update: Update Typescript versions to 3.9.8 and 4.1.4

---

packages/db/src/project/test/integration.spec.ts

Since this was missed in #3740 due to a stray `any`

Fix config in integration test

---

packages/debugger/lib/txlog/selectors/index.js

This PR makes it so that txlog will, when in a constructor context, treat code mapped to a contract definition node as if it were unmapped code.  This is due to [this Solidity bug](https://github.com/ethereum/solidity/issues/10935).
I'm a little worried this PR will screw things up for optimized code.  We'll see, I guess? :-/

Bug fix: Have txlog handle constructor code that should be unmapped but isn't

---

packages/compile-common/src/types.ts
packages/db/src/meta/batch.ts
packages/db/src/project/loadCompile/batch.ts
packages/db/src/project/loadCompile/bytecodes.ts
packages/db/src/project/loadCompile/compilations.ts
packages/db/src/project/loadCompile/contracts.ts
packages/db/src/project/loadCompile/index.ts
packages/db/src/project/loadCompile/sources.ts
packages/db/src/project/loadMigrate/batch.ts
packages/db/src/project/loadMigrate/contractInstances.ts
packages/db/src/project/loadMigrate/contracts.ts
packages/db/src/project/test/integration.spec.ts
packages/db/src/resources/compilations.ts
packages/db/src/resources/contracts.ts
packages/db/src/test/contract.graphql.ts
packages/db/src/test/contract.spec.ts
packages/db/src/test/projects.spec.ts

This PR re-uses the ProcessedSource entity for contract generated sources, removing the GeneratedSource types in the process.
In addition, this ensures that the input `id` property from the compile-common type is used for the index of a sparse array, as opposed to storing these sources in a tightly-packed array whose items encode their index. This also replaces the `any` in those types with actual interfaces (cc @haltman-at).
To get this to work, since each ProcessedSource references a Source resource, this PR reworks the sources-loading inside the Project abstraction to include information from generated sources (on top of the `sources` field already used). To do this, I've gotten rid of the hokey `Batch.Sources` abstraction and just used `Meta.Batch` directly.
Also, while I was it it, I …

Convert GeneratedSource to ProcessedSource in @truffle/db

---

packages/core/lib/commands/init/initSource/truffle-config.js

This PR adds the default db config to the `truffle init` command's default config values, with `enabled` set to `false`. It also adds a note about ensuring users can properly migrate their contracts and have them show up in the DB.

Add config defaults

---

packages/compile-solidity/package.json
yarn.lock

Addresses #3799.
In PR #3771, when attempting to clean up dependencies, I deleted the `solc` dependency from `compile-solidity`, because, hey, we don't invoke solc that way, right?  I searched for `require("solc")` to be sure.  Big mistake -- it's being used for `solc/wrap`, and my search didn't catch that.  Don't have that, and you can't compile!  Have the wrong version, and your compilation will be full of errors due to malformed import strings!  (I don't know why this happens, but it does.)  Anyway, re-added that dependency to fix the problem.  Sorry about that.

Bug fix: Re-add missing solc dependency in compile-solidity

---

packages/debugger/lib/txlog/selectors/index.js

#3790 restricted itself to constructors, because I was wary of applying that hack more generally and I thought that the problem only occurred in constructors.  Turns out it doesn't.  So, uh, I'm applying that hack in general now. :-/

Internal improvement: Avoid logging jumps to contract node regardless of context

---

packages/debugger/lib/txlog/selectors/index.js

This PR fixes a problem where the txlog would incorrectly handle function calls if said function call made a jump to unmapped code or a generated source in the middle of the function definition node.  Now we have it ignore such jumps, since they're not the real end of the function definition node.  In `data` this doesn't cause a problem because allocations can be overwritten later, but in `txlog` we deliberately *don't* do that (because we want to rely on the more robust `decodeCall` when possible), so we have to get it right the first time.  Hopefully, this should plug up the holes here.  (Well, except for optimized code, but...)

Internal improvement: Prevent txlog from being confused by unmapped code in function startup

---

packages/contract/lib/execute.js
packages/contract/lib/handlers.js
packages/contract/lib/manual-send.js

This PR fixes an issue raised by @jaspertium on Spectrum.  When `--stacktrace` was used with Truffle test, `contract.method()` wouldn't return a receipt in the proper format.  There are two reasons for this, one recent and one preexisting.
1. The recent one: You know that `translateReceipt` function I added to translate receipts from ethers format to web3 format?  Yeah, I forgot to ever actually invoke it!  Oops.  Now it's there.  That said, on its own this wouldn't fix the problem, and actually has little to do with the particular problem that @jaspertium was running into.
2. The preexisting one, and the main problem: Once we got a receipt back from `sendTransactionManual`, we had nothing to convert it to the Truffle format.  Normally that's handled in `handlers`, but since …

Bug fix: Make receipts work properly with --stacktrace

---

packages/db/src/project/loadCompile/compilations.ts
packages/db/src/project/test/integration.spec.ts

Since only runtime bytecodes can have immutables.

Use correct bytecode for immutableReferences in @truffle/db

---

packages/source-fetcher/lib/etherscan.ts
packages/source-fetcher/lib/types.ts

@truffle/source-fetcher is great for obtaining all the sources that went into compiling the contract instance at a given address!
Unfortunately, it does not make it easy to figure out which resulting compiled contract it was that ended up getting to deployed to that address.
This PR adds that information as an optional field to the result type, since Etherscan provides us with this information but Sourcify does not. (In the future, perhaps there's a solution when fetching from Sourcify to do an `eth_getCode` and bytecode match?)

Report contractName in source-fetcher if possible

---

packages/truffle/package.json
packages/truffle/webpack.config.js

@tcoulter's excellent work in #3794 made Truffle _so much faster_, but the tradeoff there is that the build itself is slower now. Easy choice, but I couldn't stand to see nothing happening in the terminal.
This PR enables [webpack's ProgressPlugin](https://webpack.js.org/plugins/progress-plugin/) to output percentage complete to the console.

Show progress when webpacking truffle

---

packages/db/src/meta/pouch/adapters/base.ts

Fix `add()` and `update()` methods to properly return results one-to-one with inputs.

Remove bad filter in @truffle/db pouch adapter

---

packages/db/src/network/index.ts
packages/db/src/project/index.ts
packages/db/src/project/test/integration.spec.ts
packages/db/src/resources/contractInstances.ts
packages/db/src/resources/types.ts
packages/db/src/test/contractInstance.spec.ts

This PR removes the non-nullability requirement for ContractInstance.creation.transactionHash to accommodate situations where it may be infeasible to obtain this information. As a result, ContractInstance.network may now represent any Network on which this instance is available at the end of that Network's historicBlock.
This means a couple things:
- `network` can no longer be an ID field, since this looser constraint means `network` is no longer unique; use `contract` and `creation` when computing ContractInstance IDs (in addition to the unchanged `address`).
- When doing `project.loadMigrate()`, if any input artifacts are missing a transactionHash, load the latest block as a Network resource and use that for any such ContractInstances.

Allow ContractInstances in @truffle/db without transactionHash information

---

packages/db/src/resources/projects/index.ts
packages/db/src/resources/projects/resolveContractInstances.ts

This PR adds the ability to look up a Project's single contract instance by address+network, rather than by contract+network.
This is a bit of an expedient hack; a better solution might be to generalize the filtering here, but I've avoided doing that now since this approach won't incur much of a performance penalty and minimizes the risk of breaking the existing mechanisms.

Allow Project.contractInstance lookup by address+network

---

packages/debugger/lib/txlog/selectors/index.js

So txlog had a problem where internal calls at the very end of a transaction wouldn't have their info properly recorded.  (I'm a little unclear on why this happens, or if the info we get is really meaningful, but we should at least include it.)  The problem was twofold:
1. Because it occurred at the very end, and rather than checking the jump location we check what's after the function definition node, this would get processed as a jump into internal sources (which it's not), so I had to special-case that;
2. Because it happend on the very last step, it would never get processed, as we don't update things happening after the last step!  So I had to special case that.
This is a bit of a hack, but the info is there now at least?

Bug fix (internal improvement?): Allow txlog to process internal calls happening at end of tx

---

packages/core/lib/commands/db/index.js

This edits the help output for the db command. This is an attempt to format it more similarly to the output for the other commands. I'm not attached to the changes made in this PR so we can close it if people don't like this as much. I'll post some screenshots to show the comparison. Here is the output with the changes made in this PR

Make minor edit to db help output

---

packages/codec/lib/export.ts
packages/codec/lib/format/utils/inspect.ts
packages/codec/lib/index.ts
packages/decoder/lib/decoders.ts
packages/decoder/test/current/contracts/CompatibleTest.sol
packages/decoder/test/current/test/compatible-nativize.js

This PR adds the `compatibleNativize` function to Truffle Codec, intended for use as part of the Truffle Contract rewrite.  It, uh, also adds some other stuff that in the process turned out to be missing.
The purpose of `compatibleNativize` is to act like `nativize`, except that instead of yielding a JS equivalent for use in the debugger, it yields the sort of thing Truffle Contract (by means of ethers) currently outputs.  There are some slight differences, but, as I'll describe below, I don't think they're a problem.
There are three `compatibleNativize` functions: `compatibleNativize`, which takes an individual value; `compatibleNativizeReturn`, which takes a `ReturndataDecoding` (assumed to be of type `"return"`, it returns `undefined` otherwise); and `compatibleNativizeEventArgs`, …

Internal improvement: Add compatibleNativize function (and some missing codec/decoder functions)

---

packages/migrate/Migration.js
packages/workflow-compile/index.js

@truffle/db is an optional dependency of Truffle because it uses sqlite3, which requires natively compiled components. If you can't install those, you won't be able to install @truffle/db. But of course Truffle shouldn't fail!
Problem is, we weren't actually `try`/`catch`-ing the corresponding `require()` statements!
This PR should fix that.
Ref: #3896

Handle situations where @truffle/db could not install

---

packages/preserve-fs/.gitignore
packages/preserve-fs/jest.config.js
packages/preserve-fs/lib/fs.ts
packages/preserve-fs/lib/index.ts
packages/preserve-fs/lib/types.ts
packages/preserve-fs/package.json
packages/preserve-fs/test/fs.fixture.ts
packages/preserve-fs/test/fs.test.ts
packages/preserve-fs/truffle-plugin.json
packages/preserve-fs/tsconfig.json
yarn.lock

This PR replaces #3722 and extracts only the @truffle/preserve-fs changes so it can be merged into develop without completing the other packages.
Changes from @gnidan's original implementation:
- Extract common types/interfaces into separate types.ts file
- Slightly reorder fs.ts to accommodate reading the file top-down
- Slight changes due to refactoring of @truffle/preserve
- Split up test file into fs.fixture.ts and fs.test.ts

Implement @truffle/preserve-fs

---

packages/debugger/lib/txlog/sagas/index.js
packages/debugger/lib/txlog/selectors/index.js

So, @cds-amal found a case where `txlog` recorded a return value for a function that has no return values.  Obviously the optimizer is to blame, but what exactly happened here?
Something crazy, that's what.  What we have here is a case where a function `f` jumps to the contract node, which then jumps to a function `g` (which was never actually called, to be clear, and there's no jump-in marking here), but then `g` returns (complete with jump-out marking, unbalancing the callstack), and since `g` has a return value, that return value gets attributed to `f`.
So to fix this, to the extent that we can, I added a check -- we won't process returns from functions we're not supposed to be in.  Specifically, when processing a return, we check, does the function we're currently in match the …

Internal improvement: Have txlog ignore returns from functions we shouldn't be in

---

packages/hdwallet-provider/package.json
packages/hdwallet-provider/src/index.ts
yarn.lock

Note that this PR is against the `eip-155` branch.
ethereumjs-tx is now named @ethereumjs/tx in its most recent version. This PR updates @truffle/hdwallet-provider to use the newer package.

Dependency update: Update ethereumjs-tx to @ethereumjs/tx

---

packages/compile-solidity/parser.js

This PR should hopefully address #3798, which has been plaguing us for a while.  (Hopefully there isn't some other second bug lurking causing the problem, and we won't have to reopen the issue later...?  But I fixed the one that @fainashalts managed to reproduce.)
The problem (or this problem, anyway) was in the Solidity import parser.  If the fake import was inserted at a spot where it couldn't legally go, the resulting compilation error would contain the fake import in its formatted message, but the error message wouldn't be about a bad import.  This meant that the error wouldn't get filtered out, and the fake import would get processed as a real import, causing the problem.
Now, the right solution to this might be to make sure that we have the correct type of error.  However I didn't …

Bug fix: Filter out fake import at end rather than start (fix compile errors)

---

packages/codec/lib/conversion.ts
packages/codec/lib/export.ts
packages/codec/lib/format/utils/inspect.ts
packages/codec/lib/index.ts
packages/debugger/test/data/calldata.js
packages/debugger/test/data/codex.js
packages/debugger/test/data/function-decoding.js
packages/debugger/test/data/global-const.js
packages/debugger/test/data/global.js
packages/debugger/test/data/helpers.js
packages/debugger/test/data/ids.js
packages/debugger/test/data/immutable.js
packages/debugger/test/data/more-decoding.js
packages/debugger/test/data/returnvalue.js
packages/debugger/test/data/yul.js
packages/debugger/test/endstate.js
packages/debugger/test/load.js
packages/debugger/test/reset.js
packages/debugger/test/txlog.js
packages/decoder/lib/decoders.ts
packages/decoder/lib/utils.ts
packages/decoder/test/current/contracts/CompatibleTest.sol
packages/decoder/test/current/test/compatible-nativize.js
packages/decoder/test/current/test/decoding-test.js
packages/decoder/test/current/test/downgrade-test.js
packages/decoder/test/current/test/wire-test.js
packages/decoder/test/legacy/test/shadow-test.js
packages/decoder/test/legacy/test/wire-test.js

**This PR is a breaking change to `@truffle/codec`.**
Redo of #3783 because it accidentally got merged early.  Please see description and all comments there.

Internal improvement: Add new, compatible nativize function and some missing codec/decoder functions

---

packages/contract/lib/contract/constructorMethods.js
packages/contract/lib/execute.js

This PR is a follow-on to #3923.  That PR added an extra network request with each transaction sent, and I wanted to fix that.
So, this PR adds a chain ID field to contract constructor objects; I called it `_chainId` because I was slightly worried about naming conflicts, but we can change it if that's not what you think it should be named.
Anyway, now when we send transactions, we check that field, and use the chain ID from there if possible; if not we fetch the chain ID from the network and then store it there.
Note, the way I wanted to do this actually would be to get it once in, say, `setProvider`, but we can't do that because it's not `async`.  So, I did the caching where it's used instead.  However I did have `setProvider` (or more generally, `configureNetwork`) set `this._chainId` …

Internal improvement: Cache chain ID to avoid extra network requests

---

packages/core/lib/console-child.js
packages/core/lib/console.js

This PR passes along the config to `truffle console` when the `--config` flag is used. This is useful for using the console with a custom config file.

Pass config file value to console if it exists

---

packages/preserve-to-filecoin/.gitignore
packages/preserve-to-filecoin/jest.config.js
packages/preserve-to-filecoin/lib/connect.ts
packages/preserve-to-filecoin/lib/dealstates.ts
packages/preserve-to-filecoin/lib/index.ts
packages/preserve-to-filecoin/lib/miners.ts
packages/preserve-to-filecoin/lib/storage.ts
packages/preserve-to-filecoin/lib/wait.ts
packages/preserve-to-filecoin/package.json
packages/preserve-to-filecoin/scripts/test.sh
packages/preserve-to-filecoin/test/filecoin.fixture.ts
packages/preserve-to-filecoin/test/filecoin.test.ts
packages/preserve-to-filecoin/test/utils/preserve.ts
packages/preserve-to-filecoin/truffle-plugin.json
packages/preserve-to-filecoin/tsconfig.json
packages/preserve/lib/ConsoleReporter.ts
packages/preserve/lib/control/controllers/ErrorController.ts
packages/preserve/lib/control/controllers/StepsController.ts
packages/preserve/lib/control/controllers/ValueResolutionController.ts
packages/preserve/lib/control/controllers/decorators.ts
packages/preserve/lib/control/controllers/index.ts
packages/preserve/tsconfig.json
yarn.lock

Changes from @gnidan's original implementation:
- Update dependencies
- Changes to accommodate updated preserve library
- Use filecoin.js for Filecoin interaction
- Remove setInterval/manual promise logic from waitForDealToFinish
- Split tests and fixture data into separate files
- Expand tests & integrate ganache
- Add storage deal options
- Report on current deal state
- Other smaller changes

Implement @truffle/preserve-to-filecoin

---

packages/hdwallet-provider/package.json
packages/hdwallet-provider/src/index.ts
yarn.lock

It looks like upgrading from `ethereumjs-tx` without extra configuration still left in some "Invalid sender"/EIP-155-related  problems. This PR downgrades this library until we want to spend time more carefully looking at this upgrade.

Bug fix: Downgrade @ethereumjs/tx

---

packages/artifactor/package.json
packages/codec/package.json
packages/contract-tests/package.json
packages/contract-tests/test/errors.js
packages/contract/package.json
packages/core/package.json
packages/db/package.json
packages/debugger/package.json
packages/decoder/package.json
packages/deployer/package.json
packages/environment/package.json
packages/external-compile/package.json
packages/interface-adapter/package.json
packages/migrate/package.json
packages/provider/package.json
packages/reporters/package.json
packages/require/package.json
packages/source-fetcher/package.json
packages/source-map-utils/package.json
packages/truffle/package.json
yarn.lock

This PR finally upgrades web3 to 1.3.5, after #3763 had to be reverted due to [1.3.4 printing warnings to the console](https://github.com/ChainSafe/web3.js/issues/3898).  That's fixed in 1.3.5, so we can finally upgrade!

Dependency update: Upgrade web3 to 1.3.5

---

packages/db-kit/src/cli/App.tsx
packages/db-kit/src/cli/hooks/useConfig.ts
packages/db-kit/src/cli/index.ts

This was all @gnidan's work, just pushing it so we can get it in develop. We are adding support for a custom config when using `db-kit`, accessed with `--config <your-custom-file>.js`.

Add support for custom config in db-kit

---

packages/core/lib/commands/develop.js

As reported by @cds-amal in [this issue](https://github.com/trufflesuite/truffle/issues/3909), the `--log` option for `truffle develop` has been broken. It is currently exiting after connecting to the existing develop session. This PR returns an unresolved `Promise` if `--log` is used so that logging can occur.

Bug fix: If --log is passed with truffle develop, leave the process open

---

packages/core/lib/debug/cli.js

Oops, this variable never got declared/defined...

Bug fix: Add missing variable in fetch-external error handling

---

.eslintrc.json

We didn't have the ESlint option turned on to prevent one from using undeclared variables.  It's annoying -- ESlint should catch undeclared variables!  So I'm turning that on.  I've also set `typeof: true` because by default, without that, it'll allow undeclared variables as an argument to `typeof`, and, well, we shouldn't have that either.
Note that this rule doesn't need a special `typescript-eslint` version, we just use the eslint version.
Of course, due to #3530, this will frequently have no effect at the moment, but, well, better than not having it, right? :-/

Internal improvement: Turn on no-undef ESlint option

---

packages/compile-common/src/profiler/requiredSources.ts

Addresses #3798.
Seems the problem was that if an imported source didn't exist, it would get added to the list of sources needing import processing, which would then fail because the source didn't exist.  This PR makes it so we just skip those.
Now, such situations will result in a Solidity compile error, like they should, rather than Truffle crashing.
(This one is my fault, sorry.  May have been an unnoticed interaction between two other changes I made...)

Bug fix: Skip import processing for sources that don't exist

---

packages/resolver/lib/sources/globalnpm.ts
packages/resolver/lib/sources/npm.ts
packages/resolver/test/fixtures/globalnpm/node_modules/otherPackage/build/OtherTest.json
packages/resolver/test/fixtures/node_modules/package/build/SomeArtifact.json
packages/resolver/test/globalnpm.ts
packages/resolver/test/npm.ts

When checking npm packages for artifacts, Truffle currently expects that package to have the structure of a Truffle project (i.e. it looks in `build/contracts` for artifacts). This PR also checks the `build` folder in those packages. This was prompted by https://github.com/trufflesuite/truffle/issues/3951 where a Uniswap package had artifacts located in a `build` directory.

Enhancement: Look inside "build" folder when resolving artifacts

---

packages/artifactor/package.json
packages/blockchain-utils/package.json
packages/box/package.json
packages/code-utils/package.json
packages/codec/package.json
packages/compile-common/package.json
packages/config/package.json
packages/db-kit/package.json
packages/decoder/package.json
packages/error/package.json
packages/hdwallet-provider/package.json
packages/interface-adapter/package.json
packages/interface-adapter/test/fabric-evm-getId.test.ts
packages/interface-adapter/test/quorum-decodeParameters.test.ts
packages/interface-adapter/test/quorum-getBlock.test.ts
packages/plugins/package.json
packages/preserve-fs/package.json
packages/preserve-to-buckets/package.json
packages/preserve-to-filecoin/package.json
packages/preserve-to-ipfs/package.json
packages/preserve/package.json
packages/provisioner/package.json
packages/resolver/package.json
packages/source-fetcher/package.json
yarn.lock

Truffle currently uses 5 different versions of TS. This PR bumps all packages to use ^4.1.4.

Dependency update: Bump TypeScript to ^4.1.4

---

packages/compile-solidity/package.json
packages/compile-solidity/test/test_supplier.js
packages/contract-schema/package.json
packages/contract-schema/test/solc.js
yarn.lock

So that Truffle uses the same version of Solidity that compile-solidity uses, this PR bumps the version in contract-schema and updates a test.
I hope this makes CI just a little bit faster.

Dependency update: Bump solc to 0.6.0 in contract-schema

---

packages/abi-utils/lib/arbitrary.test.ts
packages/abi-utils/lib/arbitrary.ts
packages/abi-utils/lib/normalize.test.ts
packages/abi-utils/lib/normalize.ts
packages/contract-schema/spec/abi.spec.json
packages/contract-schema/test/abi-schema.js

Solidity 0.8.4 introduces a new type of ABI entry: The error.  These basically look like events, except of course they're `"error"`, not `"event"`, and there's no `indexed` or `anonymous`.
This PR updates the contract-schema and abi-utils packages to account for this.  It adds the new type of ABI entry to the contract schema and adds appropriate tests.  It actually *doesn't* need to add the type to the abi-utils normalization, as this was actually already done earlier; but it does add it to the arbitraries.  (I went with a "noun noun" pattern for naming errors. :) )  And then of course I appropriately updated the tests of both normalization and the arbitraries.
I also added `"error"` to the list of keywords to avoid.
Also, while I was at it, I noticed that constructor parameters weren't …

Update contract-schema and abi-utils for Solidity 0.8.4 (add error type)

---

packages/debug-utils/package.json
yarn.lock

I've updated highlightjs-solidity for the new syntax in Solidity 0.8.4; this PR updates us to use that new version.

Dependency update: Update highlightjs-solidity to 1.0.22 (Update syntax highlighting for Solidity 0.8.4)

---

packages/core/lib/commands/watch.js

Currently the process is not being left open when `truffle watch` is executed and so "watching" does not actually happen. This PR returns an unresolved Promise so that the process stays open and "watching" will occur :)

Bug fix: Fix watch command

---

packages/source-fetcher/lib/sourcify.ts

This PR fixes the sourcify source-fetcher since they broke their interface and we have to update to match it.  Sorry there are no tests for source-fetcher at the moment; I tested it manually.
This PR does not add support for constructor arguments in the sourcify source fetcher.  I was going to, but I'm not entirely certain of the details, so I'm leaving it out for now and we can add it later; more important I think to just get this fixed first.

Bug fix: Fix sourcify support in source-fetcher

---

packages/core/lib/commands/unbox.js

The actual command line parses:
`truffle unbox [<box_name>] [destination] [--force]`  
But the command line help shows: 
` truffle unbox [destination] [<box_name>] [--force]`

Fixed bug in command line description of truffle unbox

---

packages/box/lib/utils/unbox.ts
packages/compile-solidity/compilerSupplier/loadingStrategies/Docker.js
packages/compile-solidity/compilerSupplier/loadingStrategies/VersionRange.js
packages/source-fetcher/lib/etherscan.ts
packages/source-fetcher/lib/sourcify.ts

A user reported [here](https://github.com/trufflesuite/truffle/issues/4016) that they were experiencing issues with making http requests while using Truffle from behind a proxy. It seemed reasonable to assume this had something to do with switching axios in for the deprecated request library (see https://github.com/trufflesuite/truffle/pull/3997). After a small amount of investigation I discovered that axios has an option for `maxRedirects` that defaults to 5. In an attempt to fix this http request issue, this PR increases `maxRedirects` to 50.

Bug fix: Add maxRedirects field to axios requests

---

packages/debugger/lib/evm/sagas/index.js
packages/debugger/lib/txlog/reducers.js
packages/debugger/lib/txlog/sagas/index.js
packages/debugger/lib/txlog/selectors/index.js
packages/debugger/test/txlog.js

Somehow when writing `txlog` I forgot to implement resetting it.  This has been a pain when trying to debug problems with txlog.
Unfortunately txlog is complicated enough that directly resetting it wasn't practical, so I reused a hack from `evm`: We store the initial call, and in order to reset, rather than attempting to directly reset to after the initial call, we reset to just *before* the initial call and then replay that call.  (At the beginning, there are normally two `txlog` actions; one to set the origin, the other to do the initial call.  We reset to inbetween these two, so we do keep the origin.)
Note this doesn't really alter the end result of `txlog`, but it will make debugging it substantially easier in the future.
I also added a test of this functionality.  Also as you can …

Internal improvement: Implement reset for txlog

---

packages/box/lib/utils/unbox.ts

If you cannot access `raw.githubusercontent.com` in China, then `error.response` does not exist. 
So we need to check `error.response` first, and then judge `error.response.status` in [here](https://github.com/trufflesuite/truffle/blob/develop/packages/box/lib/utils/unbox.ts#L34).
Otherwise you will get the following error.
```
$ truffle unbox metacoin-box
Starting unbox...
=================
✔ Preparing to download box
✖ Downloading
Unbox failed!
✖ Downloading
Unbox failed!
TypeError: Cannot read property 'status' of undefined
at /usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:41:1
at Generator.throw (<anonymous>)
at rejected (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:6:41)
at processTicksAndRejections …
```

Check if error.response exists

---

packages/source-fetcher/lib/sourcify.ts

On seeing #4046, I realized we ought to be doing the same thing in the Sourcify source-fetcher as well, since it also checks for 404s.  I also checked for other places we might need to make this change, but there don't seem to be any others, so it's just this.

Bug fix: Prevent error from missing error.response in source-fetcher

---

packages/debug-utils/index.js
packages/debug-utils/package.json
yarn.lock

I recently altered `highlightjs-solidity` so that instead of just registering a `solidity` language, it registers both `solidity` and `yul`.  The `yul` highlighting includes highlighting for things that don't appear in the Solidity assembly version of Yul, but appear only in the standalone version of Yul, and which previously would not have been highlighted.
So, this PR updates us to that, so we can now have proper highlighting for Yul.  It also gets rid of the hack we used to highlight Yul previously, now that Yul exists as a proper language for highlighting.

Update to proper Yul highlighting

---

packages/core/lib/debug/interpreter.js
packages/debug-utils/index.js
packages/debugger/lib/stacktrace/actions/index.js
packages/debugger/lib/stacktrace/reducers.js
packages/debugger/lib/stacktrace/sagas/index.js
packages/debugger/lib/stacktrace/selectors/index.js

This is sort of a primitive hack to address #4026; not sure it should be considered a full resolution of it.
This PR adds two commands to the debugger CLI, and adds selectors to the debugger library to support this.  The `Y` command returns to the last place an error was through.  The `y` command, only usable at the end of the trace, returns to the final error, and does nothing if the trace ends on the final error.
Since the debugger doesn't currently step backwards (#3854), this is done inefficiently by resetting and then stepping to the required step.  But, it'll do for now?
In order to do this, I've added `innerReturnIndex` to the `stacktrace` state.  It keeps track of the index of the last error.  Note that unlike `innerReturnPosition` and `innerReturnStatus`, it's only set to `null` …

Enhancement: Add `y` and `Y` commands to debugger to return to last error

---

packages/debugger/lib/txlog/actions/index.js
packages/debugger/lib/txlog/reducers.js
packages/debugger/lib/txlog/sagas/index.js
packages/debugger/lib/txlog/selectors/index.js
packages/debugger/test/txlog.js

Addresses #3822.  However I called the field `returnData` rather than `returndata`.
In more detail:
The original version of txlog would track return values for functions, as well as revert messages, but it wouldn't track raw binary returned from a fallback function.  That's because the ability to do this in Solidity was only introduced in 0.7.6!  So we didn't track it as it wasn't something that should ordinarily happen.
So, now we do that.  This didn't require any big code changes, because for fallback functions that can return data, `codec` already includes the raw data as a possible return decoding.  So we do it the same way we do `returnValues`, just instead of looking for the `function` call type and the `return` decoding type, we look for the `message` call type and the …

Internal improvement: Add `returnData` to txlog

---

packages/core/lib/debug/interpreter.js
packages/debugger/lib/stacktrace/reducers.js
packages/debugger/lib/stacktrace/selectors/index.js

Oops!  The `y` command (#4029) had nothing to make sure it only returned to *errors*.  Now we check the return status when checking whether to update the index.
Also I renamed `innerReturnIndex` to `innerErrorIndex` to match this change in behavior.  That'd be a breaking change if we had released `y`, but we hadn't yet, so whatever. :)

Bug fix: Prevent Y from returning to non-error returns

---

packages/debugger/lib/data/sagas/index.js
packages/debugger/lib/data/selectors/index.js
packages/debugger/lib/evm/selectors/index.js
packages/debugger/test/data/ids.js

Addresses #4055.
This PR solves a problem where function arguments would appear to be corrupted after the use of a bare block (a block not part of a control structure such as an `if` or a `while`) that declares local variables.  After such a block, Solidity has to pop its local variables from the stack.  However, if the block is not part of any control structure, this popping, for whatever reason, gets sourcemapped to the function definition.
This means we hit the function definition again, so the debugger thinks that the function's arguments are now at the top of the stack, and it overwrites their previous location with an incorrect location, thus leading to the incorrect values seen for them.
There were two possible ways to fix this.  The more robust way would be to make sure that …

Bug fix: Prevent function argument corruption after bare block

---

packages/db/src/meta/collections.ts
packages/db/src/meta/data.ts
packages/db/src/meta/pouch/adapters/base.ts
packages/db/src/meta/pouch/index.ts
packages/db/src/meta/pouch/types.ts
packages/db/src/meta/pouch/workspace.ts

Currently, @truffle/db defines the [`Workspace<C>`](https://www.trufflesuite.com/docs/truffle/db/interfaces/meta.workspace.html) interface for use across many modules, implementing that workspace directly via the class hierarchy of PouchDB adapters (i.e., the base [`Databases<C>`](https://www.trufflesuite.com/docs/truffle/db/classes/meta.pouch.adapters.base.databases.html) class).
In order to support future work of allowing schema migrations, we can't abide the constraints defined by `Workspace<C>` - this interface accepts/returns data in _the current schema_. We need an interface that can read/write to our PouchDB adapter via _past versions of the schema_ as well.
This PR removes `implements Workspace<C>` from the PouchDB adapter classes, implementing instead the new `Adapter<C>` …

Separate PouchDB adapter interface from existing Workspace interface in @truffle/db

---

packages/core/lib/debug/interpreter.js
packages/debug-utils/index.js
packages/debugger/lib/controller/sagas/index.js

Addresses #3827.  **Breaking change to `@truffle/debugger`** (at least technically).  (Note: I could go back and do this in a non-breaking way if people think that's important.)
This PR makes it so that sub-line breakpoints -- where you stop on a specific source location rather than a specific line, the sort you set by just pressing `b` rather than giving it an argument -- now work with Vyper and Yul.  Previously these didn't work because they were based around AST nodes, but we don't have ASTs for Vyper (OK, we have them, but we don't use them), and we only sometimes have ASTs for Yul.  This PR makes it so that instead of being based on AST nodes, these breakpoints are based on source ranges directly, with `start` and `length` fields replacing the old `node` field.  This obviously …

Bug fix: Allow node-based breakpoints to work without AST (fix sub-line breakpoints for Vyper and Yul)

---

packages/expect/.gitignore
packages/expect/package.json
packages/expect/src/index.ts
packages/expect/test-d/index.ts
packages/expect/test/index.js
packages/expect/tsconfig.json
yarn.lock

**:information_source: This is a minor release for @truffle/expect**
This PR converts @truffle/expect in order to offer type-safe guarantees of the post-conditions of using `expect.options`, etc.
This also adds `expect.has(options: {}, key: string)`, as a more simple form of `expect.options(options: {}, key: string[])`.
**Note**: for `expect.one()`, which is designed for either-or cases, the type guard asserts _exactly one_ key so as to facilitate likely usage (`expect.one(options, ["a", "b"]); const x = "a" in options ? options.a : options.b`), and also because taking the combination of all allowable expected values is just kind of excessive work for the type-checker. We may want to change the runtime behavior here, assuming it won't cause hard-to-fix breakages.
Post conditions for the …

Convert @truffle/expect to TypeScript

---

packages/config/src/configDefaults.ts

Partially addresses https://github.com/trufflesuite/truffle/issues/3992
Removes default gasPrice when none is specified as part of the network config.
It will use the last few blocks median gas price instead, as per web3js documentation: https://web3js.readthedocs.io/en/v1.2.0/web3-eth.html#getgasprice

Remove default gasPrice

---

packages/interface-adapter/lib/adapter/types.ts
packages/interface-adapter/lib/adapter/web3/index.ts
packages/migrate/Migration.js
packages/reporters/reporters/migrations-V5/messages.js
packages/reporters/reporters/migrations-V5/reporter.js
packages/truffle/test/scenarios/migrations/describe-json.js

This PR moves gas calculations and units from the reporter to the interface-adapter. That way we can bring a new architecture without branching code in the reporter.
In summary:
- Unit print values are no longer hardcoded in the message and have been added as part of the data passed.
- In order to operate with gas values to calculate totals, interface adapter returns BN values, as well as a method to convert the value to the final unit that we want to display. Conversion needs to occur at the end as BN does not support decimals.
- Added a couple of assertions to existing tests to verify that units are being added to the data payload.

Allow different blockchain network architectures in @truffle/reporters

---

packages/config/src/index.ts
packages/core/lib/commands/unbox.js
packages/core/test/lib/commands/unbox.js
packages/events/EventManager.js
packages/events/Subscriber/index.js
packages/events/SubscriberAggregator.js
packages/events/defaultSubscribers/compile.js
packages/events/defaultSubscribers/unbox.js

**Note**: This is a breaking change for @truffle/events
This PR updates the EventManager to accept and pass a `quiet` parameter instead of `muteLogging`. `quiet` is used in the rest of Truffle and it will be up to the handlers themselves to decide what `quiet === true` means. In the case of unboxing, if this option is passed then it will not display any of the spinners and show no output.

Make spinners for 'unbox' repect the `--quiet` option

---

packages/source-fetcher/lib/etherscan.ts

Addresses #4071.  See that issue for why I'm doing this.
The header is only added in the single-source Solidity case, because that's the only case where Etherscan adds a header on the website.
I tested this manually and with this change the line numbers now match up.
Note that the header we're using contains a generic placeholder in place of the date, since there doesn't seem to be any way for us to get the submission date from the API (and even if we could I'm not sure it would be so important to do!).

Bug fix: Add header to single sources downloaded from Etherscan

---

packages/codec/lib/abi-data/allocate/index.ts
packages/debugger/lib/data/selectors/index.js

This PR fixes two debugger/decoder crashes, one of which I accidentally introduced in #4015, the other of which I accidentally introduced in #4029.

Bug fix: Fix two debugger/decoder crashes

---

packages/codec/lib/contexts/utils.ts

Quick followup to #4094, I just realized that I forgot to account for the case of `null` (which is an object, but which you better not try to access the properties of).  Mind you, this should never actually happen, barring an extremely unlikely coincidence, but just to be safe, I'm putting in checks for it here.  (I mean, a number of the cases I check for here should never happen...)

Bug fix: Prevent (extremely unlikely) crash from cbor null

---

packages/compile-solidity/compilerSupplier/loadingStrategies/LoadingStrategy.js
packages/compile-solidity/compilerSupplier/loadingStrategies/Local.js
packages/compile-solidity/compilerSupplier/loadingStrategies/VersionRange.js
packages/core/lib/command.js
packages/truffle/test/scenarios/migrations/unhandled-rejection.js
packages/truffle/test/sources/migrations/unhandled-rejection/contracts/Migrations.sol
packages/truffle/test/sources/migrations/unhandled-rejection/migrations/1_initial_migration.js
packages/truffle/test/sources/migrations/unhandled-rejection/truffle-config.js

So, here's a hypothesis for the `uncaughtException` business in compile-solidity.
Solidity upgraded Emscripten from v1.35.4 to v1.37.21 in solc v0.5.1 (in [this PR](https://github.com/ethereum/solidity/pull/4486)). Inspecting the Emscripten changelog, [this issue](https://github.com/emscripten-core/emscripten/issues/4392) was closed as part of v1.36.6. Looks like the fix here may have changed buggy behavior that left `uncaughtException`s to linger.
Since we support old Solidity and need to handle pre-v0.5.1 behavior, this PR proposes that we alter the listener removal by first capturing the listeners that existed before loading solc and then removing only those listeners that are new after loading solc.
This is a different proposed solution than #4091... I haven't done any digging re: …

Only remove listeners left around by soljson

---

packages/core/lib/debug/interpreter.js
packages/debugger/lib/controller/selectors/index.js

Addresses #4049.  Or at least partly does?  It's something of a stopgap, but I don't see how we're going to do better for now.
Currently, when you try in the CLI debugger to add a breakpoint in a specified file, if there are multiple matching files, the CLI asks for disambiguation.  However, as per #4049, sometimes some sources might be named identically.  So this PR makes it so that if there's one matching file whose source path is a substring of all other matching source paths -- including, say, if there are a bunch of source paths which are identical -- then instead of asking for disambiguation, it'll print a warning and then add (or remove) them all.
In order to do this, I factored the breakpoint-setting function a bit, but be warned, it's still a big mess of imperative code that …

Enhancement: Allow setting breakpoints when two sources have the same name

---

packages/debug-utils/package.json
yarn.lock

I've made it so that highlightjs-solidity 1.1.1 highlights the `verbatim` builtin new in Solidity assembly in 0.8.5, this PR updates us to use that.

Dependency update: Update syntax highlighting for 0.8.5

---

packages/box/box.ts
packages/box/test/box.js

- don't await `setupTempDirectory`. The await promise seems to be
necessary for one test, which is rewritten to work without promise
complexity.
- don't await `setUpBox`. It is a synchronous function and the awaited
value is not used.

Remove unnecessary awaits & simplify associated test

---

packages/core/lib/console-child.js

To silence a warning that occurs whenever a command is run in the console, this PR includes the crypto library with the get-random-values package. This warning comes from a dependency of an ENS package used by Truffle which warns if there is not a good source for randomness.
This PR prevents the above warning from displaying in these cases. This is identical to what is done in `cli.js` [here](https://github.com/trufflesuite/truffle/blob/develop/packages/core/cli.js#L6-L10).

Bug fix: Add crypto lib and method to silence warning

---

packages/debugger/lib/data/selectors/index.js

Addresses #4120.
This PR fixes a bug in how I implemented #4015.  In it, when decoding an error, we attempt to get the node where the error occurred from the stacktrace.  However, I attempted to look up the node, by its ID, in `data.current.scopes.inlined`.  This doesn't work, because `data.current.scopes.inlined` only contains information about the current compilation, and the error might have occurred in a different compilation.  So, instead, we have to look it up in `data.views.scopes.inlined`, which contains information about all compilations.  Looking it up in there requires knowing the source ID in addition to just the node ID, so we now get both the source ID and the node ID from the stacktrace, and then use those with `data.views.scopes.inlined` to get the actual node.  We then …

Bug fix: Fix debugger crash from cross-compilation revert

---

packages/debugger/test/ast.js

This test has been timing out a bunch lately, upping it.

Internal improvement: Up timeout in debugger test

---

packages/artifactor/index.ts
packages/artifactor/tsconfig.json
packages/compile-common/src/profiler/getImports.ts
packages/compile-common/src/profiler/profiler.ts

- @truffle/artifactor: Minor refactor to remove code duplication and show warning if `contract_name` is missing but `contractName` is present.
- @truffle/compile-common: Make properties from `ProfilerConfig` type optional, as they are currently not being passed in some instances of @truffle/compile-vyper.
None of these are breaking changes.

Minor corrections for Tezos compiler upgrade

---

packages/box/box.ts
packages/box/test/normalizeSourcePath.js

This PR allows users to name their boxes without constraints and enforces rules for repos in the `truffle-box` org.
- `truffle-box` repos must end in `-box`, this allows for `truffle unbox bare`
- non `truffle-box` repos can be any valid repo name
Unboxing these two should work:
1. `truffle unbox azure-samples/Blockchain-Ethereum-Template`
1. `truffle unbox smartcontractkit/box`

Fix unbox to remove repo name restriction

---

packages/compile-common/src/sources.ts
packages/compile-solidity/run.js
packages/compile-solidity/test/test_metadata.js
packages/compile-vyper/vyper-json.js

Addresses #4119.
Per discussion there, this PR changes our input to the Solidity compiler so that the Truffle project directory will be replaced (in input to the Solidity compiler) with `"project://"`.  In addition to affecting the metadata, this also affects the `absolutePath` field on the AST, although we don't currently using that.  It does *not* affect the `sourcePath` field in the artifacts.
Note that this only affects sources that live in the project directory.  Sources imported from, e.g., NPM, will be unaffected.  However, since sources imported from NPM will be given by an NPM path rather than an absolute file path, this is fine.
What about FS sources living outside the project directory?  Well, those probably just won't work anymore, as the compiler won't be able to find them. …

Replace project directory in metadata with "project://"

---

packages/core/lib/debug/mocha.js

Addresses #4150.
Seems we accidentally broke this a while back when we changed out `CLIDebugger` is invoked, and nobody noticed.  Updated in-test debugging to use the new invocation and now it works fine.

Bug fix: Fix in-test debugging

---

packages/artifactor/package.json
packages/codec/package.json
packages/contract-tests/package.json
packages/contract/package.json
packages/core/package.json
packages/db/package.json
packages/debugger/package.json
packages/decoder/package.json
packages/deployer/package.json
packages/environment/package.json
packages/external-compile/package.json
packages/interface-adapter/package.json
packages/migrate/package.json
packages/provider/package.json
packages/reporters/package.json
packages/require/package.json
packages/source-fetcher/package.json
packages/source-map-utils/package.json
packages/truffle/package.json
yarn.lock

Updates web3 to 1.4.0.
This PR does *not* add support for access lists.  I think that's better saved for a separate later PR.

Dependency update: Update web3 to 1.4.0

---

packages/compile-solidity/run.js
packages/compile-solidity/test/test_metadata.js
packages/truffle/test/scenarios/solidity_testing/ImportEverything.sol

Alteration to #4137.  Double-slashes break the ability of contracts in `test` to import projects in `contract`.  Replacing with single slashes so that these imports can work.

Bug fix: Change "project://" to "project:/"

---

packages/config/src/configDefaults.ts
packages/core/lib/commands/console.js
packages/core/lib/commands/develop.js
packages/core/lib/console.js
packages/core/package.json
packages/core/test/lib/console.js
packages/core/test/sources/moreUserVariables.js
packages/core/test/sources/nameConflicts.js
packages/core/test/sources/userVariables.js

In https://github.com/trufflesuite/truffle/issues/2472 it was suggested to add a way of providing Truffle with scripts to be run when starting the console environment. This PR provides the ability so specify paths to scripts in `truffle-config.js`. 
Users can now add a `console.require` property which will either be a string or an array. If the user supplies a string, it must be a path to a JS file that will be `require`d. The `module.exports` must be a JS object with named keys. The keys will be variables set in the console environment and they will be set to the value of their value. So for example, consider the case where the user supplies the following JS:
```
// user-specified JS file
breakfast: "yes please"
};
```
When the user starts up the console via `truffle …

Feature: Run user-supplied scripts to populate the console

---

packages/box/lib/utils/unbox.ts
packages/box/test/utils-unbox.js

This PR preserves `axios` errors that could occur during box validation. Previously all non 404 errors were assumed to be a network issue. Hopefully we'll have better information to support issues like #4152

Preserve non 404 errors when unboxing

---

packages/codec/lib/compilations/utils.ts

when sourcePath is `undefined`, `inferLanguage` throws `TypeError: Cannot read property 'endsWith' of undefined`.

fix inferLanguage error with undefined sourcePath

---

packages/core/lib/debug/cli.js

This expression, `this.config.fetchExternal`, is always true due to being in an `else` block for an `if (!this.config.fetchExternal)`.  So, I just replaced it with `true`.  Presumably this is here because there didn't used to be a branch there, but now there is, so, yeah, this can now be simplified.

Internal improvement: Replace always-true expression with true

---

packages/debug-utils/index.js
packages/debug-utils/package.json
yarn.lock

I recently published highlightjs-solidity 1.2.0, which adds syntax highlighting for operators and punctuation.
This PR updates us to that version of highlightjs-solidity, and adds colors in `trufflePalette` for operators and punctuation.  (And also the lack of a color for `property`, in case that gets added in the future.)
I went with blue for operators and purple for punctuation, and, well, it looked fine when I tried it so I didn't revise it any further.

Enhancement: Add syntax highlighting for operators and punctuation (in debugger)

---

packages/truffle/test/scenarios/commands/build.js
packages/truffle/test/scenarios/migrations/unhandled-rejection.js
packages/truffle/test/scenarios/solidity_testing/ImportEverything.sol
scripts/ci.sh
scripts/geth.sh

This PR allows CI to run all integration tests and follows web3's lead to pin GETH to v1.10.3. It should be noted that web3 didn't document a reason to pin and we should probably follow up with them (@gnidan ?)

Run all integration tests

---

packages/code-utils/src/opcodes.ts

Since London is already out on testnets.  This probably won't do very much at the moment, as I doubt many people are yet using this opcode (it's not in Yul yet), but, still, here it is.

Add BASEFEE opcode to code-utils

---

packages/compile-common/src/sources.ts

Addresses #4166.  To avoid having to create regexes on the fly (which requires escaping), I just used the simpler method of skipping the replacement if `path.sep === '//'`.
I left in the code below for dealing with Windows drives just as a just-in-case thing, even though we can probably get rid of that now what with the `project:/` thing.

Bug fix: Don't change backslashes to slashes on Linux

---

packages/compile-solidity/run.js

So, ever since we stopped throwing our own source-not-found errors and exposing the Solidity ones, there's been this annoyance that the Solidity source-not-found errors end with this confusing "File import callback not supported" message.  What does that mean?  The error would be clearer if it were just stripped off.  Well, today I realized we can just, y'know, do that!  So I made this PR to strip off that suffix when we see it.

Make source not found error clearer

---

packages/config/src/configDefaults.ts
packages/config/src/index.ts
packages/core/lib/command.js
packages/core/lib/commands/test/index.js
packages/core/test/commands.js

This PR adds a `--grep|-g` command line option to `truffle test` and it works exactly like the `--grep` option for mocha. [See the mocha docs](https://mochajs.org/api/mocha). Basically you can provide a regex for mocha to search the test descriptions. It will then only run the tests whose descriptions match.
One thing to note with this PR is that there is an order of precedence when it comes to setting parameters in the `truffle-config.js` and on the command line with flags (`--bail`). We have decided to let the command line flags take precedence over the settings in `truffle-config.js`. So in other words if you set `bail = false` in your `truffle-config.js` and pass it `--bail` on the command line, `bail` will be set to `true`.
One other note here, I am trying to make it a convention in …

Feature: Add `--grep` option to `truffle test`

---

packages/compile-common/src/profiler/getImports.ts
packages/compile-common/src/profiler/requiredSources.ts

This PR is intended to address #4193.  **This needs to be tested on Windows!**  This is a quick PR that I think should resolve the problem, but I am working without actual testing here.
As best I can tell -- remember, I'm working without testing here -- the problem is that resolution of relative paths is causing aliasing of sources.  Because some paths are being given with slashes, but import resolution leads to the use of backslashes instead.
~Except, hm, we might need to apply this imports too, not just at the beginning?  Uh, I guess I need to go make more changes to this...~ OK, made that change.

Bug fix: Use backslashes on Windows while resolving imports

---

packages/preserve/package.json

Windows cannot reference paths with `../..`.   Reference the command directly as `typedoc` is a preserve dependency and should be available for a script.

Fix Truffle build on Windows.

---

packages/compile-solidity/test/sources/badSources/Imported.sol
packages/compile-solidity/test/sources/badSources/Nonrelative.sol
packages/compile-solidity/test/test_nonrelative.js
packages/resolver/lib/sources/fs.ts

This PR addresses #4161, sort of, by just disallowing such imports.
So, the problem in #4161 regards what happens when you use FS-resolved direct imports that are neither absolute nor explicitly relative.  The problem is, there's not really any reasonable way to make these work.
Truffle tries to give each source a canonical path -- not necessarily a file path, but a path it's going to pass with it to solc.  Normally when making file-system imports, you use a relative path.  This works with Truffle and with Solidity; Truffle can find the source you're looking for to pass to solc, and Solidity can resolve the relative path among the sources you pass to it.  This also works with non-FS imports for the same reasons.
But what if you use a direct import?  In this case, Solidity performs no …

Bug fix: Disallow non-absolute non-relative FS imports

---

packages/db/src/project/assignNames/getCurrent.ts

Inspired by https://github.com/trufflesuite/truffle/issues/3981
This PR fixes a bug caused by network names with characters that, when inserted into a GraphQL query, would break the query. For example, the network name "my-network" would break the query due to the "-". The PR sanitizes the name with a regex.

Bug fix: Sanitize network name for graphql query in db

---

packages/resolver/lib/sources/truffle/index.ts
packages/resolver/package.json
packages/resolver/test/truffle.js

This PR fixes truffle solidity imports on Windows  (`import truffle/Assert.sol`). 
See: #400 , and [windows CI test results](https://github.com/trufflesuite/truffle/runs/3157919036#step:6:283). This branch is working towards getting a windows CI workflow.
Note: couldn't figure out a way to test resolving `DeployedAddress`

Fix truffle resolve on windows

---

packages/provider/error.js

Note:
- "--rpc" option have been deprecated at v1.10.0
- Apply "--http" instead of "--rpc" if use Geth newer or equal v1.10.0

[chore] Update error message

---

packages/core/lib/commands/console.js
packages/core/lib/commands/debug.js
packages/core/lib/commands/develop.js
packages/core/lib/commands/test/index.js

This PR continues work from https://github.com/trufflesuite/truffle/pull/4179 and standardizes the format in which options are listed in the command files' help.

Standardize option aliases

---

packages/artifactor/package.json
packages/codec/package.json
packages/contract-tests/package.json
packages/contract/package.json
packages/core/package.json
packages/db/package.json
packages/debugger/package.json
packages/decoder/package.json
packages/deployer/package.json
packages/environment/package.json
packages/external-compile/package.json
packages/interface-adapter/package.json
packages/provider/package.json
packages/reporters/package.json
packages/source-fetcher/package.json
packages/source-map-utils/package.json
packages/truffle/package.json
yarn.lock

This updates web3 to 1.5.0, which adds London support.  Note that this PR does not add any sort of London support into Truffle; that will be done separately later.  This PR just updates web3 to a version of web3 that supports London.

Dependency update: Update web3 to 1.5.0

---

packages/contract/lib/utils/index.js

This PR adds support for London transactions, minus access lists, to Truffle Contract.
This PR is a draft because it needs to be tested.  Unfortunately, it can't be tested with Ganache at the moment, because Ganache doesn't support London yet.
Obviously, prefer to wait until Ganache supports London before doing this, but London is coming soon and after discussing things with @gnidan we decided this is important enough not to wait.  Access lists are less important, so for now we're still going to wait on that one.

Add London support (minus access lists) to Truffle Contract

---

packages/hdwallet-provider/package.json
packages/hdwallet-provider/tsconfig.json

While working on hdwallet-provider I notices that the web3 types are not necessary in this package. This PR removes them from hdwallet-provider.

Remove web3 types from hdwallet-provider

---

packages/core/lib/commands/init/initSource/truffle-config.js

This PR adds commented db settings to `truffle-config.js` so that a developer can quickly enable and configure local db storage.

Add commented storage options for @truffle/db

---

packages/fetch-and-compile/package.json

The `fetch-and-compile` package uses Typescript, but we forgot to include it as a devDependency!  This PR adds it.

Internal improvement: Add missing typescript devDependency

---

packages/debug-utils/package.json
yarn.lock

Addresses #4235.
Updates highlightjs-solidity to a version that includes [this](https://github.com/highlightjs/highlightjs-solidity/pull/51) PR.  So, we'll fix highlighting problems, at the expense of no longer having punctuation highlighting.

Update highlightjs-solidity to 1.2.1

---

packages/core/lib/commands/init/copyFiles.js

This file refers to `boxContents`, but no such variable exists.  It looks like `projectFiles` was meant.

Bug fix: Fix incorrect variable name

---

packages/source-fetcher/lib/etherscan.ts
packages/source-fetcher/lib/sourcify.ts
packages/source-fetcher/package.json
yarn.lock

Addresses #4231.
This PR makes it so that we use an external package, namely, `async-retry`, for the retry logic in source-fetcher, rather than rolling our own.  Whereas our retry logic was "just try it twice than give up", async-retry lets us do exponential backoff.
This is mostly pretty straightforward, but, some notes on this:
1. I went with 3 retries.  I think that means 3 retries past the initial one?
2. In the Etherscan fetcher, I had to decide on an initial timeout; I went with 1.5 times the timer delay?
3. I also had to decide on one for the Sourcify fetcher... I just left it at its default of 1 second.
4. In the Etherscan fetcher, I moved the wait/set timer logic from `getSuccessfulResponse` into `makeRequest`; note that during a retry this logic shouldn't be relevant (because …

Internal improvement: Use `async-retry` in source-fetcher for retry logic

---

packages/codec/package.json

Addresses #4251.  Abi-utils was classified as only a devDependency, presumably because that was true at one point, and this never got corrected.  This fixes it.

Mark abi-utils as dependency of codec

---

packages/fetch-and-compile/lib/fetch.ts

So, uh, turns out that issue #4237 was never actually a real issue.  Sorry about that.  Actually `quiet` works just fine!
The real issue was that in pulling out `fetch-and-compile` into its own package, the `quiet` option went missing.  This PR adds it back in.
Notionally we could just add it where `fetch-and-compile` is invoked, rather than inside `fetch-and-compile` itself in case people want to occasionally use it non-quiet?  But I figured I'd do it this way for now as this is easier and I can't think of such a use case.

Bug fix: Turn on quiet option in fetch-and-compile

---

packages/compile-common/src/sources.ts
packages/compile-solidity/test/test_nonrelative.js

Addresses #4165.
So, the actual effect of this PR isn't actually to require things to be in the project directory (that was already typically the case);
rather it's to bar getting around it by starting your import path with `"//"` or the like.  Issue #4165 was followed because you could import absolute paths if you just started them with `"//"`.  This PR ends that loophole -- all paths passed to the Solidity compiler have to be either relative, or begin with the project directory (as a string; no starting with `"//"`).  So, now such imports will fail, because their source got filtered out.
Note: @cameel raises the point that we might want to test this with Windows.  It's possible that due to the normalization, we should actually be checking for an an initial `"/"` rather than using …

Bug fix: Disallow absolute import paths not beginning with project root (for real)

---

packages/codec/lib/ast/import/index.ts
packages/codec/lib/compiler/types.ts
packages/codec/lib/compiler/utils.ts
packages/codec/lib/special/decode/index.ts
packages/debugger/lib/evm/reducers.js
packages/debugger/lib/web3/sagas/index.js
packages/debugger/test/data/global.js
packages/debugger/test/helpers.js
packages/debugger/test/stacktrace.js
packages/decoder/test/current/test/compatible-nativize.js
packages/source-map-utils/index.js

This PR does two things, which are basically unrelated, except that (for reasons you'll see) I had to do the second to get the tests passing for the first.
The main thing this PR does is to add support in the debugger for Solidity's `block.basefee` builtin, introduced in Solidity 0.8.7, because I forgot to do this when Solidity 0.8.7 came out.  Note that this builtin will only be displayed on Solidity versions 0.8.7 or later; on older versions it won't show up.  This involved adding a new value to the `SolidityFamily` type in `codec`.
Speaking of which, I got tired of updating all the `case` statements there, so I updated most of them to only list out earlier versions of Solidity that behaved differently, and have all versions with the current behavior just be `default`.  That way most of …

Add support for block.basefee in debugger, and fix a bug with internal function pointers

---

packages/compile-solidity/run.js
packages/events/defaultSubscribers/compile.js
packages/truffle/test/scenarios/commands/install.js

This PR adds support for compilation notices, coming in Solidity 0.8.8.  It doesn't add very much support, but it adds enough to ensure they won't break things.  Note that since Solidity 0.8.8 isn't out yet I didn't add any tests; I did test it manually with the soljson linked [here](https://github.com/ethereum/solidity/issues/11508#issuecomment-908397096).  (A danger of working ahead!)
Basically, as of Solidity 0.8.8, instead of just compilation warnings (with severity `"warning"`) and errors (with severity `"error"`), there will also be compilation notices, with severity `"info"`.  These would cause a problem for our existing code, in that in our existing code, when getting the errors, rather than checking for severity *equal to* `"error"`, we instead check for severity *not* equal to …

Add support for compilation notices

---

.github/workflows/nodejs.yml

The `yarncheck` job takes a while.  This PR aims to speed it up, and also to simplify it by removing the jury-rigged mechanism I came up with for it.
To speed it up, we can pass the `--ignore-scripts` option, so that it will only do the `yarn install` part of things, and not run all the prepare scripts.  (Thanks to @gnidan for finding this option; I missed it.)
But also, we can pass the `--frozen-lockfile` option, which makes it so that if the lockfile needs to be modified, instead it fails -- exactly what we want!  So we can remove my jury-rigged mechanism for seeing if the lockfile changed; yarn will do that for us.
So yay, it's simpler now and should be faster too!
I also removed my custom error message, we'll see if I need to add that back in. :P
**Edit**: ~~I hit an engine problem; I …

Internal improvement: Speed up and simplify yarncheck

---

packages/config/src/configDefaults.ts
packages/contract/lib/execute.js
packages/core/test/migrate.js
packages/interface-adapter/lib/adapter/types.ts
packages/interface-adapter/lib/adapter/web3/index.ts

This addresses the remaining part of #3992 
Prior to this PR, Truffle's `getGasEstimate()` function never actually estimated gas. There was a hardcoded default gas value in the configuration defaults that was added to the params before we hit the gas estimation function. The gas estimation function would check for gas in the params before estimating, and that value was never empty. 
A workaround was to add `gas: 0` to the config, which would force the estimation function to do the estimation. This was not ideal as it is not clear what is actually happening and why. This fix removes the default gas value to ensure that gas is estimated if the user does not provide their own gas in the transaction params.
*Note: user-provided gas params are still respected, and gas estimation will not occur …

Use gas estimate as default transaction gas limit

---

packages/codec/lib/export.ts
packages/decoder/test/current/contracts/CompatibleTest.sol
packages/decoder/test/current/test/compatible-nativize.js

So, the new `nativize` function in codec (as opposed to the old unsafe one) is supposed to match ethers's behavior, right?  Well, um, turns out ethers has a special behavior for the empty bytestring that I didn't realize... instead of being nativized as `"0x"`, it's rendered as `null`!  This is seems to me to be pretty dumb, but, well, the point is to be compatible, so, uh, yeah, I've changed it. :-/  (Fortunately this isn't yet actually used anywhere...)
I didn't bother adding a test of this, but I could if people think it's necessary.

Bug fix: Fix ethers-compatible nativization of empty bytestring

---

.github/ISSUE_TEMPLATE.md

I believe @CombsieZ was going to handle this as part of the website update, but since that seems to be taking a while and the issue came up again recently, I figured, why not do this now?
Feel free of course to nitpick the phrasing, but I thought I should at least put up a PR for this. :)

Internal improvement: Change Gitter link in issue template to Zendesk link

---

packages/artifactor/package.json
packages/codec/package.json
packages/contract-tests/package.json
packages/contract/package.json
packages/core/package.json
packages/db/package.json
packages/debugger/package.json
packages/decoder/package.json
packages/deployer/package.json
packages/environment/package.json
packages/external-compile/package.json
packages/interface-adapter/package.json
packages/provider/package.json
packages/reporters/package.json
packages/source-fetcher/package.json
packages/source-map-utils/package.json
packages/truffle/package.json
yarn.lock

Updates web3 to 1.5.3, now that that's out.  Should close a bunch of dependabot alerts.  Btw I tried to add @dongmingh as a reviewer on this and I couldn't?

Update web3 to 1.5.3

---

packages/core/lib/testing/TestRunner.js

I didn't notice this before -- printing of events with no arguments was broken due to some code that assumed that events must have arguments.  It looks like this was supposed to be an `if` block or something, it was just a bare block?  Anyway I added the missing conditional and now it doesn't crash...

Bug fix: Fix printing of events with no arguments

---

packages/core/lib/commands/test/index.js

When testing Truffle projects, a default ganache configuration is set up when users do not have a network configuration they wish to use. That configuration, set up in `truffle/packages/core/lib/commands/test`, erroneously set the gasLimit to the same as `gas`. Later in executing migrations, the gasLimit is actually set to be the blockLimit. This can lead to unintended errors and is ultimately unnecessary because Truffle will query ganache for the blockLimit when it is needed in gas estimation. 
This PR removes the `gasLimit` line in the default ganacheOptions for testing.

Bug fix: Remove gasLimit line from default ganache config in tests

---

packages/debug-utils/package.json
yarn.lock

A pretty small part of the 0.8.8 updates, but an easy one. :)  Updates our syntax highlighting for 0.8.8. :)  (Of course, it won't do much good until I actually make the debugger *support* those new parts of 0.8.8 that need highlighting, but, whatever, I did this first anyway.)

Dependency update: Update highlightjs-solidity to 2.0.1

---

packages/artifactor/package.json
packages/box/package.json
packages/code-utils/package.json
packages/codec/package.json
packages/compile-common/package.json
packages/compile-solidity/package.json
packages/compile-vyper/package.json
packages/contract-tests/package.json
packages/db-kit/package.json
packages/db-loader/package.json
packages/db/package.json
packages/decoder/package.json
packages/external-compile/package.json
packages/fetch-and-compile/package.json
packages/interface-adapter/package.json
packages/profiler/package.json
packages/reporters/package.json
packages/source-fetcher/package.json
packages/truffle/package.json

I noticed a bunch of the `package.json`s were missing the `bugs` and `homepage` fields.  So, I added them.
One question though: I noticed that the exsting packages are inconsistent about how they do `homepage`.  Some point to their specific package, while some point to Truffle as a whole.  We should probably figure out how we're doing this?
Like, should it be:
1. Every package's homepage points to that package?
2. Every package's homepage points to that package, except for `truffle` and `core`, which point to Truffle as a whole?
3. A package's homepage points to that package if it has a README, and otherwise points to Truffle as a whole?
4. Every package's homepage points to Truffle as a whole?
5. Something else?
My thinking is that we should go with (2), but really we should just agree …

Internal improvement: Ensure all packages have homepage and bugs fields

---

packages/fetch-and-compile/lib/recognizer.ts

This function didn't actually work, because we never actually set `this.recognized` to true anywhere in `SingleRecognizer`.  Now we do!
...and yeah, this wasn't caught till now because the fetch-and-compile package has no tests (#3837)... :-/

Bug fix: Fix `fetchAndCompile()`

---

packages/artifactor/package.json
packages/codec/package.json
packages/contract-tests/package.json
packages/contract/package.json
packages/core/package.json
packages/db/package.json
packages/debugger/package.json
packages/decoder/package.json
packages/deployer/package.json
packages/environment/package.json
packages/external-compile/package.json
packages/interface-adapter/package.json
packages/provider/package.json
packages/reporters/package.json
packages/source-fetcher/package.json
packages/source-map-utils/package.json
packages/truffle/package.json
yarn.lock

ChainSafe suggested on Slack we revert the web3 update as an experiment, see if CI is any better as a result.  (Again, inferring causality may be hard, but...).  So, here's the PR for that.

Revert "Update web3 to 1.6.0"

---

.github/workflows/nodejs.yml

It seems that, at some point, `ubuntu-latest` in GitHub Actions finally updated to 20.04, meaning we can finally unpin this.  (The "latest" version of OSes in GHA often lags behind the actual latest that they make available, so if for some reason you need the actual latest -- which we did for a while -- you have to pin it.)

Internal improvement: Unpin Ubuntu version in GitHub Actions

---

.github/workflows/nodejs.yml

Truffle no longer supports node 10

github(action): remove node 10.x from test matrix

---

scripts/npm-access.js

- This PR will only check permissions for packages in the monorepo against **truffle** org. 
- It drops checking against the **trufflesuite** org because we're not publishing there on npmjs.

Internal improvement: only check permissions for monorepo packages

---

packages/contract/lib/promievent.js
packages/debugger/lib/controller/actions/index.js
packages/debugger/lib/controller/sagas/index.js
packages/debugger/lib/session/index.js
packages/debugger/test/data/calldata.js
packages/debugger/test/data/codex.js
packages/debugger/test/data/global.js
packages/debugger/test/data/more-decoding.js
packages/debugger/test/data/returnvalue.js
packages/debugger/test/endstate.js
packages/debugger/test/load.js
packages/debugger/test/reset.js
packages/debugger/test/stacktrace.js
packages/debugger/test/txlog.js

The  debugger runs to the end with continueUntilBreakpoint method without specifying the breakpoints. See issue #3834 
Added an explicit runToEnd method and use that method in the debugger tests.

Added an explicit debugger method to run to the end

---

packages/contract/package.json

I only just noticed -- Truffle Contract has debugging output, but `debug` isn't listed as a dependency, only a devDependency.  So, I put up this PR.
Note: It's possible that we don't want to do this and instead we want to remove the debugging output from `contract`?  Well, I went ahead and put up this PR, and I can let the reviewers tell me if that's what we want to do instead. :P

Internal improvement: Move debug to dependencies from devDependencies in `contract`

---

.github/workflows/nodejs.yml

Turns out I accidentally broke yarncheck, and the lockfile got out of sync!  This PR fixes it.
I thought that `--frozen-lockfile` meant that `yarn` would error out if the lockfile needed to be updated.  No, turns out it means it just doesn't update it.  Oops.
So, this PR changes yarncheck back to working the old way.  Of course, I left in the `--ignore-scripts` flag so it'll still be fast.

Internal improvement: Fix yarncheck

---

packages/compile-solidity/index.js
packages/compile-solidity/run.js
packages/compile-solidity/test/test_metadata.js

This PR fixes a problem where fetch-and-compile would fail to compile sources that used absolute paths in their source paths.  This can't happen for sources in the single-file etherscan format, but it can happen for the other formats.  The problem was that, due to #4216, these sources would be filtered out by `collectSources`.
To address this, I added a `noTransform` option to `Compile.run()` (I also changed `language` to be a named rather than positional argument), which makes it so that `collectSources` will not filter the sources or rewrite their prefix (it'll still do its other usual transformations, of course).  I then made it so that `Compile.sources()` passes this option.  Note that I did *not* make any changes to compile-vyper; I'll discuss that more in a bit.
Now this may seem …

Bug fix: Allow fetch-and-compile to compile sources with absolute paths

---

packages/config/src/configDefaults.ts
packages/provisioner/src/index.ts

When providing values for `maxFeePerGas` and `maxPriorityFeePerGas` in `truffle-config.js`, those values were not being passed along to @truffle/contract so that they could be provided to `web3.eth.sendTransaction`. This PR provides defaults for them in Truffle Config and adds them to the whitelisted parameters in @truffle/provisioner so as to make them available on the contract object.
To test:
Mostly all transactions from contracts are passed to `web3.eth.sendTransaction` in the `sendTransaction` method in `packages/contract/execute.js`. You can verify that this change whitelists `maxFeePerGas` and `maxPriorityFeePerGas` by logging out the `params` variable here https://github.com/trufflesuite/truffle/blob/develop/packages/contract/lib/execute.js#L548.

Bug fix: Allow maxFeePerGas and maxPriorityFeePerGas for transactions

---

packages/environment/environment.js
packages/environment/package.json
packages/environment/test/develop.js

This PR fixes issue #4335 that config network is overwritten
with a custom, barebones network config.

environment.develop overwrite config options

---

packages/codec/docs/README.md
packages/codec/lib/format/index.ts

A couple things have been renamed, but references in our TypeDoc prose wasn't updated. This PR rectifies that.

Fix references to renamed components in Decoding/Encoding docs

---

packages/core/lib/debug/interpreter.js
packages/core/lib/debug/printer.js
packages/debug-utils/index.js

This PR supports CLI debugger allowing costomizing variables view
requested in truffle issue #4360.
The supported variables include solidity built-ins, contract,
and local. The variables are abbreviated as bui, con, and loc
respectively.

CLI debugger allows customizing variables view

---

packages/codec/lib/ast-constant/decode/index.ts
packages/codec/lib/conversion.ts
packages/debugger/test/data/more-decoding.js

When writing the code for decoding constants of type `bytesN`, I assumed that these would be initialized via hex numeric literals.  I didn't learn until later that string/hexstring literals can also be used as `bytesN`, and it turns out the code I wrote doesn't work for those.
Note that this problem didn't only apply to constants, but also applies to mapping keys of type `bytesN`, if you used a string/hexstring literal as a mapping key to a mapping which has `bytesN` for its key type.  Those wouldn't work properly, and this PR fixes that.  (It also affected constants used as mapping keys.)
So, I fixed that decoding to be a little more general.  I also expanded our testing of constants, of literals used as mapping keys, and constants used as mapping keys, to make sure this all works …

Bug fix: Fix decoding of constant `bytesN` initialized as string literal

---

packages/db/src/system.ts

The docs for truffle db ConnectOptions include a `workingDirectory: string;` attribute which is no longer valid.
Remove it.

Removed workingDirectory as it no longer exists

---

README.md

~This should be merged after the release of Ganache v7. That release will no longer be called ganache-cli but rather just ganache.~ These repos have already been changed so this can be merged.

Update link for Ganache to anticipate v7 release

---

packages/debug-utils/package.json
yarn.lock

I updated highlightjs-solidity for Solidity 0.8.10; this PR updates us to use the new version I just put out!

Dependency update: Update highlightjs-solidity to ^2.0.2

---

packages/core/lib/commands/init/initSource/truffle-config.js

Doing this now that Solidity 0.8.10 is out.  As @sukanyaparashar has pointed out, we should really find some way to automate this in the future, but for now, here's me doing it manually.

Update Solidity version in Truffle Init

---

packages/codec/lib/storage/decode/index.ts

Due to the 0.8.8 bug, `storageSize` now takes an optional compiler argument, but these calls to it weren't passing it.  The pointer one doesn't actually matter, but on 0.8.8, the array and mapping ones one would cause incorrect decodings of storage arrays of, or mappings of, UDVTs.  So, I changed these to pass that.  (The pointer one doesn't matter because you can't have a pointer to a UDVT.)
Because this only affects 0.8.8, and our tests aren't on that version, I didn't add any tests.  However I tested it manually to make sure it works.

Bug fix: Fix decoding of UDVT arrays in Solidity 0.8.8

---

packages/core/lib/testing/Test.js
packages/events/defaultSubscribers/index.js
packages/events/defaultSubscribers/test.js

This event was accidentally named after the incorrect command flow. While it was named "migrate:skipped", it really should have been named "test:**" as it is part of the flow for `truffle test` and not `truffle migrate`.

Rename event more appropriately after its respective command

---

packages/reporters/reporters/migrations-V5/messages.js

When there's an empty migration, the reporter prints total cost as '0 undefined'. This PR defaults the valueUnit to 'ETH' in the reporter for when this happens.

default valueUnit to ETH for reporter on empty migration

---

packages/core/lib/debug/printer.js
packages/debug-utils/index.js

This PR is to address the request in the issue #4353 to allow
Truffle debugger to display opcodes as a group.  The debugger
will now display 3 previous instructions and 3 upcoming instructions
in addition to current instruction.

Allow Truffle debugger to display opcodes as a group

---

packages/profiler/src/convertToAbsolutePaths.ts
packages/profiler/src/getImports.ts
packages/profiler/src/index.ts
packages/profiler/src/isExplicitlyRelative.ts
packages/profiler/src/requiredSources.ts
packages/profiler/src/resolveAllSources.ts
packages/profiler/src/updated.ts

I noticed a couple of the `debugModule` names here were still referencing `compile-common:profiler`, so this PR updates those and also ensures all other modules in this package have the requisite imports ready to go.

Ensure consistent use of debug package across @truffle/profiler

---

packages/decoder/lib/ProviderAdapter.ts

Since this was causing problems for tx-insight when trying to run decoder inside a browser extension

Remove usage of promisify in decoder

---

packages/hdwallet-provider/package.json
packages/hdwallet-provider/src/constructor/Constructor.ts
packages/hdwallet-provider/src/constructor/getOptions.ts
packages/hdwallet-provider/src/constructor/types.ts
packages/hdwallet-provider/src/index.ts
packages/hdwallet-provider/test/provider.test.ts
packages/hdwallet-provider/test/urlValidation.test.ts

In order to make hdwallet-provider a bit more slick, accept the arguments `provider` and `url` in the constructor.

Accept url and provider arguments in hdwallet-provider constructor

---

packages/compile-solidity/src/compileWithPragmaAnalysis.js
packages/compile-solidity/src/compilerSupplier/index.ts
packages/compile-solidity/src/index.js
packages/compile-solidity/src/run.js
packages/profiler/src/index.ts
packages/resolver/lib/resolver.ts
packages/resolver/lib/source.ts

Seeks to address #4384 
This PR roughly does two things:
1. Ensure we pass the compiler info from compile-solidity all the way through the Profiler and ultimately to the ResolverSources, which may choose to handle this information.
2. Invoke the CompilerSupplier before we run the Profiler, since otherwise we won't have the information yet (currently, compile-solidity invokes the CompilerSupplier _after_ invoking the Profiler, so this PR changes that behavior)
I've tried to be very safe about this (i.e., by making all new arguments optional), but maybe this is overly cautious and we can afford to be looser about it.

Pass compiler info to resolver sources

---

packages/resolver/lib/sources/abi.ts
packages/resolver/package.json
yarn.lock

This PR upgrades abi-to-sol to ^0.5.1, taking advantage of the new functionality in that package to generate version-specific Solidity output.
In order to accommodate this new functionality, we need to know what Solidity version to generate, and so this PR builds on the work of #4420 by hooking the compiler information into the `ABI` ResolverSource. 
Mostly straightforward, but I noticed one gotcha: when `resolver.resolve()` receives compiler info, it likely receives a version string containing the full commit and target info. This PR ensures the `ABI` ResolverSource strips that off because otherwise abi-to-sol throws an exception.

Respect solc version when importing ABI JSON files inside Solidity code

---

packages/fetch-and-compile/lib/debug.ts
packages/fetch-and-compile/lib/fetch.ts
packages/fetch-and-compile/lib/recognizer.ts
packages/fetch-and-compile/lib/types.ts

Addresses #4446.
The `SingleRecognizer` now records and returns the name of the fetcher used, in addition to the other information.  Note that to do this I put `fetchedVia` into the `FetchAndCompileResult` type; so I removed the third argument from `addCompiledInfo` as it was now redundant.  I think we can reasonably say that's not really a breaking change, as it doesn't break either `fetchAndCompile` or `fetchAndCompileForDebugger`; it only breaks `fetchAndCompileForRecognizer`, which... c'mon, that's pretty internal (it's not even used elsewhere in Truffle although I did export it).
The functionality of `fetchAndCompileForDebugger` remains unchanged.
If we really are worried about that sort of thing, I can redo it in a truly non-breaking way, but this was the most straightforward way. …

Enhancement: Have `fetchAndCompile` return name of fetcher used

---

packages/core/lib/debug/printer.js

This PR fiexes a bug reported in issue #4478: debugger throws error.
The root is that the array goes out of bounds when debugger printouts
the upcoming instructions.

Fix array out of bounds in debugger instruction printout

---

packages/contract/README.md

This PR fixes a typo in packages/contract/README

Fixing an incorrect file extension in packages/contract/README

---

packages/db-kit/package.json
packages/db/package.json
yarn.lock

Dependabot is reporting a vulnerability in madge v3.11.0. This bumps madge to latest v5.0.1. I browsed the other dependabot alerts and they all appear to be deps of deps.
1. Pull down
2. yarn bootstrap
3. in `packages/db` and `packages/db-kit` run `yarn madge`
```
yarn run v1.22.17
$ madge ./src/index.ts
Processed 37 files (1.1s) 
...
Done in 1.07s
```

upgrade madge to v5.0.01 from v3.11.0

---

packages/debugger/package.json

The way that it's necessary to clean up the after the debugger tests run is definitely something of a tripping hazard... sure, the cleanup happens automatically now, but only if the tests *succeed*!  If the tests fail, no cleanup occurs.
So, this PR alters the debugger test script so that the cleanup occurs no matter what (without accidentally making it so that failing tests are ignored).  We run the tests, save the exit status, run the cleanup, and then finally return the saved exit status (so that we get a failure if the tests failed).  It's perhaps a bit awkward, but it works.  (I did a manual test to make sure that yes, we really do get a failure if one of the tests fails.)
It's not perfect, obviously -- if you interrupt the tests, you're still going to need to run the cleanup …

Internal improvement: Have debugger test always cleanup afterward, including on failure

---

packages/codec/lib/contexts/utils.ts
packages/debugger/test/context-vyper.js
packages/debugger/test/helpers.js
scripts/ci.sh

This PR allows the debugger and decoder to recognize bytecode from a deployed Vyper contract that uses immutables.
Now, unlike Solidity, the Vyper compiler doesn't given us any `immutableReferences` output.  But fortunately, unlike Solidity, Vyper puts its immutables at the end of the bytecode -- like constructor arguments -- rather than inline.  This means that we can simply allow "constructor arguments" at the end of deployed bytecode, so long as the context we're trying to match is a Vyper one.
(I thought about not restricting it to Vyper, but decided to leave that restriction in for now.)
So, with this change, it is now possible to debug (i.e. step through) a transaction made against a Vyper contract that uses immutables.  (It also affects things like `decodeTransaction` and …

Allow recognition of deployed Vyper bytecode with immutables

---

packages/config/src/configDefaults.ts
packages/contract-tests/test/lib/utils/ens.js
packages/contract/lib/utils/ens.js
packages/contract/lib/utils/index.js
packages/provisioner/src/index.ts

Addresses #4156.
Both web3 and ethers allow setting the transaction type expicitly with the `type` option, but we weren't allowing this.  This PR whitelists the `type` option in Truffle Contract, and then in addition I added it to the list of options that users can explicitly set in their config, because it seems like something that users might want a default for.  Note that the default default is set to `undefined`, not `null`; web3 will error if you specify `type: null` (no Pokemon jokes please :P ).
Note that web3 doesn't *fully* respect the type you specify -- if you specify type 1, but don't specify an access list (and with Truffle currently, you still *can't* specify an access list!), it'll use type 0 instead -- but I don't think that's any big reason not to do this.
**Edit**: I've …

Allow users to specify transaction type explicitly, and allow use of access lists, including ENS support

---

packages/codec/lib/conversion.ts

Was working on codec when I noticed this comment made no sense.  It was clearly supposed to say "left" instead of "length".  So I fixed it, and also changed it to be an `@param` comment, FWIW.

Internal improvement: Fix confusing comment on `toHexString` function

---

packages/contract/lib/execute.js

This PR fixed an error in the key name ens when calling convertENSNames in the migrate prepareCall. The error causes truffle-box v5.1-example-box fails to migrate, see issue #4477.

Fix incorrect key name in migrate prepareCall

---

packages/debugger/package.json
yarn.lock

Updating these to resolve the dependabot alert regarding json-pointer.

Dependency update: Update reselect-tree to 1.3.5 and json-pointer to 0.6.1

---

packages/debugger/lib/stacktrace/reducers.js

This is an odd one.  The `EXTERNAL_CALL` case in the `lastPosition` reducer in `stacktrace` was typo'd to `ETERNAL_CALL`.  So external calls were getting ignored!
Why didn't this cause test failures?  Well, presumably because this would only affect the source positions given in the stacktrace, which we weren't testing.  (Notionally I could add tests for those, but due to this PR's status as an add-on to another PR, that would be impractical here; we can go back and do that later if we think it's necessary.)
Note that fixing the typo caused failures though... because I didn't account for the fact that the initial `EXTERNAL_CALL` has `location` equal to `null`.  So, I just checked for that case and ignored it.

Bug fix: Fix incorrect action name and account for null location

---

packages/contract-schema/test/schema.js

Addresses issue #4487.
I've added the tests for contract validation amid calling `Schema.normalize()`, present inside PR #4432.
Modified only `@truffle/contract-schema/test/schema.js`

Added tests for contract validation amid schema normalization (issue #4487)

---

packages/resolver/package.json
yarn.lock

The corresponding [abi-to-sol release](https://github.com/gnidan/abi-to-sol/releases/tag/v0.5.2) contains only dependency upgrades, to address dependabot issues.
This is probably not going to be comprehensive (I wasn't sure how to handle some of the alerts), but hopefully it's an improvement.
* @truffle/resolver: ^0.5.1 →  ^0.5.2

Upgrade dependency: abi-to-sol@^0.5.2

---

packages/core/lib/commands/test/index.js

To allow setting mocha reporter as a command line argument rather than changing it in the truffle-config.js file while using $truffle test command. See issue #2124.
A command line argument has been added as an enhancement feature in the $truffle test command for changing the mocha reporter type. The command can be used as - $truffle test --reporter reporter-name.

Added command line argument for changing mocha reporter

---

packages/decoder/lib/ProviderAdapter.ts

The parameter passed with this rpc method should be a `Quantity` which I believe should be encoded as a string and not a BN. See the section "HEX value encoding" https://eth.wiki/json-rpc/API

Bug fix: Correct error in ProviderAdapter

---

packages/fetch-and-compile/lib/debug.ts
packages/fetch-and-compile/lib/fetch.ts
packages/fetch-and-compile/lib/recognizer.ts
packages/fetch-and-compile/lib/types.ts

Addresses #4538.
This PR makes it so that when `fetchAndCompile` hits an error when fetching or compiling, it will actually rethrow that error, rather than throwing a generic unhelpful error.  This required a slight change to the recognizer interface, but not even a breaking one.
(Note that `fetchAndCompileForDebugger` still swallows particular errors.)
This PR has no tests because tests for this package are waiting on #4424, but tests can be added once that PR is merged.

Enhancement: Have fetchAndCompile rethrow particular errors

---

packages/debugger/test/endstate.js
packages/debugger/test/load.js

Some debugger tests have been timing out a bunch lately.  Getting these when I see them.

Internal improvement: Up timeout on debugger tests

---

.eslintrc.json
.husky/pre-commit
package.json
packages/db-kit/package.json
packages/truffle/package.json
packages/truffle/webpack.config.js
yarn.lock

This PR updates husky to v6 and hooks up lint-staged which has stopped working for some reason (#3530). It uses the newest version of Husky which relies on better git api introduced in 2016 ([See this blog post](https://blog.typicode.com/husky-git-hooks-javascript-config/) for details), as well as building on the work of @bergarces and @haltman-at wrt eslint configuration. 
Also cherry picked @haltman-at 's work around to fix a webpack `rx-lite-aggregates` issue.
<details> <summary>See details</summary>
```
truffle: ERROR in ./node_modules/rx-lite-aggregates/rx.lite.aggregates.js
truffle: Module not found: Error: Can't resolve './rx.lite' in '/home/amal/work/truffle/node_modules/rx-lite-aggregates'
truffle: resolve './rx.lite' in '/home/amal/work/truffle/node_modules/rx-lite-aggregates' …
```

Internal improvement: get husky and lint-staged working

---

packages/debugger/test/reset.js

Found another one of these tests that was timing out, upped it.
(Also, `prettier` is working!  Yay!)

Internal improvement: Increase timeout on another debugger test

---

.eslintrc.json

We need this so it doesn't complain about `BigInt` and such!

Internal improvement: Allow ES2021 globals in ESLint

---

.eslintrc.package.json

I was getting some problems because ESLint didn't recognize some files as test files.  So I expanded the pattern to cover any `ts` or `js` file in a test directory; and I also turned on both `mocha` and `jest` globals.

Internal improvement: Expand pattern for tests in .eslintrc.json

---

package.json
yarn.lock

Updating this seems harmless (since it's just a command-line wizard that we have around for convenience), and I'm hoping it might help resolve some dependabot alerts, possibly?

Dependency update: Update lerna-update-wizard to 1.1.0

---

package.json
yarn.lock

Just updating this.  We're not really using this at the moment, but per discussion with @gnidan we're not removing it (it would, after all, be quite nice to get code coverage working again!).
...I was kind of hoping this would help resolve some dependabot alerts, but now that I look more closely, it probably actually won't.  Oh well.  Still, seems good on net, right? :)

Dependency update: Update coveralls to 3.1.1

---

packages/decoder/lib/ProviderAdapter.ts
packages/decoder/lib/decoders.ts

This PR performs some formatting for the provider adapter in decoder. This adds an argument to the method responsible for sending so that each method responsible for an rpc call can specify its own formatter to use before returning the value. This will help maintain parity with the types that web3 returns (web3 transforms/formats a lot of the rpc response values) and hopefully make it easier to switch out in favor of this utility eventually.

Internal improvement: Eth adapter

---

packages/debug-utils/package.json
yarn.lock

I updated highlightjs-solidity for Solidity 0.8.11; this PR just updates us to use the new version I just put out.

Dependency update: Update highlightjs-solidity to 2.0.3

---

packages/core/lib/commands/migrate/meta.js

When using the --quiet option with the migrate command, Truffle displays the "possible unsupported option" message.
See issue #4464 .
--quiet option is added in the allowedGlobalOptions array to avoid displaying the "Possible unsupported option" message.

Add --quiet option in allowedGlobalOptions array in truffle migrate command

---

packages/debugger/lib/web3/adapter.js

Addresses #4565.  It turns out you can pass `enableMemory: true` to get the memory in recent geth versions, so this PR does that.
I didn't do a comprehensive test of other clients (didn't check besu or erigon), but Ganache (both 6 and 7 at least) have no problem with this option being passed.
Note this still leaves the problem of us not getting storage.  I thought the debugger doesn't use that; I forgot that actually it still does in certain cases (namely: when debugging failed contract creations, unless they were performed with `CREATE2`).  So we'll want to get that too, but I figure that can be left for later; first let's fix the big obvious crash.

Bug fix: Pass `enableMemory: true` when requesting traces

---

packages/core/lib/commands/debug/mergeConfigNetwork.js
packages/core/test/lib/commands/debug.js

Oops, it seems that #4552 broke the debugger when `--url` is *not* specified; looks like nobody checked that.  Basically it tries to use `url` no matter what; the check for that got lost somewhere along the way.  This is a quick fix for that; it adds in a check so that `url` isn't used unless it was actually specified.

Bug fix: Avoid using url in CLI debugger when no url specified

---

packages/debugger/test/load.js

This test has been timing out occasionally recently; increasing its timeout to 4 seconds.

Internal improvement: Increase timeout on debugger test

---

packages/debugger/lib/solidity/sagas/index.js
packages/debugger/test/solidity.js

This PR is a continuation of #3149.  That PR made it so that the phantom call guard wouldn't be cleared by jumps into unmapped code.  However, when later versions of Solidity added generated sources, I didn't think to prevent them from clearing the phantom call guard also.  This PR does that.
...OK, I'm going to need to explain that for most of the reviewers.  The phantom call guard system was added back in #2696.  It makes it so that, when you enter an external function call, the function depth only goes up once, rather than twice.  By itself, it'd go up twice -- once on entering the new contract, and again at the start of the actual function.  (Note that the phantom call guard is not used when dealing with Solidity versions older than 0.5.1, as they lacked a jump in at the start of …

Bug fix: Prevent generated sources from clearing the phantom guard

---

packages/compile-vyper/index.js
packages/compile-vyper/profiler.js
packages/resolver/lib/resolver.ts
packages/resolver/lib/sources/abi.ts
packages/resolver/lib/sources/vyper.ts

Addresses #4521.  **Is a breaking change to `@truffle/resolver`**.
Most of what there is to say about this one is already discussed in #4521.  The awkward option that defaulted to `true` is now gone; I imagine Nick will be happy about that.
Only one resolver invocation needed to be altered, and that was the one in `compile-vyper`, because that's the one all these auxiliary options were created for!  Now that `includeTruffleSources` is once again the only resolver option, I could notionally change the signature back to the old way, where instead of passing `{ includeTruffleSources: true }` you just passed `true`, but, um, I think it's fairly obvious why we don't want to do that.
(Getting rid of those extra options is also quite helpful if we ever want to implement #3855. :)  The way the …

Internal improvement: Remove unnecessary resolver options, check compiler instead

---

packages/debugger/lib/evm/reducers.js
packages/debugger/lib/evm/selectors/index.js
packages/debugger/lib/web3/adapter.js
packages/debugger/test/data/codex.js

Addresses #4583.
This PR eliminates the debugger's remaining uses of `storage` taken from the trace.  I had already mostly eliminated the use of `storage` in #3102; this gets rid of the remaining uses.
The debugger mostly doesn't use the `storage` field, because it uses the codex to determine storage, and the codex is built from the stack.  However, there's one case where the debugger bypasses the codex when determining storage: When inside a failed contract creation that was initiated with the `CREATE` opcode, the debugger would bypass the codex and read the `storage` field directly.
The reason for this is that, in order to meaningfully use the codex, we need to know the current address.  However, currently, the debugger has no way to determine the current address when inside a failed …

Bug fix: Remove remaining debugger reliance on traced storage

---

packages/core/lib/commands/init/initSource/truffle-config.js

Since we're still updating this manually, here's the version bump for 0.8.11.
Note: I made this commit with `--no-verify` because I don't think we want `prettier` running on this file (originally I didn't do that and the result was... not what we want, I think).  I may go see about turning it off for this file...

Update Truffle Init Solidity version to 0.8.11

---

packages/abi-utils/package.json
packages/compile-solidity/package.json
packages/contract/package.json
packages/db-loader/package.json

Addresses #4567.  They're all called `build` now.  (I left in `compile` as an alias in `contract`.)  People making new packages, take note, please name things accordingly!  (...assuming people agree that this is good and merge it, anyway.)

Internal improvement: Ensure consistent naming of build scripts

---

packages/core/lib/debug/printer.js
packages/debug-utils/index.js

The debugger prints error message when it does not have the code of
the contract, see issue #4566. The issue is raised in self-destruc transactions.
This PR prints a warning message instead.

Debugger print a warning message if it does not have code of the contract

---

packages/source-fetcher/lib/sourcify.ts

It turns out that Sourcify will replace colons in file paths with underscores.  Note that the metadata *itself* is unchanged, but the actual file paths are transformed.  So after we read the file paths out of the metadata, we then have to transform them before using them to fetch the corresponding file.  We don't transform them for any other purpose though; we still save it under the untransformed file path so that everything fits together properly.
I do not know if this is the only such transformation they make; it may be necessary to make others as well.  I have asked them on Gitter, hopefully they respond.
This PR has no tests because source-fetcher still has no tests but hopefully that will be rectified soon!
(Also, `prettier` made several changes.)

Bug fix: Replace special characters with underscores when fetching from Sourcify

---

packages/source-fetcher/lib/sourcify.ts

Sorry, just a quick follow-on to #4610... the regex I used didn't use the `u` flag, so if any astral-plane characters were used, it would get things wrong (replacing them with two underscores instead of one... yes I tested and Sourcify will just put the one).  This PR just adds the `u` flag that should have been there.
I guess most of the time we don't worry too much about astral-plane stuff, and I don't intend to make accounting for that like some sort of general effort (outside of codec of course which is certainly aware of that stuff :P ), but I thought I should account for it here.

Bug fix: Use Unicode matching in Sourcify replacement

---

packages/source-fetcher/lib/common.ts
packages/source-fetcher/lib/sourcify.ts

This PR fixes some compile errors that could occur when using `fetch-and-compile` to fetch sources off of Sourcify.  See, Sourcify gives us the *metadata*, which is not *quite* the same thing as actual compiler input.  For the most part we account for this, but in this case we hadn't.  The metadata settings include a setting called `compilationTarget`.  Actual compiler input doesn't include that setting, but we weren't removing it, and so sometimes the compiler would error out becasue of the presence of this setting.  So, now we delete it to prevent errors.
Ideally I would disunify the `SolcSettings` type into `SolcSettings` and `SolcMetadata`, but I didn't bother as that just seemed like needless complication (for instance, then I'd have to write a type predicate to distinguish them if I …

Bug fix: Remove compilationTarget field from metadata from Sourcify

---

packages/contract/lib/execute.js
packages/contract/lib/utils/index.js

Addresses #4457.  Supersedes #4448 because it looks @hellwolf isn't coming back to finish that.
This PR makes it so that, when making a call (not a transaction!) with Truffle Contract, any defaults for `gasPrice`, `maxFeePerGas`, or `maxPriorityFeePerGas` coming from the config are ignored.  The reason for this is that including too-high values for these parameters can cause "insufficient funds" errors on certain networks, even though you're making a call, not a transaction.  This is annoying!
Note that any values for these parameters *explicitly specified when making the call* are still respected, because, I don't know, maybe the user wants to be able to set these.  But any defaults coming from the config will be ignored.
To do this, I added an extra parameter to `getTxParams`, which …

Ignore config gas prices when making a call

---

packages/debugger/webpack/webpack.config-common.js

Small PR fix to revert the sourcemap config using a relative sourceroot.
reverting back to default processor and source-map flag.﻿
Fixes #4594

Fixing Debugger sourcemap issues.

---

packages/codec/lib/abi-data/allocate/index.ts
packages/decoder/lib/decoders.ts
packages/decoder/test/current/contracts/DowngradeTest.sol
packages/decoder/test/current/test/downgrade-test.js

Oddly, it looks like we forgot to ever open an issue for this.  Oops.  Oh well.  (Also, sorry about all the changes caused by `prettier` and ESLint.)
(**Edit**: To make this more reviewable, let me point out here where the real changes are:
1. `allocate/index.ts` -- only the added export on line 61 is real, everything else is `prettier`... sorry (OK, and lines 1259-1267 were deleted due to ESLint noticing they were never used)
2. `decoders.ts` -- nearly all the changes are real, only a tiny bit is `prettier`
3. `downgrade-test.js` -- the added test is real, the rest is `prettier`
)
Anyway, this PR allows the `ContractInstanceDecoder` to decode transactions sent to that particular contract instance, even if no bytecode was supplied for that contract in the project information.  It also …

Enhancement: Allow `ContractInstanceDecoder` to decode transactions sent to that instance even if no bytecode was supplied

---

packages/core/lib/commands/test/meta.js
packages/core/lib/commands/test/run.js

Setting the mocha reporter in the truffle-config.js file was not working after the --reporter flag was added as the command line argument. See #4627 .
The mocha reporter can now be set in the truffle-config.js and it can be run using the truffle test command. And if it is not set in the truffle-config.js file, it can be specified as an command line argument like -
truffle test --reporter <reporter_name>
And if nothing is specified when running the truffle test command or in the truffle-config.js file, the default mocha reporter is displayed which is "spec".

Fix mocha reporter issue to work with both command line and truffle-config.js

---

packages/contract/README.md

The example Contract initialization in the README includes a deprecated field and alludes to it being a required field, so I removed it.

Remove deprecated field from README

---

packages/contract/README.md

The sentence wasn't making much sense " You're given the transaction has (`result.tx`)". replace 'has' with 'hash'.

Update the README.md

---

packages/contract/lib/reason.js

Added a case for `data` being a string directly, which @davidmurdoch says is how Geth does it, and how Ganache will do it starting in 7.0.1.
@davidmurdoch, can you confirm that I've got this correct?
~~(Also, is the current way `return` or `result`?  You said `return`, but our current code is `result` and it seems to pass tests...)~~
Edit: @davidmurdoch confirms it is indeed `result`.

Bug fix: Account for Geth format in reason.js

---

packages/workflow-compile/index.js
packages/workflow-compile/test/index.js

**Breaking change to `@truffle/workflow-compile`.**  Per discussion with @gnidan.  The workflow-compile package was returning this, but it's not actually on the type, and nothing uses it (lots of stuff uses the sources info attached to the individual compilations, but not to the reduced form that was being attached to the whole thing).
Doing this as step one of fixing a more pervasive typing issue where `CompilerResult` and `WorkflowCompileResult` are being conflated in various places; before we deal with the rest of that, Nick thought it made sense to correct the actual output of workflow-compile first.

Remove sources from workflow-compile return to match TS type

---

packages/abi-utils/tsconfig.json
packages/artifactor/tsconfig.json
packages/blockchain-utils/tsconfig.json
packages/box/tsconfig.json
packages/code-utils/tsconfig.json
packages/codec/tsconfig.json
packages/compile-common/src/compilations.ts
packages/compile-common/src/index.ts
packages/compile-common/tsconfig.json
packages/compile-solidity/src/index.js
packages/compile-vyper/index.js
packages/compile-vyper/vyper-json.js
packages/config/tsconfig.json
packages/db-loader/tsconfig.json
packages/decoder/tsconfig.json
packages/external-compile/index.js
packages/fetch-and-compile/tsconfig.json
packages/hdwallet-provider/tsconfig.json
packages/interface-adapter/tsconfig.json
packages/plugins/tsconfig.json
packages/preserve-fs/tsconfig.json
packages/preserve-to-buckets/tsconfig.json
packages/preserve-to-filecoin/tsconfig.json
packages/preserve-to-ipfs/tsconfig.json
packages/preserve/tsconfig.json
packages/profiler/tsconfig.json
packages/resolver/tsconfig.json
packages/source-fetcher/tsconfig.json
packages/workflow-compile/index.js

Follow-on to #4650.  This makes it so that `compile-solidity`, `compile-vyper`, and `external-compile` all return a `WorkflowCompileResult`, instead of just a `CompilerResult`.  To do this, the logic for attaching `contracts` was moved from `workflow-compile` to `compile-common` and put in a new function called `promoteCompileResult`.  (Maybe not the best name, but feel free to suggest a better one.)  Of course, `workflow-compile` as a result got logic for concatenating the `contracts`.
Also, I wanted to use `flatMap`, but TS complained because the lib setting was on es2017.  So I updated it to es2019 (in all packages that were on es2017); we no longer support Node 10 so anything from es2019 is fair game.  (@gnidan, you think I should update `target` as well? :) )

Have individual compile packages return WorkflowCompileResult (instead of CompilerResult)

---

packages/abi-utils/tsconfig.json
packages/artifactor/tsconfig.json
packages/blockchain-utils/tsconfig.json
packages/box/tsconfig.json
packages/code-utils/tsconfig.json
packages/codec/tsconfig.json
packages/compile-common/tsconfig.json
packages/compile-solidity/tsconfig.json
packages/config/tsconfig.json
packages/db-kit/tsconfig.json
packages/db-loader/tsconfig.json
packages/decoder/tsconfig.json
packages/error/tsconfig.json
packages/expect/tsconfig.json
packages/fetch-and-compile/tsconfig.json
packages/hdwallet-provider/tsconfig.json
packages/interface-adapter/tsconfig.json
packages/plugins/tsconfig.json
packages/preserve-fs/tsconfig.json
packages/preserve-to-buckets/tsconfig.json
packages/preserve-to-filecoin/tsconfig.json
packages/preserve-to-ipfs/tsconfig.json
packages/preserve/tsconfig.json
packages/profiler/tsconfig.json
packages/provisioner/tsconfig.json
packages/resolver/tsconfig.json
packages/source-fetcher/tsconfig.json

We no longer support Node 10, and Node 12 supports everything from ES2019, so this should be safe, right?

Internal improvement: Update TS target to es2018

---

packages/debugger/lib/solidity/reducers.js
packages/debugger/package.json
packages/debugger/test/helpers.js
packages/decoder/package.json
packages/decoder/test/helpers.js
yarn.lock

We're on Node 12 now, no need to be using `lodash.flatten` anymore, that's what `array.flat` and `array.flatMap` are for. :)  I've taken out `lodash.flatten` and replaced it with uses of those functions. :)
(Note there are still plenty of places in our code that are doing other ad-hoc things instead of using `flat` and `flatMap`, but, uh, I don't think there's any hurry to go replacing those all immediately...)

Internal improvement: Remove lodash.flatten dependency

---

packages/debugger/lib/web3/adapter.js

Addresses #4635.
I'll be honest, I don't fully understand this one.  For some reason, the way that `provider.send` was being invoked, somehow `this` was getting set to the wrong value (i.e., not the provider).  As such, when `provider.send()` attempted to call `this._prepareRequest()`, intending to call its own method `provider._prepareRequest()`, it instead called `somethingElse._prepareRequest()`, causing a crash.  (I didn't bother determining the value of `somethingElse`.)
I have no idea why this happened in this case, and, for that matter, why it *doesn't* happen normally... this doesn't happen when the debugger is used via the CLI, for instance!
Regardless, it was happening, so I just used `bind` to enforce that `this` was set correctly.  This is kind of the lazy approach -- ideally …

Bug fix: Use bind with provider.send in debugger's adapter

---

.github/workflows/nodejs.yml

This PR updates truffle's slack integration. Work not captured in the PR is generating the project `secrets.SLACK_WEBHOOK_URL` from [this website](https://slack.com/apps/A0F7XDUAZ-incoming-webhooks?tab=more_info) as an authenticated user. Note, that when generating the `SLACK_WEBHOOK_URL`, you get to choose the Slack channel to target.

Update slack build integration 

---

packages/core/lib/commands/migrate/run.js
packages/environment/environment.js

This addresses https://github.com/trufflesuite/truffle/issues/4665.
Ganache logs by default, this PR suppresses logging by adding an extra argument to `Environment.fork` that allows passing options for starting Ganache. It then passes the appropriate options for suppressing logging when doing the dry run.

Bug fix: Suppress Ganache logging when running the dry run

---

packages/codec/lib/basic/decode/index.ts
packages/debugger/lib/data/sagas/index.js
packages/debugger/test/data/returnvalue.js

Here's a problem I noticed today: Codec will fail to decode bytecode returned from a constructor when it contains immutables of `function internal` type.  I was debugging a transaction that did this (a test transaction I made, obviously, not something on mainnet or something) and I noticed it was failing to decode the bytecode at the end.
Why did this occur?  Well, we use strict mode for decoding immutables; this is convenient for various reasons.  (Like, it allows for us to distinguish retryable errors and fall back into ABI mode if one occurs; this would be much more difficult without strict mode.)  But there's a problem -- strict mode was meant for ABI decoding; it's actually called `strictAbi` mode internally!  So, I made it so that codec will refuse to decode internal function …

Bug fix: Fix decoding of bytecode with internal function pointers in immutables

---

packages/deployer/src/actions/new.js

This PR is to remove the *unnecessary* await in the deployer code to deploy. The function takes a TruffleContract abstraction and the arguments (`args`) it needs to deploy the associated Solidity contract. For some reason, the code considers the `args` to be promises and awaits them in a Promise.all. 
I tried two mutually exclusive paths forward, #4674 using the resolved promises in `contract.new` invocation, and this PR, which doesn't await the promise. Both PRs passed CI, and after consulting with the team to go with this PR's approach.  Arguments to Contracts should not be promises.
``` 
module.exports = function(contract, args, deployer) {
return async function() {
deployer.logger.log("Creating new instance of " + contract.contract_name);
// Evaluate any arguments if they're promises …
```

Don't resolve args

---

packages/abi-utils/tsconfig.json
packages/artifactor/tsconfig.json
packages/blockchain-utils/tsconfig.json
packages/box/tsconfig.json
packages/code-utils/tsconfig.json
packages/codec/tsconfig.json
packages/compile-common/tsconfig.json
packages/config/tsconfig.json
packages/db-loader/tsconfig.json
packages/decoder/tsconfig.json
packages/fetch-and-compile/tsconfig.json
packages/hdwallet-provider/tsconfig.json
packages/interface-adapter/tsconfig.json
packages/plugins/tsconfig.json
packages/preserve-fs/tsconfig.json
packages/preserve-to-buckets/tsconfig.json
packages/preserve-to-filecoin/tsconfig.json
packages/preserve-to-ipfs/tsconfig.json
packages/preserve/tsconfig.json
packages/profiler/tsconfig.json
packages/resolver/tsconfig.json
packages/source-fetcher/tsconfig.json

This PR downgrades the ts target in a few truffle packages as the recent update caused an error when trying to deploy to various test-nets using `@truffle/hdwallet-provider` (`rinkeby` and `ropsten` were the ones tested in this case.) Downgraded the other packages for the sake of consistency. This PR addresses issue #4676.
- `git checkout lee/hdwallet-provider-fix`
- ` cd packages/hdwallet-provider`
- ` yarn link`
-  `cd /path/to/your/new/truffle-test-project`
- `truffle init`
-  Configure `rinkeby` or `ropsten` in your `truffle-config.js`
-  `yarn link @truffle/hdwallet-provider`
-  `truffle migrate --network {your-testnet}`

Bug Fix: Revert ts target to es2016

---

packages/compile-solidity/tsconfig.json
packages/db-kit/tsconfig.json
packages/error/tsconfig.json
packages/expect/tsconfig.json
packages/provisioner/tsconfig.json

Just a quick follow-on to #4688, I noticed a few packages weren't downgraded, so I put in this PR to get the remaining ones for consistency.

Downgrade remaining TS packages to `target: es2016`

---

packages/core/.eslintrc.json
packages/core/lib/version.js

Resolved issue #4678 by reading from Truffle's package.json for Ganache's version number.
Once Ganache adds .version, we can make a change to use that instead. 
Also, BUNDLE_VERSION is causing an eslint no-undef rule complaint, this variable is now on the package level eslintrc.json, should this be moved to global eslintrc.json?

Core: add managed ganache version info to the output of truffle version

---

.github/workflows/nodejs.yml

This PR updates the Slack notification target channel in order to consolidate our GitHub notifications. 
As we evaluate the Slack Integration, we may eventually need to turn this one off. We want to ensure all job runs are captured, but it is unclear if the Slack integration can provide that coverage.
Changes
- change notification channel to #truffle-ci-notifications
- update fields
N.B. secretes.SLACK_WEBHOOK_URL also has to be updated here: https://trufflesuite.slack.com/apps/A0F7XDUAZ-incoming-webhooks\?tab\=more_info
Watch the #truffle-ci-integration channel and see if things are integrated.

Dedupe slack notification channel

---

.eslintrc.json
packages/core/.eslintrc.json

What with @lsqproduction dealing with `BUNDLE_VERSION` in #4686, and @cds-amal dealing with `BUNDLE_CHAIN_FILENAME` in #4671, I thought it was probably best to just take the whole list of these variables and stick them in the main `.eslintrc.json`, so we don't have to keep worrying about this (unless we add new ones of these!).
(Hope you don't mind @cds-amal!)

Internal improvement: Put all BUNDLE globals in main .eslintrc.json

---

packages/source-map-utils/index.js

This function in `source-map-utils` used `source.split("")` to split `source` into characters.  This splits surrogate pairs.  So I changed it to `Array.from(source)`, which doesn't.
...of course, doing this still doesn't *really* solve the problem, as what we really want here is something more like grapheme clusters, not code points.  But solving that problem is harder and would presumably require introducing a dependency, so I thought I'd just throw up this PR quickly to start.  I could open an issue for that though?

Bug fix: Prevent source-map-utils from splitting surrogate pairs

---

packages/deployer/ENSRegistry.json
packages/deployer/ens.js
packages/deployer/package.json
yarn.lock

This PR removes the package @ensdomains/ens. The package is only used for the ENSRegistry artifact, which is now saved in @truffle/deployer. This will eliminate the baggage of including @ensdomains/ens in Truffle. In the future we might move to relocate the ENSRegistry artifact to @truffle/resolver but we should probably wait until other parts of Truffle want to access the artifact or we decide to include more artifacts in Truffle.

Internal improvement: Remove @ensdomains/ens and include ENSRegistry artifact in deployer

---

packages/config/.eslintrc.json
packages/config/package.json
packages/config/src/index.ts
packages/config/test/unit.test.ts
yarn.lock

This PR removes the [lodash.assignIn](https://lodash.com/docs/4.17.15#assignIn) dependency with a native JavaScript implementation. `TruffleConfig.with` is the only place that uses `lodash.assignIn`, *however,* it normalizes all inputs and, in the process, removes their prototype references making `lodash.assignIn` overkill. We can instead use `Object.assign` for this `assignIn` business.

Replace lodash.assignIn with native JS implementation

---

packages/fetch-and-compile/lib/fetch.ts
packages/fetch-and-compile/lib/index.ts
packages/fetch-and-compile/lib/types.ts
packages/fetch-and-compile/package.json
packages/fetch-and-compile/test/fetch.test.ts
packages/source-fetcher/lib/common.ts
packages/source-fetcher/lib/etherscan.ts
packages/source-fetcher/lib/index.ts
packages/source-fetcher/lib/networks.ts
packages/source-fetcher/lib/sourcify.ts
packages/source-fetcher/lib/types.ts

Addresses #4643.  This PR adds a `getSupportedNetworks()` function to `@truffle/fetch-and-compile`, and a static `getSupportedNetworks()` method to each source fetcher in `@truffle/source-fetcher`.  It also adds a quick test of this functionality.
This PR is mostly pretty straightforward.  For the source-fetcher part, each source fetcher now has a static `getSupportedNetworks()` function.  I could have added an instance version too (like we have for `fetcherName`) but I didn't see a need so I didn't.  I moved the networks information out of `common.ts` and into a new file `networks.ts`.  For now it's pretty bare-bones and continues to make the assumption that network ID equals chain ID.
The networks are returned indexed by name, and each is given as an object with fields `name`, …

Enhancement: Add getSupportedNetworks() to source-fetcher and fetch-and-compile

---

packages/fetch-and-compile/package.json

Apparently this needs to be a dependency, not a devdependency, because `Config` is used directly in the signature of exported functions.
I didn't move over `compile-common` as well because `WorkflowCompileResult` is only used within other types, not directly on exported function signatures.  That's OK, right?  Well, uh, let me know if it isn't...

Reclassify @truffle/config as dependency of @truffle/fetch-and-compile

---

packages/debug-utils/index.js
packages/debug-utils/package.json
yarn.lock

Addresses #4726.  Updates our chromafi fork to the one I just published that gets rid of a bunch of dependencies.  It's 3.0.0 because one of those dependencies I removed was providing actual functionality, so it was a breaking change... but it doesn't break anything for us, as the removed functionality (the `highlight` option) wasn't anything we were using.  (No, that option did *not* control whether syntax highlighting is on or not; it's confusingly named and frankly I don't really understand *what* it did.)  I also removed the comment in debug-utils about that option since it's gone now.

Dependency update: Update @trufflesuite/chromafi to 3.0.0

---

packages/dashboard/package.json

Just added some fields I noticed were missing.  I left out `description` and `keywords` because I wasn't sure what to put for those, but, uh, @rkalis, feel free to update this PR to add those in?

Internal improvement: Add some missing fields to @truffle/dashboard package.json

---

packages/debugger/lib/evm/selectors/index.js
packages/debugger/lib/solidity/selectors/index.js
packages/debugger/test/solidity.js

Addresses #4697.  This PR attempts to finally get the function depth and the phantom call guard right once and for all.  Previous versions of these had focused solely on getting function depth working well enough to distinguish variables; however, I forgot that function depth has a second function, namely, stepping.  With this PR, function depth should be reliable enough that it can also be used for stepping without too much worry.
This PR was intended to fix one specific bug (#4697), but on the way I found a second, so I fixed that too.  I also added three more tests that will hopefully catch this sort of problem if we need to alter this code in the future.
The problem is this.  Suppose you enter an external function call, on Solidity 0.5.1 or greater.  Without the phantom call guard, …

Bug fix: Fix phantom call guard and function depth interaction with fallback functions (and some other things)

---

packages/source-fetcher/lib/etherscan.ts
packages/source-fetcher/lib/types.ts

I noticed this was missing from the `VyperSettings` type.  There's no functional change here as Etherscan doesn't currently support this flag, so there was no need to make any updates to make the fetcher support it, but I thought I'd at least update the type (and comments).

Internal improvement: Add `optimize` flag to `VyperSettings` type in source-fetcher

---

packages/core/package.json

Just noticed this field was missing.  Adding it.

Internal improvement: Add license field to core package.json

---

packages/debug-utils/package.json
yarn.lock

I just put out a new release of highlightjs-solidity to update its highlighting for Solidity 0.8.12.  (Specifically, I added highlighting for the new `string.concat` builtin.)  This PR updates Truffle to use it.

Dependency update: Update highlightjs-solidity to ^2.0.4

---

packages/core/lib/console.js

A quick change from console.log to debug module, as console logging the stderr was adding extra lines to the end of the migration output.

core: use debug module for spawnResult error handling

---

packages/contract-schema/spec/contract-object.spec.json
packages/debugger/test/context.js
packages/debugger/test/helpers.js

As of Solidity 0.8.12, we can now get `immutableReferences` from Yul contracts that use immutables.  However, the keys for these are not numeric AST IDs, but rather simply the names of the immutables.  So, I'm taking out the `patternProperties` and replacing it with `additionalProperties`, since the keys can now be anything.
This PR doesn't do the work of allowing us to actually do things with Yul immutables, like decode them.  I figure that can come later (I've put up issue #4747 for that).  This is just updating the contract schema.
Note: I checked our existing immutable-handling code and as best I can tell this shouldn't screw any of it up.
Edit: Actually, you know what, I was a little bit unsatisfied with this, so I went back and added a test -- not a test of the `contract-schema` …

Allow non-numeric immutable keys in contract-schema and add test of Yul immutable recognition

---

packages/box/test/sandbox.js
packages/box/test/utils-unbox.js

This PR awaits `assert.rejects` as per spec.

Await `assert.rejects` in box tests

---

packages/core/package.json
packages/dashboard-message-bus/package.json
packages/dashboard-provider/package.json
packages/dashboard/package.json

This PR "downgrades" the package.json versions for the three new packages, so as to facilitate `lerna version` setting these to v0.1.0 in the next release.
This is just playing it safe; from what I recall, `lerna version` doesn't like it when you try to bump a package's version to itself.

Prepare @truffle/dashboard* packages for release

---

packages/compile-solidity/package.json
yarn.lock

Apparently, as of Solc 0.8.12, `solc/wrapper` has now been made considerably smaller in size?  So, that seems like a good thing to update to.  This PR does that.

Dependency update: Update solc/wrapper to 0.8.12

---

packages/codec/lib/contexts/types.ts
packages/debugger/lib/evm/actions/index.js
packages/debugger/lib/evm/reducers.js
packages/debugger/lib/session/index.js
packages/debugger/lib/solidity/selectors/index.js
packages/debugger/test/solidity.js

Addresses #4756.  It turns out I wasn't *quite* done with fixing the function depth -- I still hadn't fixed it for Yul contracts!  Yul contracts shouldn't have the phantom call guard set, as when you call them, you are legitimately running outside a function at first.  So, we want to restrict the phantom call guard to when the language is Solidity.  This PR does that.
(What about Vyper, you may ask?  Vyper also shouldn't have the guard set, because like Solidity <0.5.1 the initial function call lacks a jump marking; but this was already handled by the check that the guard only applies to things compiled with `solc`.)
To do this, we have to check the language of the context's primary source; we only set the guard if the language is `"Solidity"`.  Problem: How can we check this?  Once we're …

Bug fix: Fix function depth for Yul contracts

---

packages/deployer/src/linker.js
packages/deployer/test/deployer.js
packages/deployer/test/helpers/eventSystem.js

Finally does away with #2838!
This PR allows `deployer.link` to take a library *instance* in the first argument, rather than just a library *constructor*.  This allows for linking to a library at a specified address in deployment:
```
const libraryInstance = await Library.at(address);
await deployer.link(libraryInstance, Contract);
```
thus finally solving issue #2838.
This PR is mostly pretty straightforward; the primary functional change is that now, when looking for the library name, we check `library.constructor.contractName` if `library.contractName` doesn't exist (and `library.constructor` does exist).  You may be wondering how it's possible that I was able to seamlessly replace `library.contract_name` with `library.contractName`; the answer is that these getters are synonyms, so I …

Enhancement: Allow deployer to link library instances

---

packages/debugger/lib/session/sagas/index.js
packages/debugger/lib/trace/actions/index.js
packages/debugger/lib/trace/reducers.js
packages/debugger/lib/trace/sagas/index.js

This PR removes the indirect system of communication between `next` and `advance` in the debugger's `trace` submodule.  I noticed that this was overly complicated while going through the code with @dongmingh.  So, now, `next` is gone; the whole thing is replaced by `advance`.  The listener is of course gone too, which means that `session` no longer has to start the listener.  And, that's it.  I don't know if this will meaningfully improve debugger performance, but it's definitely simpler to read, at least.
(Also, `prettier` made some changes as well.)
Edit: Oops, I forgot to remove the definition of the `NEXT` action itself!  Went back and did that now.
Edit again: One more thing -- I figured while I was at it, I would rename `BACKTICK` to `TOCK` and `TOCK` to `ADVANCE`.  I think that …

Internal improvement: Remove listener from debugger trace submodule

---

packages/codec/lib/core.ts
packages/codec/lib/types.ts
packages/core/lib/testing/SolidityTest.js
packages/core/lib/testing/TestRunner.js
packages/decoder/lib/decoders.ts
packages/decoder/lib/types.ts
packages/truffle/test/scenarios/solidity_testing/testEventsAndMixedTests.js
packages/truffle/test/sources/mixed_testing/.eslintrc.json
packages/truffle/test/sources/mixed_testing/contracts/StrangeEventTest.sol
packages/truffle/test/sources/mixed_testing/migrations/2_deploy_contracts.js
packages/truffle/test/sources/mixed_testing/test/SolTest.sol
packages/truffle/test/sources/mixed_testing/test/js-test.js
packages/truffle/test/sources/mixed_testing/truffle-config.js

Addresses #4722.  This PR adds the `disableChecks` option codec and decoder when decoding events.  If this option is passed, codec will be a bit looser about checking that its event decodings are strictly accurate.  This can, in some cases, lead to events being incorrectly decoded as ambiguous (where, without the option set, they would correctly be decoded as unambiguous).
So why add such an option?  Well, it turns out that Solidity versions older than 0.7.6, when using ABI encoder V1, sometimes incorrectly encodes the empty string (using an encoding for it that has more padding than it should).  And this is particularly a problem for us because the `TestEvent`s that we use for Solidity testing often include empty strings in their arguments!  In the case of a passing test, this would …

Bug fix: Remove incorrect warnings from `truffle test --show-events` (and prevent Solidity tests from incorrectly passing?)

---

packages/core/lib/commands/test/run.js

No way to set Truffle network config options for Truffle Test's internal Ganache network. See issue #4327 
This PR solves the issue of non-configurable Truffle test's managed ganache network from the truffle-config.js.
If the configured network is "test" and provider, host or url doesn't exist, or there is no configured network defined, then managed ganache is started overriding with the user specified configurations or the default configurations.
If there is a configured network in the config, then it connects to that external network.

Set Truffle network config options for Truffle test's internal ganache network

---

packages/core/lib/commands/init/initSource/truffle-config.js

Just realize we didn't update this for 0.8.12.  Since we still have no automation for this, here's a manual PR.  Again, I used `--no-verify` to keep prettier from altering the comment indentation on the db stuff.

Update Solidity version in Truffle Init to 0.8.12

---

packages/contract-tests/test/deploy.js
packages/contract-tests/test/errors.js
packages/contract-tests/test/sources/ABIV2UserDirectory.sol
packages/contract-tests/test/sources/Example.sol
packages/contract-tests/test/util.js
packages/contract/lib/reason.js
packages/debug-utils/index.js

Addresses #3873.  This PR adds support for panic codes in Truffle Contract.  More specifically, `reason.js` will now return a reason not only for revert strings, but also for panic codes.  Of course there's still no support for custom errors, which wouldn't be reasonable to support in Truffle Contract right now, but I did add a case for these with the generic message `"Custom error (could not decode)"`.
Anyway, as for the actual decoding, it's pretty straightforward.  Of course I could have used Truffle Codec here, but I think probably we shouldn't introduce that dependency yet?  So instead it's just done manually in line with the current way.  While I was doing this I took the time to try to make some of the variables a bit clearer.
Note that getting the string for the panic code is done …

Enhancement: Support panic codes in Truffle Contract

---

packages/artifactor/utils.ts
packages/codec/lib/abi-data/allocate/index.ts
packages/codec/lib/abi-data/encode/index.ts
packages/codec/lib/ast/utils.ts
packages/codec/lib/contexts/utils.ts
packages/codec/lib/storage/allocate/index.ts
packages/compile-solidity/src/compileWithPragmaAnalysis.js
packages/compile-solidity/src/index.js
packages/config/src/index.ts
packages/debugger/lib/data/sagas/index.js
packages/debugger/lib/data/selectors/index.js
packages/debugger/lib/stacktrace/selectors/index.js

This PR imports only the `lodash` methods needed in each package, to reduce bundle size and follow `lodash` best practices as described [here](https://lodash.com/per-method-packages).

Reduce lodash imports to those necessary

---

packages/core/lib/debug/printer.js
packages/source-map-utils/index.js

This PR is to address the crash reported in issue #4616.
The root cause of the issue is that an instruction's byte-offset to the start of the range in the source code is past the end of source code. This is impossible since the byte-offset should always be within the range of the source code. Then the debugger sets the source range to null for such an instruction since it does not exist in the source code. And the null source range causes crash when printing the source code.  However, all instructions along with their attributes including the byte-offset are given by the source map which is provided by the compiler. Hence, this issue is caused by the invalid input from the compiler.
However, the debugger needs to be protected from crash with such an invalid input or even does something …

Allow debugger to handle an instruction with invalid source range

---

packages/debugger/lib/stacktrace/actions/index.js
packages/debugger/lib/stacktrace/reducers.js
packages/debugger/lib/stacktrace/sagas/index.js
packages/debugger/lib/stacktrace/selectors/index.js
packages/debugger/test/stacktrace.js

Addresses #4739.  This PR re-adds the system that I removed in #2976.  As such there's not really much new here, it's mostly just adding the deleted code back in and then adjusting the tests appropriately.  I did rename some of the fields and variables because I feel like the old names could have been clearer.  There is one new thing I had to add -- but I'll get to that.
Anyway, to explain: As of Solidity 0.5.1, when we make an external call, there's a jump-in marking, so without any additional work, `stacktrace` would generate two stackframes; one for the external call, then one for the jump-in.  In the `solidity` submodule, we have the phantom guard system to ensure that these get combined.  It wasn't being applied here.  Now we apply it here.  (The reason it wasn't being applied here …

Re-add system to skip uninformative frames in stacktraces

---

packages/contract-tests/test/methods.js
packages/contract/README.md
packages/contract/lib/contract/properties.js
packages/contract/lib/reformat.js

This PR adds support for `BigInt` as a `numberFormat`. Issue with a description of the task #4777.
Works done:
- Truffle version (`truffle version`): 5.5.2

Support for "BigInt" as a numberFormat (for output)

---

packages/debugger/lib/debugger.js
packages/debugger/lib/session/index.js

These were added in #4808, but after seeing some tests time out on my local machine, I'm potentially worried that there might be a performance impact.  @gnidan said to just go ahead and break things rather than risk that, so, here we are.

Internal improvement: Remove compatibility selectors from debugger (breaking change)

---

packages/core/lib/commands/debug/meta.js

Just noticed this was missing.  Ideally I'd like to do this as `[--network <network>|--url <provider_url>]` but the way that `network` gets tacked on at the end prevents that.  Oh well?  Let me know if there's a better way to do this.

Internal improvement: Add url to debugger usage line

---

packages/hdwallet-provider/src/constructor/getOptions.ts

Currently hdwallet-provider's checks for input arguments is a bit primitive. It just checks to see if you passed one argument as the check for "new-style input arguments". If you were trying to use old-style arguments (positional) and provided just one argument (let's say a string for the provider url), it will then fail with an unhelpful "cannot use in with string"-type error. This PR adds one more check to make sure that that argument is an object.
This PR also adds some information to the message for the error that is thrown when the input arguments do not validate successfully, telling the user to make sure they provide both provider info as well as private keys/mnemonic which are required.

Bug fix: Improve hdwallet-provider argument validation

---

packages/debug-utils/index.js
packages/debugger/lib/stacktrace/reducers.js
packages/debugger/lib/stacktrace/selectors/index.js
packages/debugger/test/stacktrace.js

This PR makes it so that when printing out Solidity stacktraces, calls to constructors appear as `new Contract` rather than just `Contract`.
To do this, I added an `isConstructor` field into the frames of the stacktrace object.  This is a boolean and describes whether that stackframe takes place in a constructor.  (For external calls it's taken from the context; for internal calls it copies the stackframe below.)  Then, when creating the test stacktrace, for stackframes of type `"external"` and with `isConstructor` set, and with no associated function name (not sure how that would happen), we print `new Contract` instead of `Contract`.  Pretty simple!  Note the function in the stacktrace selectors that performs the shifting of the locations also had to be updated to include this in its …

Display "new" before contract name in stacktraces for constructors

---

packages/core/cli.js
packages/core/lib/console-child.js

In https://github.com/trufflesuite/truffle/pull/4128 we shimmed the crypto library as webpack strips it out and ensjs requires the `getRandomValues` function. If it is not present it will print warnings to the console. This PR attempts to simplify the `crypto` shim as we don't need the entire `crypto` package.

Internal improvement: Simplify Truffle's crypto.getRandomValues shim

---

packages/core/lib/commands/test/run.js

`truffle test` command was breaking when invalid or "*" is passed as network_id from `truffle-config.js`.
Added a sanitize function for the ganache options passed from the `truffle-config.js`.

Add sanitize function for network_id in truffle test

---

packages/debug-utils/package.json
yarn.lock

Updates our syntax highlighting for Solidity 0.8.13; see [here](https://github.com/highlightjs/highlightjs-solidity/pull/65) for the actual PR on the highlightjs-solidity repo that this is updating us to have.

Dependency update: Update highlightjs-solidity to 2.0.5

---

packages/environment/package.json
yarn.lock

This PR does two things.  First, it updates node-ipc to 9.2.1, because may as well update.  Second and more importantly, it *pins* it there, because node-ipc 9.2.2 has [this](https://github.com/RIAEvangelist/node-ipc/issues/233) ghastly thing in it, and we have to make sure users of `@truffle/environment` don't encounter that...

Dependency update: Update node-ipc to 9.2.1 and pin it

---

packages/codec/lib/abi-data/allocate/index.ts
packages/codec/lib/abi-data/utils.ts
packages/codec/lib/core.ts
packages/codec/lib/evm/utils.ts
packages/codec/lib/wrap/address.ts
packages/codec/lib/wrap/function.ts

The `codec` package has a bunch of places where it imports `web3-utils` untyped.  I think this was necessary at one point?  Well, it definitely isn't any longer.  This PR cleans that up and replaces them with typed imports.  It also eliminates a few unused imports in the process.
Also, `prettier` made some changes too, which actually ends up being the bulk of the PR.  Sorry!
...and then also, `prettier` introduced a syntax error at one point, and I had to change a coercion from `<>` to `as` to get it to something `prettier` would handle properly...

Internal improvement: Use typed imports for web3-utils in codec

---

packages/compile-solidity/src/index.js

In [this commit](https://github.com/trufflesuite/truffle/commit/34e716be929f3a53e6e3b7bd83d245887e59f5a4) the compilation results were shimmed and converted to `WorkflowCompileResult`s. The output from `compileWithPragmaAnalysis` was accidentally left out. This PR shims that method as well.

Bug fix: Shim output from compileWithPragmaAnalysis

---

packages/decoder/tsconfig.json
packages/encoder/tsconfig.json

The encoder and decoder packages had a duplicate `paths` key in their `tsconrfig.json`. This PR removes the first occurrence, leaving the one that JavaScript would use in this case.

Remove clobbered `paths` key from tsconfig

---

packages/core/lib/commands/test/run.js

The code written in `truffle/packages/core/lib/commands/test/run.js` needed some refactoring.
The code is refactored for better readability/understanding.

Refactor code in truffle test command run.js

---

.gitignore
package.json
yarn.lock

Generates dependency-graph.pdf in the root of the repo that shows
dependencies between the packages in our workspace. Solid lines reflect
runtime dependencies, dashed lines reflect dev dependencies, and dotted
lines reflect peer dependencies.

Add dependency-graph script

---

packages/core/test/lib/commands/compile.js

We're getting a lot of timeouts recently!  This test in particular has been timing out a lot recently!  So I'm upping it!
If this PR fails CI I may add other timeout increases to it as well.

Internal improvement: Increase timeout on docker tags test

---

packages/core/test/lib/commands/compile.js

4 seconds is working better than 2 seconds, but still timing out occasionally.  Let's try 8!

Internal improvement: Turn up docker tag list timeout even further

---

packages/core/lib/commands/init/initSource/truffle-config.js

`truffle-config.js` needs the latest solc version.
`truffle-config.js` is updated with the latest solc 0.8.13 version.

Update default solc-compiler in truffle config

---

packages/dashboard-message-bus/lib/message/types.ts
packages/dashboard-message-bus/lib/utils.ts
packages/dashboard/src/Dashboard.tsx
packages/events/defaultSubscribers/dashboard/client.js
packages/events/defaultSubscribers/dashboard/index.js

This PR does a few things:
- Add a new `"debug"` message type, intended for logging in the browser console. This message type behaves like `"provider"` messages, in that it waits for a response from a subscriber.
- Handle this new message type in the frontend by logging and then issuing a blank response to clear it from the message-bus requests queue
- Initialize a quick DashboardMessageBusClient for use in @truffle/events. Define a `sendAndAwait` method to behave similarly to the @truffle/dashboard-message-bus util function
- Use this client to send an example debug message to the browser upon `"compile:start"`

Hook up example events -> dashboard communication

---

.github/workflows/nodejs.yml

Reverts trufflesuite/truffle#4919 
Apparently it wasn't even doing anything for us

Revert "Run CI for PRs targeting `feature/dashboard`"

---

README.md
packages/core/lib/commands/init/initSource/truffle-config.js
packages/truffle/README.md

`truffle-config.js` and README files have an outdated url mentioned. See #4912 .
The outdated url is replaced with the new url pointing to the required documentation (in `truffle-config.js` and `README.md`).

Update url in the comments in config and README

---

packages/compile-solidity/src/compileWithPragmaAnalysis.js
packages/compile-solidity/test/compileWithPragmaAnalysis.js
packages/compile-solidity/test/sources/badSources/Imported.sol
packages/compile-solidity/test/sources/badSources/NoPragma.sol
packages/compile-solidity/test/sources/multipleSolcVersions/withImports/D.sol
packages/compile-solidity/test/sources/multipleSolcVersions/withImports/NoPragma.sol

addresses https://github.com/trufflesuite/truffle/issues/4928
There is currently a bug where Truffle throws an unhelpful error when a user utilizes the "pragma" compiler setting and doesn't include a pragma expression in one of their sources. Though this is legal Solidity, Truffle requires the user to have a pragma expression in the sources the user creates because Truffle needs to load a version of the Solidity parser to find imports for the source.
There is code meant to handle this case but it turns out that it fails before running this code as it tries to index into a regex match when that result could possibly be `null`. This PR adds a check that determines whether a result is present before attempting to index into the result.
I'm going to try and write (a) test(s) for this bug fix.

Bug fix: Check matching result for null values with pragma setting

---

packages/dashboard/src/utils/utils.ts
packages/events/Subscriber/helpers.js

[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.

refactor: replace deprecated String.prototype.substr()

---

packages/codec/lib/export.ts
packages/codec/lib/format/utils/inspect.ts

[browser-util-inspect](https://www.npmjs.com/package/browser-util-inspect) is pretty cool because it provides the Node.js `util.inspect` functionality in the browser! It even supports custom inspect functions...
... except instead of looking for the symbol `util.inspect.custom`, it looks for a method called `inspect`.
This PR aliases the existing symbol-defined method with an additional `inspect` interface for use by this package in the browser.

Add custom inspect alias to codec inspectors, to support browser-util-inspect

---

packages/core/lib/commands/migrate/index.js
packages/core/lib/commands/migrate/prepareConfigForRealMigrations.js
packages/core/lib/commands/migrate/run.js
packages/core/lib/commands/migrate/runMigrations.js
packages/core/lib/commands/migrate/setUpDryRunEnvironmentThenRunMigrations.js
packages/core/test/config.js
packages/core/test/ethpm.js
packages/core/test/migrate.js
packages/truffle/test/scenarios/commands/obtain.js

addresses https://github.com/trufflesuite/truffle/issues/2928
When Truffle forks for a dry run, it initializes a Ganache instance. That Ganache instance is passed a provider, presumably with the user's unlocked accounts. On initialization, however, Ganache generates another set of 10 accounts that are unlocked which pushes any accounts the user has unlocked to the second half of the array of unlocked accounts. This behavior is probably not what we want, as the user should probably expect that his unlocked accounts will start at index 0.
To remedy this, this PR adds `wallet: { totalAccounts: 0 }` to the list of options passed to Ganache. This causes Ganache to refrain from unlocking additional accounts.
To test this, you can simply create a network configuration that has a provider with …

Bug fix: Don't autogenerate accounts when forking for a dry run

---

packages/events/defaultSubscribers/migrate/Messages.js
packages/events/defaultSubscribers/migrate/Reporter.js
packages/spinners/lib/spinner.ts
packages/spinners/typings/spinnies/index.d.ts

Works around a bug in the `spinnies` module (jcarpanelli/spinnies#34) where removal of the final spinner may cause the spinner text to not disappear and/or may cause the process to hang on termination due to an interval not being cleared.

spinners: fix remove logic

---

packages/core/lib/commands/opcode/run.js

The problem was that the `truffle opcode` gave instruction indexes instead of PC values. Issue: #4835.
Works done:
- Truffle version (`truffle version`): 5.5.6

Show program counter instead of instruction index in `truffle opcode`

---

packages/codec/lib/wrap/utils.ts
packages/encoder/test/address.test.ts
packages/encoder/test/function.test.ts

A thing I forgot while writing encoder: If `x` is callable, then `typeof x` will return `"function"`, not `"object"`!  This means that callable objects wouldn't be accepted as input for external functions.  It was always my intention that those would work (because of the intended use case with Truffle Contract, that with a rewritten version of Truffle Contract one could actually pass in the methods), but they didn't.  So, I made that work, and also added a test.
I also did the same for contract input, because, well, why not; figured it makes the most sense for it to act analogously.

Bug fix: Allow functions as input for functions and contracts in `@truffle/encoder`

---

packages/contract-schema/index.js

The `normalize` function in the `contract-schema` package has a behavior that was copying `ast` value to the `legacyAST` value field when legacyAST value is absent.
This PR removes that behavior from the schema properties because **legacy AST** has been removed from `solc 0.8.0` onwards. However, it is advised not to remove the `legacyAST` property entirely from the schema.

Remove function that copies ast value to legacyAST value in contract-schema

---

packages/core/lib/commands/create/helpers.js
packages/core/lib/commands/migrate/setUpDryRunEnvironmentThenRunMigrations.js
packages/core/lib/commands/test/copyArtifactsToTempDir.js
packages/core/lib/copy.js
packages/core/package.json
yarn.lock

Truffle has a `copy` utility responsible for copying files or directories. It uses a very old package called `cpr` which this PR swaps out for a package with very few dependencies called `mvdir`. A lot of the code in the `copy` utility was also updated to be more modern and simple.

Internal improvement: Swap in mvdir for cpr package

---

packages/codec/lib/export.ts
packages/codec/lib/format/errors.ts
packages/codec/lib/format/utils/exception.ts
packages/codec/lib/format/utils/inspect.ts
packages/codec/lib/storage/read/index.ts
packages/core/lib/debug/printer.js
packages/debugger/lib/data/sagas/index.js
packages/debugger/lib/session/index.js
packages/debugger/test/data/more-decoding.js

Note: This PR is not quite up to my usual standards, but I'm PRing it anyway because we're trying to get this out fast!  I'm intending to address the problems in a later PR.  (Possibly I'll just handle this when I implement reverse ENS resolution, or possibly I'll do it separately first.)
This PR adds an option to the debugger's `variables` and `variable` methods so that it will indicate which storage variables are unknown, as opposed to just filling in the missing values with zero.  It then also sets the CLI debugger to use that option, and display such missing values with gray question marks.  (Note that when dealing with complex values, parts can be known and parts unknown!)  It also makes it so that the debugger will print an explanatory note when there is at least one such gray …

Enhancement: Indicate which storage variables have unknown values in debugger

---

packages/codec/lib/abi-data/allocate/index.ts

Oops, it looks like I accidentally checked in some commented-out code!  This shouldn't be there.  Removing it.

Internal improvement: Remove some commented-out code

---

packages/core/lib/debug/cli.js

Bit of an embarrassing one. Seems I've come to lean too heavily on the TS compiler 😊

core: fix debugger -x crash due to missing spinner

---

.gitignore

Add the following items to .gitignore relevant to Windows based development environments: Thumbs.db and $RECYCLE.BIN/

Add items to .gitignore specific to Windows based dev envs

---

packages/box/lib/utils/index.ts
packages/events/defaultSubscribers/unbox.js

Fixes some minor errors in the output of the `unbox` command. Namely duplicate messages on failure due to the `unbox:fail` event firing twice, and a bad spinner success message due to a missed string when migrating from `spinnes` to `@truffle/spinners`.

Fix unbox event output

---

packages/codec/lib/format/utils/circularity.ts

Once again, it seems that my use of a `for ... in` loop is causing problems for VSCode.  Since in this case I was using it to loop over a non-sparse array, I just changed it to a C-style loop.  Hopefully that should get rid of the problem.
It may be worth doing a more thorough sweep of the codebase (or at least debugger and codec) for these loops if they're going to keep causing problems for VSCode, but this PR just fixes this particular case.

Bug fix: Replace for/in loop with C-style loop to prevent VSCode problems

---

packages/db-kit/package.json
packages/encoder/package.json
yarn.lock

I think during a merge conflict an extra `version` field was left in the encoder and db-kit packages. This PR removes the extra `version` field.

remove extra version fields

---

packages/dashboard-provider/test/DashboardProvider.test.ts
packages/dashboard/test/DashboardServer.test.ts

Before this change the dashboard and dashboard provider tests took about 2 minutes each to run. Now they take around 20 seconds each.

fix slow ethers tests

---

packages/codec/lib/format/utils/inspect.ts

Did a review of other for-in loops in debugger and codec.  This one was the only one I found that seemed likely to cause trouble, so I'm getting rid of it pre-emptively.  @michaeljohnbennett let me know if you encounter problems with any others and I can get rid of those too, but this was the only one that seemed worth changing pre-emptively.

Internal improvement: Eliminate another for-in loop

---

packages/codec/lib/compilations/utils.ts

Addresses #5007.
This PR fixes a debugger crash that would occur when using `--fetch-external` to debug contracts written with Solidity versions prior to 0.4.9.
Now, we basically don't support Solidity versions that old... but ideally the debugger wouldn't crash, at least.  Especially as a person using `--fetch-external` doesn't necessarily know in advance which Solidity versions would be involved!
(Frankly I'm surprised that `compile-solidity` doesn't run into problems in such cases... I thought that's where the problem was...)
Because we don't really support Solidity that old, this PR isn't intended as any sort of full fix; it's basically just meant to patch over the problem.  Actually truly making such old versions work, issue #1679, is another matter.
Long story short, it turns out …

Bug fix: Fix debugger crash on ancient Solidity versions

---

packages/debugger/package.json
yarn.lock

We're no longer using this, @gnidan suggested removing it.

Internal improvement: Remove esdoc from debugger

---

packages/core/package.json
packages/truffle/package.json
yarn.lock

Addresses #399 and its duplicate #1005; supersedes #4944 (apologies @percentcer, but thanks for bringing our attention to the issue!).
I tried updating `yargs` to a more recent version, and, hey, that solved the problem!  Why to 13.3.0 specifically, and not an even more recent version?  Simple: More recent versions didn't pass CI!  Note we're currently on 8.x, so going to 13.3.0 is blowing past a number of breaking releases... however, it seems to work, and this version passes CI, so I guess it's OK?

Dependency update: Update yargs to ^13.3.0

---

packages/db/src/project/test/compilationSources/.eslintrc.json
packages/db/src/project/test/compilationSources/truffle-config.js
packages/db/src/project/test/integration.spec.ts
packages/deployer/test/ens.js
packages/hdwallet-provider/test/provider.test.ts
packages/hdwallet-provider/tsconfig.json
packages/interface-adapter/test/fabric-evm-getId.test.ts
packages/interface-adapter/test/quorum-decodeParameters.test.ts
packages/interface-adapter/test/quorum-getBlock.test.ts

Makes it so that the tests in question don't require open ports to listen on, and are therefore easier to execute in parallel.

Make most tests use ganache provider instead of server

---

packages/compile-solidity/package.json
packages/compile-solidity/src/compilerSupplier/loadingStrategies/Docker.ts
packages/core/lib/debug/cli.js
packages/core/package.json
packages/events/defaultSubscribers/migrate/Reporter.js
packages/events/defaultSubscribers/obtain.js
packages/events/package.json
packages/spinners/lib/spinner.ts
packages/spinners/package.json
yarn.lock

spinners: fix spinner color issues

---

packages/encoder/test/wrap-fc.test.ts

So, #4932 was supposed to fix this, but didn't quite.  Hopefully this one actually does.  So why do I think that this one will work where the previous one failed?
Well, the problem with #4932 is that it assumed that the discrepancy would be at most a certain *absolute* size.  However, after looking at more counterexamples, it's clearer what's actually going on.  If there is a discrepancy, it always begins in the 15th decimal place after the first nonzero one.  It's the relative error, not the absolute error, that matters.
So why the 15th decimal place?  Well, why are discrepancies occurring at all?  Well, it's because we're converting from `Big` (decimal) to `number` (binary) and then back to `Big`.  That's necessarily going to be a bit lossy, especially as `number` has limited precision. …

Internal improvement: Re-fix sporadically failing encoder test

---

packages/debugger/lib/txlog/actions/index.js
packages/debugger/lib/txlog/reducers.js
packages/debugger/lib/txlog/sagas/index.js
packages/debugger/test/txlog.js

Addresses #3884.
This PR fixes a problem where intermediate state -- specifically, the `waitingForFunctionDefinition` field -- was appearing in final txlogs.  Why was this problem occurring?  Basically, we had a case where the conditions for a jump out and for an identify were triggered on the same step.  So an action was triggered for each, and, uh, I guess these things don't always work synchronously?  IDK, I'm a little unclear on that point.  Regardless, the jump out action deleted the `waitingForFunctionDefinition` intermediate state... and then the identify added it back in (setting it to `false`).  Oops.
So, in order to prevent this from happening, I had to make the identify case exclusive of the other cases.  Why wasn't it exclusive before?  Well, what if we have a simultaneous …

Bug fix: Prevent intermediate state from appearing in final txlog

---

packages/encoder/lib/encoders.ts

Thanks to @gnidan for catching this.  So here's a fairly dumb mistake on my part.  The decoder uses the encoder for watching mapping keys.  The encoder allows the use of ENS for addresses (if this is turned on), and the decoder, by default, turns it on.  Yet ENS wasn't working; in the encoder, it wasn't actually getting turned on.  What's the problem?
Well, so, the decoder uses a special route for creating the encoder that avoids repeating certain work.  And, I accidentally restricted the encoder's ENS setup code to the normal route, rather than running it uncondtionally.  Oops.  Anyway, this PR moves that code out of the conditional so it'll run regardless.
I had meant to include an automated test of this, but I ran into some trouble setting it up, so I just excluded it for now.  But if …

Bug fix: Allow use of ENS with mapping key watching in decoder

---

packages/fetch-and-compile/README.md
packages/fetch-and-compile/lib/fetch.ts
packages/fetch-and-compile/lib/index.ts
packages/fetch-and-compile/lib/types.ts
packages/fetch-and-compile/lib/utils.ts
packages/fetch-and-compile/test/fetch.test.ts
packages/source-fetcher/lib/index.ts

Addresses #4485.
This PR alters the interface for `fetch-and-compile` so that its functions now, instead of a Truffle Config, take either a Truffle Config *or* a new type of object containing the necessary info.  All the exported functions now accept this alternate input (which is intended to now be the primary input).  The new input type is based on the one suggested by @gnidan in the commentson #4485, although there have been some minor alterations for typing convenience.
To accomplish this, all the functions now run their input first through a `normalizeInput` function which normalizes things to the new format.  Since `Config` is a class rather than just a type, we detect if the input is a `Config` with a simple `instanceof` check.
The rest of the code has been altered appropriately. …

Enhancement: Add new interface for fetch-and-compile that doesn't require a Truffle config

---

packages/debugger/package.json
yarn.lock

See trufflesuite/reselect-tree#10; this PR updates us to use the fixed version.

Dependency update: Update reselect-tree to 1.3.6

---

packages/environment/.eslintrc.json
packages/environment/chain.js
packages/environment/develop.js
packages/environment/test/connectOrStartTest.js
packages/environment/test/develop.js

This PR 
- updates the use of the Ganache's `server.close()` method, which uses a promise instead of node's callback idiom. We should tear down Ganache properly.
- cleans up the logic for `connectOrStart`
- adds 2 tests to verify `connectOfStart` try/catch logic path.

Internal improvement: refactor connectOrStart

---

packages/fetch-and-compile/test/fetch.test.ts
packages/source-fetcher/lib/etherscan.ts
packages/source-fetcher/lib/networks.ts
packages/source-fetcher/lib/sourcify.ts

So, it turns out that Sourcify and Etherscan (or rather, "Blockscan", to use the new more general name -- no, I didn't go changig our name for it) have added support for a bunch more networks; this PR updates source-fetcher to support them as well.
So, what's it do in more detail?
First off, it adds all these new networks to the big list of networks.  You'll notice there's another thing it adds to the big list of networks -- Avalanche.  I'd previously excluded Avalanche due to network ID / chain ID mismatches that would cause a problem for us; but as best I can tell, they've now changed their network IDs to match their chain IDs, so there's no reason to exclude them anymore.
Also, for consistency, I added POA Core to the big list, even though neither fetcher supports it.  This is for the …

Enhancement: Add even more networks to source-fetcher

---

packages/db/src/project/test/integration.spec.ts

Removes a unit test that was blocking provider and web socket work. There's a rework in progress of the network portion of db and most of the tests are going to be reworked along with some of the tools so this is a benign removal that also comes as a (well justified) request [here](https://github.com/trufflesuite/truffle/pull/5029/files/2d3c56da47369c9f3eade31dfa2a48033f714362#r859540144) to help keep the git history clean and avoid burying this change in unrelated provider work.

Remove unit test from db

---

packages/source-fetcher/lib/etherscan.ts
packages/source-fetcher/lib/networks.ts

Looks like Etherscan just added this network.  Adding it here.

Enhancement: Add cronos testnet to etherscan source fetcher

---

packages/source-fetcher/lib/networks.ts
packages/source-fetcher/lib/sourcify.ts

Looks like Sourcify just added a bunch of networks.  (Including finally adding Oneledger mainnet; I don't know why previously they only supported the testnet.)  Adding them.  (Would have combined this with #5113 had I realized!)

Enhancement: Add more networks to sourcify source fetcher

---

packages/source-fetcher/lib/networks.ts
packages/source-fetcher/lib/sourcify.ts

Sorry, just a quick renaming, sorry about all these tiny source-fetcher PRs!  But it seems that this "wagmi" network is part of Avalanche?  So I figured I'd alter our name for it appropriately.  That's all.

Internal improvement: Fix name of network in source-fetcher

---

packages/codec/lib/abi-data/allocate/index.ts
packages/codec/lib/core.ts
packages/codec/lib/export.ts
packages/debugger/lib/data/actions/index.js
packages/debugger/lib/data/reducers.js
packages/debugger/lib/data/sagas/index.js
packages/debugger/lib/data/selectors/index.js
packages/debugger/lib/evm/selectors/index.js
packages/debugger/lib/session/actions/index.js
packages/debugger/lib/session/index.js
packages/debugger/lib/session/sagas/index.js
packages/debugger/lib/txlog/actions/index.js
packages/debugger/lib/txlog/reducers.js
packages/debugger/lib/txlog/sagas/index.js
packages/debugger/lib/txlog/selectors/index.js
packages/debugger/test/txlog.js

Addresses #3824.  (Well, the first part of it -- probably best to close the issue once this is released, and I'll make a second issue for the second part of it, i.e., the flattened log and the CLI command to show it.)
This PR adds events to the txlog.  Specifically, it creates a new type of action, type `"event"`.  This new type of action does not itself have an `actions` subfield, note, because it doesn't represent any sort of call, that might have subactions; it simply represents the logging of an event, something that cannot have subactions.
In fact, this new type of action has only one subfield other than `type`, which is `decoding`, a `LogDecoding` as output by Truffle Codec.  All txlog information about the event is found in here.  (We don't explicitly record the event's address or …

Enhancement: Put events in txlog (txlog part 2)

---

packages/core/lib/commands/init/initSource/truffle-config.js

I used `--no-verify` to get it to leave the comma in after `compilers`. :P

Update truffle init solc version to 0.8.14

---

packages/contract/README.md

The truffle contract README includes some misleading examples.  I updated these and linted the file.  Happy to remove the linting if it's offensive.
I also updated a lot of instances of ```MyContract.deployed().then(function(instance) {...})``` to ```const instance = await MyContract.deployed();``` since that syntax is more common these days.

Update truffle/contract README examples

---

packages/fetch-and-compile/test/fixture.js

So, uh, some of our fetch-and-compile tests were accidentally hitting the real network for their sources.  Oops! >_>  This is due to me messing up the URLs in the test fixtures.  I fixed the URLs and now the tests don't hit the network anymore (tested by running the tests with internet turned off).
(Why not obviate this problem by preventing the tests from hitting the real network at *all*, rather than just the specified URLs?  Because when you do that, they fail to fetch solc...)

Internal improvement: Prevent fetch-and-compile tests from hitting the network

---

packages/contract/typings/index.d.ts

In response to https://github.com/trufflesuite/truffle/issues/4825, this PR removes the types from @truffle/contract.

Bug fix: Remove incorrect typings from contract

---

packages/source-fetcher/lib/networks.ts
packages/source-fetcher/lib/sourcify.ts

Didn't include this one in #5156 because Sourcify didn't support it yet... but now it does.  So there you go.

Add non-testnet DFK to sourcify fetcher

---

packages/debug-utils/index.js
packages/debugger/lib/controller/sagas/index.js
packages/debugger/lib/controller/selectors/index.js
packages/debugger/lib/data/sagas/index.js
packages/debugger/lib/data/selectors/index.js
packages/debugger/lib/sourcemapping/selectors/index.js
packages/debugger/lib/stacktrace/selectors/index.js
packages/debugger/test/step.js

Addresses #4561, supersedes #4677.
This PR fixes some longstanding problems with the debugger's stepOver and stepOut functionality.  Specifically:
1. `stepOut` now behaves consistently; the unnecessary special case it had has been removed
2. When `stepOver` is used while on a function definition, the function will (usually) be stepped over rather than into
How does this work?  Well, (1) there's not much to say about... I just removed the special case that shouldn't have been there.
As for (2), I made it so that, if you are on a function definition, then `stepOver` will defer to `stepOut` instead.  Note that this relies on being able to *determine* that you're on a function definition, so this won't work with Vyper (or with Solidity older than 0.4.12, or assembly/Yul older than 0.6.0).
It …

Bug fix: Fix behavior of stepOver and stepOut on function definitions

---

packages/debug-utils/index.js

Fix typo in index.js

---

packages/codec/lib/core.ts
packages/codec/lib/export.ts
packages/codec/lib/index.ts
packages/codec/lib/types.ts
packages/decoder/lib/decoders.ts
packages/decoder/test/current/contracts/WireTest.sol
packages/decoder/test/current/test/wire-test.js

Addresses #4133.  This PR adds `interpretations` to decodings returned by `@truffle/decoder`, with one interpretation currently existing: multicall.
This is mostly pretty straightforward -- the decoder, after decoding a transaction, will check whether it's a multicall (as in: name `multicall`, arguments a single `bytes[]`), and, if it is, will then recurse over the subcalls and decode them, sticking the result in `interpretations.multicall`.  There's not much to say about the logic here!  I also added a test of this functionality.
I also updated `CalldataDecodingInspector` so that it will check for `interpretations.multicall`, and, if it finds it present, print out the the calls made rather than the raw bytestrings for each entry.  In the process I found that the existing logic for …

Enhancement: Add decoding of multicalls to `@truffle/decoder`

---

packages/db/package.json
yarn.lock

older version uses a vulnerable version of node-fetch
Output of `npm list node-fetch` when using `truffle:5.5.17` (also checked that the vulnerable version is included in `5.5.18` as well:
```
| `-- truffle@5.5.17
|   `-- @truffle/db@1.0.10
|     +-- apollo-server@3.8.2
|     | `-- apollo-server-core@3.8.2
|     |   `-- apollo-server-env@4.2.1
|     |     `-- node-fetch@2.6.7  deduped
|     +-- pouchdb@7.2.2
|     | `-- node-fetch@2.6.0               >>>> This is the vulnerable version, updating to `pouchdb:7.3.0` pulls the updated package
|     `-- pouchdb-find@7.3.0
|       `-- pouchdb-fetch@7.3.0
|         `-- node-fetch@2.6.7  deduped
```
ref: https://github.com/pouchdb/pouchdb/pull/8448

Bump pouchdb version

---

packages/deployer/src/deployment.js

There are some methods in the deployer that seem unused. This PR gets rid of them. They look like "private" methods and I can't find any reference to them.

Internal improvement: Remove seemingly unused methods

---

packages/core/lib/commands/init/initSource/truffle-config.js

This PR updates the `solc` version in `truffle-config.js` to the latest **0.8.15**.

Update truffle init solc version to 0.8.15

---

packages/deployer/src/deferredchain.js
packages/truffle/test/scenarios/migrations/deferred-chain.js
packages/truffle/test/sources/migrations/deferred-chain/.eslintrc.json
packages/truffle/test/sources/migrations/deferred-chain/migrations/1_initial_migration.js
packages/truffle/test/sources/migrations/deferred-chain/truffle-config.js

Addresses #3066.
So, normally here I'd explain how the PR works... but the fact is, after spending a lot of time looking at the deployer, I still can't really claim to understand it to any real extent.  I can tell you why this was a plausible thing to try; I can't tell you why it was the right thing to do.
So why was this a plausible thing to try?  Well, when you do `.then()` with the deferred chain, it not only adds a `.then()` to the chain, it also adds a `.catch()`.  This `.catch` apparently doesn't properly rethrow the error, so it results in the promise being accepted, not rejected.  This causes issue #3066 where you advance to the `.then()` instead of the `.catch()`.  So, I added a `throw` to the end, and now it works.
That's my best understanding, anyway!
I didn't include any tests …

Bug fix: Ensure errors are rethrown in deferred-chain deployment

---

packages/compile-solidity/package.json
packages/contract-schema/package.json
yarn.lock

This PR updates the `solc` version to latest `0.8.15` in the `compile-solidity` and `contract-schema` packages.

Dependency update: Update solc version to 0.8.15

---

packages/artifactor/package.json
packages/codec/package.json
packages/contract-tests/package.json
packages/contract/package.json
packages/core/package.json
packages/db-kit/package.json
packages/db/package.json
packages/debugger/package.json
packages/decoder/package.json
packages/decoder/test/current/test/compatible-nativize.js
packages/decoder/test/current/test/decoding-test.js
packages/decoder/test/current/test/downgrade-test.js
packages/decoder/test/current/test/receive-test.js
packages/decoder/test/current/test/wire-test.js
packages/decoder/test/legacy/test/shadow-test.js
packages/decoder/test/legacy/test/wire-test.js
packages/deployer/package.json
packages/encoder/package.json
packages/environment/package.json
packages/events/package.json
packages/external-compile/package.json
packages/fetch-and-compile/package.json
packages/hdwallet-provider/package.json
packages/interface-adapter/package.json
packages/provider/package.json
packages/resolver/package.json
packages/source-fetcher/package.json
packages/source-map-utils/package.json
packages/truffle/package.json
yarn.lock

This PR upgrades to latest web3 (1.7.4)
It turns out Truffle had a Ganache teardown issue with the decoder tests because the test providers used `eager instamine mode`. Truffle should use `instamine strict` mode, as it models how GETH and other clients behave. A good summary of how the different modes behave is [outlined in this doc](https://hackmd.io/wv7c5wn5Q0ebUWUH-N1H5A)

Upgrade to Web3 1.7.4

---

packages/dashboard-message-bus-client/package.json
packages/dashboard-message-bus-common/package.json

[issue#5235](https://github.com/trufflesuite/truffle/issues/5235), [discussion#5237](https://github.com/trufflesuite/truffle/discussions/5237)
Some Dashboard-related packages were newly introduced in the latest release (v5.5.19), and due to misconfigured `package.json`, the following Truffle packages fail to import when individually installed.
<details>
<summary>Installable, but fail on import</summary>
<code>
@truffle/box @truffle/compile-michelson @truffle/compile-smartpy @truffle/compile-solidity @truffle/compile-vyper @truffle/config @truffle/dashboard @truffle/dashboard-message-bus @truffle/dashboard-message-bus-client @truffle/dashboard-message-bus-common @truffle/dashboard-provider @truffle/db @truffle/db-kit @truffle/environment @truffle/events @truffle/external-compile …

Fix broken imports

---

scripts/ci.sh
scripts/geth.sh

Geth just released a new version, yay! 🥇 However, in https://github.com/ethereum/go-ethereum/releases/tag/v1.10.20 they removed the `js` subcommand. 🤕 Now CI is broken, oh my!
This pins Geth to v1.10.19 until we can find out what the proper fix is.

pin geth to v1.10.19

---

packages/contract-sources/index.js

**THIS IS A BREAKING CHANGE FOR contract-sources**
This removes the callback from the default export's signature.

Internal improvement: Simplify contract-sources's default export

---

packages/core/lib/console-child.js
packages/truffle/test/scenarios/commands/console.js
packages/truffle/test/sources/console/truffle-config.js

PR #5087 broke `truffle console --network` because it [hardcoded the `network name` to be `develop`
](https://github.com/trufflesuite/truffle/blob/b7896bb42b932eaf506369315f43405e5762535f/packages/core/lib/console-child.js#L45)
This was because `console-child.js` had logic exclusively used by the `truffle develop` command. When `truffle console --network <network_name>` is used, it adds the `develop` network into `config` which is not required. This behaviour doesn't make sense after PR #5087 because `console-child.js` has to satisfy more code paths such as:
- `truffle console --network`
- `truffle console --url` 
- `truffle develop`
This PR  makes `console-child.js` more robust to handle the above cases. And also adds an integration test for the `truffle console --network` option. …

Refactor console-child.js to make the network settings more robust

---

packages/source-fetcher/lib/networks.ts
packages/source-fetcher/lib/sourcify.ts

This PR adds support to the Sourcify fetcher for the new networks that Sourcify has added support for this month (it looks to me like they may have gone on to a monthly update schedule? We'll see if that holds up).  I excluded Crystaleum, however, as it once again has network ID different from chain ID (it uses network ID 1), which we still can't handle.
As with the way I've done things in the past, since Sourcify has added support for the godwoken testnet, I've also put the godwoken mainnet in the networks file, even though neither fetcher presently supports it.
Sourcify has also partially *removed* support for ropsten and kovan with this update, but I've left those in; unlike when Etherscan removed support for hoo, Sourcify says existing verified contracts on ropsten or kovan will …

Add Sourcify networks for July 2022

---

packages/resolver/package.json
yarn.lock

`abi-to-sol` had a minor bump a few releases ago and semver range wouldn't resolve to its new version. This PR fixes that.
abi-to-sol
* @truffle/resolver: ^0.5.2 → ^0.6.2

resolver: update dependency: abi-to-sol@^0.6.2

---

scripts/ci.sh
scripts/geth-accounts.js
scripts/geth.sh

Trying out a replacement for https://github.com/trufflesuite/truffle/pull/5249

ci: fix geth accounts script

---

packages/truffle/test/scenarios/commandRunner.js
packages/truffle/test/scenarios/commands/debug.js
packages/truffle/test/sources/debug/truffle-config.js

This PR includes few integration tests for `truffle debug` which includes the following scenarios -
- when runs with `--network` option with a config file.
- when runs with `--url` option -
1) with a config file.
2) without a config file (outside a truffle project).

Add integration tests for debug command

---

.github/workflows/nodejs.yml

This PR builds on #5230 to address #5236 by adding a GitHub action to CI. I didn't create a separate job for the dependency check because it would require the expensive `yarn bootstrap` command and I don't want CI to take longer. Instead, I inserted the dependency-check into the matrix strategy `build` job to take advantage of the matrix's short-circuiting behavior.  If one matrix job fails, it cancels all others. I also updated the Slack-app config and made the matrix-build job a dependency of `yarncheck`. `yarncheck` resolves in ~2.5 minutes and then the matrix job runs, followed by Slack notification.
If this is approved, I will rebase to remove all simulated errors

Add GHA dependency check

---

packages/core/lib/console.js
packages/truffle/test/scenarios/commands/develop.js

Addresses #3349.
This PR fixes the issue where expressions of the form `foo = await bar`, when entered in the Truffle Console, would perform the assignment but then not return the resulting value.  Note that this PR does **not** fix the more general issues with the use of `await` in the Truffle Console, which is issue #1546.  Fixing the broader problems are probably going to have to wait until we have removed support for both Node 12 and Node 14.
The fundamental problem, and the reason for #1546, is that all our `await`-handling code in the console is a bunch of hacks.  The ultimate solution to all of this, once we don't need to support Node 12 and Node 14 anymore, will be to remove all these hacks and do things the straightforward way that Node 16 will allow us to do it.  However, in the …

Bug fix: Correctly return value for `foo = await bar` in console

---

package.json
yarn.lock

As a Truffle developer that yarn bootstraps many times a day, you must be tired of pesky messages like this
This PR removes it!
- `browserslist@latest --update-db` was run at project root, `yarn.lock` reflects the change that took place.
- Yarn running the script corrected the order of dev dependencies listed in `package.json` at project root.

Internal improvement: Clear `Browserslist caniuse-lite is outdated` message when building dashboard

---

packages/hdwallet-provider/package.json
packages/hdwallet-provider/src/constructor/getOptions.ts
packages/hdwallet-provider/test/provider.test.ts
packages/hdwallet-provider/test/urlValidation.test.ts
yarn.lock

Use newer ethereumjs-util

---

packages/core/cli.js
packages/core/lib/command-utils.js

Address #5186, truffle crashes when an invalid truffle command is used. 
For example `truffle --version` or `truffle liang`
Added a better error and prompts the user to use `truffle help` to see the list of available valid commands. 
I thought it is cleaner looking to just display the error message instead of the error message and stack trace together, do let me know if you think otherwise. Or if you have a better suggestion on how to handle this error.

core: error better on scenarios with incorrect truffle command

---

packages/dashboard-message-bus-common/lib/utils.ts

It runs fine in node but not in the browser, which creates problems when dashboard's frontend uses it.

Internal improvement: Add missing `buffer` import in `dashboard-message-bus-common`

---

packages/source-fetcher/lib/networks.ts
packages/source-fetcher/lib/sourcify.ts

I guess I was at least partly wrong about Sourcify going to a monthly schedule, because they just added this network.  As with other testnets where they only support the testnet but not the mainnet, I listed both the mainnet and the testnet in `networks.ts` even though only the testnet got added to `sourcify.ts`.

Enhancement: Add support for XinFin Apothem testnet to sourcify fetcher

---

packages/contract/package.json

The broken types for @truffle/contract were removed in https://github.com/trufflesuite/truffle/pull/5142. There is still a reference to the types in its package.json that this PR removes.

Internal improvement: Remove leftover typings entry in contract's package.json

---

packages/decoder/test/current/test/compatible-nativize.js

This test has been timing out a bunch recently for whatever reason, so I'm turning up the timeout to 4 seconds.  Hopefully that's enough!

Internal improvement: Up timeout on decoder test

---

packages/debugger/lib/txlog/actions/index.js
packages/debugger/lib/txlog/reducers.js
packages/debugger/lib/txlog/sagas/index.js
packages/debugger/lib/txlog/selectors/index.js
packages/debugger/test/txlog.js

This one is pretty straightforward. It adds a `raw` field to `event` actions in the txlog, so there will be info even if decoding failed.  The `raw` field has four subfields: `address`, `codeAddress`, `topics`, and `data`.  The `topics` and `data` fields are what you expect.  The `address` is the address that officially omitted the event, and `codeAddress` is the address of the *code* that emitted the event.  These can be different if the event was emitted from a delegatecall (e.g. a library), as officially it's the caller of the library that emits the event, but I thought it was good to include the `codeAddress` as well to tell you what contract's *code* emitted the event.
Note that if an event is emitted from a constructor, both `address` and `codeAddress` will be equal to the address …

Enhancement: Include raw event data in txlog

---

package.json

This change, albeit small, fixes a weird issue that causes `yarn bootstrap` to hang in my local dev environment.
During #5222, I opted to use a package called `npm-run-all` to avoid the `&&` operator in defining the build script command for `@truffle/require`. I did this because windows shells don't understand the `&&` operator, and I didn't want to introduce a change that would break the Windows build.
So instead of writing `"build": "yarn build:compile && yarn build:copyfiles`, I did `"build": "run-s build:compile build:copyfiles"`. These two script definitions are functionally identical in that the `run-s` command just executes the specified `package.json` scripts sequentially.
That worked great all through dev and test, but now that I've merged latest develop into my branch, I've …

Run `lerna bootstrap` via yarn exec instead of npx

---

packages/source-fetcher/lib/etherscan.ts

Celoscan is moving from celoscan.xyz to celoscan.io; this PR updates those URLs.

Update celoscan url

---

packages/db/package.json
packages/db/test/jest-resolver.js

I'm not too sure why this isn't happening on develop, but take a look at [this failed ci run](https://github.com/trufflesuite/truffle/runs/7512994995).
We recently upgraded to jest 28, and it's trying to use an esm version of uuid (a pouchdb dep), things break because of that. So I added a custom jest resolver that forces jest to use the cjs version of uuid.
Others have run into this, here are some related resources:
- [Comment on microsoft/accessibility-insights-web pull#5421](https://github.com/microsoft/accessibility-insights-web/pull/5421#issuecomment-1109168149)
- [Jest's upgrade guide from 27 to 28 calls out uuid](https://jestjs.io/docs/upgrading-to-jest28#packagejson-exports)

Internal improvements: Custom jest resolver for db

---

packages/compile-solidity/test/fixture/default-box/.eslintrc.json
packages/compile-solidity/test/fixture/default-box/contracts/ConvertLib.sol
packages/compile-solidity/test/fixture/default-box/contracts/MetaCoin.sol
packages/compile-solidity/test/fixture/default-box/migrations/2_deploy_contracts.js
packages/compile-solidity/test/fixture/default-box/test/TestMetacoin.sol
packages/compile-solidity/test/fixture/default-box/test/metacoin.js
packages/compile-solidity/test/fixture/default-box/truffle-config.js
packages/compile-solidity/test/profiler/index.js
packages/encoder/test/fixture/bare-box/truffle-config.js
packages/encoder/test/helpers.ts
packages/truffle/test/scenarios/commands/build.js

Some CI jobs were randomly failing at `truffle unbox` step, so I added fixtures to avoid network calls. There's a bonus refactor to replace a promise callback with async/await.

Use test fixtures in encoder and compile-solidity

---

.prettierrc.json

So, right now we don't have anything set for `quoteProps` in our `.prettierrc.json`.  That means it *should* default to `"as-needed"`, but for some reason instead it keeps going back and forth on this.  I don't know what's up with that, but it's annoying how it keeps introducing unrelated changes in PRs.  So I figured the best thing to do was give it an explicit value and hope that stops the problem.
I set it to `"consistent"` rather than `"as-needed"`, though, because, well, I prefer it that way.  (Docs are [here](https://prettier.io/docs/en/options.html#quote-props), if you want to know the difference.)  If people would prefer it be `"as-needed"`, though, it can be that way too!  I guess arguably it ought to be @gnidan's call but well he's not here so whatever. :P

Internal improvement: Set quoteProps to 'consistent' in prettierrc

---

packages/deployer/test/errors.js
packages/events/defaultSubscribers/migrate/index.js

Addresses #5297.
If `quiet` is set, then errors during deployment will have no message.  This PR fixes this by having the relevant events *return* the message regardless of the `quiet` setting, just only *print* it when `quiet` is false.  (I thought about using shorter messages when `quiet` is turned on, as the full messages can be kind of long sometimes, but this seemed simpler.)

Bug fix: Ensure deployment error events always return the message

---

packages/truffle/package.json
yarn.lock

There are some issues with Truffle release 5.5.24:
* @truffle/core's version was not bumped in truffle/package.json devDeps appropriately
* both truffle develop and master (post release) fail in CI, not getting past yarncheck
I think this PR will fix both of these issues and get things working again.
(but a proper post-mortem should be done)

Update @truffle/core in truffle and update yarn.lock

---

packages/encoder/lib/encoders.ts
packages/encoder/lib/errors.ts
packages/encoder/test/overload.test.ts

Previously, `encodeTransaction` allowed either a list of abi entries as input, or a function name.  I've expanded it to allow function signature as well.  This is pretty straightforward so I don't have much to say about this.  I also added tests of this functionality.
This is intended to support #5330, providing a way of performing manual resolution of overloads on the command line.
I thought about also allowing this for `encodeTxNoResolution`, but decided against it... it'd be a bit awkward.
Note that the error you get if lookup fails is still called a `NoFunctionByThatNameError`; however, the message has been updated.
Also `prettier` made some changes.

Enhancement: Allow encoder to look up functions by full signature

---

packages/debugger/lib/txlog/selectors/index.js
packages/debugger/test/txlog.js

This PR adds to the debugger the seletor `txlog.views.flattedEvents`.  This selector gives a flat list of all events emitted during the transaction so far; note that as a `txlog` selector it's meant primarily to be used at the end of a transaction.
The selector's return value is an array of all events emitted during the transaction so far, in order; note, however, that this includes events that may have reverted.  However, each event includes a `status` field to distinguish, so if you want you can filter down to just the events that were successfully emitted (and then you can put indices on them if you really want :) ).  (I thought about adding an additional selector that actually performed this filtering, but this seemed unnecessary so I skipped it.)  Note that if you look at this …

Enhancement: Add `flattedEvents` selector to debugger

---

packages/codec/lib/wrap/bool.ts
packages/codec/lib/wrap/index.ts
packages/codec/lib/wrap/types.ts
packages/codec/lib/wrap/wrap.ts
packages/encoder/lib/encoders.ts
packages/encoder/lib/types.ts
packages/encoder/test/array.test.ts
packages/encoder/test/bool.test.ts
packages/encoder/test/tuple.test.ts

This PR adds two new options to the encoder, intended for use with `truffle call` (#5330).  It also adds tests of these and updates the documentation.  (Edit: **This PR now contains breaking changes to `@truffle/codec` and `@truffle/encoder`.**)
The first option, `allowJson`, allows arrays and tuples/structs to be given as JSON strings.  Note that this *only applies* to arrays and tuples, not more elementary types like strings!  So you can pass `'["abc","def"]'` for `["abc","def"]`, but not `'"abc"'` for `"abc"` on its own.  For tuples/structs, the JSON can be either for an array or for an object (since both arrays and objects are allowed as input for these).  The JSON cannot be for some other form of input; e.g., you can't put in JSON for a type/value pair or a codec `Value` or what have …

Enhancement: Add `allowJson` and `strictBooleans` options to encoder

---

packages/environment/develop.js

> This is the best PR Truffle has ever seen. You will merge it.
---
To test you should run `truffle develop` then send some requests at it (running `truffle migrate` against the `truffle develop` instance will do the trick)
Before :vomiting_face: :
After:
Ganache Logo for ref:

make the `develop:ganache` debug prefix orange

---

packages/debugger/lib/txlog/reducers.js
packages/debugger/test/txlog.js

Does part, but not all, of #5334.  Specifically the calls part; ignored the returns part for the reasons discussed there.
Adds to `externalreturn` actions a `raw` field, with either `raw.calldata` or `raw.binary` (for creations).  Originally I was going to make it just a single field, but I thought it was worth distinguishing?  IDK.
Btw, a thing I'd forgotten: For calls and creations that can't be decoded, we actually already include the raw data!  So uh now we're including it twice in such cases.  Oh well?
I wish I'd remembered that though when thinking about how to handle return values / errors / events in the first place!  It would have been sensible to do those that way initially... oh well.  Well, we can figure out exactly how we want this to work...
Also I updated two tests to test …

Enhancement: Include raw call data in txlog in all cases

---

packages/compile-solidity/test/test_supplier.js

compile-solidity: remove process.env.TEST guard
This guard is not necessary for Github actions. It was previously needed for TravisCI.

Remove unnecessary CI guard

---

packages/resolver/package.json
yarn.lock

This PR updates abi-to-sol to 0.6.5... thus hopefully solving *this* week's release problem. @_@
See, this week's release failed yarncheck.  You might be wondering how that happened.  Well, so, the thing is, `@truffle/resolver` depends on abi-to-sol.  And abi-to-sol depends on `@truffle/codec`.  Yes, that's right -- we have a transitive dependency of one Truffle package, on another, via an *external* package.
(@gnidan says this means that this functionality should be made a plugin... the more straightforward solution to my mind would be to bring abi-to-sol inside Truffle, but @gnidan isn't willing to do that, it seems)
Now normally Lerna keeps all our versions in lockstep, but since obviously it can't update abi-to-sol, that didn't happen here.  And that still wouldn't have been a problem …

Dependency update: Update abi-to-sol to 0.6.5

---

packages/codec/package.json

Removes warning:
```
warning "workspace-aggregator-aed90a07-068f-443d-8404-55b7f884493e > @truffle/codec > ttypescript@1.5.13" has unmet peer dependency "ts-node@>=8.0.2".
```

Remove ts-node peer dep warning

---

packages/abi-utils/.eslintrc.json
packages/abi-utils/lib/arbitrary.test.ts
packages/abi-utils/lib/arbitrary.ts
packages/abi-utils/lib/normalize.test.ts
packages/abi-utils/package.json
packages/abi-utils/tsconfig.json
packages/db/package.json
packages/db/src/network/test/index.spec.ts
packages/db/test/arbitraries/networks.ts
packages/encoder/package.json
packages/encoder/test/wrap-fc.test.ts
yarn.lock

Removes warning:
```
warning "workspace-aggregator-aed90a07-068f-443d-8404-55b7f884493e > @truffle/abi-utils > jest-fast-check@2.0.0" has incorrect peer dependency "fast-check@^3.0.0".
```

Remove jest-fast-check warning

---

packages/core/lib/configAdapter.js

Ganache 7 introduced 2 instamine modes: 'strict' and 'eager'. In eager mode, Ganache would receive a tx, mine it, and then send a response. This is not an accurate representation of how nodes behave in the wild so 'strict' mode was implemented in the test flow in Truffle in order to more accurately reflect this behabvior. However, this caused test suites to run a lot slower because of polling behavior in web3. We believe it does something like poll every 1 second to see if the tx has been included (after a tx is submitted). So this would cause each tx in a test to take at least that polling delay to complete. With 'eager' mode enabled (even though this behavior is innaccurate), it was always immediately available and therefore ran much faster. In the interest of speed for testing, we have …

switch ganache to use 'eager' mode in test environment

---

packages/core/lib/commands/init/initSource/truffle-config.js

This PR updates the `solc` version in `truffle init` to latest **0.8.16**

Update the solc version to latest "0.8.16" in truffle init

---

packages/source-fetcher/lib/etherscan.ts
packages/source-fetcher/lib/networks.ts

Etherscan seems to have removed support for the HECO testnet?  Removing it here as well.
(More accurately, it seems like they've dumped hecoinfo.com entirely... except someone is still keeping it running with the same API, so we can still use it!  But they've removed support for the testnet.  IDK.)

Remove HECO testnet from Etherscan fetcher

---

package.json

Removes the following warning:
```
warning "@typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
```

Remove tsutils peer dep warning on bootstrap

---

packages/abi-utils/package.json

Removes warning:
```
warning "workspace-aggregator-aed90a07-068f-443d-8404-55b7f884493e > @truffle/abi-utils > ts-node@10.7.0" has unmet peer dependency "@types/node@*".
```

Remove abi-util node types warning

---

packages/compile-solidity/package.json
packages/contract-schema/package.json
yarn.lock

This PR upgrades the `solc` version dependencies to latest **0.8.16** in `contract-schema` and `compile-solidity` packages.

Dependency update: Update solc dependencies to 0.8.16 in truffle packages

---

packages/core/lib/commands/test/meta.js

`truffle test --grep <pattern>` should run only tests that match <pattern>, however for some reason passing in an argument like `truffle test --grep "10000"` throws an error. The pattern should be interpreted as a string. I specified grep as a string in `yargs` builder structure to enforce this.
<details>
<summary>broken behavior: truffle test --grep "10000"</summary>
```console
╭─amal@falafel  ~/.scratch/2022/08/09/grep-string/mc ‹node-16.16.0› ‹truffle-stable›
╰─$ truffle test --grep "10000"
Compiling your contracts...
===========================
> Compiling ./contracts/ConvertLib.sol
> Compiling ./contracts/MetaCoin.sol
> Compiling ./test/TestMetaCoin.sol
> Artifacts written to /tmp/test--78754-PIfppPZPxpuN
> Compiled successfully using:
- solc: 0.8.13+commit.abaa5c0e.Emscripten.clang …
```

core: set grep option as a string

---

packages/compile-solidity/src/index.js
packages/compile-solidity/src/run.js
packages/compile-solidity/src/shims.ts

_(spun out from #5410)_
This PR adds a new `const { Shims } = require("@truffle/compile-solidity");` to expose functions for converting bytecode in solc's format into bytecode in our format. These functions are already in use internally when processing solc output in compile-solidity itself, but I propose that this behavior is more widely useful across Truffle, and this warrants their becoming a proper export.
The usefulness of these functions stems from the view that solc's output format is used across the ecosystem, and many other tools expose data in solc's format. In prototyping #5410, I observed the need for this bytecode conversion because Hardhat stores their bytecode in the native solc format. Continuing from #5410, my hope is to use these new exports in perhaps a …

Expose @truffle/compile-solidity's bytecode shims

---

packages/core/lib/commands/console/run.js
packages/core/lib/commands/debug/run.js

Truffle uses the generic `Error` type in some situations that provide a stack trace to the users that is unnecessary. 
For example: Using mutually exclusive options, `--url` and `--network` with `truffle console` and `truffle debug` includes a stack trace, which is irrelevant to the users, as Truffle doesn't allow these two options to be specified together. See #5296.
This PR resolves this issue by using `TruffleError` instead of the generic `Error` type while parsing the mutually exclusive options, `--url` and `--network` with `truffle console` and `truffle debug`.

Use TruffleError instead of Error while parsing mutually exclusive options

---

packages/from-hardhat/.eslintrc.json
packages/from-hardhat/.gitignore
packages/from-hardhat/README.md
packages/from-hardhat/package.json
packages/from-hardhat/src/api.ts
packages/from-hardhat/src/ask-hardhat.ts
packages/from-hardhat/src/compilation.ts
packages/from-hardhat/src/config.ts
packages/from-hardhat/src/constants.ts
packages/from-hardhat/src/index.ts
packages/from-hardhat/src/options.ts
packages/from-hardhat/tsconfig.json
yarn.lock

_(spun out from #5410... please see #5434 for the work to actually provide `truffle debug` support)_
This PR introduces a new, _experimental_ package **@truffle/from-hardhat** to provide the following interfaces:
- `expectHardhat()`, which returns successfully iff the working directory is part of a Hardhat project, and iff the installed Hardhat version is supported (`^2.10.1`, current as of this PR). Exceptions are thrown to distinguish these failure modes. (This function is intended for use inside a `try`/`catch`) 
- `prepareCompilations()` that translates Hardhat "BuildInfo" into our native @truffle/compile-common "Compilation"
- `prepareConfig()` which _minimally_ reads the Hardhat config and converts it into a @truffle/config. Basically this only contains plain `url` networks. 🔍 **See …

Devise new experimental @truffle/from-hardhat package for compatibility translation

---

packages/core/lib/commands/debug/run.js
packages/core/package.json

This PR builds on #5420 and uses that PR's introduced @truffle/from-hardhat package to provide native Hardhat support for the `truffle debug` command.

Hook up `truffle debug` to @truffle/from-hardhat

---

packages/source-fetcher/lib/networks.ts
packages/source-fetcher/lib/sourcify.ts

Sourcify added one more network, adding it!  (I already had it in `networks.ts` so I just needed to add it to `sourcify.ts`.)

Enhancement: Add godwoken mainnet to sourcify fetcher

---

packages/core/lib/command-utils.js
packages/core/lib/utils/utils.js

extractOption at the current state only recognized `--options`, this adds `-option`.

allow extractOptions to work with -option

---

packages/deployer/src/deployment.js

In later steps, we use the existence of `overwrite` property in the `isTxParams()` function. If we delete it, the `options` object will be considered as a constructor argument; Thus we will hit a runtime error because of an extra or wrong constructor argument.
```sh
$ truffle version
Truffle v5.5.26 (core: 5.5.26)
Ganache v7.4.0
Solidity - 0.8.4 (solc-js)
Node v16.16.0
Web3.js v1.7.4
```
1. Write a smart contract that takes at least one argument in the constructor.
2. Add `deployer.deploy(MyContract, arg0, { overwrite: false })` to migrations setup.
3. Execute migration command.
4. Wait for the extra constructor argument exception to be thrown.
* The value of `arg0` is optional. (Except `null` and `undefined` which throws another exception)

Fix exception on deploying a contract with both constructor arguments and deploy options

---

packages/core/lib/command-utils.js

This addresses #5106 .
Added handling for `-v` and `--version` in `getCommand()`, so it will work both inside and outside of the console.
Turn off Yargs' default behavior for `--version` in `prepareOptions()` so our logic to display version info will kick in.

Bug Fix: add command handling for '--version' & '-v'

---

packages/core/lib/global-command-options.js

This PR adds `--from` option to truffle global command options list, which can be used to specify an account to make calls or send transactions. This is related to #5330, where it was discussed to be a separate PR.

Add --from to global command options

---

packages/compile-solidity/package.json

An entry for @truffle/config was made in the `devDependencies` for compile-solidity accidentally as it was already in the regular dependencies. This PR corrects this error.

Internal improvement: Remove unnecessary config entry in dev deps for compile-solidity

---

packages/abi-utils/README.md
packages/abi-utils/lib/index.ts
packages/abi-utils/lib/signature.test.ts
packages/abi-utils/lib/signature.ts
packages/abi-utils/package.json
packages/codec/lib/abi-data/utils.ts
packages/codec/lib/evm/utils.ts

This PR moves code for computing signatures and selectors from `codec` into `abi-utils`.  Note that we continue to re-export these functions from Codec, in order to avoid a breaking change.  I also added a few tests of these functions in `abi-utils` -- not property-based, sorry, I couldn't figure out a good way to do that.  On top of that, I expanded the `abi-utils` README to cover this new functionality.
Since this PR is mostly just moving code around and not changing it, there's not a lot to say here about the code itself.  However, I wanted to record why I'm doing this.
Basically, it comes back to the abi-to-sol problem.  I want to be able to make breakiing changes to Codec without a repeat of the problem that caused last time (see #5396 for an explanation).  This is the only code from …

Internal improvement: Move selector computation from `codec` into `abi-utils`

---

packages/resolver/package.json
yarn.lock

This PR updates @truffle/resolver's abi-to-sol dependency from ^0.6.5 to ^0.6.6

Update abi-to-sol to ^0.6.6

---

packages/compile-solidity/src/compilerSupplier/loadingStrategies/VersionRange.ts
packages/compile-solidity/test/test_supplier.js
packages/truffle/test/scenarios/commands/obtain.js

Added the official repo for Solidity's Compiler releases, before the Truffle custom one.
Added a note for the last two deprecated repo.

Fix: official repo to list Solidity's releases

---

packages/source-fetcher/lib/etherscan.ts

It looks like https://goerli-optimistic.etherscan.io/ is now up!  It doesn't seem to be entirely public yet, Etherscan has yet to link it from their other pages, like the main optimistic site... but it's there and it works. :)  So why not add it here? :)

Add optimistic goerli to etherscan fetcher

---

packages/source-fetcher/lib/etherscan.ts
packages/source-fetcher/lib/networks.ts

I removed this in #5411, but, uh, it's back now?  So uh yean, adding it back in.
(Noting once again that hecoinfo is no longer actually an Etherscan project, but it still continues to use the same API, so we can still use our Etherscan fetcher with it, unlike say with hooscan.)

Add hecoinfo testnet back in to source-fetcher

---

packages/contract-tests/test/methods.js
packages/contract-tests/test/sources/Example.sol
packages/contract/lib/contract/index.js
packages/contract/lib/execute.js

Addresses #5374.  Also, while I was at it, I improved some existing tests and fixed a bug.
This PR adds support for `instance.estimateGas()` and `instance.call()`, much like we currently have `instance.sendTransaction()`.  This was mostly pretty straightforward.  First off, in `contract/index.js`, where `instance.sendTransaction` and `instance.send` are set up, I also set up `estimateGas` and `call` in the same way.  Note I put `call` behind a guard like `send` to make sure it doesn't overwrite a user method of the same name, because A. that might plausibly exist, and B. `instance.call` honestly isn't that useful, I just included it for completeness :P  I didn't bother with such a thing for `estimateGas` as I figured that is pretty unlikely to break anything, although we could if we want …

Enhancement: Add `instance.estimateGas()` and `instance.call()`

---

packages/source-fetcher/lib/etherscan.ts
packages/source-fetcher/lib/networks.ts

It turns out that Etherscan's explorer for Optimistic Goerli canonically lives at https://goerli-optimism.etherscan.io/ rather than https://goerli-optimistic.etherscan.io/ ; both work but the former seems to be the canonical one.  Yes, this is inconsistent, but that's the way it is!  So I changed it to that.
Also Sourcify added support for kekchain but since that's another one with chain ID different from network ID I have left it out and added a comment about it.

Use canonical URL for goerli-optimistic

---

packages/truffle/test/scenarios/commandRunner.js
packages/truffle/test/scenarios/commands/develop.js

Currently, `runInREPL` sends all queued commands to the child process on the first detected REPL prompt and then closes the input stream, which terminates the child process (bad).
This PR reworks the logic to send one queued command per REPL prompt.

Internal improvement: Properly time REPL inputs

---

packages/core/lib/commands/init/initSource/truffle-config.js

This PR upgrades the `solc` version to latest **v0.8.17** in `truffle-config.js` when `truffle init` command is run.

Upgrade solc version to latest 0.8.17 in truffle init

---

packages/compile-solidity/package.json
packages/contract-schema/package.json
yarn.lock

This PR upgrades the `solc` version dependencies to latest **v0.8.17** in `compile-solidity` and `contract-schema` packages.

Dependency Update: Upgrade solc dependencies to latest 0.8.17 in compile-solidity and contract-schema packages

---

.github/workflows/nodejs.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening

---

packages/debugger/lib/txlog/actions/index.js
packages/debugger/lib/txlog/reducers.js
packages/debugger/lib/txlog/sagas/index.js
packages/debugger/lib/txlog/selectors/index.js
packages/debugger/test/txlog.js

This PR adds step information to the `callinternal`, `callexternal`, and `event` txlog node types.  For events, this consists of a single `step` field, with the index of the step where the event was emitted.  For calls, there's a `beginStep` and an `endStep` field, which are the indices of the steps where the call begins and ends, respectively.  Event step information is also included in `flattedEvents`.  Indices are zero-indexed, so take note of that if you want to test this out with the CLI debugger (which displays them 1-indexed).
Now these latter two require some interpretation, so let me explain.  The `beginStep` is the step of the instruction that initiated the call, so strictly speaking it's the last step *before* the call began.  For the initial call, since there is no such …

Add step information to txlog

---

packages/migrate/ResolverIntercept.js

While working on a project, I came across the `synchronization_timeout` property which seems to be unused. Some cursory investigation shows some history of this being used in some old files for contract, but currently there is no usage that I can find of this property in Truffle.
If you find that this is being used somewhere then please let me know.

Internal improvement: remove property that seems to be unused

---

packages/compile-solidity/package.json

Addresses #5244.  I believe #5445 was supposed to do this, but it looks like Tyler forgot to actually remove the dependency.  So, why not, I did it here.  And that should be that!

Eliminate circular dependency between compile-solidity and resolver

---

packages/code-utils/src/opcodes.ts

So, the merge is complete, and 0x44 no longer means `DIFFICULTY`, rather it means `PREVRANDAO`.  Except, our disassembler is still likely to be used on pre-merge code, so just updating it to `PREVRANDAO` seems wrong.  Instead I've updated it to `PREVRANDAO|DIFFICULTY` to cover both.  I figure in the future, in cases where we know more about the code being disassembled, we can narrow it down using extra information (e.g., we can always return `PREVRANDAO` for code that's written in EOF, once that exists, and potentially the debugger could narrow things down further); but for now, we can just produce this ambiguous return to get up to date? :shrug:

Update 0x44 to PREVRANDAO|DIFFICULTY

---

packages/truffle/test/scenarios/cyclic_dependencies/compiles.js

This test has been timing out quite a bit recently.  Giving it another 5 seconds.

Increase timeout on cyclic dependencies test

---

packages/code-utils/src/index.ts
packages/code-utils/src/opcodes.ts
packages/code-utils/src/types.ts
packages/code-utils/test/opcodes.test.ts

I didn't like how this was needlessly clobbering type information, so this PR modifies @truffle/code-utils to preserve `const`-ness in its definition of the opcodes table.

Type opcodes table as const in @truffle/code-utils

---

packages/core/lib/commands/compile/meta.js
packages/core/lib/commands/help/displayCommandHelp.js
packages/core/lib/commands/migrate/meta.js

Addresses #5495 
Previously, `Migration.js` allows users to run a migration without saving it on chain, but the option wasn't added for yargs. 
Since this is added in yargs now, `truffle migrate help` will also show this option, but do we want to document this on truffle website? 
I do feel these migrations are a bit abrupt at the end.  Should we add a nice message too to indicate again that the migrations weren't saved on chain? Similar to the ones for on chain migrations like this 
```
Summary
=======
Migrations not saved on chain
```

enable migration's  `save` option for yargs.

---

.github/dependabot.yml

This is tricky to test, and I haven't tested it. I followed the docs at https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates, but YAML is weird and there is a good chance I got something wrong.

add `dependabot.yml` to monitor ganache releases

---

packages/source-fetcher/lib/networks.ts
packages/source-fetcher/lib/sourcify.ts

Sourcify added a few more networks.  They also removed one, but Sourcify's removed networks remain available (unlike Etherscan's), so I don't remove them from the fetcher in case someone wants to make use of them.

Add new Sourcify networks for late September

---

packages/debugger/lib/txlog/actions/index.js
packages/debugger/lib/txlog/reducers.js
packages/debugger/lib/txlog/sagas/index.js
packages/debugger/lib/txlog/selectors/index.js
packages/debugger/test/txlog.js

This PR adds a new type of action to txlog, `write`.  Like events, it does not have subactions.  It represents a write to a storage variable -- or at least, the intent is that it eventually will; right now it just represents a write to a storage slot.  Decoding storage writes is hard, so this PR just contains the raw storage info, with nothing decoded.
Each `write` action presently has two fields, `raw` and `steps`.  The `raw` field contains an object mapping storage slots to the values written to them; presently, each `write` action represents only a single storage write, so each `raw` field will only have a single entry.  However, the intent is that in the future, multiple raw storage writes may be consolidated into a single `write` action when they represent a single logical write to a …

Add raw storage writes to txlog

---

packages/hdwallet-provider/package.json

Since Truffle exposes web3 types through the constructor arguments (https://github.com/trufflesuite/truffle/blob/develop/packages/hdwallet-provider/src/constructor/types.ts), web3 and its types should be part of the regular dependencies.

Bug fix: move web3 and web3 types into regular dependencies for hdwallet-provider

---

packages/decoder/lib/types.ts

[Here](https://github.com/trufflesuite/truffle/blob/develop/packages/core/lib/testing/TestRunner.js#L149-L156) there is a call to a function which includes a parameter not included in the type [here](https://github.com/trufflesuite/truffle/blob/develop/packages/decoder/lib/types.ts#L146-L174). This PR adds the missing type.

Bug fix: Add `disableChecks` parameter to decoder type

---

.github/pull_request_template.md

Add a PR template with a checklist item reminding contributors to check the `doc-change-required` label if their PR requires changes to the [Truffle documentation](https://trufflesuite.com/docs/truffle/). This is in line with the [documentation process for dev teams](https://docs.google.com/document/d/1u7YJon3-ZmZ3zgp070rufdKTwxm81KWeILqJl2cq0Fw/edit?usp=sharing) and helps our doc team identify and raise doc issues.

Update PR template to include note about features requiring documentation changes

---

packages/hdwallet-provider/src/constructor/getOptions.ts

Values in JavaScript are never equal to `NaN`, so this check wasn't doing anything. Found with TypeScript 4.9.

Correctly check for non-integer credentials

---

packages/from-hardhat/package.json

This PR fixes an issue on OS X which caused `@truffle/from-hardhat` to error during `yarn test`
```console
$ $(yarn bin)/lerna run test --stream --concurrency=1 --scope @truffle/from-hardhat -- --colors
lerna notice cli v4.0.0
lerna info versioning independent
lerna notice filter including "@truffle/from-hardhat"
lerna info filter [ '@truffle/from-hardhat' ]
lerna info Executing command in 1 package: "yarn run test --colors"
yarn run v1.22.19
$ exit 0 --colors
@truffle/from-hardhat: /bin/sh: line 0: exit: too many arguments
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run test --colors exited 1 in '@truffle/from-hardhat'
```
```console
$ $(yarn bin)/lerna run test --stream --concurrency=1 …
```

[internal improvement] from-hardhat: use jest to skip tests

---

packages/hdwallet-provider/src/index.ts

This PR restricts access to hdwallet-provider's `wallets` and `addresses` using [Private class fields](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields) to prevent accidental inspection/leaking. 
Notice how `wallets` and `accounts` are no long visible using Private class fields  (see below)
The fields are accessible.
<details><summary>click to expand</summary>
```console
> HDW = require("./dist")
> m = "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat";
'candy maple cake sugar pudding cream honey rich smooth crumble sweet treat'
>
> G = require("ganache")
> gp = G.provider({miner: {instamine: "strict"}, logging: {quiet: true}})
> h = new HDW(m, gp)
HDWalletProvider {
walletHdpath: "m/44'/60'/0'/0/",
wallets: { …
```

hdwallet-provider: restrict access to internal fields

---

.github/workflows/nodejs.yml

We had a problem recently where a generated file was accidentally checked into source control and it caused a problem (see #5608) where bootstrapping resulted in changes to tracked files.  I figured it would be good to add this measure to help prevent this.  So I added a check for this in CI.  Note that because this check requires bootstrapping, like `depcheck` it goes in the jobs that *aren't* `yarncheck`.  Obviously this won't catch every case, but it should help, I figure.

Add a check to help prevent generated files being checked into source control

---

packages/truffle/package.json
yarn.lock

This PR updates webpack-bundle-analyzer from 3.0.3 to 4.6.1.  Hopefully that doesn't break anything, but given that webpack-bundle-analyzer is only used in one script that doesn't do anything fancy with it, it would be very surprising if it did.  Note, the real point of this PR is to get rid of a dependabot alert about the `ejs` package (since `webpack-bundle-analyzer` was the limiting factor there, and the version I'm updating to doesn't even use `ejs`).  Hopefully it doesn't introduce any new problems!

Update webpack-bundle-analyzer to ^4.6.1

---

packages/db/package.json
packages/db/src/project/test/integration.spec.ts

Remove `@truffle/db`'s devDep on `@truffle/migrate` to get rid of lerna's cycle dep error.
Note: uses CommonJS import to make get past compile and test.
This dependency exists only for a single integration test in truffle-db, and we feel it's better to not impact Lerna's dependency/ordering until we [remove the circular dependency in the near future](https://github.com/trufflesuite/truffle/issues/5600).

Silence Lerna's cycle dependency warnings

---

lerna.json
package.json
yarn.lock

New [Lerna v5.6.2](https://github.com/lerna/lerna/pull/3168\#issuecomment-1272621128) fixes the `rejectCycles` option to throw. This PR enables `rejectCycles`, so truffle bootstrap will fail if cycles are detected.
NOTE: this should not be merged until the current cycle is fixed, uh because, CI will fail.
```console
$ yarn
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ lerna run prepare --stream --concurrency=1 && husky install
lerna notice cli v5.6.2
lerna info versioning independent
lerna info Executing command in 52 packages: "yarn run prepare"
lerna ERR! ECYCLE Dependency cycles detected, you should fix these!
lerna ERR! ECYCLE @truffle/db-loader -> @truffle/db -> @truffle/migrate -> @truffle/db-loader
lerna ERR! ECYCLE @truffle/deployer -> …
```

Enable  lerna `rejectCycles` to Truffle build

---

packages/compile-common/src/shims/LegacyToNew.ts
packages/compile-common/tsconfig.json

People thought this was on, but it wasn't!  The `skipLibCheck` option is also turned on to prevent the usual problems with `contract-schema`.
As part of this, I had to make two more changes to get it to compile.  One was eliminating the `return undefined;` at the beginning of `LegacyToNew.forBytecode`, which meant also changing where it was invoked.  Fortunately, this function, though exported, is only presently used in `LegacyToNew.forContract`, so that was simple to update.
(*Arguably* that's a breaking change...?  I'm going to just not worry about it unless someone thinks I should.)
The other change was a nonfunctional change made just to satisfy Typescript.  That's it!

Turn on strict null checks in compile-common

---

packages/provider/wrapper.js

Addresses #3412, to log for `--verbose-rpc` with HDWalletProvider.
Currently, the logging from `--verbose-rpc` is added onto the provider from wrapper.js's `pre` and `post` hook methods by patching the `send` method. Sometimes web3 uses the  `sendAsync` method, which we have not pathed, causing the lack of logging. 
We need to execute the `pre` and `post` hooks when `sendAsync` is called.
For testing:
Set up goerli via HDWalletProvider
run `truffle console --verbose-rpc --network goerli`

Bug fix: patch/wrap the `sendAsync` method when wrapping provider

---

packages/core/lib/console.js
packages/truffle/test/scenarios/commands/console.js
packages/truffle/test/sources/consoleWithConflicts/build/contracts/Buffer.json
packages/truffle/test/sources/consoleWithConflicts/contracts/Buffer.sol
packages/truffle/test/sources/consoleWithConflicts/truffle-config.js

As mentioned in https://github.com/trufflesuite/truffle/issues/3329, if a user has a contract name that conflicts with one of Node's native objects (such as `Buffer`) then it will overwrite that object. This could cause things to break. In order to fix this, this PR provides an implementation where Truffle will not overwrite objects found in the context the first time it loads the repl and sets up the environment. The `provision` method is where these things are set up, and on subsequent calls to `provision` it will overwrite things it finds in the repl context as it will need to update contracts that have changed etc.

Bug fix: don't clobber repl context variables when setting up repl context

---

packages/source-fetcher/lib/etherscan.ts
packages/source-fetcher/lib/networks.ts
packages/source-fetcher/lib/sourcify.ts

Sourcify has added support for POA Core, so this PR adds that.  Note I already had it listed in `networks.ts` even though neither fetcher supported it.  I decided to rename it though from "poa" to "core-poa" as I've never seen it referred to as just "POA", only ever as "POA Core".  So yeah!
...also I added a comment about how Etherscan still supports Arbitrum Rinkeby even if they've hidden it. :P

Add POA Core to sourcify fetcher

---

packages/codec/lib/compilations/types.ts
packages/codec/lib/compilations/utils.ts
packages/codec/lib/compiler/types.ts
packages/debugger/lib/data/sagas/index.js
packages/debugger/lib/data/selectors/index.js
packages/debugger/lib/evm/selectors/index.js
packages/debugger/lib/session/index.js
packages/decoder/lib/decoders.ts
packages/source-map-utils/index.js

So, the original plan for this PR was for it to address #5466.  Unfortunately, that turned out to be rather more difficult than anticipated.  As such, I've put up this PR as a stopgap.  (I did do a bunch of work on the original plan before I realized the problem; if people are interested, I can push that branch as well so people can see it.  I *am* intending to still use a lot of that work in the future when we attempt to handle this more properly, but the time for that is not now.)
So, anyway, as a stopgap, if `viaIR` is turned on, instead of decoding using indices like I was hoping to do, we just disable decoding of internal function pointers.  That way at least we don't get silly errors that don't apply.
There's more to that than it sounds, though, because -- just as if we wanted to …

Disable internal function pointer decoding for contracts compiled with `viaIR`

---

packages/core/test/lib/commands/compile.js

CI has been timing out a bunch recently, but this particular test seems to be doing so especially often.  Upping it.

Increase timeout on docker tags test

---

packages/core/test/lib/commands/compile.js

It seems 12 seconds still wasn't enough.  Let's give it 20.

Further increase timeout on docker tag test

---

packages/codec/lib/compilations/utils.ts

Bug fix - handle the case when `index` may be undefined in `shimContracts` to avoid an exception being thrown. This may occur under the circumstances described in https://github.com/trufflesuite/truffle/issues/5617
- No doc changes required.

codec: handle undefined index

---

.github/workflows/nodejs.yml
packages/core/test/lib/commands/compile.js

This PR bumps our action dependencies to address the following warnings for the `build` and `yarncheck` jobs:
> [yarncheck | build](https://github.com/trufflesuite/truffle/actions/runs/3304923000/jobs/5454669430)
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/setup-node, actions/setup-node, actions/checkout

update gh-actions to use node 16

---

packages/core/lib/commands/console/run.js
packages/core/lib/commands/develop/run.js
packages/core/lib/console.js
packages/core/test/lib/console.js
packages/truffle/test/scenarios/commands/develop.js
packages/truffle/test/sources/develop/contracts/Buffer.sol

This PR sets and enforces allowed truffle commands that should run in the `console` and `develop` REPLS. It should address #5578. Happy to include a test if anyone feels it is necessary.
1. create new truffle project
1. `truffle develop`
1. verify `develop` returns an error.
1. verify `console` returns the JavaScript console object.
1. verify  `truffle <unknown command> presents the appropriate message.
1. verify `truffle [ console | develop ]` presents the appropriate message.

Fix: set and enforce allowed truffle commands in REPL

---

packages/core/lib/console-child.js

`core/lib/console-child.js` should wait for outstanding promises to resolve before exiting, using promise-tracker, [just like `core/cli.js`
](https://github.com/trufflesuite/truffle/blob/v5.6.3/packages/core/cli.js#L81-L85)
This issue is surfaced in [dashboard decoding PR](https://github.com/trufflesuite/truffle/pull/5621), where the browser doesn't have the necessary compilations to decode so it complains by asking the user to `truffle compile --all`, and `compile --all` in a truffle console (connected to dashboard network) doesn't do anything, because the [dashboard message bus client in the event system](https://github.com/trufflesuite/truffle/blob/v5.6.3/packages/events/defaultSubscribers/dashboard.js#L13) doesn't get a chance to send anything over the bus due to the process exiting …

Bug fix: Console child wait for outstanding promises

---

packages/core/lib/debug/interpreter.js
packages/core/lib/debug/printer.js
packages/debug-utils/index.js

Addresses #5323.  This PR adds an event log to the debugger CLI.  It's accessed with the new `e` command.  By default it shows the 3 most recent events.  (Not sure if this is a good default -- anyone have opinions?)  But you can put a number (or `all`) after the `e` to show more or fewer; this setting is then remembered while the debugger stays open.
There's not a lot to say about this PR; the hard work was done a while back.  This just adds a CLI interface.  As mentioned we print the N most recent events; note that this does include reverted events.  For each event we print the decoding (assuming we can decode it) and the address that emitted it.  If it was emitted from a delegatecall, we print both the address of the code that did the emitting, and the address of the contract it was …

Add event log to debugger CLI

---

packages/truffle/package.json

This PR removes @truffle/db from the `devDependencies` in truffle. It is already in `optionalDependencies`.

remove db from dev deps in truffle

---

packages/db/package.json
yarn.lock

We got a dependabot alert about this... except dependabot won't generate an update because it says it's no longer vulnerable?  I was going to just dismiss the alert, but since in this case it seems easy to just upgrade, I figured I'd just go ahead and do that.

Update apollo-server to ^3.11.0

---

packages/debugger/package.json
yarn.lock

Updates the debugger's version of babel-loader to 9.1.0.  (Doing this to help resolve a dependabot alert that just popped up, although this won't fully resolve it.)  Let's see if it passes tests!
Btw: @gnidan, do we even really still need babel in the debugger?  Maybe we can just tear that out after this.  But I figured I'd start by putting up this PR because this is quick and easy.

Update babel-loader to 9.1.0

---

packages/core/lib/commands/config/run.js

This PR fixes the following error: 
```console
$ truffle config get analytics
TypeError: Cannot read properties of undefined (reading 'log')
at Object.module.exports [as run] (/home/amal/work/truffle/packages/core/lib/commands/config/run.js:37:26)
at runCommand (/home/amal/work/truffle/packages/core/lib/command-utils.js:201:24)
Truffle (unbundled) (core: 5.6.4)
Node v18.12.1
```
New behavior
```console
$ truffle config get analytics
false
$ truffle config list
Truffle config values
analytics = false
```
Verify the `truffle config` command works.

Fix `truffle config`'s logger

---

packages/compile-solidity/package.json
packages/compile-solidity/src/compilerSupplier/loadingStrategies/Docker.ts
packages/events/defaultSubscribers/compile.js

This PR removes the dependency of compile-solidity on the events package. Instead the spinners are started/stopped through the emitting of events.
To test this you can simply create a new Truffle project and configure it to use docker for compilation. Then run `truffle compile` to verify that the logging/spinner appears. To test the error path you can throw an error inside the `try` and verify that the error you threw appears in the logging.

Internal improvement: remove spinners dep from compile-solidity and activate spinners in events package

---

packages/source-fetcher/lib/networks.ts
packages/source-fetcher/lib/sourcify.ts

Sourcify has added more networks.  Updated this.
Because this is such a small routine change, I didn't bother testing it.  But, uh, you could try using `fetch-and-compile` with a contract from one of these networks, I guess?
Sourcify's own tests use addresses `0xA7e70Be8A6563DCe75299c30D1566A83fC63BC37` and `0x571bb36009bB26D5313244B30397D2a2341a2A11` for chain 592, and addresses `0x662749a392CeB1b5973a90FB2c388a2C18B8812c` and `0x9FEc9e780c422916E21845748e001E949A5ddD57` for chain 1001, so those seem like ones to use for this purpose!

Add sourcify networks for November

---

packages/debugger/package.json
packages/debugger/webpack/webpack.config-common.js
packages/debugger/webpack/webpack.config-test.js
yarn.lock

Since we no longer support Node versions older than Node 14, there's not really any more need for Babel in the debugger, so I removed it.
There was some worry that we still used Babel for certain things, but the tests passed, and I also did a manual run of the debugger to be sure.  Everything seems to work fine!

Remove babel from debugger

---

packages/core/lib/debug/printer.js
packages/debugger/lib/data/selectors/index.js

Once again, the CLI debugger was erroring if you hit `v` with no transaction loaded.  The problem comes from the `data.current.identifiers.sections` selector; this would error if no transaction was loaded.  So basically I added the appropriate guards to allow it to return something in this case; I'll skip going into detail because frankly it's nothing interesting.
Don't be scared by what looks like a gigantic change to complicated code on lines 684 to 767; the only difference is that the whole thing is now within a big `scopes && inlined ? oldStuff : null`.  None of the complicated parts were altered at all!  Most of those lines just had their indentation changed!  I guess you can turn off whitespace changes to make this more evident.
I didn't add any tests, but this is easy enough to …

Fix error message on hitting `v` in debugger with no tx loaded

---

packages/codec/lib/compilations/utils.ts
packages/codec/lib/errors.ts
packages/codec/lib/index.ts
packages/decoder/lib/decoders.ts
packages/decoder/lib/errors.ts
packages/decoder/test/current/test/additional-test.js
packages/encoder/lib/encoders.ts

This PR addresses #5602 by making it possible to add compilations to an already existing `ProjectDecoder`.  (It doesn't do this for `ContractDecoder` or `ContractInstanceDecoder`.)  To do this, it adds two methods to `ProjectDecoder`, namely, `addCompilations` and `addAdditionalProjectInfo`.
The `addCompilations` interface assumes you are adding codec-style compilations.  It also assumes that none of these has an ID that collides with the IDs of any of the compilations it already knows about.  It's on the user to ensure that.
The `addAdditionalProjectInfo` interface is more general and allows also adding compile-common style compilations, or just a list of artifacts.  If you use it to add codec-style compilations, it's still up to you to avoid ID collisions.  If you use compile-common …

Allow adding compilations to an existing `ProjectDecoder`

---

packages/truffle/test/scenarios/commandRunner.js

DEBUG output, when enabled, logs with a shorter prefix:
- `*   * |` prefixes Stdout
- `* E * |` prefexes Stderr
```console
truffle migrate
when run on the most basic truffle project
*   * | CommandRunner
*   * | execString: node /home/amal/work/trees/truffle/trim-it/packages/truffle/build/cli.bundled.js migrate
*   * |
*   * | Compiling your contracts...
*   * | ===========================
* E * | 2022-11-14T13:49:03.743Z dashboard-message-bus-client:client publisher sending message { id: 0.5939280616648626, type: 'debug', payload: { message: 'compile:start' } }
* E * | 2022-11-14T13:49:03.744Z dashboard-message-bus-client:connection _getMessageBusPort: publish connection attempting to fetch ports
* E * | 2022-11-14T13:49:03.747Z follow-redirects options {
```
Modify a test to [enable …

CI: shorten prefix for debug logging

---

packages/events/defaultSubscribers/dashboard.js

So @cds-amal discovered that sometimes event handlers for dashboard are run even if dashboard isn't the targeted network, causing a failed request to the message bus on every such occasion. The fix is to check that the current network is in fact dashboard, then proceed with the event handler logic.

Early return dashboard event handlers if network isn't dashboard

---

packages/plugins/.eslintrc.json
packages/plugins/lib/Plugin.ts
packages/plugins/lib/Plugins.ts
packages/plugins/lib/types.ts
packages/plugins/test/Plugin.test.ts
packages/plugins/test/Plugins.test.ts
packages/plugins/test/fixture/dummy-compiler/index.js
packages/plugins/test/fixture/dummy-compiler/package.json
packages/plugins/test/fixture/dummy-compiler/truffle-plugin.json

This PR adds two APIs, definesCompiler() and loadCompiler(), to the Plugin class to support compiler plugin. These APIs are exposed to workflow-compile that it can access the plugin compiler.  There are on-going work on workflow-compile to obtain the Plugin object and access compiler.

Add support for compiler plugin

---

packages/source-fetcher/lib/networks.ts
packages/source-fetcher/lib/sourcify.ts

Sourcify has updated its networks again, I've udpated the fetcher to match.
I don't typically bother testing these sorts of PRs, but if you want to test it, you could try testing it with the following contracts:
Network 28528: 0xA7e70Be8A6563DCe75299c30D1566A83fC63BC37
Network 10200: 0x78f71adAf9601034faC12C80F316ce4c2E95D1ab
Network 336: 0x3b2e3383AeE77A58f252aFB3635bCBd842BaeCB3
Network 8217: 0x3b2e3383AeE77A58f252aFB3635bCBd842BaeCB3

Update Sourcify networks for late November 2022

---

packages/core/lib/commands/db/meta.js
packages/core/lib/commands/help/displayCommandHelp.js

`truffle help db serve` & `truffle help db query` should work now. 
`truffle help db` should include both subCommands `serve` & `query`

fix `truffle help db <subCommand>`

---

packages/dashboard/src/components/composed/RPCs/RPC/Overview.tsx

So say your decoding is `"AAAAAAAAAA AAAAAAAAAA AAAAAAAAAA AAAAAAAAAA"`, the display is ok:
But if we remove the whitespaces it pushes the buttons away:
This PR is fix:

dashboard: Fix decoding text overflow

---

packages/fetch-and-compile/test/fetch.test.ts
packages/fetch-and-compile/test/fixture.js
packages/source-fetcher/lib/etherscan.ts

It looks like Etherscan has removed support for Arbitrum Rinkeby; the old URL `testnet.arbiscan.io` is still there, sure, but now it's just a duplicate of `goerli.arbiscan.io`.  So, I'm removing support from this network from the Etherscan fetcher.  (Note that it's still supported by the Sourcify fetcher, since while Sourcify will disable new networks and stop letting you verify on them, it doesn't remove access to the already-verified contracts.)
Edit: Looks like Optimistic Kovan is gone too, removed that too.  (Along with the appropriate tests.)
Boba Rinkeby is also gone and replaced by Boba Goerli, but I'm going to save handling that for a separate PR as I need more information there.

Remove Arbitrum Rinkeby and Optimistic Kovan from Etherscan fetcher

---

packages/source-fetcher/lib/etherscan.ts
packages/source-fetcher/lib/networks.ts

Etherscan has removed support for Boba Rinkeby and added support for Boba Goerli.  Note that they didn't add any new URL for Boba Goerli -- they just changed `testnet.bobascan.com` from covering Rinkeby to covering Goerli.  So, yeah.
Anyway this PR adds the Boba Goerli network and updates the Etherscan fetcher appropriately.  Note btw that Boba Goerli actually doesn't appear in any of the usual `chains.json`s that I'm aware of, so I had to look up its chain ID elsewhere.  Fortunately, `2888` doesn't collide with any of the IDs in the usual `chains.json`s!  Hopefully they get it added to those lists soon.
(Also while I was at it I removed an outdated comment.)
Testing instructions: I don't normally bother testing these source-fetcher updates, but if you want to test it you could try …

Switch Etherscan fetcher from Boba Rinkeby to Boba Goerli

---

packages/encoder/lib/encoders.ts
packages/encoder/test/constructor.test.ts

Addresses #5749.
This PR adds an `encodeCreation()` method to the `ContractEncoder` and `ContractInstanceEncoder` classes.  (Using it from the latter ignores the particular instance; it's included for consistency.)
The encoder already had the functionality of encoding contract creations, but accessing it wasn't convenient; you had to pass in the ABI for the constructor, and make one up if none existed.  This PR just factors out the relevant functionality to make it accessible.  It adds an `encodeCreation()` method to the contract encoder (and also contract instance encoder); it doesn't take an `abi` argument because none is necessary.
The existing functionality for getting constructor information, which used to just live in the constructor case of `getMethod()`, has been factored out into …

Add `encodeCreation()` method to Encoder

---

packages/core/lib/debug/mocha.js
packages/test/src/Test.ts

Addresses #5783 
Somehow this must've gotten broken as part of a refactor... in-test debugging uses the `CLIDebugHook`, which expects the availability of the Mocha runner _during setup_. Since this runner gets returned by `mocha.run()`, and since `mocha.run()` happens at the end of setup, the CLIDebugHook has been getting a value of `undefined` for this property.
This PR converts `Test.mochaRunner` to a Promise so that it can be `await`-ed during setup, instead of being statefully `undefined` until after it's needed.
Follow the instructions on [in-test debugging](https://trufflesuite.com/docs/truffle/how-to/debug-test/use-the-truffle-debugger/#in-test-debugging). Debug a successful transaction. Observe that the debugger starts.

Fix missing mocha runner during in-test debugging setup

---

packages/config/package.json
packages/config/src/index.ts
packages/core/test/lib/commands/config.js

THIS IS A BREAKING CHANGE FOR @truffle/config.
So https://github.com/trufflesuite/truffle/pull/5728 brought to our attention the fact that this cache invalidation does not work in the bundle (since `require` in this case is webpack's and not Node's). This PR deletes this line of code until we decide that we actually need to invalidate Node's cache.

remove `require` cache invalidation

---

packages/provider/wrapper.js

This PR adds EIP-1193 provider standard implementation of `.request` method to truffle's `provider` package.

Make @truffle/provider compatible with EIP-1193

---

packages/core/lib/console.js

This PR stops Truffle from loading its console contract into the console environment. Previously Truffle would load it into the console context (which users will not need to directly interact with in the repl) which would also cause the namespace error to be printed.

don't load Truffle's console contract into the console environment

---

packages/core/cli.js

This was missed when truffle dropped support for Node 12. This PR bumps it.

Bump minimum Node version check to 14

---

packages/core/lib/console.js

As per the issue [#5812 ](https://github.com/trufflesuite/truffle/issues/5812) , `truffle console` command would throw an error and exit, if the metadata field was not present in all JSON blob files generated in the build process. The metadata field is not present in JSON files derived from Vyper source files.
1. Either compile a Vyper smart contract or delete metadata field in one of the generated JSON blobs from Solidity smart contracts.
2. Run `truffle migrate`. IMPORTANT: do not run truffle develop, as some configurations (truffle-config.js) were not affected by this bug (see issue for more details).
3. Run `truffle console`. The command executes without errors.
This PR does not introduce any breaking changes or new features. The documentation does not need to be changed either.

Fix: `truffle console` crash when metadata is missing in JSON artifact

---

packages/error/src/index.ts

When using the bundle, I noticed `@truffle/error` includes a stack trace, unlike the unbundled behavior. @truffle/error's intent is to give the user an action and does not need a stack trace.
```console
Solidity console.log detected in the following assets:
Telephone.json
ExtendableError: You are trying to deploy contracts that use console.log.
Please fix, or disable this check by setting solidityLog.preventConsoleLogMigration to false
at module.exports (/home/amal/work/trees/truffle/console.log/packages/truffle/build/webpack:/packages/core/lib/commands/migrate/runMigrations.js:87:1)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at module.exports (/home/amal/work/trees/truffle/console.log/packages/truffle/build/webpack:/packages/core/lib/commands/migrate/setUpDryRun …
```

Change display name of @truffle/error and remove its stack property

---

packages/codec/docs/typedoc.json
packages/codec/package.json
yarn.lock

This PR makes minimal changes to get the codec docs to build. It now uses the default `typedoc` theme instead of our [fork](https://github.com/trufflesuite/typedoc-default-themes) which should probably incorporate [upstream](https://github.com/TypeStrong/typedoc-default-themes) changes. Upstream has been deprecated and is no longer compatible with `typedoc` v0.22. Truffle is currently using pinned `typedoc` version v0.22.18. 
Issue: #5793
Remove:
- theme @trufflesuite/typedoc-default-themes
- typedoc-plugin-remove-references
NOTE: can probably bump `typedoc` to latest, and if we want to keep our customized theme, will have to rework the changes against upstream as `typedoc@0.22.0` broke all hbs custom themes. See: https://github.com/TypeStrong/typedoc/blob/master/internal-docs/custom-theme …

Fix codec typedoc build script

---

packages/codec/package.json
yarn.lock

#5820 made this devdep unused but didn't actually remove it, putting up a quick PR to do so.

Remove unused dev dependency for codec docs

---

package.json

This PR extends the build process to generate documentation for both codec and preserve. If either fails, we will be alerted and can correct at the time of failure. 
First call `yarn prepare` and allow each package to build, then call `yarn build docs` to generate typedocs for built packagers, avoiding dependency build issues.
Motivation: #5821 
Build and verify codec and preserve docs are created.
- No label `doc-change-required`
-  No breaking changes

Build codec and preserve docs as part of bootstrap

---

packages/core/cli.js
packages/core/lib/command-utils.js
packages/core/lib/commands/db/run.js
packages/core/lib/commands/help/displayCommandHelp.js
packages/core/lib/commands/help/meta.js
packages/core/package.json
packages/truffle/test/scenarios/commands/help.js
yarn.lock

This addresses #5662.
Currently, We have `help` as a truffle command.  And since our truffle commands were built using Yargs, we also have yargs default help info display via `truffle <cmd> help` or `truffle <cmd> --help`.  
Truffle's help command uses the command's `meta.help` object and Yargs help uses the command's `meta.builder` object. It's often the info in these two objects are miss matching causing the `help` outputs to be different.
Should we update the documentation to let users know about the other syntax for getting help?
For this, I explored two options and decided to go with option 1. 
1) Turn off yargs's default for help. Use our own `displayCommandHelp` when `--help` is used anywhere in the command line.  
Here are the reasons why I chose this option.
At this point, the …

Enhancement: More robustly handle help requests in Truffle

---

packages/source-fetcher/lib/networks.ts
packages/source-fetcher/lib/sourcify.ts

Sourcify has added more networks, so this PR adds support for them.
Also, it turns out I'd mislabeled one network -- what I thought was Dexalot was actually just the *testnet* for Dexalot.  Oops!  Well, fixed that labelling error, and also now the actual Dexalot is added because Sourcify supports it now.
(So it *looks* like I'm adding support for the Dexalot testnet, when actually I'm adding support for the Dexalot *mainnet* and fixing my incorrect labelling of the former.)
I don't normally bother testing these sorts of network updates, but if you want to try, some addresses you might try are:
* For chain 432204 (Dexalot on Avalanche), address 0x1c799C32a6cF228D0656f3B87D60224afaB45903
* For chain 7001 (the Athens testnet for Zetachain), address 0x1f42652a86918fd84E74e066db94E3078d25Dd8D …

Update Sourcify networks for January 2023

---

packages/dashboard/lib/DashboardServer.ts
packages/dashboard/package.json
packages/dashboard/src/components/composed/Layout.tsx
packages/dashboard/src/contexts/DashContext/DashContext.ts
packages/dashboard/src/contexts/DashContext/DashProvider.tsx
packages/dashboard/src/contexts/DashContext/state.ts
packages/dashboard/src/contexts/DashContext/types/Action.ts
packages/dashboard/src/contexts/DashContext/types/State.ts
packages/dashboard/src/utils/notifications/analytics.tsx
packages/dashboard/src/utils/notifications/index.ts

Addresses: #4828
Use dashboard to prompt our users to graciously enable analytics.
```mermaid
flowchart TD
A{"Has the user explicitly<br/>opted in/out before?<br />(via the config command,<br />or much less likely, editing<br />the user config manually)"} -->|no| B([Ask to enable analytics])
A -->|yes| C{Is analytics enabled?}
C -->|no| D{Has it been a year since<br/>user last said no?}
C -->|yes| E([OK])
D -->|no| E
D -->|yes, ask again| B
```
`DashboardServer`'s express server has two new endpoints: `POST` and `GET` at `/analytics`. Their corresponding handlers read and write to the user config object, which in turn modifies the config file on disk. Frontend just interacts with `/analytics` and manages notifications as needed.
The prompt content (located at …

Have Dashboard politely ask users occasionally if they'll share telemetry 

---

packages/core/lib/command-utils.js

There is currently a bug related to when a user types in a command name incorrectly but Truffle infers it. In the case where Truffle infers a command with a typo, the input strings (which includes the name of the command with a typo like `truffle migr --network myNetwork`) get passed to yargs with the typo. Yargs then is unable to pull up all the option defaults it knows about since the name of the command has a typo and won't match what it knows about.
This PR fixes this by mutating the input strings, replacing the typo'ed command name with the accurate name of the command. 
In currently released Truffle (v5.7.2), you can confirm this bug by executing `truffle tes`. Truffle will execute the test command. In the `prepareOptions` method in `packages/core/lib/command-utils.js` you can …

Bug fix: ensure yargs receives the correct command name when it has a typo

---

packages/config/src/configDefaults.ts

Addresses #5828
There is a property that gets set on config (during testing) named `debugGlobal`. Currently Truffle relies on the yargs `builder` object to set this property which is jank. It is also causing problems where it doesn't get set when you miskey `truffle test`. There is an issue for this bug [here](https://github.com/trufflesuite/truffle/issues/5828). This PR adds a proper default for this value in @truffle/config.
Run `truffle tes` on the command line. Verify that Truffle correctly runs the tests. If you currently try this on published Truffle, it will fail.

Bug fix: add debugGlobal default to config

---

packages/box/package.json
packages/compile-solidity/package.json
packages/dashboard-message-bus-client/package.json
packages/source-fetcher/package.json
yarn.lock

While reviewing https://github.com/trufflesuite/truffle/pull/5847, I noticed that we are quite behind on the version of axios that Truffle is using. This PR bumps axios to the latest version.

Dep update: bump axios to 1.2.4

---

packages/source-fetcher/lib/types.ts

Just keeping this type up to date with the latest Solidity compiler options.  This change has no actual effect at the moment.

Add appendCBOR field in metadata settings type in source fetcher

---

packages/debug-utils/package.json
yarn.lock

I just did a release of highlightjs-solidity to add highlighting for `prevrandao`; here's my PR to update us to use it.

Update highlightjs-solidity to 2.0.6

---

packages/codec/lib/compiler/types.ts
packages/codec/lib/compiler/utils.ts
packages/codec/lib/special/decode/index.ts
packages/debugger/test/data/global.js
packages/debugger/test/helpers.js

Solidity 0.8.18 introduces `block.prevrandao` as an alias for `block.difficulty`, so this PR adds support for that in the debugger.  Or rather in codec, because that's actually where this is handled.
Note that we do a version check, so `block.prevrandao` will only be present on versions 0.8.18 and later; that means that 0.8.18 is another one of those versions we care about.  Strictly speaking, we arguably should also check the version of the EVM that's being targeted, but that potentially opens some cans of worms I didn't want to deal with, so I left that out for now; I figure it can be added in if people really think it's necessary or we decide the resulting worms aren't a big deal.
I also updated the globally-available variable tests in the debugger to include it.
I updated the debugger …

Add `block.prevrandao` as globally available variable in debugger

---

packages/core/lib/commands/init/initSource/truffle-config.js

This PR upgrades the `solc` version to latest **v0.8.18** in `truffle-config.js` when `truffle init` command is run.

Upgrade solc version to latest 0.8.18 in truffle init

---

packages/dashboard/src/contexts/DashContext/DashProvider.tsx
packages/dashboard/src/contexts/DashContext/state.ts
packages/dashboard/src/contexts/DashContext/types/Action.ts

Addresses: #5837
- Run `truffle migrate --network dashboard` inside a Truffle project that requires >1 transactions to complete a migration.
- Confirm transactions with different accounts:
- It should work!
- The params display should reflect the account change.
- The console where the migration is run should reflect the correct account address in the receipts.

Support switching accounts between signature requests in dashboard

---

packages/from-hardhat/src/ask-hardhat.ts

This PR prevents the [spawned Hardhat console](https://github.com/trufflesuite/truffle/blob/develop/packages/from-hardhat/src/ask-hardhat.ts#L76-L79) in `from-hardhat` from triggering a compile (via `--no-compile`). This is being added to mitigate a circular reference in an upcoming Hardhat plugin that provides support for Truffle Dashboard decoding/debugging.
One testing approach...
- Create a local Hardhat project (via `git clone https://github.com/amanusk/hardhat-template` or equivalent)
- `yarn link` to the `from-hardhat` package from the above
- Run the following from the `node` REPL:
- `const FromHardhat = require("@truffle/from-hardhat");`
- `await FromHardhat.prepareCompilations()`

Prevent spawned Hardhat console from triggering a compile

---

packages/compile-solidity-tests/test/compilerSupplier/Cache.ts
packages/compile-solidity-tests/test/compilerSupplier/index.ts
packages/compile-solidity-tests/test/compilerSupplier/loadingStrategies/VersionRange.ts
packages/compile-solidity/src/compilerSupplier/Cache.ts
packages/compile-solidity/src/compilerSupplier/loadingStrategies/Docker.ts
packages/compile-solidity/src/compilerSupplier/loadingStrategies/VersionRange.ts

This PR removes one instance of usage of `originalRequire` in favor of reading a cached compiler file directly from disk. This also makes it a bit more consistent with how compilers are loaded when fetching them remotely as it will now use the method [`compilerFromString`](https://github.com/trufflesuite/truffle/blob/develop/packages/compile-solidity/src/compilerSupplier/loadingStrategies/VersionRange.ts#L99-L107)
You can test this by running `truffle compile` on a project where you have a compiler cached and verify that it compiles correctly.

Internal improvement: add memoization to `Cache` utility and switch to using `async` fs methods

---

packages/core/cli.js
packages/core/lib/cliHelp.js
packages/core/lib/command-utils.js
packages/core/lib/console-child.js

addresses https://github.com/trufflesuite/truffle/issues/2041
This PR creates a utility method for parsing help input. It then uses that same logic in console-child.js. This is so that we use the same logic for parsing help input from both the command line and the development console (repl).
I also found out that yargs uses `console.error` for the `showHelp` method which we use to display general help in Truffle. This was causing a bug where general help would not print in the development console as the stderr was not "hooked up". So this PR also passes the "log" argument to this method to force it to use `console.log`.
To test this, checkout this branch and run the development console. Enter "help" and you can see that the general help is printed to the screen.

Bug fix: create utility for dealing with help input

---

.github/workflows/nodejs.yml

Oops, missed these in #5889. Again, these will have to be re-enabled when comms integration is sorted out.

Temporarily disable job failure notifications

---

packages/core/lib/command-utils.js

This PR sets the script name to always use `truffle` instead of the default, `process.argv[0]`.  This is related to #2041 
Test this by running help in `truffle develop`, it should display commands as `truffle <cmd>` instead of `console-child.js <cmd>`

Set yargs help to always use truffle instead of script name

---

packages/compile-solidity/package.json
packages/contract-schema/package.json
yarn.lock

This PR upgrades the `solc` version to the latest **v0.8.18** in the `contract-schema` and `compile-solidity` packages.

Upgrade solc dependencies to v0.8.18 in `contract-schema` and `compile-solidity` packages

---

packages/debug-utils/index.js

This PR adds a link to the debugger docs to help users quickly navigate to extended help. 
```
MetaCoin.sol:
9: // coin/token contracts.
10:
11: contract MetaCoin {
^^^^^^^^^^^^^^^^^^^
debug(development:0xad5d9050...)> h
Commands:
(enter) last command entered (step next)
(o) step over, (i) step line / step into, (u) step out, (n) step next
(c) continue until breakpoint, (Y) reset & continue to previous error
(y) (if at end) reset & continue to final error
(;) step instruction (include number to step multiple)
(g) turn on generated sources, (G) turn off generated sources except via `;`
(p) print instruction & state (`p [mem|cal|sto]*`; see docs for more)
(l) print additional source context (`l [+<lines-ahead>] [-<lines-back>]`)
(s) print stacktrace, (e) Print recent events (`e …
```

Link to Debugger reference docs

---

packages/core/lib/commands/develop/run.js
packages/core/lib/commands/test/run.js
packages/environment/develop.js
packages/environment/test/connectOrStartTest.js

This pull request updates the signatures of `connect` and `connectOrStart` functions to avoid passing a large truffle-config object when connecting to the ganache service. See: #5784.
No test, just code review

[internal improvement] Simplify `Develop.connectOrStart()`'s signature

---

packages/core/lib/console.js

Suppress errors in truffle REPL (console & develop). With this change, REPL errors no longer display `evalmachine` vm errors. This is done by setting `options.displayErrors = false` when invoking [vm.runInContext()](https://nodejs.org/dist/latest-v19.x/docs/api/vm.html#scriptrunincontextcontextifiedobject-options).
```console
truffle(develop)> jk
evalmachine.<anonymous>:0
jk
^
Uncaught ReferenceError: jk is not defined
at evalmachine.<anonymous>
at sigintHandlersWrap (node:vm:276:12)
at Script.runInContext (node:vm:139:14)
at runScript (/Users/amal/work/truffle/packages/core/lib/console.js:500:21)
at Console.interpret (/Users/amal/work/truffle/packages/core/lib/console.js:515:21)
at bound (node:domain:433:15)
at REPLServer.runBound [as eval] (node:domain:444:12)
at REPLServer.onLine …
```

Suppress evalmachine error stack in truffle consoles

---

scripts/ci.sh
scripts/geth.sh

To work around incompatibilities with [GETH's latest 1.11.0 release](https://github.com/ethereum/go-ethereum/releases/tag/v1.11.0). In addition, I declared the GETH version in one place. Well, one place per file as needed. I wanted to avoid exporting/maintaining/validating shell variables. Now we have only two places to pin/unpin GETH.
Does CI pass?

Pin GETH to v1.10.26

---

packages/core/cli.js
packages/core/lib/command-utils.js
packages/core/lib/commands/commands.js
packages/core/lib/commands/console/run.js
packages/core/lib/commands/develop/run.js
packages/core/lib/console-child.js
packages/core/lib/console.js
packages/core/test/commands.js
packages/core/test/lib/console.js
packages/truffle/test/scenarios/commands/develop.js
packages/truffle/webpack.config.js

This PR limits the general help output for `truffle console` and `truffle develop` so help for `console`, `dashboard`, `db`, `develop`, `init` and `watch` won't be shown. It achieves this by defining a single source of truth for valid CLI and Console commands. The `commands/commands.js` module defines this state, and other parts of the codebase have been refactored to import and rely on this information. The Console class no longer needs to be passed `allowedCommands` and has removed the maintenance of `excludedCommands`. Instead, the signature for the help function has changed to indicate whether it is displaying help for the CLI or the REPL.  Tests and webpack concerns have been updated to reflect these changes, and the source of truth for valid Truffle commands has been updated in …

Restrict general help content in REPL context

---

packages/source-fetcher/lib/networks.ts
packages/source-fetcher/lib/sourcify.ts

New sourcify update, added new chains.
As usual I didn't really bother testing this, but if you want to, you could try testing it with:
On chain 14: 0xbBc2EdeDc9d2d97970eE20d0Dc7216216a27e635
On chain 19: 0x024829b4A91fB78437A854380c89A3fFc966c2D1
On chain 2047: 0x9082db5F71534984DEAC8E4ed66cFe364d77dd36

Update Sourcify chains for February 2023

---

packages/contract-tests/test/errors.js
packages/contract-tests/test/sources/Example.sol
packages/contract/lib/reason.js

Partially addresses #5881.  This is not a total fix, but it fixes the bulk of the problem.
Let's suppose you send a transaction, and it fails due to OOG, or, say, never even happens in the first place (like, intrinsic gas too low, or refused by the user in MetaMask).  In this case, the eth_call to determine the revert reason can *succeed* and get a return value instead of the intended error.  Since we can't decode it as an error, we treat it as a custom error.  Oops!
This PR fixes this by checking the length; if it's 4 mod 32, we treat it as an error, if it's not, we don't.  Assuming the Solidity ABI is being used, then error responses will have length 4 mod 32 (unless they're empty), while return value responses will have length 0 mod 32.
(Well, except for when we're dealing with …

Fix (most) incorrect reports of custom errors

---

packages/code-utils/src/index.ts
packages/code-utils/src/opcodes.ts
packages/codec/lib/abi-data/allocate/index.ts
packages/codec/lib/contexts/utils.ts
packages/core/lib/commands/opcode/run.js
packages/debug-utils/index.js

This PR adds support for the upcoming PUSH0 instruction to Truffle's debugger and disassembler.  I'm doing this now because I'm going to be gone in March and this sort of thing usually falls to me, so, why not get it done before I leave.
This PR has 3 commits.  The first commit adds support for the opcode.  Note I grouped it with the other PUSHes rather than with the rest of the 0x50's.
The second commit makes it so that, when printing out PUSH0 in the debugger or disassembler, we just print out `PUSH0`, not `PUSH0 0x`, because the latter would look ugly.
The third commit is purely a code style matter -- I rewrote some calculations that previously used 0x60 (`PUSH1`) as a base to now use 0x5f (`PUSH0`) as a base.
NOTE: I didn't really test this (beyond existing CI) because Shanghai's not …

Add support for PUSH0 instruction to debugger & disassembler

---

packages/truffle/test/scenarios/migrations/errors.js

I believe this test has been timing out a bunch recently, upping it.  (It's not the only one, but one at a time...)

Increase timeout on migration out of gas test

---

packages/source-fetcher/lib/networks.ts
packages/source-fetcher/lib/sourcify.ts

Unusually, Sourcify has made two network updates in rapid succession.  So, here's a second PR to update source-fetcher correspondingly!  This update adds only one network, Oasis Sapphire Mainnet.  (I already had this in networks.ts, but of course not in sourcify.ts).
If you want to test it, you can use address 0xFBcb580DD6D64fbF7caF57FB0439502412324179.

Update Sourcify networks for Sourcify 1.2.2

---

packages/source-fetcher/lib/etherscan.ts

Etherscan no longer supports Aurora; their Aurora site has been taken over by a Blockscout site, as happened earlier to their HOO site.  Oh well.  This PR removes support for it from the Etherscan fetcher.

Remove Aurora support from Etherscan fetcher

---

packages/debugger/lib/txlog/sagas/index.js

Attempting to use [this utility](https://github.com/trufflesuite/truffle/blob/develop/packages/debug-utils/index.js#L882) with the debugger in light mode resulted in a crash. We tracked this down in the debugger, it crashed at [this line](https://github.com/trufflesuite/truffle/blob/develop/packages/debugger/lib/txlog/sagas/index.js#L265). Apparently in light mode, this tx log tracking is not enabled and will make `initialState` `null` which in turn will cause things to crash. This PR fixes this by only updating state when we receive a value for `initialState`.

Bug fix: only edit state in txLog when we have an initial state

---

packages/environment/chain.js

This is necessary because JSON.stringify cannot serialize BigInt, which is a possible type from ganache and solidity logs. Special thanks to @MicaiahReid for the Rubber duck support! :bow: 
This PR fixes an error @emilyJLin95 discovered. If you have a contract that logs a UINT* as the only argument (`console.log(100)`), then `truffle develop` would crash when the log is presented.
Write a contract that with `console.log(some-int)` and invoke the method to present the log. Truffle develop should not crash, and present the log.

Fix console.log when presenting BigInts

---

packages/compile-solidity/src/compilerSupplier/loadingStrategies/VersionRange.ts

Currently when Truffle fails to save the Solidity compiler to the cache directory, it will throw an error. This PR changes this behavior so that it displays a warning to the user and continues on with the rest of the compilation flow.

add a warning when unable to save the solidity compiler to disk instead of throwing

---

packages/from-hardhat/src/api.ts

As raised by @emilyJLin95, this PR fixes a problem where `hre.config` now contains non-serializable data. Since @truffle/from-hardhat needs only a small portion of the data in `hre.config`, this PR takes the approach to pre-process it, whittling it down to just what we need. This prevents serialization issues that may arise.
In repo root:
```console
git checkout fix/from-hardhat-bigints
yarn
cd packages/from-hardhat && yarn link && cd -
```
In a new directory for a fresh HH project:
```console
npx hardhat # follow the wizard, the wonderful wizard
npx hardhat compile
yarn link @truffle/from-hardhat
node
```
In that node repl that just started:
```js
const FromHardhat = require("@truffle/from-hardhat");
await FromHardhat.prepareConfig();
```
Observe that it does not break.
Oh, and you'll …

Stop serializing HH config data we don't need

---

packages/core/lib/commands/init/initSource/truffle-config.js

This PR upgrades the `solc` version to latest **v0.8.19** in `truffle-config.js` when `truffle init` command is run.

Upgrade solc version to latest 0.8.19 in truffle init

---

packages/resolver/lib/resolver.ts

... since only the first argument is required and the others are optional, but the type incorrectly specifies that 2 arguments are required
This was raised [here](https://github.com/rkalis/truffle-plugin-verify/pull/196#discussion_r1123032692)

Ensure resolver.resolve()'s type only needs 1 arg.

---

packages/dashboard-hardhat-plugin/package.json

- Ensure we specify `repository` and `bugs` the same way we do in our other packages
- Ensure we include the two README images in the `files`, so NPM has them to display on npmjs.com

Fix @truffle/dashboard-hardhat-plugin's `package.json`

---

packages/from-hardhat/src/ask-hardhat.ts

Addresses #5967. This is needed for windows to spawn npx correctly

Enable shell option for spawn

---

packages/core/README.md

I add the link to the License in README.md: `[MIT](./LICENSE)`
It would be more convenient for users.

Add the link to the License in README.md

---

packages/blockchain-utils/tsconfig.json
packages/config/tsconfig.json
packages/from-hardhat/tsconfig.json
packages/hdwallet/tsconfig.json

Fixes build breaks with typescript@next per https://github.com/microsoft/TypeScript/issues/53122#issuecomment-1459064997 because of incorrect typeRoots

Fix typeRoots for tsconfig.json

---

packages/source-fetcher/lib/etherscan.ts
packages/source-fetcher/lib/networks.ts
packages/source-fetcher/lib/sourcify.ts

A quick update to the fetchers while I'm away!
Etherscan added support for base Base Goerli (but *not* Base Mainnet), and Sourcify added support for the same and for Bear.  This PR adds those.
Contracts you can use for testing if you like:
1. Bear on Sourcify: 0x0f103813fa15CA19b6C4B46a0Afe99440b81d7C3
2. Base Goerli on Sourcify: 0x8F78b9c92a68DdF719849a40702cFBfa4EB60dD0
3. Base Goerli on Etherscan: 0xB7eD95bbE808A72C1175fb3845581616e29642B0
(Feel free to merge this one without me, obviously!)

Update Sourcify and Etherscan fetchers w/Base Goerli & more

---

packages/codec/lib/format/types.ts

Fix typo in interface category name in Decoding/Encoding docs

---

packages/source-fetcher/lib/etherscan.ts
packages/source-fetcher/lib/networks.ts

Etherscan has added support for Polygon ZKEVM!  Both mainnet and testnet.  I've added support to the Etherscan fetcher for these.
As usual, I didn't actually bother testing this PR, but if you want to, you could try it with the following addresses:
* Polygon ZKEVM mainnet (network ID 1101): 0xee1727f5074E747716637e1776B7F7C7133f16b
* Polygon ZKEVM testnet (network ID 1442): 0x1dAC955a58f292b8d95c6EBc79d14D3E618971b2

Add support for Polygon ZkEVM to Etherscan fetcher

---

packages/dashboard-hardhat-plugin/README.md
packages/dashboard-hardhat-plugin/package.json
packages/dashboard-hardhat-plugin/src/index.ts
packages/dashboard-hardhat-plugin/src/type-extensions.ts
packages/dashboard-hardhat-plugin/tsconfig.json

Addresses #5958 
This PR modifies the @truffle/dashboard-hardhat-plugin to respect custom Dashboard configuration inside truffle-config.js.
At a high-level, this does a couple things:
- Automatically add the `truffleDashboard` network to the Hardhat networks configuration based on the Dashboard host/port configuration found via `TruffleConfig.detect()`
- Allow users to disable this network management if they want to configure this network themselves.
- Whichever way the network is configured, connect to the dashboard-message-bus with the configured host/port.
This adds a new `truffle` section to `hardhat.config.ts` with a few settings:
- `dashboardNetworkName` (default `"truffleDashboard"`), to specify the name of the Truffle Dashboard network
- `dashboardNetworkConfig` (default `{}`), to …

Make @truffle/dashboard-hardhat-plugin automatically manage the Dashboard Hardhat network configuration (while still allowing customization)

---

packages/source-fetcher/lib/etherscan.ts
packages/source-fetcher/lib/networks.ts

Etherscan has removed support for CLV.  The website https://clvscan.com/ still exists, but it's been converted to Blockscout.  Hopefully we'll have a Blockscout fetcher soon, but for now, I've just removed support from the Etherscan fetcher.

Remove clover support from etherscan fetcher

---

packages/source-map-utils/index.js

Make `getCharacterOffsetToLineAndColumnMapping()` handle multibyte characters properly. Previously, it counts all characters as 1 byte.
Addresses https://github.com/trufflesuite/truffle/issues/5914
Run `truffle debug 0xfb6027725ccff056d8fe4065227fecd335fe123e8ab4da3a85a71377f7e9c6f9 --fetch-external`. With this bugfix, source mapping seems correct
1. Start ganache in terminal 1
```console
ganache --fork
```
2. In terminal 2 
```console
truffle debug 0xfb6027725ccff056d8fe4065227fecd335fe123e8ab4da3a85a71377f7e9c6f9 --fetch-external --url http://localhost:8545
```
3.  In Truffle debugger
```console 
debug(localhost:8545:0xfb602772...)> b AggregationRouterV5.sol:2849
debug(localhost:8545:0xfb602772...)>  c
```
4. observe source misalignment w/ highlight

fix source map with multibyte characters

---

packages/config/src/configDefaults.ts
packages/contract/lib/utils/ens.js
packages/deployer/index.js
packages/deployer/test/ens.js
packages/provisioner/src/index.ts

This PR addresses #5997. I'm not entirely happy with this one, but, well, I figured I ought to put it up as it is and we can iron out the problems in review.
Basically, I altered both Truffle Contract and Truffle Deployer to check 4 places for the ens registry address:
1. `config.network_config.registryAddress`
2. `config.network_config.registry.address`
3. `config.ens.registryAddress`
4. `config.ens.registry.address`
Note that specific network configs are checked before the overall ENS config, so that a specific network config can override the overall ENS config.
Now I say I altered Truffle Contract, but actually I didn't -- the easiest place to make these changes was actually the provisioner, rather than Contract itself.  Not sure if that's appropriate, but I didn't want to deal with …

Consistify location of user ENS registry address setting

---

packages/codec/lib/export.ts
packages/codec/lib/format/utils/inspect.ts
packages/dashboard/src/components/composed/Debugger/Variables.tsx

I have not tested this.
Usage: `util.inspect(new ResultInspector(result, { renderMappingsViaObjects: true }), inspectionOptions)` or just `util.inspect(new ResultInspector(result, { renderMappingsViaObjects: true }))`
This'll have some nasty merge conflicts with #5895!  I made this by cherry-picking a commit from there and then modifying it...

Add compatibility flag to ResultInspector for when Maps can't be inspected

---

packages/config/src/configDefaults.ts
packages/deployer/test/ens.js

The docs say you can do `config.network_config.ens.registry.address`, so, guess I'd better implement that.  I also added a test.
Will have to update the docs after this is merged...

Add even more ways to specify ens registry address so as to be consistent with docs

---

packages/core/lib/debug/printer.js

Panics weren't displaying correctly in the debugger CLI because I screwed up the check for them!  Fixed now.

Fix incorrect check for panic

---

packages/source-fetcher/lib/networks.ts
packages/source-fetcher/lib/sourcify.ts

Sourcify has added more chains, updating!
Addresses you can test with if you want:
7701: 0x37e12c98b4663DcE9ab1460073D9Fe82A7bFD0d8
888: 0xC3649123BCa36c0c38A71bDbd2F508AB4f939f47
999: 0x500E12a948E9Fc594bC6Fe86B3B270B5a67332D8
7668: 0x6C0cE8d62F1D81464F6F4DecB62f97aa83B8Df89
7672: 0x225F2cD344c61152F8E7200E62e03dEfD683f2c4
295: 0x00000000000000000000000000000000002265bb

Add new chains for Sourcify for May 2023

---

packages/config/src/configDefaults.ts

This `null` was screwing things up, I was using `null` to mean *no* registry, not *default* registry >_>
I guess likely I should have done things differently but oh well this is a simple fix and shouldn't break anything...

Change default registry in config from null to undefined

---

packages/debugger/lib/stacktrace/selectors/index.js

I recently created the `StringValueInfoToStringLossy` function in Codec to make working with Codec strings easier.  But, for some reason I didn't factor out this bit of code and apply it here?  Well, factored now.

Use StringValueInfoToStringLossy function in debugger

---

packages/source-fetcher/lib/etherscan.ts

It seems that Etherscan has removed all support for Ropsten, Kovan, and Rinkeby... you can't even go and browse what was once there.  It's just all gone.  So, time to remove it from the Etherscan fetcher...

Remove ropsten, kovan, rinkeby support from Etherscan fetcher

---

packages/abi-utils/README.md
packages/abi-utils/lib/index.ts
packages/abi-utils/lib/parse.test.ts
packages/abi-utils/lib/parse.ts
packages/abi-utils/lib/signature.test.ts

This PR adds functions to ABI utils for parsing signatures.  There's `parseFunctionSignature`, `parseEventSignature`, and `parseErrorSignature`, depending on the entry type you want out.  There's also just a bare-bones `parseSignature` that doesn't return a valid ABI entry, but which is used to back the other three.
This is intended as precursor work for our upcoming solution to #6029.
Note that the ABI entries generated by these functions will have default values for lots of fields... so e.g. `anonymous` will always be `false`, `outputs` will always be `[]`, etc.  Best we can do in the situation, seems to me.  It won't be relevant in the contexts we need this (#6029) anyway.
Also note that the parser doesn't fully validate the input... when it came to primitive types, I just checked that …

Add `parseSignature` functions to ABI utils

---

packages/dashboard-hardhat-plugin/test/hardhat.test.ts
packages/debugger/test/step.js

This test keeps failing its 10-second timeout.  Increasing the time from 10 seconds to 15.
May add more timeout increases to this PR if I see more that we need to get.

Increase time on various tests that were timing out

---

packages/source-fetcher/lib/networks.ts
packages/source-fetcher/lib/sourcify.ts

Adding symplexia and dogechain.  Looks like Sourcify may have "shadow-dropped" these two, oy.
Note that Sourcify also removed a bunch of networks recently, but unlike Etherscan, when Sourcify removes a network, it still leaves up the verified contracts, so I don't typically remove support from the fetcher since there's still something for it to fetch.

Add two more sourcify networks

---

packages/compile-solidity/src/compilerSupplier/loadingStrategies/VersionRange.ts

It seems like somewhere along the line the event declaring success for fetching the list of Solidity compilers got accidentally removed? This PR re-adds this event.

Bug fix: re-add event that seems like it was accidentally removed

---

packages/compile-solidity/src/index.ts
packages/compile-solidity/src/profiler/index.ts
packages/compile-solidity/src/profiler/loadParser.ts

This PR is an optimization. In certain cases during the compilation flow, the CompilerSupplier is instantiated twice and it fetches the list of Solidity compiler versions twice. This is because it needs to see what compiler versions are available when making sure it has the right version and because we need the parser to determine what a sources dependencies are for compilation. So this PR passes the compiler to the Profiler when it has it so that it doesn't need to be fetched again.

pass solc when available to profiler to avoid fetching the solc list again

---

packages/codec/lib/wrap/index.ts
packages/codec/lib/wrap/priority.ts
packages/encoder/lib/encoders.ts
packages/encoder/test/overload.test.ts

Addresses #6028.
The point of this is that, if there's an overloaded function with a bool overload and a string overload, then `truffle call Contract f true` ought to hit the bool overload, not the string overload.  Of course this only makes sense if we're restricted to string input, which is more or less what the `strictBooleans` flag means.
I added tests also.  You could also test it manually by making a function with a `string` overload and a `bool` overload and try calling it with `truffle call`.
*Arguably* this is a breaking change (to codec and encoder), but I'd consider it a bug fix.  Overload resolution is never guaranteed anyway! :)

Swap priority order of bools/strings if strictBooleans is on

---

packages/codec/lib/format/utils/inspect.ts

While working on https://github.com/trufflesuite/truffle/pull/6058 we ran across a problem related to inspecting maps. To be honest I don't understand it too well but @haltman-at was the one that originally did this work. This PR is a part of the aforementioned PR and is broken out here in an attempt to make that one briefer and less complicated.

update ResultInspector options

---

packages/dashboard/lib/DashboardServer.ts
packages/dashboard/package.json

This PR adds a route in preparation for getting https://github.com/trufflesuite/truffle/pull/6058 merged.
The visual debugger will be fetching verified sources externally in the case that it doesn't have compilations for some of the contracts the tx touches. In order to implement this, this route is added. It allows dashboard to give the server a list of addresses and a network to use to attempt to fetch the source material. This route fetches what it can, compiles everything, and then returns it to dashboard.

add new route in preparation for visual debugger PR

---

packages/workflow-compile/legacy/index.js

This PR was prompted by https://github.com/trufflesuite/truffle/issues/6066.
The resolver package exports were changed and the legacy workflow compile package imports for it were not updated which caused it to break. This PR corrects the import in legacy workflow-compile.

Bug fix: correct resolver import in legacy workflow compile

---

packages/source-fetcher/lib/etherscan.ts
packages/source-fetcher/lib/types.ts

As of Solidity 0.8.20, it's now possible to use the Solidity compiler in a mode where, instead of passing `language: "Solidity"` or `language: "Yul"`, you pass `language: "SolidityAST"`, and put in the AST of what you want compiled (it's the long-awaited companion to the stop-after-parsing option).
I got worried about the possibility that Etherscan might allow verifying input in this form.  I haven't actually yet tested whether it does, I intend to test that later.  But I thought it would be good to put in a bit of defensive coding against that possibility right now, since there's no way we can reasonably handle it (at least, not quickly right now).

Reject SolidityAST contracts verified on Etherscan

---

packages/debugger/lib/web3/adapter.js
packages/decoder/lib/decoders.ts

This PR fixes an issue noticed by @gnidan.  Turns out that ENSJS will throw an error if you try to resolve an ENS name which contains certain characters not permitted in URLs[0], such as 🪴 (but apparently 🍑 is fine).  This despite the fact that it has no problem with them on reverse resolution, and apparently it was possible to register these names in the first place (presumably by just not using ENSJS).
Since I don't really want to go tearing out ENSJS right now, I'm fixing this the crudest way possible, with a blunt try/catch.  I could check for the particular error message, but that's probably too brittle.
(Notionally I could use a library (ideally one we're already implicitly using) to check for the particular illegal characters, but that seems a bit too much work for something like …

Put try/catch guard around ENS forward resolution in decoder/debugger

---

packages/source-fetcher/lib/networks.ts
packages/source-fetcher/lib/sourcify.ts

Sourcify has added more chains!
Contracts you can test these with:
Cronos: 0xEdE2053329D203E8261B47A10540Ee4b7a596667
Elysium: 0x20563837F7423465699D7675BCB82f886a761c25
Bitkub: 0xC75f4D89A0DdA70Ad613908D9976E90dAb42035c
Bitkub testnet: 0x58909Ef2F2b167F52cF46575f1582500287cCE48
Taiko testnet alpha 3: 0x68107Fb54f5f29D8e0B3Ac44a99f4444D1F22a68

Add chains for Sourcify 2.2.3

---

.github/workflows/nodejs.yml
scripts/prepare-release.sh

Since `yarn bootstrap` seems to be causing such problems, and I can't figure out the root cause, here's a simple workaround... replacing `yarn bootstrap` with `yarn install`.   There used to be a difference between these, but due to every package using `prepare` now, there no longer is.  Hopefully this is all OK and solves the problem?

Replace bootstrap with install in scripts/workflows

---

packages/test/src/Test.ts

Allow to override the chai instance from the config. This allows one to reduce the test boilerplate when chai plugins are used, e.g. this snippet could move to the config, instead of being repeated in every test:
```js
import chai from 'chai';
import chaiAsPromised from 'chai-as-promised';
chai.use(chaiAsPromised);
const { assert } = chai;
```
require chai from the config and point config's `chaiOverride` to it. No default value is offered as the default is undefined.
Trivial change, no docs required.
Non-breaking.

Allow to override chai from the config

---

packages/codec-components/src/react/components/codec/format.errors.internal-use-error.tsx
packages/codec-components/src/react/components/codec/format.errors.re-encoding-mismatch-error.tsx
packages/codec-components/src/react/contexts/custom-components.ts
packages/codec-components/src/react/index.ts
packages/codec-components/src/utils/index.ts
packages/codec-components/src/utils/type-guards/decoder-error/internal-use-error.ts
packages/codec-components/src/utils/type-guards/decoder-error/re-encoding-mismatch-error.ts

I merged #6057 while ignoring that it adds a new codec error type which needs a component, crap!  So uh I added that quickly.
I didn't actually test this component because this error should never actually appear onscreen and also I just want develop not broken.  It builds, that's good enough for me. :P  Next time I write a component, which will be something that could appear onscreen, I will bother to test it. :P

Add missing codec component for new error type

---

packages/config/src/configDefaults.ts
packages/core/lib/commands/dashboard/meta.js
packages/core/lib/commands/dashboard/run.js

Addresses #6095
It can be useful in some environments to not want Dashboard to open in browser on start.
To test:
- `truffle dashboard --no-auto-open`
- `truffle dashboard` in a Truffle project with `dashboard.autoOpen` set in truffle-config.js
CLI value takes precedence.

Allow Truffle Dashboard to run without launching a browser window automatically

---

packages/dashboard-hardhat-plugin/test/hardhat.test.ts

This test times out so much, even after the timeout has been turned up ridiculously.  It's likely hanging rather than timing out, although I don't know why.
I've put up this PR to remove it because it's just causing so much trouble in CI.
@gnidan has suggested that an alternative solution, rather than removing the test, might be just upgrading hardhat to a newer version (but still below 2.10.1).  The trouble is, it would be difficult to know if such a step had worked.
I figure, if someone else wants, they can do that (or put the test back in and do that).  I'm tired of dealing with it, I'm just submitting a PR to remove it!

Remove flaky hardhat test

---

packages/truffle/README.md

- Added Notes for installation
- Minor changes

Added Notes for installation

---

packages/source-fetcher/lib/networks.ts
packages/source-fetcher/lib/sourcify.ts

Adds the zora chain to the sourcify fetcher.
If you want to test it, you could try testing it with address 0x090734f94FA67590702421A9B61892509b7CE80A.

Add zora network to Sourcify fetcher

---

packages/codec-components/src/react/components/codec/format.values.magic-value.tsx

This updates the `MagicValue` component to omit the prefix specifying which kind of magic variable it is, instead putting that information in the tooltip.
See:

Specify "magic" variables' type only in component tooltip, not via prefix

---

packages/dashboard/src/components/composed/Debugger/Variables.tsx

Use `<ul>` instead of `<dl>` for variables in Dashboard Debugger and ensure the name/value is displayed via `<NameValuePair />`.
Here's what it looks like:
Run the debugger and see it

Display Dashboard Debugger variables in <ul>s with <NameValuePair>s

---

packages/source-fetcher/lib/etherscan.ts
packages/source-fetcher/lib/networks.ts

Etherscan no longer supports the Cronos Testnet (still the mainnet but no longer the testnet!) -- it's Blockscout now! -- so I'm removing it.

Remove cronos testnet from etherscan fetcher

---

packages/test/src/Test.ts

Consider Truffle's test flow. Normally we set up a `createInTestDebug` function which does what it says and pass it to test. A user reported [here](https://github.com/trufflesuite/truffle/issues/6105) that running test programmatically (without the CLI and core) is crashing. It turns out that we never handled the case where this function wasn't passed to @truffle/test. This PR inserts a value for this function that gives the user a helpful message if they try to use `debug` and it is not available.

handle case when a user uses @truffle/test without core

---

packages/codec/lib/abi-data/allocate/index.ts
packages/codec/lib/abi-data/allocate/types.ts
packages/codec/lib/ast/types.ts
packages/codec/lib/export.ts
packages/codec/lib/types.ts
packages/debugger/test/helpers.js
packages/decoder/test/current/truffle-config.js

So, Solidity 0.8.20 is out, and it changes which events get listed in a contract's ABI!  That means our existing event allocation code won't work with 0.8.20 contracts.  Fortunately, they also added the `usedEvents` property to contract nodes (much like the existing `usedErrors`), which lets us distinguish when we're in this case, and also helps us handle it.  So, now we have two event allocation pathways; one for pre-0.8.20, and one for post-0.8.20.
In addition to this, there's also one change to the event decoding return type; `definedIn` can now be `null`, as distinct from `undefined` (same as with errors).  The use of `null` here means that the event was defined at file level, as opposed to `undefined`, which means we don't know where it was defined.  Now you may say, but Solidity …

Properly handle event decoding in Solidity 0.8.20

---

packages/source-fetcher/lib/networks.ts
packages/source-fetcher/lib/sourcify.ts

Sourcify added two more chains, updating.
Addresses you can test these with if you want:
570: 0x1187124eC74e2A2F420540C338186dD702cF6340
57000: 0x736bfcA6a599bF0C3D499F8a0bC5ab2bA2030AC6
Note: Count the zeroes!  These are 570 and 57000, not 57 and 5700, which are Syscoin and its testnet.  (I assume there's some relation between Rollux and Syscoin?  They both named their testnet "tanenbaum"...)

Add Rollux & its testnet to Sourcify fetcher

---

packages/codec/lib/basic/decode/index.ts
packages/codec/lib/format/elementary.ts
packages/codec/lib/format/utils/inspect.ts
packages/debugger/test/data/more-decoding.js

Addresses #5913.  Adds a `contractClass` interpretation to address values.  Basically, if we can identify what sort of contract a given address is, it will have this interpretation with more information; otherwise it won't.
Yes, this means that the address/contract distinction is now pretty silly -- they now contain the same information but formatted differently.  Oh well.  I don't want to make a breaking change to make them more unified.
The code is pretty straightforward, not much to explain.  I could have further eliminated some minor recomputation by just using `decodeContract` and then doing everything based on the results of that, but I decided it was clearer to do it this way, even if that means calling `Evm.Utils.toAddress` twice. :P
I also updated the inspector so that it now …

Add `contractClass` interpretation to address values

---

packages/decoder/lib/decoders.ts
packages/decoder/lib/types.ts
packages/decoder/test/current/test/compatible-nativize.js
packages/decoder/test/current/test/wire-test.js

Addresses #6080.  This makes it so that fields in `Log` or `Transaction` that previously were `number` are now `number | string | bigint`, and fields that were `number | null` are now `number | string | bigint | null`.
Most of these fields are ignored, so the type is changed and that's all.
The one changed field that's actually used is `blockNumber`, so I just changed things so that if we get that and it's not null, we convert it to a number.
I do have to also discuss what happened to the `DecodedLog` type.  For simplicity, `DecodedLog` extends `Log`.  However, `Log` has just had its type broadened.  But while that's fine for `Log`, because it's an input type, `DecodedLog` is an output type.  So to broaden its type would be a breaking change.  So I re-narrowed the types of the appropriate …

Allow strings and bigints instead of numbers in decoder input fields

---

packages/codec/lib/export.ts
packages/debug-utils/index.js

I noticed tonight that the `CalldataDecodingInspector` doesn't actually pass its inspector options through when inspecting intepretations as multicalls or etc.  Oops.  Changed that to pass that through.  Also turned on the `noHideAddress` option in debug-utils, because we always use that option in the debugger.
I'm going to be honest, I didn't really test this one, I wanted to get it up quick...
Because I changed the argument order of `formatFunctionLike`, which is exported, this is technically a breaking change to Codec (and indeed, I had to adjust the use in `debug-utils` appropriately).
It could be done in a non-breaking way, but that would be ugly.  Arguably we should switch from positional params to named params, but that would also be breaking, and frankly I don't think it's worth …

Ensure CalldataDecodingInspector always passes through inspector options

---

packages/codec/lib/export.ts
packages/codec/lib/types.ts
packages/decoder/lib/decoders.ts
packages/decoder/test/current/contracts/WireTest.sol
packages/decoder/test/current/migrations/2_deploy_contracts.js
packages/decoder/test/current/test/wire-test.js

Addresses #6079.  This PR adds support for the new methods from Multicall v3 -- `aggregate3` and `aggregate3Value` -- to the decoder's multicall interpretation support.
The `aggregate3` method allows you to specify `allowFailure` for each call (in addition to the target and the data), and `aggregate3Value` allows both `allowFailure` and `value`.  So, I added two new fields to the `CallInterpretationInfo` type, `allowFailure` (a boolean) and `value` (a BN).
When a simple `aggregate` is detected, these fields will be included in the decoding, with `allowFailure` set to `false` and `value` set to zero.  When a `tryAggregate` is detected, `allowFailure` will be set to the negation of the `requireSuccess` field.
When `aggregate3` or `aggregate3Value` is detected, these will be set as …

Add support for multicall3 to decoder interpretations

---

packages/source-fetcher/lib/networks.ts
packages/source-fetcher/lib/sourcify.ts

More Sourcify networks.  They also added support for Ethereum Classic, but we only handle networks with network ID = source ID, so I excluded that.
Addresses you can use for testing if you want:
6119: 0x212F6222fB4937978A806b14FB2725169825078F
33101: 0xeb6Ea260eDFb9837ed100B09c559081AfA5b0785
32769: 0x6F85669808e20b121980DE8E7a794a0cc90fDc77
314: 0x23396626F2C9c0b31cC6C2729172103961Ae2A26
111000: 0x60E9b3CD8C160Ce6408dD6E2Fa938895cfF7E087
2221: 0x40b4f95C3bafc8d690B4c3fDD1E8303c4817Cd9C
2222: 0xAdFa11e737ec8fA6e91091468aEF33a66Ae0044c

Update sourcify networks for sourcify 2.4.0

---

packages/debugger/lib/controller/sagas/index.js
packages/debugger/lib/controller/selectors/index.js
packages/debugger/lib/stacktrace/actions/index.js
packages/debugger/lib/stacktrace/reducers.js
packages/debugger/lib/stacktrace/sagas/index.js
packages/debugger/lib/stacktrace/selectors/index.js

@gnidan noticed a problem whereby a generated source could appear in a stacktrace even though generated sources were turned off.  What's up with that?
Well, turns out that in this case, a function in a generated source called another function in that generated source, and due to optimization part of the latter function ended up sourcemapped to a user source!  So when you stepped, you would hit that source range, and see that you were now inside a user source called from a generated source.  Yikes!
The fix for this is that, if generated sources are turned off, you shouldn't hit such a source range in the first place, as logically it should really be considered to be within a generated source.  So I changed it so that, while stepping, the debugger won't stop while there are generated …

Have debugger skip anything called from a generated source while stepping

---

packages/dashboard/src/components/composed/RPCs/RPC/Overview.tsx

This PR adds a tooltip to the Debug button in the transaction signer in Dashboard. See screenshot below:

add a tooltip for the debug button in the tx signer for dashboard

---

packages/dashboard/src/components/composed/Debugger/Sources/index.tsx
packages/dashboard/src/components/composed/Debugger/Stack.tsx
packages/dashboard/src/components/composed/Debugger/Variables.tsx
packages/dashboard/src/components/composed/Debugger/index.tsx

The visual debugger currently stores data for the current source range at a high level of the component structure. It also relies on re-renders to set the data as it is not stored in the state. This PR creates a state variable for it and moves it into the `Sources` component. It now also updates the current source range data in a `useEffect` hook.

move source range data into Sources

---

packages/source-fetcher/lib/networks.ts
packages/source-fetcher/lib/sourcify.ts

Updates Sourcify networks for Sourcify 2.5.0, adding Base Mainnet, MAP, and the MAP testnet Makalu.  Also updated a comment. :P
Addresses you can test with if you want:
Base: 0x5e357053DDa704D059D146444cCC81afC1B2a662
MAP: 0xAbdE047dD5861E163830Ad57e1E51990035E1F44
MAP Makalu: 0xAbdE047dD5861E163830Ad57e1E51990035E1F44

Update sourcify networks for sourcify 2.5.0

---

packages/codec/lib/ast/types.ts
packages/codec/lib/compilations/utils.ts
packages/compile-solidity/src/run.ts
packages/debugger/lib/data/selectors/index.js
packages/debugger/lib/helpers/index.js
packages/debugger/test/data/more-decoding.js
packages/debugger/test/data/yul-source.js
packages/debugger/test/helpers.js

This PR allows decoding of variables while decoding Yul sources that were compiled with solc 0.8.21 or greater.  Note this PR does **not** address #3831, I figured that was better saved for later.
It was already possible to decode Yul variables in Solidity `assembly` blocks, but not in straight Yul files, because Solidity wouldn't give us ASTs for the latter.  But now it does!
Well, now it does if we ask for them right.  For some reason, Solidity makes us ask for the ast at the contract level when compiling Yul, instead of at the file level like normal; I've filed [an issue](https://github.com/ethereum/solidity/issues/14452) about that (although for 0.8.21 compatibility we'll have to leave this extra bit in anyway).  Also, there's another bug regarding these (which I've also [filed an …

Allow decoding while debugging Yul sources in Solidity 0.8.21 (and related changes)

---

packages/source-fetcher/lib/networks.ts
packages/source-fetcher/lib/sourcify.ts

New networks for Sourcify.  They are: Edgeware; the Filecoin calibration testnet; Fantom (already supported by Etherscan, so doesn't need to be added to networks.ts); Arbitrum Nova (also already supported by Etherscan); the Beam testnet (doesn't appear to have a mainnet yet?); and Taiko Eldfell (also, I renamed Taiko Alpha 3 as it's now Taiko Grimsvotn).

Add sourcify chains for sourcify 2.6.0

---

packages/debugger/lib/data/sagas/index.js
packages/debugger/lib/data/selectors/index.js
packages/debugger/lib/helpers/index.js

This PR fixes an old bug regarding detection of arguments to modifiers, and factors some code in the process.
Both mapping key handling and modifier argument detection can require looking inside nodes that aren't sourcemapped because they're no-ops on the EVM level and so don't correspond to any instruction.  (Certain type conversions; unary plus in Solidity prior to 0.5.0; and `wrap`/`unwrap` for UDVTs.)  When dealing with these, we often need to peel away the node representing the no-op, to find the node inside representing an actual operation.
For mapping-key handling, this code has been kept up to date.  But for modifier argument detection, which had the logic separate, it was not.  I didn't notice this until going over the code with @cds-amal this past Friday.
This PR factors out the …

Fix modifier argument detection by factoring out no-op handling

---

packages/codec/docs/tsconfig.json

Add "dom" to lib at packages/codec/docs/tsconfig.json

Fix build error at codec while upgrading web3.js to v4

---

packages/fetch-and-compile/README.md
packages/source-fetcher/lib/sourcify.ts

Remove invalid networks check from Sourcify fetcher

---

packages/source-fetcher/lib/networks.ts
packages/source-fetcher/lib/sourcify.ts

There's a new Sourcify version out, so even though it doesn't matter anymore, I've updated the chains.
Also, I fixed a problem where I used an inconsistent name for the beam testnet.  Oops.  Probably there ought to be some type-level way of preventing this, but I figure now is not the time to worry about that.

Add new sourcify networks; fix problem with beam testnet

---

packages/compile-solidity/src/compilerSupplier/loadingStrategies/VersionRange.ts

For reasons discussed elsewhere.

Deprioritize Truffle relays

---

.github/workflows/nodejs.yml

CI is currently failing due to a regression in Node.js v20. This temporarily pins to the penultimate version pending a fix.
- https://github.com/vitejs/vite/issues/14299#issuecomment-1706557322
- https://github.com/babel/babel/issues/15927
- https://github.com/nodejs/node/issues/49497
- https://github.com/nodejs/node/pull/49500

chore(ci/tests): pin nodejs 20 to 20.5 due to regression in 20.6

---

.github/workflows/nodejs.yml
yarn.lock

Currently `yarn.lock` pins multiple different versions of the same package, even if a single version would satisfy all the constraints. This wastes disk space, computational time, human time, and environmental resources ;)
This PR deduplicates packages with the `@babel/` and `babel-` prefixes, saving ~400MB.
```
#Before
$ du -hs node_modules
2.1G    node_modules
$ du -hs node_modules
1.7G    node_modules
```
Based on #6177 as they touch the same lines and that one seems higher priority.

devDeps: deduplicate babel packages

---

packages/dashboard/package.json
yarn.lock

dedupes various runtime libraries (a devDep or two might have snuck by but trying to keep this relatively scoped).
The impact on runtime of a fresh install without yarn cache (for example on a fresh developer environment) should be bigger than is visible in ci due to the dedupe of `keccak`.
- #6185
- #6188

deps: dedupe runtime libraries

---

yarn.lock

Dedupes and performs lockfile bumps of packages in the `ethers`, `ethereumjs`, and `web3` families.
Note that this implies a major upgrade of transitive `bn.js` from v4 to v5.
- #6191 
- #6185
- #6188

deps: dedupe and lockbump ethers, ethereumjs, web3

---

packages/contract/package.json
packages/dashboard/package.json
packages/db-kit/package.json
packages/db/package.json
packages/debugger/package.json
packages/truffle/package.json
yarn.lock

This performs a complete deduplication of all remaining duplicates that have overlapping semver ranges in workspace `yarn.lock`.
Some that may be noteworthy have been split out as manually crafted individual commits here and eventually the final resolution was done using `yarn deduplicate` from #6193 .
For the curious: To see the difference vs what running that auto-dedupe using `--strategy highest` instead of `--strategy fewer` would look like, see [here](https://github.com/legobeat/truffle/compare/yarn-dedupe-full-fewer...legobeat:truffle:yarn-dedupe-full-highest).
`madge` is causing a lot of duplication and bumping it was brought in here but also posted separately as #6195 .

deduplicate all dependencies and devDependencies

---

.github/workflows/nodejs.yml
package.json
yarn.lock

- New workspace package scripts
- `deduplicate:check`: exits with error if any redundancies in `yarn.lock` are detected
- `deduplicate`: performs a best-effort attempt to resolve such duplicates
- `lint:dependencies`: `deduplicate:check && depcheck`
- `lint:dependencies:fix`: `deduplicate && depcheck`
- ci: fail if `yarn lint:dependencies` errors
- new devDependency [`yarn-deduplicate`](https://www.npmjs.com/package/yarn-deduplicate)
- see this package for details about how the dedupe is done and possible configuration (the main one being if `highest` or `fewer` should be used - this uses `fewer` but it's a tradeoff and up to maintainer to decide if `fewer` or `highest` is preferred)
- #6194 
- though the scripts could be broken out separately without the ci checks to make those not …

ci: enforce deduped lockfile when linting dependencies
